#import "../typst-template/nebli_v2_apostila.typ": *

#discursiva("Q1",
  [Explique por que potencialidade e grau de diferenciação são grandezas inversas ao longo da linhagem que vai do zigoto à hemácia madura. Use no máximo dois exemplos concretos de células em pontos diferentes da escala.],
  [Conforme a célula adquire especialização funcional, ela ativa um subconjunto restrito de genes e silencia os demais por mecanismos epigenéticos estáveis. Esse comprometimento progressivo *fecha* o leque de destinos disponíveis. O zigoto é totipotente (origina embrião + anexos) porque seu padrão de expressão é generalista; a HSC já só gera células do sangue (multipotente — uma linhagem) porque seu padrão epigenético travou os genes hematopoiéticos como acessíveis; a hemácia madura, ultradiferenciada (perdeu núcleo para carregar mais hemoglobina), tem potencialidade nula. Eficiência funcional custa versatilidade.])

#discursiva("Q2",
  [Descreva os quatro mecanismos canônicos de herança epigenética e justifique por que se chamam *epigenéticos* e não *genéticos*. Para cada mecanismo, dê uma frase sobre como a memória é transmitida nas divisões celulares.],
  [Os quatro mecanismos: (1) *alça de retroalimentação positiva* — proteína ativa o próprio gene; filhas herdam moléculas no citoplasma e recriam o estado; (2) *modificação de histonas* — marcas nas caudas histônicas mantêm cromatina aberta/fechada; nucleossomos parentais recrutam complexos que repropagam as marcas na replicação; (3) *metilação de CpG* — DNMT1 reconhece sítios hemimetilados após replicação e copia o padrão na fita nova; (4) *RNAs não codificantes (miRNAs)* — repertório herdado regula pós-transcrição. São #strong[epi]genéticos porque o padrão de expressão é transmitido sem alterar a sequência de DNA — exatamente o oposto da herança genética por mutação.])

#discursiva("Q3",
  [Julgue cada item a seguir como Verdadeiro (V) ou Falso (F), justificando mecanisticamente em 1–2 frases: (a) células multipotentes originam os três folhetos embrionários; (b) diferenciação celular ocorre somente durante a embriogênese; (c) quanto mais diferenciada uma célula, maior sua potencialidade; (d) a herança epigenética é transmitida por modificações na sequência primária do DNA; (e) toda divisão assimétrica depende exclusivamente do nicho ambiental.],
  [a) F — quem origina os três folhetos é a *pluripotente* (massa celular interna, ES, iPS); multipotente gera só uma linhagem (HSC → sangue; mesenquimal → tecido conjuntivo). b) F — continua na vida adulta nos compartimentos com turnover (epiderme, intestino, sangue, satélite muscular). c) F — relação *inversa*: hepatócito (altamente diferenciado) tem potencialidade quase nula. d) F — é justamente o oposto, padrão herdado *sem* alterar sequência (via metilação, histonas, ncRNAs, alças). e) F — existe assimetria *intrínseca* (herança desigual de determinantes citoplasmáticos como Numb, mRNAs localizados) além da ambiental.])

#discursiva("Q4",
  [O controle combinatorial da expressão gênica permite que poucos reguladores transcricionais gerem muitos tipos celulares. Explique o princípio matemático e conecte-o ao experimento de Yamanaka (2006) com a geração de iPS a partir de fibroblasto adulto.],
  [Com 3 reguladores binários (ativo/inativo), temos 2³ = 8 combinações possíveis; com 10 reguladores, mais de 1000. O genoma humano (~20 mil genes) precisa de apenas algumas dezenas de reguladores combinatórios para construir os ~200 tipos celulares histologicamente reconhecíveis. Yamanaka explorou esse princípio: introduziu *quatro* fatores transcricionais (Oct3/4, Sox2, c-Myc, Klf4) num fibroblasto adulto humano; a combinação ativou cascatas que recriaram o estado epigenético da célula-tronco embrionária. Quatro entradas reprogramaram centenas de marcas — confirmação experimental do controle combinatorial.])

#discursiva("Q5",
  [Um paciente de 23 anos com diabetes mellitus tipo 1 é candidato a um protocolo experimental de terapia celular autóloga baseada em iPS. Descreva mecanisticamente: (a) a etapa de reprogramação do fibroblasto do paciente em iPS; (b) a sequência de diferenciação dirigida da iPS até a célula-beta funcional; (c) duas vantagens conceituais da iPS sobre a célula-ES nesse contexto; (d) um risco residual conhecido da abordagem com os quatro fatores clássicos de Yamanaka.],
  [a) Fibroblasto da pele do paciente é colhido por biópsia e transduzido com Oct3/4, Sox2, c-Myc e Klf4; em poucas semanas, parte das células reverte a um estado morfológica e funcionalmente equivalente à ES. b) As iPS são direcionadas em cultura por morfógenos sequenciais: endoderma definitivo → progenitor pancreático (Pdx-1) → progenitor endócrino (Ngn3) → célula-beta funcional (MafA, Pax4) produtora de insulina. c) Não exige embrião humano (sem o problema ético da ES) e é autóloga (sem risco de rejeição imunológica). d) c-Myc é oncogene clássico — sua expressão forçada aumenta risco tumorigênico, e protocolos modernos buscam substituí-lo ou usar veículos não integrativos.])
