#import "../typst-template/nebli_v2_apostila.typ": *

#resumindo-page((
  ("Reconhecimento hierárquico",
   [Antes de ler antígeno, o sistema pergunta se há homeostasia. Quem responde primeiro são os PRR; a resposta deles é o contexto que decide o desfecho do antígeno depois.]),
  ("Tolerância ou resposta",
   [Não é próprio versus não-próprio que decide: é o estado homeostático do tecido de onde o antígeno veio. Daí a tolerância ao tumor e a rejeição do enxerto.]),
  ("PAMP e DAMP",
   [PAMP é assinatura de micro-organismo (LPS, RNA dupla-fita); DAMP é molécula do hospedeiro extravasada por dano. Mesmos receptores, mesmas vias — muda a origem do sinal.]),
  ("Onde cada PRR vigia",
   [TLR em membranas (plasmática e do lisossomo), NLR em membranas e citoplasma, RLR no citoplasma (RNA viral), ALR no núcleo. O complemento é o PRR solúvel do plasma.]),
  ("Ativação do TLR",
   [O ligante dimeriza dois TLR isolados ou muda a conformação de um dímero pré-formado. Ligante típico mais citado: LPS pelo TLR4 — típico, nunca exclusivo.]),
  ("MyD88 e TRIF",
   [MyD88 converge em NF-κB e AP-1 e produz citocinas e quimiocinas inflamatórias; TRIF ativa os IRF e produz interferons do tipo I. As duas vias se cruzam.]),
  ("Outras saídas do TLR",
   [Sobrevivência por AKT, apoptose por caspase-8 e ativação do inflamassoma por TRIF. Qual predomina depende da quantidade de TLR e dos outros sinais que a célula recebe.]),
  ("Inflamassoma",
   [Plataforma molecular montada por NLR (NLRP3, IPAF) e AIM2 que ativa a caspase-1, a qual cliva pró-IL-1-beta e pró-IL-18. Os NOD, ao contrário, ativam NF-κB.]),
  ("Priming: dois sinais",
   [O inflamassoma não transcreve a citocina, só corta o precursor. Sem um sinal anterior que induza a pró-IL-1-beta, não há substrato — e não há liberação.]),
  ("Interferon do tipo I",
   [A célula infectada não se salva: o interferon que ela libera bloqueia a replicação viral nas vizinhas. Seus efeitos sistêmicos explicam boa parte dos sintomas da gripe.]),
  ("Citotoxicidade e fagocitose",
   [Citotoxicidade induz apoptose no alvo (grânulos ou FasL-Fas), não destrói de fora. Fagocitose: quimiotaxia, opsonização, zíper, fagolisossomo e explosão respiratória.]),
  ("Citocinas",
   [Proteínas pleiotrópicas que só agem onde há receptor. IFN-alfa e beta são tipo I; IFN-gama é o único tipo II. Febre é defesa — o lagarto impedido de aquecer morre mais.]),
))
