#import "../typst-template/nebli_v2_apostila.typ": *

#intro-box[
  O linfócito T é a célula que comanda a resposta imune adquirida, e ela tem uma limitação estrutural que organiza toda esta aula: ela não enxerga o antígeno. Uma bactéria inteira pode estar encostada nela e nada acontece. Para que o linfócito T reconheça alguma coisa, outra célula precisa capturar aquele agente, quebrá-lo em pedaços pequenos e segurar um desses pedaços numa moldura própria, exposta na superfície — a molécula do complexo principal de histocompatibilidade. Esse caminho de três tempos — capturar, processar, apresentar — é o assunto deste resumo. A PARTE I explica por que essa intermediação é obrigatória e quais células têm licença para fazê-la. A PARTE II abre a molécula que carrega o peptídeo: como é a fenda, por que existem duas classes, como esses genes são herdados e por que eles são os mais variáveis do genoma humano. A PARTE III segue o peptídeo desde a proteína de origem até a superfície, pelas duas rotas de processamento que a célula mantém em paralelo, e fecha no que acontece depois do encontro — porque apresentar, sozinho, ainda não é ativar.
]

#parte-title("PARTE I — Por que o linfócito T precisa que alguém mostre", primeira: true)

#subtopico("1.1 — Reconhecer é o primeiro ato")

O sistema imune é, antes de qualquer outra coisa, um sistema de reconhecimento. Suas células estão distribuídas pelos tecidos para perceber qualquer coisa que tire aquele tecido do equilíbrio, e só depois de perceber é que uma resposta é montada. A consequência dessa ordem é importante: a qualidade da resposta depende inteiramente da qualidade do reconhecimento inicial. Se o organismo identifica corretamente que o agressor é um fungo, ele monta a resposta que elimina fungo; se identifica errado, monta a resposta errada contra o alvo certo. Vale notar que sair da homeostase não exige patógeno nenhum — variação de glicose, de temperatura, de osmolaridade, e principalmente material próprio fora do lugar, como cristais de ácido úrico depositados numa articulação, deflagram a mesma maquinaria de reconhecimento.

O braço inato faz esse trabalho com receptores herdados, os mesmos em todas as pessoas, que leem #termo-nota[padrões moleculares associados a patógenos][estruturas conservadas e compartilhadas por classes inteiras de micro-organismos — parede bacteriana, RNA de fita dupla viral, parede de fungo — ausentes das células do hospedeiro] (#sigla("PAMP", [padrão molecular associado a patógeno — estrutura conservada que identifica uma classe de micro-organismo])). Esses receptores estão distribuídos em três endereços que se complementam. Solúveis no plasma, como a proteína C-reativa e as proteínas do complemento, que grudam na superfície do agressor e o marcam. Ancorados na membrana plasmática e na membrana de vesículas internas, como os receptores do tipo Toll (#sigla("TLR", [receptor do tipo Toll — receptor de membrana que reconhece padrões moleculares de patógenos])), que têm um domínio externo de encaixe e uma cauda intracelular que dispara sinalização. E livres no citosol, como os receptores do tipo NOD (#sigla("NLR", [receptor do tipo NOD — sensor citosólico de produtos microbianos e de dano celular])), que vigiam justamente o compartimento onde o TLR não chega — o interior da célula, onde um vírus deposita seu material genético ou uma bactéria invasora se instala.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-14.png",
  largura: 56%,
  legenda: [Os três endereços dos receptores de padrão: solúveis no plasma, ancorados na membrana e livres no citosol. A divisão não é organizacional — cada compartimento tem sensores próprios porque um agressor pode estar em qualquer um deles.])

O sensor citosólico ilustra bem como reconhecer vira consequência. Quando um NLR encontra um produto bacteriano ou um cristal no citoplasma, ele se polimeriza com uma proteína adaptadora e com a pró-caspase-1, formando o #termo-nota[inflamassoma][complexo multiproteico citosólico que reúne sensor, adaptador e caspase-1, e cuja montagem converte pró-interleucina-1β na citocina ativa]. A montagem do complexo ativa a caspase-1, e a enzima faz um corte preciso: converte a pró-interleucina-1β, que já estava estocada inativa dentro da célula, na #sigla("IL-1β", [interleucina 1 beta — citocina pró-inflamatória que produz febre, dor e recrutamento celular]) madura. Repare que a citocina não é fabricada nesse momento — ela é liberada de uma forma inativa por clivagem, o que permite uma resposta em segundos. Na gota, é exatamente essa sequência que produz a articulação quente, inchada e insuportavelmente dolorosa: o fagócito tenta engolir o cristal de urato, fracassa, e a fagocitose frustrada dispara o inflamassoma.

#mini-resumo[O inato reconhece classes de agressores por receptores herdados em três compartimentos, e o reconhecimento é o passo que determina qual resposta será montada. O adquirido precisa da mesma informação — mas não consegue obtê-la sozinho.]

#subtopico("1.2 — O linfócito B vê a molécula inteira; o linfócito T, só um fragmento")

O braço adquirido também reconhece, mas de outro jeito: seus receptores são gerados por rearranjo de genes durante a maturação da célula, um por clone, cada um com uma especificidade única. É aqui que aparece a assimetria que dá nome à aula. O receptor do linfócito B (#sigla("BCR", [receptor de antígeno do linfócito B — o próprio anticorpo ancorado na membrana da célula])) é um anticorpo ancorado na membrana, e ele encaixa diretamente na proteína alvo na conformação nativa, do jeito que ela existe no meio — sem intermediário, sem processamento, sem ajuda. Já o receptor do linfócito T (#sigla("TCR", [receptor de antígeno do linfócito T — heterodímero de cadeias α e β que reconhece peptídeo apresentado em molécula de MHC])), formado por uma cadeia α e uma cadeia β, é incapaz disso. Ele não reconhece proteína dobrada, não reconhece açúcar de superfície, não reconhece o micro-organismo. Ele reconhece um trecho linear curto daquela proteína, encaixado dentro de uma molécula de superfície de outra célula.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-23.png",
  largura: 68%,
  legenda: [Os dois braços lado a lado. À direita, a frase que organiza o resto da aula: o BCR reconhece moléculas inteiras, o TCR reconhece moléculas processadas — e por isso precisa que alguém mostre.])

A diferença tem consequência imediata sobre o que cada um consegue enxergar. O epítopo do linfócito B é uma superfície da proteína dobrada, formada muitas vezes por resíduos distantes na sequência mas próximos no espaço; se a proteína desnatura, aquele epítopo deixa de existir. O #termo-nota[epítopo][a porção do antígeno efetivamente reconhecida pelo receptor — de superfície e conformacional para o BCR, linear e interno para o TCR] do linfócito T é o oposto: um segmento contínuo da cadeia de aminoácidos, frequentemente enterrado no interior da proteína nativa, que só se torna acessível depois que alguém a cortou. Por isso a mesma proteína entrega alvos diferentes aos dois braços, e por isso o linfócito T depende estruturalmente de uma célula que faça o corte por ele.

Há um segundo motivo, este dentro da própria célula T, para que o reconhecimento nunca seja um ato solitário. As caudas citoplasmáticas das cadeias α e β do TCR são curtíssimas e não têm capacidade de sinalizar; o encaixe acontece, mas a informação não desce. Quem transmite o sinal para dentro é um conjunto de cadeias acessórias associadas ao TCR, o complexo #sigla("CD3", [complexo de cadeias acessórias associado ao TCR, responsável por transmitir o sinal do reconhecimento para o interior do linfócito]). O reconhecimento, portanto, é montado em peças: uma molécula que encaixa, outra que avisa. Guardar essa modularidade ajuda adiante, quando aparecerem o correceptor e o segundo sinal.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-29.png",
  largura: 62%,
  legenda: [Em cima, linfócito T CD4 e antígeno solúvel juntos: nada acontece. Embaixo, o mesmo antígeno depois de capturado, cortado e apresentado como epítopo peptídico por uma apresentadora: o linfócito reconhece e expande. A diferença entre as duas linhas é a aula inteira.])

#confusao-prevista(
  titulo: "Ter antígeno em excesso não substitui apresentação",
  aluno_acha: [se houver antígeno suficiente, em algum momento o linfócito T acaba encostando nele e reconhecendo],
  mecanismo: [a falha não é de quantidade, é de formato. O TCR só encaixa numa superfície composta — peptídeo curto deitado dentro de uma fenda de molécula de MHC. Antígeno nativo, por mais concentrado que esteja, não tem essa forma e nunca terá.],
)

#subtopico("1.3 — Três células têm licença para conversar com o linfócito T virgem")

Se o linfócito T depende de intermediário, a pergunta operacional passa a ser quem pode ser esse intermediário — e a resposta é deliberadamente restrita. Uma célula que ativa um linfócito T CD4 virgem precisa reunir quatro capacidades: internalizar o antígeno por endocitose ou fagocitose, quebrá-lo em peptídeos, expor esses peptídeos em moléculas do complexo principal de histocompatibilidade (#sigla("MHC", [complexo principal de histocompatibilidade — conjunto de moléculas de superfície que carregam peptídeos para reconhecimento pelo linfócito T])) de classe II, e ainda exibir moléculas extras que confirmem que aquele encontro é legítimo. Só três tipos celulares têm o conjunto completo, e por isso são chamadas apresentadoras profissionais (#sigla("APC", [célula apresentadora de antígeno — célula capaz de processar antígeno e expô-lo em MHC de classe II para o linfócito T CD4])): a célula dendrítica, o macrófago e o linfócito B.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-34.png",
  largura: 72%,
  legenda: [As três apresentadoras profissionais e o que cada encontro produz. A dendrítica é a única que ativa o linfócito T virgem; macrófago e linfócito B conversam com linfócitos já ativados, e a conversa volta em benefício da própria apresentadora — o macrófago é ativado para matar, o linfócito B é levado a produzir anticorpo.])

A restrição não é um detalhe de nomenclatura, é um mecanismo de segurança. O linfócito T CD4 ativado comanda macrófago, neutrófilo, linfócito B e linfócito T CD8 — é o regente da orquestra. Ativá-lo por engano significa desencadear uma resposta inteira contra um alvo que talvez seja próprio. Limitar a expressão de MHC de classe II a três tipos celulares equivale a limitar quem tem permissão de dar essa ordem, e reduz drasticamente a chance de uma ativação acidental. Por isso a distribuição das duas classes é assimétrica: MHC de classe I está em toda célula nucleada do corpo, enquanto MHC de classe II é privilégio das profissionais.

Cada uma das três serve melhor a um momento. A célula dendrítica é a melhor no papel mais difícil — acordar o linfócito T que nunca viu antígeno algum. O macrófago apresenta sobretudo para linfócitos T já diferenciados, e o resultado da conversa é ele próprio ser ativado para destruir o que fagocitou. O linfócito B apresenta e, em troca, recebe do CD4 o estímulo que o converte em plasmócito produtor de anticorpo. Vale notar um refinamento no linfócito B que explica sua eficiência: ele não captura antígeno ao acaso, e sim pelo próprio BCR, que gruda especificamente na proteína que aquele clone reconhece e a internaliza junto. Isso concentra o antígeno certo e permite que o linfócito B apresente com eficiência mesmo quando o antígeno está muito diluído — é a base mecanística da cooperação entre linfócito B e linfócito T contra o mesmo agente.

#subtopico("1.4 — A dendrítica troca de ofício no caminho até o linfonodo")

Uma célula dendrítica na pele e a mesma célula dendrítica dentro do linfonodo são, na prática, duas células diferentes — e a transformação entre uma e outra é o que torna a apresentação possível. Na epiderme e na mucosa, logo abaixo do epitélio, a dendrítica é imatura: coberta de receptores de reconhecimento, com enorme avidez fagocítica, emitindo prolongamentos que tateiam o ambiente. Ela é excelente catadora e péssima professora. Quando engole um micro-organismo e simultaneamente aciona seus TLR, a sinalização inicia uma reprogramação completa: ela perde adesividade ao tecido, passa a expressar o receptor de quimiocina #sigla("CCR7", [receptor de quimiocina que direciona a célula dendrítica madura para a zona de linfócitos T do linfonodo]) e entra num vaso linfático aferente rumo ao linfonodo que drena aquela região.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-31.png",
  largura: 58%,
  legenda: [A trajetória completa: captura na epiderme, perda de adesividade, migração pelo linfático aferente, maturação durante o trajeto e apresentação na zona de linfócitos T do linfonodo. O processamento acontece no caminho — ela chega pronta para ensinar.])

Durante o trajeto ela vai digerindo o que capturou e trocando de fenótipo. Reduz os receptores de captura, que já cumpriram seu papel, e aumenta na superfície aquilo que agora importa: moléculas de MHC carregadas com os peptídeos do agressor e moléculas acessórias de estímulo. Quando chega à zona de linfócitos T, é uma célula madura, com alta densidade de complexos peptídeo-MHC estáveis e capacidade de ativar um linfócito virgem. O ganho de uma capacidade custa a perda da outra, e essa troca é deliberada — capturar bem e estimular bem são talentos que não convivem na mesma célula ao mesmo tempo.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-36.png",
  largura: 66%,
  legenda: [Imatura à esquerda, madura à direita. A sinalização por TLR induz o CCR7 e aumenta o processamento de antígenos; nos linfonodos, a célula madura exibe complexos peptídeo-MHC e moléculas coestimuladoras, e instrui os linfócitos T virgens.])

Duas consequências valem ser fixadas. Primeira: a resposta adquirida não acontece no tecido agredido, e sim no órgão linfoide secundário — linfonodo para o que entra pela pele, mucosa e tecido conjuntivo, baço para o que cai na corrente sanguínea. O antígeno é levado até onde os linfócitos estão, porque procurar o clone certo entre milhões seria inviável se cada célula tivesse de percorrer o corpo. Segunda: a migração não é ao acaso — a maturação instala no citoesqueleto da dendrítica um endereço químico, e o CCR7 lê exatamente o sinal produzido na zona T. Essa combinação de trânsito dirigido e mudança de fenótipo é o que entrega, ao linfócito virgem, um antígeno já capturado, já cortado e já montado. O que ele encontra na superfície da dendrítica não é mais o patógeno: é um peptídeo dentro de uma molécula. É essa molécula que a PARTE II abre.

#parte-title("PARTE II — A molécula que mostra: fenda, classes e herança")

#subtopico("2.1 — A fenda carrega o peptídeo, e o TCR lê os dois ao mesmo tempo")

A molécula de MHC não reconhece nada. Ela é uma bandeja: sua porção externa forma uma cavidade alongada, a fenda, cujo assoalho e cujas paredes seguram um peptídeo deitado e o mantêm exposto para fora da célula. Quem faz reconhecimento é o TCR, e o que ele encontra ali em cima não é o peptídeo isolado nem a molécula isolada, e sim uma superfície composta pelos dois. Separar esses dois papéis — carregar e reconhecer — evita a confusão mais persistente do tema.

Dentro da fenda, os aminoácidos do peptídeo se dividem em duas funções que apontam para lados opostos. Alguns mergulham em depressões da fenda, os bolsos, e funcionam como #termo-nota[resíduos-âncora][aminoácidos do peptídeo que se encaixam em bolsos específicos da fenda do MHC e sustentam a ligação, sem serem lidos pelo TCR] — são eles que sustentam a ligação, e não são vistos pelo linfócito. Outros apontam para cima, para fora da fenda, e é essa face que o TCR toca. Ao mesmo tempo, as bordas da fenda expõem os resíduos que mais variam entre pessoas, os resíduos polimórficos da própria molécula de MHC, e o TCR também encosta neles. Reconhecer, aqui, é reconhecer o par.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-37.png",
  largura: 56%,
  legenda: [O corte transversal do encontro. O resíduo-âncora do peptídeo afunda no bolso do MHC e prende; o resíduo de contato aponta para cima e é lido pelo receptor; e o resíduo polimórfico do MHC, na borda, é tocado junto. O TCR lê uma superfície mista.])

A consequência desse arranjo é maior do que parece. Como o encaixe depende de poucas posições de ancoragem, uma mesma molécula de MHC consegue carregar não um peptídeo, mas milhares de peptídeos diferentes — todos os que, por acaso, tenham os aminoácidos certos nas posições certas. Esse conjunto de exigências é o motivo de ligação daquela molécula. Peptídeos derivados de proteínas completamente distintas, de vírus diferentes ou de proteínas próprias, competem pela mesma fenda desde que respeitem o motivo. Daí decorre um raciocínio que reaparece na PARTE III e explica muita coisa em imunologia clínica: o alelo de MHC que uma pessoa herdou determina qual repertório de peptídeos ela consegue mostrar — e, portanto, contra quais fragmentos de um mesmo micro-organismo ela consegue montar resposta.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-43.png",
  largura: 74%,
  legenda: [Motivo de ancoragem em duas moléculas de MHC de classe I. Peptídeos de origens sem relação alguma — ovalbumina, vírus da influenza, proteínas de camundongo — ocupam a mesma fenda porque compartilham os aminoácidos das posições de ancoragem, destacadas em amarelo. O resto da sequência é livre.])

#subtopico("2.2 — Duas classes, duas arquiteturas, dois tamanhos de peptídeo")

Existem duas moléculas de MHC, e a diferença entre elas começa na contagem de cadeias. A molécula de classe I é formada por uma única cadeia α, dobrada em três domínios globulares — α1, α2 e α3 — associada a uma proteína acessória pequena, a #termo-nota[β2-microglobulina][cadeia acessória invariável que se associa à cadeia α da classe I e é indispensável para que a molécula se dobre corretamente e alcance a superfície]. A fenda é construída pelos domínios α1 e α2, e suas extremidades são fechadas, como uma canaleta com paredes nas duas pontas. A molécula de classe II é formada por duas cadeias distintas, α e β, e a fenda nasce da aproximação dos domínios α1 e β1, com as extremidades abertas.

#figura-lateral("/figuras/imuno-20-mhc-processamento-apresentacao/slide-39.png",
  lado: "right",
  largura-figura: 42%,
  texto: [Vistas de cima, as duas moléculas mostram a diferença de imediato. Na classe I, à esquerda, quase todo o corpo é de uma cadeia só (em branco), com o peptídeo em vermelho encaixado num sulco curto; na classe II, à direita, duas cadeias de cores diferentes se encontram e o peptídeo atravessa a fenda de ponta a ponta, escapando pelas bordas.],
  legenda: [Classe I e classe II vistas de cima, com o peptídeo em vermelho.])

Dessa arquitetura sai a consequência que governa toda a PARTE III. Com as pontas fechadas, a fenda da classe I comporta um peptídeo curto e inteiro, de oito a dez aminoácidos, que precisa caber por completo. Com as pontas abertas, a fenda da classe II acomoda um peptídeo mais longo, tipicamente de treze a dezoito aminoácidos, cujas extremidades simplesmente sobram para fora. Se os peptídeos têm tamanhos sistematicamente diferentes, é porque foram gerados por processos de corte diferentes — e é por isso que existem duas maquinarias de processamento distintas, cada uma alimentando uma das classes.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-66.png",
  largura: 76%,
  legenda: [O contraste organizado. Repare que o tamanho do peptídeo não é uma curiosidade: é o resultado direto de a fenda ser fechada ou aberta, e é o que obriga cada classe a ser abastecida por uma via de processamento própria.])

A β2-microglobulina merece um parágrafo próprio porque explica um comportamento da classe I. Ela é invariável, igual em todas as pessoas, e nem sequer é codificada dentro do complexo MHC — vem de outro cromossomo. Sua função é estrutural: sem ela, a cadeia α não se dobra de maneira estável e a molécula não completa a montagem, ficando retida dentro da célula. Guardar isso ajuda a entender por que a classe I é, entre as duas, a mais dependente de ter todas as peças reunidas antes de subir para a superfície.

#subtopico("2.3 — O correceptor emparelha classe com linhagem, e o timo impõe a restrição")

Emparelhar cada classe com um tipo de linfócito é o que transforma duas arquiteturas em duas linhas de comunicação separadas. O linfócito que expressa #sigla("CD8", [correceptor do linfócito T citotóxico, que se liga ao domínio α3 da molécula de MHC de classe I]) tem, ao lado do TCR, uma molécula que se liga ao domínio α3 da classe I; o linfócito que expressa #sigla("CD4", [correceptor do linfócito T auxiliar, que se liga ao domínio β2 da molécula de MHC de classe II]) tem uma molécula que se liga ao domínio β2 da classe II. Repare onde esses correceptores encostam: em domínios que não variam entre pessoas e ficam longe da fenda. Eles não participam da escolha do peptídeo — eles estabilizam o encontro e trazem para perto a maquinaria de sinalização, garantindo que o linfócito certo converse com a classe certa.

#atencao-box("O par classe-correceptor é o eixo de tudo o que vem depois",
  [O erro de trocar as duas linhas contamina cada raciocínio adiante, porque as duas classes são abastecidas por vias diferentes e produzem respostas diferentes. Classe I emparelha com CD8, é expressa por toda célula nucleada e mostra o que está sendo produzido dentro da célula — por isso o CD8 é a linhagem que mata células infectadas por vírus e células tumorais. Classe II emparelha com CD4, é privilégio das três apresentadoras profissionais e mostra o que veio de fora — por isso o CD4 é a linhagem que coordena. Quando a memória falhar, reconstrua pelo mecanismo, não pelo número: quem vigia o interior de toda célula precisa estar em toda célula.])

A especificidade do TCR é moldada no timo, e o resultado desse treinamento é uma exigência dupla que se chama restrição ao MHC. O linfócito T em maturação precisa reconhecer as moléculas de MHC do próprio indivíduo — se o TCR que ele gerou não encaixa em nenhuma molécula própria, ele é inútil e morre por falta de sinal. Mas ele também não pode reconhecer, dentro dessas moléculas próprias, os peptídeos próprios que ali circulam — se reconhece, é perigoso e é eliminado. O que sobrevive é a célula capaz de reconhecer peptídeo estranho apresentado por molécula própria. Trocar qualquer metade do par anula o reconhecimento: o mesmo peptídeo dentro de uma molécula de MHC de outra pessoa não é visto por aquele TCR.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-46.png",
  largura: 70%,
  legenda: [Três cenários. À esquerda, peptídeo x na molécula própria: reconhecimento. No meio, o mesmo peptídeo x numa molécula de MHC diferente: não há reconhecimento. À direita, molécula própria com outro peptídeo: também não. O TCR foi selecionado para o par, não para uma das partes.])

Há uma exceção que confirma a regra. Alguns produtos bacterianos e virais, chamados #termo-nota[superantígenos][toxinas que se ligam simultaneamente à face externa do MHC de classe II e a uma região lateral do TCR, ativando muitos clones de linfócitos T de uma só vez, sem processamento], não passam por nenhuma etapa de captura e corte. Eles grudam pelo lado de fora, grampeando a molécula de classe II a uma região lateral da cadeia β do TCR, e forçam a aproximação sem que haja peptídeo específico na fenda. Como o encaixe ignora a especificidade, não é um clone que responde, e sim uma fração enorme do repertório ao mesmo tempo.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-47.png",
  largura: 64%,
  legenda: [O superantígeno bacteriano e o viral fazem a mesma coisa: ligam-se por fora da fenda, unindo MHC de classe II e TCR sem depender do peptídeo apresentado. À direita, a estrutura real — o peptídeo, em vermelho, permanece no fundo, irrelevante para o encaixe.])

#clinica-box("Choque tóxico: quando a resposta é rápida demais para ter sido processada",
  [Uma infecção estafilocócica ou estreptocócica pode produzir, em horas, febre alta, hipotensão, exantema e falência de múltiplos órgãos. O tempo é o que denuncia o mecanismo: não houve prazo para capturar a bactéria, digeri-la, migrar até o linfonodo e expandir um clone específico — a resposta adquirida clássica leva dias. O que ocorre é ativação policlonal por superantígeno, com liberação maciça e simultânea de citocinas por uma fração enorme dos linfócitos T. O dano não vem da bactéria diretamente, e sim da magnitude descontrolada da resposta que ela desencadeou por atalho.])

#subtopico("2.4 — HLA: duas coleções herdadas inteiras, e o sistema mais variável do genoma")

Em seres humanos, o complexo principal de histocompatibilidade recebe o nome de #sigla("HLA", [antígeno leucocitário humano — o nome do complexo MHC nos seres humanos]). Os genes ficam agrupados numa região do cromossomo 6, organizados em blocos: os loci de classe I, que geram as moléculas HLA-A, HLA-B e HLA-C, e os loci de classe II, que geram HLA-DR, HLA-DP e HLA-DQ. Vale notar, olhando o mapa dessa região, que ela abriga também genes que não são moléculas apresentadoras — genes de subunidades do proteassoma e dos transportadores de peptídeo, além de proteínas do sistema complemento e citocinas. A maquinaria que fabrica o peptídeo está codificada ao lado da molécula que o carrega, e a PARTE III mostra o quanto isso é coerente.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-40.png",
  largura: 70%,
  legenda: [O complexo HLA no cromossomo 6. À direita, os loci de classe I (A, B, C); à esquerda, os de classe II (DP, DQ, DR); no meio, a região dita de classe III, com complemento e citocinas. Note os genes de proteassoma e de transportadores encaixados junto aos de classe II.])

Cada pessoa herda esse bloco inteiro de cada genitor. O conjunto ligado — um HLA-A, um B, um C, um DR, um DP, um DQ — que vem de um único genitor é um #termo-nota[haplótipo][o conjunto de alelos HLA fisicamente ligados no mesmo cromossomo, herdado em bloco de um dos genitores]. Cada indivíduo tem dois haplótipos, e a expressão é codominante: os alelos dos dois se manifestam ao mesmo tempo, na mesma célula. Não há alelo silenciado. Na prática, uma única célula exibe simultaneamente moléculas de classe I derivadas de ambos os haplótipos, e o mesmo vale para as de classe II — o que multiplica a variedade de peptídeos que aquela pessoa consegue mostrar. Entre irmãos, como cada um herda uma combinação dos mesmos dois pares de haplótipos, a chance de dois irmãos serem idênticos nos dois haplótipos é de um em quatro; de compartilharem apenas um, de um em dois.

O segundo eixo de variação é populacional. Para cada um desses loci existem, na espécie humana, centenas a milhares de alelos diferentes, e a variação se concentra justamente nos resíduos que formam a fenda e as bordas — exatamente os que decidem qual peptídeo ancora e o que o TCR toca. É o sistema mais polimórfico do genoma humano, e o motivo é adaptativo: se toda a população apresentasse os mesmos peptídeos, um único patógeno capaz de escapar daquele repertório poderia varrer a espécie inteira. Vale separar dois conceitos que costumam se embaralhar: poligenia é ter vários genes diferentes de MHC no mesmo indivíduo; polimorfismo é ter muitos alelos possíveis para cada um desses genes na população.

#clinica-box("Por que existe banco de doadores de medula",
  [O que salva o transplante de células-tronco hematopoéticas é o grau de identidade HLA entre doador e receptor, porque os linfócitos T do enxerto leem as moléculas de MHC do receptor como o par errado e atacam seus tecidos. A busca começa entre irmãos, onde há um em quatro de identidade completa de haplótipos, e frequentemente fracassa: famílias pequenas tornam provável que nenhum irmão seja idêntico. Aí a busca vai para bancos com milhões de doadores cadastrados, e ainda assim pode não haver par — não por falha do sistema, e sim porque o polimorfismo do HLA é a maior barreira genética entre duas pessoas quaisquer. O mesmo mecanismo que protege a população de um patógeno único é o que dificulta encontrar doador.])

#parte-title("PARTE III — Processar: as duas vias que fabricam o peptídeo")

#subtopico("3.1 — Não é quem é o agressor que decide a via, é onde a proteína está")

A PARTE II fechou com uma pendência mecanística: se a fenda da classe I é curta e fechada e a da classe II é longa e aberta, os peptídeos precisam ser produzidos por duas maquinarias diferentes. Elas existem, funcionam em paralelo dentro da mesma célula e são separadas por um critério só — o compartimento em que a proteína de origem se encontra no momento em que é degradada.

Uma proteína que está no citosol é degradada no citosol, por um complexo proteolítico próprio, e os fragmentos curtos que saem daí abastecem a classe I. É o caso de tudo o que a célula fabrica dentro de si: proteínas próprias em renovação normal, proteínas virais produzidas pela maquinaria sequestrada por um vírus e proteínas tumorais mutadas ou superexpressas. Faz sentido que essa via alimente o CD8, a linhagem que mata: mostrar o que se produz por dentro é a única forma de uma célula qualquer denunciar que foi tomada, e a única forma de o sistema imune saber que ela precisa ser eliminada.

Uma proteína que entrou por endocitose ou fagocitose está dentro de uma vesícula, e é degradada ali quando essa vesícula se funde com um lisossomo. Os fragmentos maiores gerados nesse ambiente abastecem a classe II, e o interlocutor é o CD4, a linhagem que coordena. Também faz sentido: o que veio de fora, em geral, é material extracelular que precisa ser combatido por anticorpo e por fagócito ativado, e não por destruição da célula que o engoliu.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-69.png",
  largura: 78%,
  legenda: [As duas vias em esquema. Em cima, a via citosólica: antígeno endógeno, marcação por ubiquitina, proteassoma, transporte por TAP até o retículo, complexo com classe I. Embaixo, a via endocítica: antígeno exógeno, endocitose ou fagocitose, compartimentos endocíticos, complexo com classe II. Repare que peptídeos podem simplesmente terminar como aminoácidos — nem todo fragmento vira apresentação.])

O ponto que mais escapa é que a via não é escolhida pela identidade do agente. Um vírus cujas proteínas estão sendo sintetizadas no citoplasma segue a via citosólica; o mesmo vírus, se for capturado já montado dentro de uma vesícula por uma célula que não está infectada, segue a via endocítica. O agente é o mesmo, o destino é outro, porque o compartimento é outro.

#subtopico("3.2 — Via citosólica: etiqueta, proteassoma, TAP e montagem no retículo")

A degradação de proteínas no citosol é uma rotina permanente da célula, e a apresentação por classe I é um aproveitamento inteligente dessa rotina. Proteínas defeituosas, envelhecidas ou simplesmente em excesso recebem uma etiqueta de #termo-nota[ubiquitina][pequena proteína acoplada em cadeia a outra proteína, funcionando como endereçamento para degradação pelo proteassoma], que não destrói nada por si — apenas endereça. A proteína etiquetada é conduzida ao #termo-nota[proteassoma][complexo proteolítico citosólico em forma de barril, que corta proteínas marcadas em peptídeos de poucos aminoácidos], um cilindro oco cujo interior guarda os sítios que cortam. O produto são fragmentos curtos, de tamanho compatível com a fenda fechada da classe I. Vale notar um refinamento: quando a célula está num ambiente inflamatório e recebe #sigla("IFN-γ", [interferon gama — citocina que reprograma a célula para apresentar melhor por MHC de classe I]), ela troca algumas subunidades catalíticas do proteassoma por outras, e o complexo resultante passa a cortar preferencialmente em posições que geram peptídeos com a extremidade certa para as etapas seguintes. A célula não só apresenta mais em inflamação — ela apresenta melhor.

O problema seguinte é geográfico. O peptídeo foi gerado no citosol, mas a molécula de classe I está sendo montada dentro do #sigla("RE", [retículo endoplasmático — compartimento onde proteínas de membrana são sintetizadas e montadas antes de seguir para a superfície]), e as duas coisas estão separadas por uma membrana. A travessia é feita por um transportador da membrana do retículo, o #sigla("TAP", [transportador associado ao processamento de antígenos — bomba da membrana do retículo que leva peptídeos do citosol para o interior do retículo]), formado por duas subunidades e dependente de #sigla("ATP", [adenosina trifosfato — moeda energética da célula]). Não é difusão: é bombeamento ativo, com gasto de energia, de peptídeos selecionados do citosol para dentro do retículo.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-68.png",
  largura: 80%,
  legenda: [A via completa em cinco passos: proteína no citosol, ubiquitinação e degradação pelo proteassoma, transporte pelo TAP, montagem do complexo peptídeo-classe I no retículo com a cadeia α e a β2-microglobulina, e exportação pelo Golgi em vesícula até a superfície, onde o linfócito T CD8 encontra o complexo pronto.])

Dentro do retículo, a cadeia α recém-sintetizada e a β2-microglobulina aguardam num complexo de moléculas auxiliares que as mantêm parcialmente dobradas e posicionadas junto ao poro do TAP, prontas para receber o peptídeo assim que ele chegar. A regra que fecha a via é rígida e vale ser fixada: a molécula de classe I só é liberada do retículo depois que a fenda é ocupada. Sem peptídeo, o conjunto não se estabiliza e fica retido. Uma vez carregada, a molécula segue pelo Golgi dentro de uma vesícula até a membrana plasmática, onde permanece exposta. O que chega à superfície é, portanto, sempre um complexo completo — molécula, cadeia acessória e peptídeo.

#clinica-box("Vírus que fecham a porta do retículo",
  [Vários vírus de latência longa, como os da família do herpes, codificam proteínas que bloqueiam o TAP ou retêm a classe I recém-montada. O efeito é direto e explica a estratégia: sem peptídeo entrando no retículo, a molécula de classe I não se estabiliza, não sobe para a superfície, e a célula infectada deixa de exibir o que está produzindo. O linfócito T CD8 passa por ela sem nada para reconhecer, e a infecção se mantém silenciosa por anos. Repare que a evasão não ataca o linfócito — ela desliga a via de apresentação, o que é bem mais eficiente do que enfrentar a resposta depois de deflagrada.])

#subtopico("3.3 — Via endocítica: um tampão na fenda até a hora certa")

A molécula de classe II tem um problema que a de classe I não tem, e entender esse problema é entender a via inteira. Ela também é montada no retículo endoplasmático — só que o retículo é justamente o compartimento cheio de peptídeos recém-bombeados pelo TAP, destinados à classe I, e é atravessado o tempo todo por proteínas próprias em síntese. Se a fenda da classe II saísse aberta de fábrica, ela seria ocupada ali mesmo, por peptídeos próprios, e chegaria à superfície apresentando material do próprio corpo a linfócitos CD4 — exatamente a linhagem cuja ativação indevida desencadeia autoimunidade.

A solução é ocupar a fenda antes que qualquer outra coisa a ocupe. Ainda no retículo, uma proteína chamada #termo-nota[cadeia invariante][proteína que ocupa a fenda da classe II recém-sintetizada, impedindo a ligação de peptídeos no retículo e endereçando a molécula ao compartimento vesicular] se encaixa na fenda e a mantém bloqueada. Ela cumpre duas funções ao mesmo tempo: tapa a fenda e funciona como endereço, dirigindo a molécula de classe II para o compartimento vesicular onde o antígeno de fora está sendo digerido. Quando as duas correntes se encontram — a vesícula com o antígeno digerido e a molécula de classe II com a fenda tampada —, as proteases do ambiente digerem também a cadeia invariante, e o que sobra dela é um fragmento curto ainda alojado na fenda, chamado #termo-nota[CLIP][fragmento residual da cadeia invariante que permanece na fenda da classe II até ser removido, liberando o espaço para o peptídeo antigênico].

#confusao-prevista(
  titulo: "A cadeia invariante não é o antígeno — ela é o que impede o antígeno errado",
  aluno_acha: [que a cadeia invariante e o CLIP são peptídeos apresentados ao linfócito CD4],
  mecanismo: [os dois são tampões temporários. A cadeia invariante existe para que nenhum peptídeo do retículo ocupe a fenda da classe II, e o CLIP é o resto dela depois da digestão. Ambos precisam sair para que a apresentação aconteça — o que chega ao CD4 é o peptídeo do antígeno externo que tomou o lugar deles.],
)

A troca final não é espontânea. Uma molécula acessória da mesma família, o HLA-DM, atua como editor: ela desestabiliza o CLIP, favorece sua saída e permite a entrada dos peptídeos disponíveis, dando preferência aos que se ligam com mais firmeza. O resultado é que a molécula de classe II não sobe carregando qualquer coisa, e sim o peptídeo que forma o complexo mais estável — o que dura mais tempo na superfície e tem mais chance de encontrar o clone certo. Só depois dessa edição a classe II segue para a membrana plasmática, onde exibe ao linfócito CD4 um fragmento do que veio de fora.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-57.png",
  largura: 62%,
  legenda: [As duas correntes que se encontram. Pela esquerda, a classe II sai do Golgi com a cadeia invariante ocupando a fenda; por cima, o antígeno externo entra por endocitose e é digerido. No compartimento comum, o DM opera a troca, e o complexo editado é levado à superfície.])

#mini-resumo[A classe I é carregada no retículo com peptídeo trazido do citosol pelo TAP, e só sai quando a fenda está ocupada. A classe II sai do retículo com a fenda tampada de propósito e só é carregada na vesícula, depois que o DM remove o CLIP. Duas soluções opostas para o mesmo risco: apresentar o peptídeo errado.]

#subtopico("3.4 — A exceção que resolve um impasse, e por que apresentar ainda não é ativar")

A separação limpa entre as duas vias cria um impasse prático. Para se tornar citotóxico e matar células infectadas, o linfócito T CD8 precisa de ajuda do CD4 — e essa ajuda funciona melhor quando os dois são estimulados pela mesma apresentadora, ao mesmo tempo e no mesmo lugar. Só que a célula dendrítica que fagocita uma célula infectada por vírus está, pelas regras da PARTE III, condenada a processar aquele material pela via endocítica e apresentá-lo apenas por classe II, isto é, apenas ao CD4. O CD8 ficaria de fora justamente na infecção viral, que é o alvo natural dele.

Algumas células dendríticas resolvem isso com uma capacidade especial: parte do conteúdo do fagossomo escapa para o citosol. Uma vez ali, aquelas proteínas de origem externa passam a ser tratadas como qualquer proteína citosólica — vão ao proteassoma, atravessam pelo TAP, entram no retículo e são montadas em classe I. É a #termo-nota[apresentação cruzada][capacidade de algumas células dendríticas de desviar antígeno capturado do exterior para a via citosólica, apresentando-o em MHC de classe I ao linfócito T CD8]. A mesma célula passa então a apresentar por classe II ao CD4 e por classe I ao CD8, e os dois linfócitos são ativados lado a lado — o CD4 fornecendo ao CD8 o estímulo que o torna citotóxico. A exceção não desfaz a regra do compartimento: ela cria uma passagem entre compartimentos.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-59.png",
  largura: 66%,
  legenda: [Via endógena à esquerda e via exógena à direita, na mesma célula. A seta tracejada no centro é a apresentação cruzada: material capturado de fora atravessa para o citosol e entra na via do proteassoma, terminando em classe I e em apresentação ao linfócito citotóxico.])

Falta um último passo, e ele muda o desfecho de tudo o que foi construído até aqui. O encaixe entre TCR e o complexo peptídeo-MHC é chamado de primeiro sinal, e ele sozinho não ativa o linfócito. A célula apresentadora precisa exibir, na mesma superfície, moléculas coestimuladoras que se ligam a receptores do linfócito — a mais conhecida é a família B7, que encontra o #sigla("CD28", [receptor de coestimulação do linfócito T, que se liga às moléculas B7 da célula apresentadora e fornece o segundo sinal]) da célula T — e moléculas de adesão que mantêm as duas coladas por tempo suficiente. O conjunto forma uma zona organizada de contato, a sinapse imunológica. Esse segundo sinal é o que autoriza a divisão celular e a diferenciação.

#figura-nebli("/figuras/imuno-20-mhc-processamento-apresentacao/slide-61.png",
  largura: 66%,
  legenda: [A sinapse imunológica. No centro, o primeiro sinal: peptídeo, MHC, TCR e CD3, com o correceptor CD4 ou CD8. Ao redor, os pares de coestimulação e adesão — B7 com CD28, CD40 com CD40L, moléculas de adesão que sustentam o contato. Sem a periferia, o centro não basta.])

#atencao-box("Sinal 1 sem sinal 2 não é ausência de resposta — é desligamento ativo",
  [O linfócito que encontra seu peptídeo apresentado por uma célula que não exibe coestimulação não fica neutro: ele entra em anergia, um estado de não-resposta duradouro em que deixa de reagir mesmo diante de uma apresentação completa depois. O desenho é intencional. Moléculas coestimuladoras só aparecem em quantidade na apresentadora que foi ativada pelo reconhecimento inato — aquela que viu um padrão de patógeno pelos seus receptores. Assim, tecido próprio apresentado na ausência de perigo silencia o clone em vez de despertá-lo, e o segundo sinal se torna a assinatura de que existe um agressor real. É o inato autorizando o adquirido.])

Autorizado a responder, o linfócito T CD4 expande clonalmente e se diferencia em subtipos funcionais, sob influência das citocinas produzidas pela própria apresentadora — um terceiro sinal. Uma dendrítica que reconheceu bactéria intracelular induz um perfil que produz interferon gama e ativa o macrófago; uma que reconheceu helminto induz outro perfil, produtor de interleucina 4, adequado a parasita extracelular. A instrução que o linfócito recebe sobre em que se transformar é, no fim, uma leitura do que foi reconhecido lá atrás pelos receptores do inato. É a mesma informação, transportada por três etapas, chegando ao ponto em que vira resposta.

#conclusao-box[
  Um princípio único sustenta as três PARTES: o linfócito T é cego para o antígeno e depende de que outra célula transforme uma molécula em fragmento e um fragmento em superfície reconhecível. Tudo o mais é consequência dessa condição. O mecanismo nuclear é a fenda do MHC carregando um peptídeo cujos resíduos-âncora prendem e cujos resíduos de contato são lidos pelo TCR junto com os resíduos polimórficos da própria molécula — e é a arquitetura dessa fenda que impõe o resto: fechada e curta na classe I, abastecida pelo proteassoma e pelo TAP a partir do citosol, emparelhada com o CD8 e presente em toda célula nucleada; aberta e longa na classe II, abastecida na vesícula depois que o DM remove o tampão de CLIP, emparelhada com o CD4 e restrita a três apresentadoras profissionais. A clínica retomada mostra o quanto isso é concreto: os vírus que bloqueiam o TAP sobrevivem porque uma classe I sem peptídeo não chega à superfície e a célula infectada perde a única forma de denunciar o que produz; o superantígeno adoece em horas porque grampeia MHC e TCR por fora da fenda e ativa de uma vez o que a apresentação normal ativaria clone a clone em dias; e a busca por doador compatível é difícil porque o polimorfismo que protege a população faz de cada pessoa um repertório apresentador quase único. Daqui em diante, a pergunta se desloca do reconhecimento para o efeito: o que o linfócito T faz depois de ativado — como se diferencia nos subtipos que produzem citocinas distintas, como um deles ajuda o linfócito B a fabricar anticorpo e como outro se torna capaz de matar a célula que está apresentando. O que se aprendeu aqui é a etapa que decide qual desses caminhos será tomado.
]
