#import "../typst-template/nebli_v2_apostila.typ": *

#discursiva("Q1",
  [O esôfago tem músculo estriado esquelético no terço superior e músculo liso no terço inferior. Explique o que essa troca de tecido significa para o controle da deglutição e por que ela precisa acontecer justamente nesse segmento do tubo digestório.],
  [A deglutição começa como ato voluntário: a pessoa decide engolir, e o músculo estriado obedece a essa decisão. Ela precisa, porém, terminar como processo automático, porque ninguém empurra conscientemente o bolo até o estômago. O esôfago é o trecho em que essa passagem de comando acontece, e por isso a parede muda de tecido no meio do caminho — estriado no terço superior, misto no médio, liso no inferior. A consequência é que a onda peristáltica, uma vez iniciada, prossegue sozinha; a gravidade ajuda, mas não é necessária, e por isso a deglutição se completa mesmo em decúbito.])

#discursiva("Q2",
  [Na junção esofagogástrica não existe anel muscular espesso comparável ao piloro. Explique por que, ainda assim, o conteúdo gástrico normalmente não sobe, e o que se perde quando o hiato esofágico se alarga.],
  [A competência ali é somada, não anatômica. Quatro fatores atuam juntos: o tônus da musculatura lisa distal, a pinça do pilar direito do diafragma sobre o esôfago no hiato, o ângulo agudo de entrada, que se fecha mais quando o fundo gástrico se enche, e a compressão do curto segmento intra-abdominal pela pressão positiva do abdome. Quando o ligamento frenoesofágico afrouxa e a junção desliza para o tórax, perdem-se três desses fatores de uma vez: some o segmento intra-abdominal, a pinça diafragmática deixa de coincidir com a zona de alta pressão, e o ângulo se abre.])

#discursiva("Q3",
  [Explique por que uma úlcera da face anterior e uma úlcera da face posterior do estômago produzem quadros clínicos diferentes, e nomeie as estruturas que justificam cada desfecho.],
  [A diferença é de vizinhança. A face anterior olha para o diafragma, para o lobo esquerdo do fígado e, mais abaixo, para a cavidade peritoneal livre — a úlcera que a atravessa despeja conteúdo e ar nessa cavidade, produzindo peritonite química e o ar livre visível sob a cúpula diafragmática. A face posterior olha para o leito gástrico, através da bolsa omental: pâncreas, baço, artéria esplênica, rim e suprarrenal esquerdos, cólon transverso. Ali não há cavidade livre para onde extravasar; a úlcera penetra no pâncreas e pode erodir a artéria esplênica, produzindo hemorragia digestiva alta.])

#discursiva("Q4",
  [Explique por que um único cálculo impactado na papila maior do duodeno é capaz de produzir icterícia e pancreatite ao mesmo tempo.],
  [Porque a anatomia uniu as duas vias antes da saída. O colédoco, que traz a bile, e o ducto pancreático, que traz as enzimas, convergem numa dilatação comum — a ampola hepatopancreática — imediatamente antes de desembocarem na papila maior, situada na parede posteromedial da segunda porção do duodeno. Um cálculo alojado nessa ampola bloqueia as duas drenagens no mesmo ponto. A bile represada reflui para o sangue e produz icterícia; o suco pancreático represado ativa as enzimas dentro da própria glândula, que passa a se autodigerir. Um obstáculo, duas vias, dois quadros simultâneos.])

#discursiva("Q5",
  [Explique como o padrão de arcadas e de vasos retos permite distinguir jejuno de íleo na peça anatômica, e por que essa leitura importa diante de uma isquemia mesentérica.],
  [Toda a irrigação vem da artéria mesentérica superior, que emite ramos jejunais e ileais dentro do mesentério. Esses ramos se anastomosam formando arcadas, e das arcadas partem os vasos retos que penetram a parede. No jejuno há poucas arcadas, grandes, com vasos retos longos atravessando janelas amplas de mesentério translúcido. No íleo há muitas arcadas curtas e sobrepostas, vasos retos curtos e gordura avançando até a borda da alça. A consequência prática é direta: no jejuno cada vaso reto irriga sozinho um território extenso, e ocluí-lo isquemia um segmento largo; no íleo, as arcadas em série criam caminhos colaterais que limitam a área comprometida. Ler o mesentério, portanto, informa qual segmento está acometido e quanto intestino está em risco.])
