#import "../typst-template/nebli_v2_apostila.typ": *

#intro-box[
Uma célula normal vive num equilíbrio estreito: recebe oxigênio, nutrientes e sinais de crescimento na medida certa, e mantém tamanho, número e função constantes. Quando alguma dessas variáveis muda — a carga de trabalho sobe, o hormônio some, o sangue diminui, um irritante químico se instala —, a célula tem três destinos possíveis. Pode se ajustar e alcançar um novo ponto de equilíbrio, e isso é *adaptação*. Pode não conseguir se ajustar e entrar em sofrimento ainda reversível. Ou pode ultrapassar o ponto de retorno e morrer. Este material percorre o primeiro desses destinos em duas frentes que a Patologia trata como capítulos irmãos. A PARTE I cobre as adaptações que mudam *tamanho, número e identidade* da célula — hipertrofia, hiperplasia, atrofia e metaplasia. As PARTES II e III cobrem o que acontece quando a célula, adaptada ou não, passa a *guardar dentro de si* o que não consegue metabolizar ou exportar: gordura, proteína, glicogênio, pigmento e cálcio. O fio condutor é sempre o mesmo — todo achado morfológico que o microscópio revela é a marca visível de um desequilíbrio metabólico que veio antes.
]

#parte-title("PARTE I — A célula que se adapta: tamanho, número e identidade", primeira: true)

#subtopico("1.1 — Adaptação é o degrau entre o normal e a lesão")

A adaptação celular é uma alteração morfológica e funcional que a célula produz em resposta a um estímulo e que a leva a um *novo estado de equilíbrio*, preservando sua viabilidade e modulando sua função. Cada palavra dessa definição carrega peso. "Novo estado de equilíbrio" significa que a célula não está sofrendo continuamente: ela se reorganizou e agora é estável naquele novo patamar. "Preservando a viabilidade" significa que ela está viva e continuará viva enquanto o estímulo durar. E "modulando a função" avisa que o preço da adaptação costuma ser funcional — o órgão adaptado quase nunca funciona exatamente como o original.

O que separa a adaptação da lesão é justamente essa estabilidade. Diante de um estresse, a célula tenta primeiro se adaptar; se a intensidade ou a duração do estímulo excedem a capacidade adaptativa, ela entra em *lesão reversível* — um estado instável, com inchaço, perda de microvilosidades, dispersão de ribossomos, do qual ela só volta se o estímulo for removido a tempo. Se o estresse persiste, chega-se ao ponto sem retorno, marcado pela incapacidade de restaurar a produção de #sigla("ATP", [adenosina trifosfato — moeda energética da célula]) e pela ruptura da integridade das membranas; daí em diante o desfecho é morte celular, por necrose ou por apoptose. Adaptação, lesão reversível e lesão irreversível não são três doenças diferentes: são três posições ao longo de um mesmo contínuo, e a posição depende da relação entre a agressão e a reserva funcional daquela célula.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-02.png", largura: 60%, legenda: [O contínuo que organiza toda a aula. Repare que da célula normal partem duas setas: a do estresse, que leva à adaptação, e a do estímulo lesivo, que leva à lesão celular. A seta pontilhada entre adaptação e lesão é a que interessa — quando a célula é incapaz de se adaptar, ela cai no ramo da lesão; e só a lesão grave e progressiva desemboca em morte.])

Antes de percorrer os tipos de adaptação, é preciso um dado que decide *qual* adaptação é possível em cada órgão: a capacidade proliferativa do tecido. Aqui a divisão em três categorias discretas é mais clara que a prosa. Os *tecidos lábeis* se dividem continuamente ao longo de toda a vida, porque perdem células o tempo todo e precisam repor — são as superfícies epiteliais da pele, da cavidade oral, dos ductos excretores, do #sigla("TGI", [trato gastrointestinal]), do útero, da vagina e do trato urinário, além das células hematopoiéticas da medula óssea. Os *tecidos estáveis* estão parados em G0, quiescentes, mas guardam a capacidade de voltar a se dividir quando um sinal apropriado chega — é o caso do parênquima do fígado, do pâncreas e do rim, e das células de origem mesenquimal como fibroblasto e músculo liso. Os *tecidos permanentes* perderam essa capacidade: neurônios, músculo esquelético e músculo cardíaco não repõem população significativa depois de formados.

Essa classificação não é catálogo decorativo. Ela explica por que um estímulo idêntico produz respostas diferentes conforme o órgão: uma sobrecarga de trabalho imposta ao endométrio gera mais células, enquanto a mesma lógica de sobrecarga imposta ao ventrículo esquerdo só pode gerar células maiores — o miocárdio é permanente e a via da multiplicação está fechada para ele.

#mini-resumo[A adaptação leva a um novo equilíbrio estável com a célula viva; a lesão é instabilidade. E o tipo de tecido (lábil, estável ou permanente) determina se a adaptação disponível será aumentar o número de células ou apenas o tamanho delas.]

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-04.png", largura: 65%, legenda: [O mesmo miócito em três destinos. À esquerda, a resposta adaptativa ao aumento de carga: a célula fica maior, o núcleo aumenta, e a peça macroscópica mostra parede ventricular espessa com cavidade preservada. À direita, o caminho da lesão: o miócito lesado de forma reversível acumula vacúolos, e a peça de morte celular mostra a parede afinada e a cavidade dilatada.])

#subtopico("1.2 — Hipertrofia: a célula cresce porque foi mandada crescer")

Hipertrofia é o aumento do tamanho das células, que resulta em aumento do tamanho do órgão — e a definição precisa incluir o que ela *não* é: não há células novas, há células maiores. O ganho de volume vem de síntese aumentada de proteínas estruturais e de organelas, não de divisão. Por isso a hipertrofia é a única adaptação de crescimento disponível para tecidos permanentes, e por isso o coração e o músculo esquelético respondem a demanda exclusivamente engrossando as fibras que já existem.

A hipertrofia é fisiológica quando nasce de aumento da demanda funcional ou de estímulo hormonal e de fatores de crescimento. O músculo esquelético do atleta engrossa porque a carga mecânica repetida sinaliza síntese proteica; o útero da gestante multiplica sua massa sob estrogênio, combinando hipertrofia das fibras musculares lisas com hiperplasia delas. É patológica quando nasce de uma doença: a hipertrofia do miocárdio na hipertensão arterial ou na doença valvar aórtica é o exemplo canônico — o ventrículo precisa gerar pressão maior a cada sístole, e responde engrossando a parede.

O mecanismo molecular é onde a hipertrofia deixa de ser descrição e vira raciocínio. Dois desencadeantes principais chegam ao miócito: o *estiramento mecânico* da fibra, detectado por sensores de membrana ligados à matriz extracelular (as integrinas são as candidatas), e a *ativação de receptores adrenérgicos* e de outros agonistas humorais, entre eles a angiotensina II e a endotelina, além de fatores de crescimento como o #sigla("IGF-1", [fator de crescimento semelhante à insulina tipo 1]). Ambos convergem para vias de transdução de sinal que terminam ativando um punhado de #termo-nota[fatores de transcrição][proteínas que, uma vez ativadas, entram no núcleo e ligam ou desligam conjuntos inteiros de genes de uma só vez] — GATA4, NFAT e MEF2 — e é aí, nesse ponto de convergência, que se concentra o interesse terapêutico: bloquear a via a montante desses fatores é bloquear a hipertrofia patológica antes que ela se instale.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-11.png", largura: 75%, legenda: [A cascata da hipertrofia, do estímulo ao desfecho. Três entradas — estiramento mecânico, agonistas adrenérgicos e fatores de crescimento — convergem para os mesmos fatores de transcrição (círculo vermelho, o ponto de interesse terapêutico). A saída se divide em três ramos: indução de genes embrionários/fetais, síntese de proteínas contráteis e produção de mais fatores de crescimento, que realimentam a via.])

Os fatores de transcrição ativados abrem três programas gênicos distintos. O primeiro é a *re-expressão de genes embrionários*, que estavam silenciados desde a vida fetal. O miócito hipertrofiado volta a produzir fator natriurético atrial, um hormônio de ação diurética que reduz a carga hemodinâmica ao promover perda de sódio e água — ou seja, a própria célula sobrecarregada emite o sinal que tenta aliviar sua sobrecarga. Ainda nesse programa fetal ocorre a troca de isoformas da cadeia pesada de miosina: a forma adulta αMHC é substituída pela forma fetal βMHC, que tem *menor* atividade ATPásica. O resultado é contra-intuitivo e vale fixar — a contração fica mais lenta, porém mais econômica em ATP por unidade de força. O segundo programa é o dos *genes de resposta imediata*, que produzem mais fatores de crescimento e mantêm a via ligada. O terceiro é o dos *genes de proteínas constitutivas*, que fornecem a matéria-prima do crescimento: miosina e α-actina, as peças do sarcômero novo.

#confusao-prevista(
  titulo: "Hipertrofia não é hiperplasia com outro nome",
  aluno_acha: [o aluno tende a usar os dois termos como sinônimos de "órgão aumentado", ou a supor que todo órgão que cresce faz as duas coisas ao mesmo tempo.],
  mecanismo: [são mecanismos diferentes com pré-requisitos diferentes. Hipertrofia = mais citoplasma por célula, sem divisão; disponível para *qualquer* tecido, inclusive os permanentes. Hiperplasia = mais células, por divisão; disponível *apenas* para tecidos lábeis e estáveis. O útero gravídico faz as duas porque o músculo liso é mesenquimal e estável; o ventrículo hipertenso só faz hipertrofia porque o miocárdio é permanente.],
)

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-09.png", largura: 62%, legenda: [Miocárdio normal (acima) e hipertrofiado (abaixo, à direita) na mesma escala. O que muda não é a quantidade de fibras no campo, e sim o diâmetro de cada uma e o tamanho dos núcleos, que ficam volumosos e retangulares — a assinatura microscópica de "mais citoplasma por célula, sem célula nova".])

Toda adaptação tem teto, e o da hipertrofia é o mais didático. Conforme a fibra engrossa, dois recursos deixam de acompanhar. A vascularização não cresce na mesma proporção, e a difusão de oxigênio da capilar até o centro da fibra passa a ser insuficiente; e o próprio maquinário de síntese proteica chega ao limite de sustentar uma massa cada vez maior. Nesse ponto começam as alterações degenerativas: o miócito sofre, morre, é substituído por fibrose. O coração perde complacência, dilata e evolui para insuficiência. A adaptação, que existia para preservar a função, terminou destruindo a função — e essa reviravolta é o motivo de a hipertrofia patológica ser tratada e não celebrada.

#clinica-box("Cardiopatia hipertensiva: a adaptação que vira doença", [A hipertensão arterial crônica impõe ao ventrículo esquerdo uma pós-carga aumentada a cada sístole. O miócito responde com hipertrofia concêntrica: sarcômeros novos são adicionados em paralelo, a parede engrossa e a cavidade *diminui*. A parede espessa normaliza a tensão sobre cada fibra e, por anos, o débito cardíaco se mantém. O preço aparece em duas frentes. A parede rígida enche pior na diástole, e a pressão de enchimento sobe até se transmitir para a circulação pulmonar — surge a dispneia. E o miocárdio espesso demanda mais oxigênio justamente quando a densidade capilar por grama de músculo caiu, o que o torna vulnerável à isquemia mesmo com coronárias pouco obstruídas. Quando fibras morrem e são trocadas por fibrose, o ventrículo passa a dilatar em vez de engrossar: é a passagem da hipertrofia compensada para a insuficiência cardíaca.])

#subtopico("1.3 — Hiperplasia: mais células, e ainda sob controle")

Se a hipertrofia é a resposta dos tecidos que não podem se dividir, a hiperplasia é a resposta dos que podem. Trata-se do aumento do número de células de um órgão por proliferação a partir de células maduras que reentram no ciclo e, em alguns casos, de células-tronco teciduais — em quase todo epitélio existe uma população de reserva ainda não especializada, e é dela que saem células novas quando o tecido precisa repor perda. O ponto que define a hiperplasia como adaptação, e não como tumor, é que ela é *dirigida por sinal*: enquanto o estímulo está presente a proliferação continua; retirado o estímulo, ela para.

A hiperplasia fisiológica se divide em duas modalidades pelo tipo de sinal. Na *hormonal*, um hormônio aumenta a massa funcional de um órgão-alvo: o epitélio glandular da mama prolifera na gravidez sob estrogênio e progesterona, o endométrio prolifera a cada ciclo, e a medula óssea aumenta a linhagem eritroide quando a eritropoetina sobe em resposta a sangramento ou a hipóxia. Na *compensatória*, o gatilho é a perda de massa: retirada uma porção do fígado, o remanescente prolifera até restaurar o volume funcional original. O fígado é o modelo experimental clássico dessa resposta — e a reposição é feita por hepatócitos maduros que saem de G0 e voltam ao ciclo, não por uma reserva de células-tronco especializada.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-16.png", largura: 68%, legenda: [Regeneração hepática após hepatectomia parcial. À esquerda, os lobos remanescentes restauram a massa do órgão. À direita, o eixo temporal: citocinas como TNF e IL-6 fazem o "priming", tirando o hepatócito de G0; só então os fatores de crescimento (HGF, TGF-α) empurram a célula para a replicação do DNA e a mitose. Repare que o processo tem freio próprio — os inibidores de crescimento, com o TGF-β à frente, encerram a proliferação quando a massa é recuperada.])

A hiperplasia patológica nasce quase sempre de estimulação hormonal excessiva ou de excesso de fatores de crescimento. O desequilíbrio entre estrogênio e progesterona produz hiperplasia do endométrio e sangramento uterino anormal; o estímulo androgênico sustentado produz a hiperplasia nodular da próstata; algumas infecções virais induzem proliferação epitelial que se manifesta como verrugas e pólipos, porque o próprio vírus fabrica fatores de crescimento ou desliga freios do ciclo celular. Há ainda a hiperplasia do tecido conjuntivo na cicatrização, em que fibroblastos e vasos proliferam sob fatores de crescimento liberados na inflamação.

A fronteira com a neoplasia merece cuidado nos dois sentidos. De um lado, hiperplasia patológica *não* é neoplasia: na neoplasia a célula deixou de obedecer aos sinais de partida e de parada da proliferação, e cresce de forma autônoma mesmo sem o estímulo original. De outro lado, hiperplasias são terreno fértil para neoplasias — uma população que está proliferando muito acumula mais erros de replicação do #sigla("DNA", [ácido desoxirribonucleico]) e tem mais chance de sofrer a mutação que quebra o controle. A hiperplasia endometrial é o exemplo mais direto dessa continuidade de risco.

#clinica-box("Hiperplasia prostática: sintoma mecânico, causa hormonal", [A próstata tem uma zona de transição que envolve a uretra prostática. Com o envelhecimento, a conversão de testosterona em di-hidrotestosterona dentro da própria glândula aumenta a sinalização androgênica local, e a resposta é hiperplasia de estroma e de epitélio glandular formando nódulos. O crescimento nodular comprime a uretra, e daí vêm os sintomas: jato fraco, esforço miccional, esvaziamento incompleto e, com o tempo, hipertrofia compensatória da parede da bexiga — repare que aqui uma adaptação de um órgão gera a adaptação de outro. Duas correções importantes: essa hiperplasia é da zona de transição, enquanto o carcinoma prostático nasce tipicamente da zona periférica, e a hiperplasia nodular *não* é a lesão precursora do carcinoma. Bloquear a enzima que produz a di-hidrotestosterona reduz o volume glandular justamente porque a proliferação depende do sinal — a marca da adaptação.])

#subtopico("1.4 — Atrofia: encolher é uma decisão de economia")

Um prédio que perde inquilinos fecha andares para não pagar conta de área vazia. A célula atrófica faz o mesmo: reduz o tamanho pela perda de substância celular, retraindo-se até um tamanho menor em que a sobrevivência é possível com o aporte disponível. Quando o processo envolve todas as células, o órgão inteiro fica atrófico. E o ponto central é este: as células *não estão mortas*. Elas têm menos mitocôndrias, menos retículo endoplasmático e menos miofilamentos, funcionam num patamar mais baixo — e continuam vivas e reversíveis se o estímulo trófico voltar.

#atencao-box("Atrofia não é morte celular", [A inversão mais cara desta aula é ler órgão atrófico como órgão em necrose. Atrofia é adaptação: a célula diminuiu deliberadamente sua demanda para caber no que recebe, e a redução envolve tanto queda de síntese quanto aumento controlado de degradação. Confundir os dois muda a leitura clínica inteira — um cérebro atrófico do idoso ou um músculo atrófico do acamado indicam perda de estímulo, não tecido morto, e a conduta é restaurar o estímulo (reabilitação, carga, inervação, hormônio), não tratar necrose. O corolário também vale: como a célula está viva, a atrofia é potencialmente reversível enquanto a causa for removível.])

As causas se organizam por qual sinal trófico foi retirado. A *diminuição de carga* pelo desuso atrofia músculo e osso do paciente acamado ou do membro imobilizado. A *perda de inervação* retira o estímulo trófico contínuo que o nervo motor fornece à fibra muscular, e produz atrofia mais rápida e mais profunda que a do simples desuso. A *isquemia* reduz o aporte de oxigênio e substrato, e é a causa da atrofia local — o rim que perde fluxo por estenose da artéria renal encolhe, e a chamada atrofia senil de cérebro e coração tem componente vascular importante. A *nutrição inadequada* atrofia por falta de substrato e, na caquexia associada a inflamação crônica e a neoplasias, por ação direta de citocinas como o #sigla("TNF", [fator de necrose tumoral]) sobre o músculo e sobre o apetite. A *perda de estímulo hormonal* atrofia o endométrio e a mama após a menopausa. E a *compressão tecidual* atrofia por um mecanismo que já conhecemos: comprimir é reduzir fluxo, e o que atrofia de fato é a isquemia resultante.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-20.png", largura: 58%, legenda: [Cérebro normal (à esquerda) e cérebro atrófico (à direita). Repare no que a atrofia produz macroscopicamente: os giros ficam estreitos e afilados, e os sulcos se alargam para ocupar o espaço perdido. O crânio não encolhe — o que sobra de espaço é preenchido por líquor, e por isso os ventrículos também se dilatam.])

No nível molecular, a atrofia é um balanço entre duas alavancas: síntese proteica diminuída e degradação proteica aumentada. A síntese cai porque o estímulo trófico e o aporte de nutrientes diminuíram. A degradação sobe principalmente pela *via ubiquitina-proteassoma*. A ubiquitina é uma proteína-etiqueta: enzimas ligases penduram várias delas na proteína-alvo, e essa cadeia funciona como um rótulo que significa "destruir". O proteassoma é o cilindro proteolítico que lê o rótulo, desenrola a proteína marcada e a corta em peptídeos curtos. Quando corticoides, hormônio tireoidiano, TNF ou #sigla("IL-1", [interleucina 1 — citocina pró-inflamatória]) atuam sobre a célula, o número de proteínas ubiquitinadas aumenta e a massa proteica cai; a insulina faz o contrário, empurrando a síntese. A segunda via de degradação é a #termo-nota[autofagia][processo em que a própria célula envolve organelas e porções de citoplasma numa vesícula de membrana dupla e as entrega ao lisossomo para digestão], que remove organelas inteiras quando o encolhimento precisa ser maior. Vale registrar que essa mesma via de proteólise é a que sustenta o catabolismo intenso observado em pacientes com neoplasias avançadas.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-23.png", largura: 60%, legenda: [A via ubiquitina-proteassoma. As enzimas E1, E2 e E3 transferem sucessivamente a ubiquitina até montar a cadeia sobre o substrato; a proteína poliubiquitinada é reconhecida pelo complexo 19S, desenrolada e digerida no núcleo 20S do proteassoma. A ubiquitina é reciclada — repare nas setas de retorno.])

Um par de termos vizinhos precisa ser separado aqui, porque a distinção é morfologicamente invisível e historicamente decisiva. Atrofia é perda de massa que o órgão *já teve*. #termo-nota[Hipoplasia][desenvolvimento incompleto de um órgão, que nunca alcançou o tamanho e a massa normais] é outra coisa: o órgão nunca se desenvolveu direito. E no extremo dessa falha de desenvolvimento está a #termo-nota[aplasia][ausência completa ou quase completa de um órgão por falha total de desenvolvimento embrionário]. Diante de um rim pequeno, portanto, o tamanho sozinho não fecha diagnóstico — é a história de desenvolvimento do órgão que separa as três possibilidades.

#clinica-box("Osteoporose: atrofia de um tecido que também é depósito", [O osso é tecido vivo em remodelação permanente, com osteoclastos reabsorvendo e osteoblastos depositando matriz. Quando a carga mecânica diminui (imobilização prolongada, ausência de peso) ou quando o estrogênio cai na menopausa, o equilíbrio pende para a reabsorção — e o resultado é #termo-nota[osteoporose][redução da massa óssea por unidade de volume, com matriz de composição normal, resultando em osso quantitativamente diminuído e frágil]. Repare no que a imagem histológica mostra: as trabéculas do osso esponjoso ficam finas, algumas se rompem e perdem conexão com as vizinhas, e o espaço medular aumenta. Não há material anormal depositado nem osso "doente" — há menos osso normal. Por isso a fratura de vértebra por compressão ou de colo de fêmur após queda banal é a manifestação clínica esperada: a arquitetura perdeu as vigas que distribuíam carga.])

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-26.png", largura: 62%, legenda: [Osso esponjoso vertebral normal (A) e osteoporótico (B). As trabéculas se afinam e perdem conexões transversais — a rede que distribuía carga vira um conjunto de hastes isoladas, e é por isso que a vértebra colapsa sob esforço que antes tolerava.])

#subtopico("1.5 — Metaplasia: trocar de identidade para aguentar o ambiente")

As três adaptações anteriores mudam quanto de célula existe. A metaplasia muda *que tipo* de célula existe: um tipo celular adulto e diferenciado é substituído por outro tipo celular adulto e diferenciado. A palavra-chave do mecanismo é reprogramação. Não se trata de uma célula madura que regride e depois se especializa em outra coisa — o que ocorre é a reprogramação genética das células-tronco de reserva do epitélio, que passam a receber um novo conjunto de sinais e a gerar uma linhagem diferente da original.

A lógica que governa a troca é de resistência ao ambiente. O novo tipo celular é mais capaz de suportar as condições hostis que se instalaram. O exemplo canônico é o epitélio respiratório do fumante: o epitélio colunar pseudoestratificado ciliado do brônquio é substituído por epitélio escamoso estratificado, que aguenta muito melhor a agressão química e térmica da fumaça. A troca funciona, no sentido em que impede a ulceração da mucosa — mas o preço é alto e mecanicamente óbvio: o epitélio escamoso não tem cílio nem célula caliciforme, de modo que a depuração mucociliar, principal defesa mecânica da via aérea, é perdida justamente onde ela mais faria falta. Adaptação, aqui como na hipertrofia, é troca de um problema por outro problema menor no curto prazo.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-29.png", largura: 72%, legenda: [Em A, o esquema da metaplasia escamosa: o epitélio colunar normal (à esquerda) é substituído por epitélio escamoso estratificado (à direita) sobre a mesma membrana basal. Em B, o correlato histológico. Em C, o princípio geral aplicado ao mesênquima — uma célula mesenquimal pluripotente pode ser dirigida para miotubo, fibroblasto, adipócito ou osteoblasto conforme os fatores de crescimento e a matriz do ambiente; é essa plasticidade de destino que a metaplasia explora.])

O mesmo raciocínio explica a metaplasia que ocorre na direção oposta. No esôfago distal exposto cronicamente ao refluxo ácido, o epitélio escamoso estratificado nativo — bom para atrito mecânico, ruim para ácido — é substituído por epitélio colunar do tipo intestinal, com células caliciformes produtoras de muco, que tolera pH baixo muito melhor. Repare que as duas trocas seguem a mesma regra e produzem resultados morfologicamente opostos: no brônquio o colunar vira escamoso, no esôfago o escamoso vira colunar. Quem manda não é uma direção preferencial, e sim qual epitélio resiste melhor ao agressor daquele local.

O ponto final é a fronteira com o câncer, e ela precisa ser dita com precisão. A metaplasia em si é adaptativa, organizada e reversível — retirado o estímulo, o epitélio original tende a se restabelecer. O problema aparece quando os estímulos persistem: a mesma sinalização que reprogramou a célula-tronco continua atuando sobre uma população em proliferação, e o acúmulo de alterações pode levar à #termo-nota[displasia][desarranjo da maturação epitelial com atipia nuclear, perda de polaridade e mitoses fora da camada basal — diferentemente da metaplasia, é lesão pré-maligna] e, adiante, à transformação maligna. Não é a metaplasia que causa o tumor; é a persistência do agressor sobre o tecido metaplásico que abre a porta.

#clinica-box("Esôfago de Barrett: metaplasia com vigilância", [No refluxo gastroesofágico crônico, o suco gástrico banha repetidamente a mucosa esofágica distal. A resposta adaptativa é a metaplasia intestinal: aparece epitélio colunar com células caliciformes onde deveria haver epitélio escamoso, e endoscopicamente isso se vê como língua de mucosa avermelhada subindo acima da junção esofagogástrica. Do ponto de vista sintomático o paciente pode até melhorar, porque o epitélio novo tolera o ácido. O motivo da vigilância endoscópica com biópsias é outro: essa população reprogramada e proliferativa, mantida sob agressão, é o solo em que pode surgir displasia e, dela, o adenocarcinoma de esôfago. A conduta reúne as duas ideias da PARTE: remover o estímulo, porque adaptação depende de sinal, e vigiar o tecido, porque estímulo persistente sobre tecido proliferativo acumula risco.])

#mini-resumo[As quatro adaptações respondem a perguntas diferentes sobre a mesma célula: hipertrofia muda o tamanho, hiperplasia muda o número, atrofia reduz os dois para caber no aporte, e metaplasia troca a identidade para resistir ao ambiente. Todas dependem de sinal, todas são reversíveis enquanto o sinal for removível, e todas cobram um preço funcional.]

#parte-title("PARTE II — Quando a célula acumula: a lógica geral, os lipídios e as proteínas")

#subtopico("2.1 — Quatro rotas levam ao mesmo achado: material guardado dentro da célula")

A PARTE I terminou com a célula ajustando tamanho, número e identidade para continuar viável. Há, porém, um segundo tipo de resposta ao desequilíbrio metabólico, e ele deixa marca ainda mais visível ao microscópio: a célula passa a acumular dentro de si substâncias que não consegue metabolizar nem exportar. Os acúmulos intracelulares são, portanto, resposta a distúrbios do metabolismo — e a primeira classificação útil é pelo *que* se acumula. Pode ser um constituinte normal da célula presente em excesso, como água, lipídio ou proteína. Pode ser uma substância anormal, de origem endógena ou exógena, como proteína mal dobrada, cálcio ou mineral. Ou pode ser um pigmento, tema da PARTE III.

Mais produtiva que essa lista é a classificação pelo *como*, porque ela transforma o achado morfológico em raciocínio mecanístico. São quatro rotas, e vale percorrê-las com a figura ao lado.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-33.png", largura: 75%, legenda: [As quatro rotas do acúmulo intracelular. (1) Metabolismo anormal de um constituinte normal — o hepatócito produz triglicerídeo mais rápido do que exporta, e o resultado é fígado gorduroso. (2) Mutação que compromete dobramento e transporte — a proteína anormal se agrega no citoplasma. (3) Falta de enzima — o substrato complexo não é convertido em produtos solúveis e se acumula no lisossomo, que é a doença de depósito. (4) Ingestão de material indigerível — o macrófago fagocita partícula que nenhuma enzima sua quebra, e ela fica ali para sempre.])

Na primeira rota, o metabolismo de um constituinte normal está alterado: a célula sintetiza ou capta o material numa velocidade maior do que a velocidade com que o remove. É o mecanismo da esteatose hepática, que abre o próximo subtópico. Na segunda, uma proteína mutada ou danificada não consegue se dobrar corretamente nem seguir sua rota de transporte, e se acumula na forma de agregados — o mesmo princípio vale para a proteína normal produzida em quantidade que ultrapassa a capacidade de dobramento da célula. Na terceira, falta a enzima que degrada um substrato: o material chega ao lisossomo, não é convertido nos produtos solúveis que sairiam de lá, e o lisossomo se torna um depósito crescente. É o mecanismo das doenças de depósito lisossômico, quase sempre hereditárias. Na quarta, a célula ingere um material que nenhuma enzima sua consegue digerir — pigmento de tatuagem, partícula de carbono inalada — e o acúmulo persiste indefinidamente porque não existe rota de saída.

Três variáveis modulam o desfecho de qualquer uma dessas rotas. A primeira é a *toxicidade* do material: lipofuscina é inerte e acompanha o envelhecimento sem lesar, enquanto proteína mal dobrada e ferro livre lesam ativamente. A segunda é a *localização*: material no citosol, no lisossomo ou no núcleo produz consequências funcionais diferentes. A terceira é a *origem* — a célula pode ela mesma produzir o material em excesso, ou pode apenas armazenar o que lhe é entregue de fora. Em todos os casos, o mesmo critério mecanístico organiza o raciocínio: identificar se o acúmulo vem de produção aumentada ou de remoção diminuída. Essa decisão muda completamente onde procurar a causa.

#mini-resumo[Todo acúmulo intracelular é um descompasso entre entrada e saída. As quatro rotas — metabolismo alterado, dobramento defeituoso, enzima ausente e material indigerível — são quatro maneiras de esse descompasso acontecer.]

#subtopico("2.2 — Esteatose: por que é o fígado quem engorda")

A #termo-nota[esteatose][acúmulo anormal de triglicerídeos no citoplasma de células parenquimatosas, também chamado de degeneração gordurosa] ocorre com muito mais frequência no fígado do que em qualquer outro órgão, e a razão é funcional antes de ser anatômica: o hepatócito é o principal centro de processamento de gordura do corpo. Todo ácido graxo que sai do tecido adiposo passa por ele, e é lá que se decide o destino dessa molécula. Coração, rim e músculo também podem apresentar esteatose, mas em circunstâncias mais restritas. As causas mais comuns são a desnutrição, o alcoolismo e as doenças metabólicas — diabetes mellitus, obesidade e dislipidemia.

O mecanismo se entende melhor como um balanço com uma entrada e várias saídas possíveis. O ácido graxo livre chega ao hepatócito pelo sangue. Dentro da célula, ele tem destinos alternativos: pode ser oxidado a corpos cetônicos e dióxido de carbono, pode ser incorporado a fosfolipídios de membrana, pode virar éster de colesterol, ou pode ser esterificado com α-glicerofosfato formando triglicerídeo. O triglicerídeo formado não sai sozinho — para deixar o hepatócito, ele precisa ser conjugado com apoproteínas, montando lipoproteínas, principalmente a #sigla("VLDL", [lipoproteína de densidade muito baixa — a partícula que exporta triglicerídeo do fígado para os tecidos]). Qualquer interferência nesse circuito — excesso na entrada, desvio para a esterificação, bloqueio da oxidação ou falha na exportação — produz o mesmo achado: gotículas de gordura acumuladas no citoplasma.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-36.png", largura: 62%, legenda: [O balanço lipídico do hepatócito. A entrada, em amarelo, são os ácidos graxos livres vindos do sangue. As saídas alternativas, em vermelho, competem entre si: oxidação a corpos cetônicos, fosfolipídios, ésteres de colesterol. A rota que leva ao acúmulo é a de baixo — esterificação a triglicerídeos, que só deixam a célula depois de conjugados com apoproteína na forma de lipoproteína.])

O primeiro grupo de causas atua pelo *excesso de oferta*. Tanto o jejum prolongado e a desnutrição quanto o diabetes descompensado provocam mobilização intensa de ácidos graxos do tecido adiposo. O ponto que mais confunde é o do jejum: à primeira vista, comer menos deveria reduzir a gordura hepática, e o efeito é o contrário. Sem substrato energético disponível, o organismo quebra o triglicerídeo estocado no adipócito e despacha ácido graxo para o fígado, que recebe muito mais matéria-prima do que consegue oxidar ou exportar, e reesterifica o excedente. No diabetes, o mecanismo tem um nome preciso: no adipócito existe uma lipase hormônio-sensível que quebra o triglicerídeo armazenado, e a insulina é quem a mantém freada. Faltando insulina, essa lipase trabalha sem controle, o ácido graxo inunda a circulação e o fígado repete a mesma reesterificação.

O segundo grupo atua pela *redução da exportação*. Na inanição, faltam aminoácidos para sintetizar as apoproteínas, e sem apoproteína não se monta lipoproteína — o triglicerídeo fica preso dentro da célula mesmo quando a oferta de ácido graxo não é excessiva. É o mecanismo da esteatose do kwashiorkor. O tetracloreto de carbono chega ao mesmo resultado por outra porta: seu metabólito radicalar lesa o retículo endoplasmático liso, justamente a maquinaria onde as lipoproteínas são montadas.

O terceiro grupo é o do *álcool*, e ele soma três mecanismos ao mesmo tempo. O alcoolista costuma ter desnutrição crônica, o que já reduz a exportação. O etanol tem ação lesiva direta sobre o hepatócito. E há o desvio metabólico, que é o mais elegante: a oxidação do etanol a acetaldeído e deste a ácido acético consome #sigla("NAD⁺", [nicotinamida adenina dinucleotídeo na forma oxidada — aceptor de elétrons das reações de oxidação]) e gera #sigla("NADH", [forma reduzida do NAD, carregada de elétrons]) em grande quantidade. O acetato em excesso é matéria-prima para sintetizar ácido graxo, e o excesso de NADH sinaliza para a célula que há energia sobrando — o que freia a oxidação de ácidos graxos e favorece a síntese. Ou seja: o álcool aumenta a produção de gordura e diminui a queima dela ao mesmo tempo.

#confusao-prevista(
  titulo: "Esteatose não é morte do hepatócito",
  aluno_acha: [ao ver o fígado amarelado e cheio de vacúolos, o aluno lê o quadro como necrose ou como fígado "destruído".],
  mecanismo: [a célula esteatótica está viva e funcionando. O que existe é triglicerídeo estocado no citoplasma, e o quadro é reversível se a causa for removida — a abstinência alcoólica ou o controle glicêmico revertem a esteatose pura em semanas. O que muda o prognóstico é o que vem *junto* com a gordura: inflamação e balonização do hepatócito caracterizam esteato-hepatite, e a fibrose que ela induz é o passo que não regride facilmente.],
)

Vale ainda distinguir dois padrões morfológicos, porque eles apontam para mecanismos diferentes. Na #termo-nota[esteatose macrovesicular][padrão em que uma única vacúola grande de gordura ocupa o citoplasma e desloca o núcleo para a periferia da célula], típica do álcool, do diabetes e da obesidade, o dano é de balanço metabólico. Na esteatose microvesicular, em que múltiplas gotículas pequenas cercam o núcleo mantido no centro, o problema costuma ser falência aguda da β-oxidação mitocondrial — padrão da esteatose aguda da gravidez e da síndrome de Reye, e clinicamente muito mais grave.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-40.png", largura: 66%, legenda: [Acima, o fígado esteatótico macroscópico: aumentado, de bordas arredondadas, amarelo e untuoso ao corte — a cor traduz literalmente a gordura acumulada. Abaixo, o correlato histológico: vacúolas grandes e opticamente vazias empurrando o núcleo do hepatócito contra a membrana. As vacúolas parecem vazias porque a gordura é dissolvida pelos solventes usados no processamento da lâmina.])

#clinica-box("Doença hepática alcoólica: três estágios, um mecanismo por vez", [O consumo crônico de álcool percorre uma sequência que ilustra bem a diferença entre adaptação, lesão e cicatriz. O primeiro estágio é a esteatose: o desvio metabólico do etanol enche o hepatócito de triglicerídeo, o fígado aumenta e amarela, os exames de função hepática mudam pouco — e tudo isso regride com abstinência. O segundo é a hepatite alcoólica: agora há necrose de hepatócitos, infiltrado de neutrófilos e agregados de filamentos intermediários no citoplasma, os corpúsculos de Mallory. Aqui já se atravessou a linha da lesão. O terceiro é a cirrose: a fibrose depositada em resposta à lesão repetida reorganiza o fígado em nódulos separados por septos de colágeno, distorce a vasculatura e não regride. A lição que a sequência ensina é a mesma da PARTE I — o acúmulo em si é reversível; o que fixa o dano é o processo cicatricial que a agressão repetida desencadeia.])

#subtopico("2.3 — Colesterol e seus ésteres: o mesmo lipídio, três cenários")

O colesterol e seus ésteres seguem uma lógica diferente da dos triglicerídeos. O colesterol não é resíduo: é matéria-prima obrigatória da síntese de membranas celulares, e toda célula precisa dele. O acúmulo aparece quando a captação local supera a capacidade local de utilização e de remoção — e o achado morfológico é quase sempre o mesmo, independentemente do órgão: um macrófago abarrotado de gotículas de éster de colesterol, com citoplasma finamente vacuolado, que os patologistas chamam de célula espumosa.

O primeiro cenário é a aterosclerose, e é o mais importante clinicamente. Na íntima das artérias de grande e médio calibre, lipoproteínas ricas em colesterol se acumulam e sofrem modificação oxidativa; monócitos migram para a íntima, se tornam macrófagos, capturam esse colesterol modificado e viram células espumosas. Somam-se a elas células musculares lisas que migraram da média e passaram a produzir matriz. O resultado é a placa de ateroma: um núcleo central lipídico, com colesterol extracelular que pode formar cristais em forma de fenda, recoberto por uma capa fibrosa. A placa estreita a luz do vaso e, sobretudo, pode romper e desencadear trombose.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-42.png", largura: 55%, legenda: [Corte transversal de artéria com placa de ateroma. Repare na geometria do achado: a lesão se instala na íntima, entre o endotélio e a média, e cresce para dentro da luz, que fica reduzida e excêntrica. O material mais claro no centro da placa é o núcleo lipídico; a faixa mais rósea que o recobre é a capa fibrosa.])

O segundo cenário é a #termo-nota[colesterolose][acúmulo de macrófagos espumosos na lâmina própria da mucosa da vesícula biliar, que dá à superfície interna o aspecto pontilhado amarelo descrito como "vesícula em morango"], achado frequente e clinicamente inócuo. O terceiro são os xantomas: agregados de macrófagos espumosos no tecido conjuntivo subcutâneo e nos tendões, formando nódulos amarelados visíveis. Ao contrário da colesterolose, o xantoma tem valor de sinal — ele aparece tipicamente em estados de hiperlipidemia hereditária ou adquirida, e sua presença na pele ou no tendão de Aquiles convida a investigar o perfil lipídico do paciente.

#clinica-box("Hipercolesterolemia familiar: o mesmo acúmulo em três territórios", [Na hipercolesterolemia familiar, mutações no receptor de LDL impedem a captação hepática normal do colesterol circulante. Sem essa remoção, o colesterol plasmático permanece altíssimo desde a infância, e o excesso é depositado onde houver macrófago disponível. Nos tendões extensores e no tendão de Aquiles, forma xantomas palpáveis; nas pálpebras, xantelasmas; na córnea, o arco corneano precoce; e nas artérias, ateromas que produzem infarto do miocárdio décadas antes do esperado. É o mesmo mecanismo — captação que supera a remoção — expresso em três morfologias distintas conforme o tecido. E é por isso que um xantoma tendíneo em paciente jovem é achado que muda conduta: ele é a face visível de um risco cardiovascular que ainda está silencioso.])

#subtopico("2.4 — Acúmulos proteicos: produção demais, reabsorção de menos, dobramento errado")

Uma fábrica pode entupir de três maneiras: produzindo peças rápido demais, deixando de escoar o que recebe, ou fabricando peças tortas que travam a linha. Os acúmulos proteicos intracelulares seguem exatamente essas três lógicas. Ao microscópio óptico, eles se manifestam como glóbulos eosinofílicos arredondados, como cristais, ou como material amorfo que preenche o citoplasma — e a morfologia sozinha raramente diz qual das três causas está em jogo.

O primeiro mecanismo é o *excesso de produção*. O caso clássico é o do plasmócito neoplásico do mieloma múltiplo, que sintetiza imunoglobulina numa velocidade que ultrapassa sua capacidade de secretá-la; o excesso se condensa no retículo endoplasmático rugoso em glóbulos arredondados, os corpúsculos de Russell. Note o encadeamento: a célula não está doente por acumular — ela acumula porque está produzindo demais, e a produção excessiva é a doença.

O segundo é a *dificuldade de reabsorção*. As células do túbulo contorcido proximal reabsorvem rotineiramente pequenas quantidades de proteína que escapam do filtro glomerular, e as digerem em lisossomos. Quando a barreira glomerular está lesada e passa muito mais proteína do que o normal — na síndrome nefrótica, por exemplo —, a reabsorção satura e as vesículas se acumulam no citoplasma como gotículas hialinas. Aqui a produção é normal e o defeito é de escoamento; e o achado, importante, é reversível se a proteinúria for controlada.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-44.png", largura: 58%, legenda: [Gotículas proteicas de reabsorção no epitélio tubular renal. O material rosado granular está *dentro* das células que revestem o túbulo — não confundir com o cilindro proteico, que é material solidificado ocupando a luz tubular. A distinção topográfica separa dois processos diferentes.])

O terceiro mecanismo é o do *dobramento defeituoso*, e é o que mais interessa mecanisticamente. Uma proteína recém-sintetizada precisa adquirir sua conformação tridimensional correta, e esse processo é assistido por chaperonas — proteínas que impedem agregações prematuras e dão ao polipeptídio novas chances de se dobrar certo. Quando uma mutação torna o dobramento impossível, ou quando estresse oxidativo, calor ou radiação danificam proteínas já maduras, as chaperonas tentam primeiro o resgate. Se o resgate falha, a proteína é marcada com ubiquitina e destruída no proteassoma — a mesma via que vimos governando a atrofia. O acúmulo aparece quando a produção de proteína defeituosa supera a capacidade conjunta de resgate e de degradação: os agregados se depositam no citoplasma ou no retículo, e passam a lesar a célula.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-45.png", largura: 68%, legenda: [Em A, o controle de qualidade normal: chaperonas acompanham o peptídio nascente e o entregam dobrado, seja ao citosol, seja à mitocôndria. Em B, o que acontece sob estresse: a proteína danificada é reconhecida, tentada pela chaperona e, se irrecuperável, ubiquitinada e digerida no proteassoma. Quando essa saída satura, os agregados se acumulam — e a via converge para morte celular.])

A deficiência de α-1-antitripsina ilustra o mecanismo com uma consequência dupla e instrutiva. A proteína mutada não consegue deixar o hepatócito e se acumula lá dentro, formando glóbulos que lesam a própria célula hepática — daí a hepatopatia. Ao mesmo tempo, como ela não chega ao pulmão, falta ali o inibidor que normalmente contém as elastases liberadas por neutrófilos, e o resultado é enfisema. Um mesmo defeito de dobramento produz dano por acúmulo num órgão e dano por ausência em outro.

No extremo da agregação proteica está o #termo-nota[amiloide][material proteico extracelular de estrutura em folha β pregueada, eosinofílico e amorfo à coloração de rotina, que se cora pelo vermelho Congo e exibe birrefringência verde à luz polarizada]. Diferentes proteínas precursoras — cadeias leves de imunoglobulina no mieloma, proteína amiloide sérica na inflamação crônica, peptídio β-amiloide no cérebro — podem adotar essa mesma conformação e se depositar entre as células, comprimindo o parênquima e comprometendo a difusão de nutrientes. Nas placas senis da doença de Alzheimer, esse depósito extracelular convive com o emaranhado neurofibrilar intracelular, e o resultado da soma é perda neuronal e atrofia cerebral — a mesma atrofia que a PARTE I descreveu, agora com uma causa molecular nomeada.

#mini-resumo[Proteína acumulada dentro da célula quase sempre responde a uma de três perguntas: produziu demais (mieloma), não conseguiu escoar (túbulo renal na proteinúria) ou dobrou errado e escapou do controle de qualidade (α-1-antitripsina, amiloide).]

#parte-title("PARTE III — Glicogênio, pigmentos e cálcio: o catálogo com mecanismo")

#subtopico("3.1 — Glicogênio: excesso de oferta ou enzima que falta")

O glicogênio é a fonte rápida de energia estocada no organismo — um polímero ramificado de glicose que o fígado e o músculo montam quando há glicose sobrando e desmontam quando falta. Como todo estoque, ele obedece ao balanço entre o que entra e o que sai, e as duas maneiras de acumulá-lo em excesso correspondem exatamente às duas metades desse balanço.

A primeira é o *distúrbio adquirido do metabolismo*, e o exemplo é o diabetes mellitus mal controlado. Com glicemia persistentemente alta, células que captam glicose de forma independente de insulina recebem muito mais substrato do que precisam e o polimerizam. O glicogênio se acumula então no epitélio do túbulo contorcido distal e da alça de Henle, nos hepatócitos, nas células β das ilhotas pancreáticas e no miocárdio. Repare que aqui a maquinaria enzimática está intacta: o que está errado é a oferta.

A segunda é o *defeito genético*, e aí a oferta é normal e o que falta é uma enzima. As #termo-nota[glicogenoses][grupo de doenças hereditárias em que a deficiência de uma enzima da síntese ou da degradação do glicogênio faz o polímero se acumular nos tecidos que mais dependem dele] são um conjunto de doenças autossômicas recessivas em que a via de degradação — ou, mais raramente, a de síntese — está interrompida. A consequência clínica depende de duas variáveis: qual enzima falta e em qual tecido ela é mais necessária.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-48.png", largura: 72%, legenda: [O catálogo das glicogenoses, organizado por enzima deficiente e tecido afetado. Leia a tabela pelo mecanismo, não pelo nome próprio: as formas *hepáticas* (von Gierke, Hers) travam a liberação de glicose para o sangue e produzem hipoglicemia com hepatomegalia; as *musculares* (McArdle, Tarui) travam o uso do estoque local e produzem cãibra e fadiga ao exercício; e Pompe é o caso à parte, em que a enzima ausente é lisossômica e o acúmulo compromete o coração.])

As formas hepáticas ilustram bem o raciocínio. Na doença de von Gierke, do tipo I, falta a glicose-6-fosfatase, a enzima que executa o último passo antes de a glicose deixar o hepatócito e entrar no sangue. Sem ela, o fígado consegue quebrar o glicogênio mas não consegue exportar o produto: o órgão aumenta de volume, cheio de glicogênio, enquanto o paciente tem hipoglicemia de jejum grave. E como a glicose-6-fosfato acumulada é desviada para outras rotas, surgem também acidose láctica, hiperlipidemia e hiperuricemia. Nas formas musculares, como a doença de McArdle, do tipo V, falta a fosforilase muscular: o músculo tem estoque, mas não consegue mobilizá-lo durante o esforço, e o paciente relata cãibra e fadiga precoces ao exercício, sem elevação do lactato no teste de esforço isquêmico. A doença de Pompe, do tipo II, é diferente das outras porque a enzima ausente — a maltase ácida — é lisossômica: o glicogênio se acumula dentro do lisossomo, e não no citosol, o que a coloca no grupo das doenças de depósito lisossômico e explica o comprometimento cardíaco grave na infância.

#clinica-box("A criança que não pode jejuar", [Uma lactente com fígado muito aumentado, face arredondada, crescimento lento e episódios de sonolência e convulsão sempre que passa algumas horas sem mamar é o quadro clássico da doença de von Gierke. A cadeia é toda mecanística: sem glicose-6-fosfatase, o fígado não entrega glicose ao sangue no jejum; a glicemia despenca e produz os sintomas neurológicos; o glicogênio que não pode ser exportado se acumula e faz a hepatomegalia; e o desvio da glicose-6-fosfato acumulada para a glicólise e para a via das pentoses produz o lactato, os triglicerídeos e o ácido úrico elevados. O tratamento decorre diretamente do mecanismo: fornecer glicose de liberação lenta em intervalos curtos — inclusive à noite — para que o organismo nunca precise recorrer a um estoque que ele não consegue acessar.])

#subtopico("3.2 — Lipofuscina e melanina: os pigmentos que não vêm da hemoglobina")

Pigmento, em Patologia, é qualquer substância com cor própria acumulada em tecido. A divisão mais útil separa os *exógenos*, que vêm de fora, dos *endógenos*, produzidos pelo próprio organismo — e entre os endógenos, os que derivam da hemoglobina dos que não derivam. Os exógenos são o exemplo mais direto da quarta rota de acúmulo vista na PARTE II: o carbono inalado da poluição e da fumaça é fagocitado por macrófagos alveolares, transportado aos linfonodos hilares e ali permanece indefinidamente, porque nenhuma enzima humana o digere. O mesmo vale para o pigmento de tatuagem, capturado por macrófagos dérmicos que o guardam pela vida inteira.

A #termo-nota[lipofuscina][pigmento pardo-amarelado, granular e intralisossômico, formado por polímeros de lipídios e proteínas resultantes da peroxidação de membranas] é o primeiro pigmento endógeno não derivado da hemoglobina. Ela é chamada de pigmento do envelhecimento ou do desgaste porque é literalmente o resíduo insolúvel da peroxidação lipídica das membranas celulares ao longo dos anos: radicais livres oxidam lipídios de membrana, os produtos se polimerizam com proteínas, e o material resultante não pode ser degradado nem exportado, ficando estocado em lisossomos residuais. O ponto mecanístico decisivo é que ela é *atóxica* — não lesa a célula. Sua importância é de sinal: onde há muita lipofuscina, houve muito estresse oxidativo acumulado. Por isso ela se destaca justamente em células permanentes e longevas, como o miócito cardíaco e o neurônio, e por isso aparece em quantidade nos órgãos atrofiados de idosos e de pacientes caquéticos. Quando o coração ou o fígado atrofiados ganham tonalidade acastanhada por essa carga de pigmento, o achado recebe o nome de #termo-nota[atrofia parda][órgão atrófico cuja cor acastanhada resulta do acúmulo de lipofuscina nas células remanescentes] — repare que o pigmento não causa a atrofia; ele apenas fica mais concentrado num órgão que perdeu volume.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-53.png", largura: 64%, legenda: [À esquerda, grânulos de lipofuscina acumulados no polo perinuclear dos miócitos cardíacos — a posição junto ao núcleo é característica. À direita, o correlato macroscópico da atrofia parda: coração pequeno, de coloração acastanhada, típico de paciente idoso ou com caquexia.])

A melanina é o segundo pigmento endógeno não hemoglobinogênico, e o único pigmento endógeno de cor castanha que é *fisiológico*. Ela é sintetizada exclusivamente pelo melanócito, célula de origem na crista neural que reside na camada basal da epiderme, a partir da tirosina: a enzima tirosinase converte tirosina em di-hidroxifenilalanina, que segue por uma sequência de oxidações até o polímero de melanina. Um detalhe funcional que costuma passar batido é que o melanócito não guarda o pigmento para si — ele o empacota em melanossomos e os transfere para os queratinócitos vizinhos, que ficam com o pigmento posicionado sobre o núcleo, como um guarda-sol que protege o #sigla("DNA", [ácido desoxirribonucleico]) da radiação ultravioleta. A pele de pessoas de fototipos diferentes tem número semelhante de melanócitos; o que varia é a quantidade e a distribuição do pigmento produzido e transferido.

#confusao-prevista(
  titulo: "Dois pigmentos pardos que não se confundem sob o Perls",
  aluno_acha: [como lipofuscina e hemossiderina são ambas pardas e granulares na coloração de rotina, é tentador tratá-las como variações do mesmo achado.],
  mecanismo: [a diferença é o ferro. A hemossiderina é agregado de ferritina e carrega ferro — por isso cora em azul intenso pela reação de Perls, o azul da Prússia. A lipofuscina não tem ferro nenhum e permanece parda nessa mesma coloração. Uma lâmina e um reagente separam um pigmento que só marca desgaste oxidativo de outro que sinaliza sobrecarga de ferro potencialmente lesiva.],
)

#subtopico("3.3 — Hemossiderina, sobrecarga de ferro e bilirrubina")

Os dois pigmentos endógenos mais importantes derivam da mesma molécula — a hemoglobina — e se separam exatamente por um átomo. Quando a hemácia é destruída e a hemoglobina é degradada, o grupo heme se divide em dois caminhos: o *ferro* é recuperado e estocado, e o *anel porfirínico*, sem ferro, é convertido em bilirrubina. Fixar essa bifurcação resolve de uma vez a confusão mais comum do tema.

O caminho do ferro produz a #termo-nota[hemossiderina][pigmento granular pardo-amarelado formado por agregados insolúveis de micelas de ferritina, corável em azul pela reação de Perls]. O organismo estoca ferro ligando-o à apoferritina, formando micelas de ferritina — a forma solúvel e dispersa, invisível ao microscópio óptico. Quando a quantidade de ferro excede o que a ferritina consegue manter em solução, essas micelas se agregam em grânulos grosseiros e insolúveis, e é isso que se vê como hemossiderina, principalmente em fígado, medula óssea e baço, órgãos ricos em macrófagos. O achado é sempre a marca de um excesso local ou sistêmico de ferro.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-56.png", largura: 66%, legenda: [O mesmo tecido, duas colorações. À esquerda, hematoxilina-eosina: grânulos pardos grosseiros no citoplasma dos hepatócitos e dos macrófagos. À direita, a reação de Perls: o ferro reage e o pigmento fica azul-intenso, tornando inequívoca a identificação. É esse par de lâminas que separa hemossiderina de qualquer outro pigmento pardo.])

As causas se organizam por escala. Localmente, qualquer hemorragia produz hemossiderina: o hematoma muda de cor ao longo dos dias exatamente porque a hemoglobina extravasada é degradada por macrófagos, e o pardo tardio é hemossiderina. Sistemicamente, o excesso vem de hemólise crônica, de transfusões repetidas ou de aumento da absorção intestinal de ferro. Quando o depósito é generalizado mas não causa dano, fala-se em hemossiderose; quando a carga de ferro é grande o suficiente para lesar os órgãos, o quadro é de hemocromatose. A hemocromatose primária é genética e o defeito está na regulação da absorção intestinal de ferro, que passa a captar mais do que o necessário mesmo com estoques cheios; ela é surpreendentemente frequente, com prevalência estimada entre um em duzentos e um em quinhentos indivíduos em populações de origem europeia. A secundária vem de fora: politransfusão em pacientes com anemias crônicas, sobrecarga dietética ou hemólise persistente.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-57.png", largura: 58%, legenda: [Fígado com sobrecarga de ferro: a peça macroscópica tem coloração pardo-escura característica, e o corte histológico corado pelo Perls mostra o ferro depositado em azul, distribuído por hepatócitos e por septos fibrosos. A fibrose visível é a resposta do tecido à lesão oxidativa contínua — o passo que separa hemossiderose de hemocromatose.])

O mecanismo do dano na hemocromatose merece um degrau a mais. O ferro em excesso escapa dos sítios de estoque e, na forma livre, catalisa a formação de radicais livres a partir de peróxido de hidrogênio. Esses radicais peroxidam lipídios de membrana e ativam células estreladas hepáticas, que depositam colágeno. Daí a tríade clínica clássica: cirrose no fígado, diabetes mellitus quando as ilhotas pancreáticas são lesadas — o que rendeu à doença o apelido de diabetes bronzeado — e miocardiopatia com arritmias quando o ferro se deposita no coração. A pigmentação bronze da pele resulta da combinação de hemossiderina dérmica com aumento da produção de melanina.

#clinica-box("Hemocromatose: uma doença que se trata retirando o excesso", [O paciente típico é um homem de meia-idade com fadiga, dor articular, pele escurecida, diabetes de início recente e alterações nos exames hepáticos. A explicação da preferência pelo sexo masculino é elegante: a menstruação e as gestações funcionam como perdas periódicas de ferro que retardam o acúmulo, de modo que mulheres costumam manifestar a doença mais tarde. A confirmação combina saturação de transferrina e ferritina séricas elevadas com estudo genético. E o tratamento devolve a lógica do balanço que organiza toda esta PARTE: como não existe via fisiológica de excreção ativa de ferro, retira-se ferro removendo sangue — flebotomias seriadas, repetidas até normalizar os estoques. Quando iniciado antes da cirrose, o tratamento devolve expectativa de vida próxima à normal, e é por isso que reconhecer o pigmento cedo importa tanto.])

O outro ramo da bifurcação é a bilirrubina, principal componente da bile. Ela deriva da hemoglobina mas *não* contém ferro — é o anel porfirínico aberto e reduzido. Quando se acumula, produz a coloração amarelo-esverdeada característica: a icterícia da pele e das escleras e a impregnação biliar dos órgãos. As causas seguem, de novo, o balanço entre produção e eliminação: hemólise produz bilirrubina em excesso; a lesão hepatocelular compromete a captação e a conjugação; e a obstrução das vias biliares impede a saída da fração já conjugada, que reflui para o sangue. Ao microscópio, a colestase se manifesta como pigmento castanho-esverdeado dentro dos hepatócitos e como tampões biliares nos canalículos entre eles.

#subtopico("3.4 — Calcificação patológica: cimento em tecido morto ou cálcio a mais no sangue")

Cimento endurece onde é despejado, e o cálcio se comporta de modo parecido: quando precipita num tecido, aquele ponto perde flexibilidade para sempre. A calcificação patológica é a deposição *anormal* de sais de cálcio em tecidos — anormal porque exclui a mineralização fisiológica do osso e do dente. Existem duas formas, e a diferença entre elas é a chave de todo o tema: o que separa uma da outra não é a aparência do depósito, e sim *onde ele ocorre* e *como está o cálcio no sangue*.

A #termo-nota[calcificação distrófica][deposição de sais de cálcio em tecidos necróticos ou previamente lesados, com concentração sérica de cálcio normal] ocorre em tecido morto ou em degeneração, e o ponto que precisa ficar gravado é que ela é *independente* da concentração de cálcio no sangue e de qualquer distúrbio do metabolismo do cálcio. O mecanismo é local: a membrana da célula em necrose perde a capacidade de manter o cálcio fora do citoplasma, o cálcio intracelular sobe, vesículas ricas em fosfolipídios concentram cálcio e fosfato, e a partir desses núcleos iniciais o cristal cresce. Os cenários clássicos são a necrose caseosa da tuberculose, as placas de aterosclerose, as valvas cardíacas alteradas pela senilidade ou pela sequela de febre reumática, os tumores com áreas de necrose e as cicatrizes antigas. Nada disso é inócuo: a valva aórtica calcificada não abre direito e produz estenose, e o ateroma calcificado torna a artéria rígida e difícil de tratar.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-50.png", largura: 60%, legenda: [Calcificação distrófica. À esquerda, o material basofílico granular e amorfo depositado sobre área de necrose. À direita, a parede de um vaso com depósito calcificado na camada média. Em ambos os casos o cálcio sérico do paciente é normal — o que atraiu o cálcio foi a lesão prévia do tecido.])

A #termo-nota[calcificação metastática][deposição de sais de cálcio em tecidos vivos e normais, consequência de hipercalcemia] segue a lógica oposta. Aqui o tecido é viável e normal, e o que está errado é a concentração de cálcio no sangue: a hipercalcemia empurra a precipitação em qualquer lugar onde as condições locais favoreçam. E as condições favoráveis são conhecidas — os depósitos ocorrem preferencialmente em tecidos que perdem ácido e ficam relativamente alcalinos, como a mucosa gástrica, os túbulos renais, as veias pulmonares e os vasos sistêmicos.

#atencao-box("\"Metastática\" aqui não tem nada a ver com metástase de tumor", [O nome é uma armadilha semântica que produz erro de raciocínio inteiro. Calcificação metastática significa apenas que o cálcio saiu de sua fonte — o osso, o intestino — viajou pelo sangue e se depositou à distância, em tecido *vivo e normal*. Não há célula tumoral envolvida, não há disseminação de neoplasia. O contraste com a distrófica precisa ser lido nas duas variáveis ao mesmo tempo: distrófica é tecido *morto* com cálcio sérico *normal*; metastática é tecido *vivo* com cálcio sérico *alto*. Confundir os termos leva o raciocínio para o lado errado logo no primeiro passo, porque a distrófica pede que se procure a lesão local, e a metastática pede que se procure a causa sistêmica da hipercalcemia.])

As causas de hipercalcemia se agrupam em quatro. O aumento da secreção de #sigla("PTH", [paratormônio — hormônio da paratireoide que eleva o cálcio sérico]) aumenta a reabsorção óssea e devolve cálcio à circulação; é o caso do adenoma de paratireoide e também da produção ectópica de peptídio relacionado ao PTH por alguns tumores. A destruição direta do tecido ósseo libera cálcio sem intermediação hormonal, como ocorre no mieloma múltiplo e nas metástases ósseas. Os distúrbios relacionados à vitamina D, por intoxicação ou por produção aumentada em doenças granulomatosas, elevam a absorção intestinal de cálcio. E há o caso da insuficiência renal, que merece detalhamento porque a cadeia é contra-intuitiva.

#figura-nebli("/figuras/patologia-adaptacao-acumulos/slide-51.png", largura: 55%, legenda: [Calcificação metastática em tecido pulmonar viável. Os depósitos basofílicos se distribuem ao longo de septos e paredes vasculares num parênquima que, fora isso, está preservado — a assinatura morfológica de "cálcio a mais no sangue", e não de "tecido lesado atraindo cálcio".])

#clinica-box("Por que o rim doente calcifica os vasos", [Na doença renal crônica, o rim perde a capacidade de excretar fosfato, que se acumula no sangue. O fosfato elevado se liga ao cálcio circulante e derruba o cálcio ionizado; além disso, o rim doente produz menos da forma ativa da vitamina D, e a absorção intestinal de cálcio cai junto. A paratireoide lê a hipocalcemia e responde da única forma que sabe: aumenta a secreção de PTH de modo sustentado — é o hiperparatireoidismo *secundário*, chamado assim porque a glândula não é a doente, apenas reage. O PTH cronicamente alto reabsorve osso, o que gera a osteodistrofia renal e devolve ainda mais cálcio e fosfato à circulação. Com o produto cálcio-fosfato elevado, a precipitação ocorre em tecidos moles e, sobretudo, na parede dos vasos — o que torna a calcificação vascular uma das principais causas de morte cardiovascular nesses pacientes. Repare que a cadeia inteira nasce de uma adaptação legítima da paratireoide que, mantida por anos, passa a lesar.])

#conclusao-box[
Um único princípio atravessa as três PARTES: *toda morfologia que o microscópio revela é o registro de um balanço metabólico que se desequilibrou antes*. Na PARTE I o balanço era entre demanda e capacidade — a célula respondeu mudando tamanho, número ou identidade, e o tipo de tecido definiu qual resposta estava disponível. Nas PARTES II e III o balanço era entre o que entra e o que sai da célula — e quando a entrada supera a saída, o excedente fica guardado como gordura, proteína, glicogênio, pigmento ou sal de cálcio.

O mecanismo nuclear, o que reaparece em quase todos os subtópicos, é o par *produção versus remoção*. Ele explica a hipertrofia (síntese proteica acima da degradação) e a atrofia (a mesma balança invertida, com a via ubiquitina-proteassoma acelerada); explica a esteatose (ácido graxo que chega mais rápido do que a lipoproteína consegue exportar); explica o acúmulo proteico (dobramento defeituoso acima da capacidade da chaperona e do proteassoma); e explica a hemossiderina (ferro além do que a ferritina mantém solúvel). Diante de qualquer acúmulo, portanto, a primeira decisão é sempre a mesma: procurar se o problema está na entrada ou na saída.

A clínica já mostrou aonde esse raciocínio leva. O ventrículo hipertrofiado alivia a tensão de parede até que a vascularização deixe de acompanhar e a adaptação vire insuficiência. O esôfago de Barrett troca um epitélio por outro que resiste ao ácido, e é a persistência do estímulo sobre esse tecido novo que constrói o risco de displasia. O fígado do alcoolista acumula triglicerídeo de forma reversível e só se torna irreversível quando a fibrose entra. E o rim crônico dispara um hiperparatireoidismo que começa como resposta correta e termina calcificando artérias. Em todos, a mesma advertência: adaptação preserva a viabilidade, mas cobra função, e o estímulo mantido converte proteção em dano.

O passo seguinte é o da fronteira que este material apenas encostou. Quando o estímulo ultrapassa a capacidade adaptativa, a célula deixa o contínuo da adaptação e entra no da lesão — e aí valem outras regras: perda de integridade de membrana, colapso da produção de ATP, e a bifurcação entre necrose e apoptose. Chegar ali com o mapa das adaptações e dos acúmulos já montado torna o tema seguinte muito mais simples de ler, porque necrose e apoptose passam a ser, respectivamente, o que acontece quando a economia celular quebra de forma desordenada e o que acontece quando ela é desmontada de forma programada.
]
