#import "../typst-template/nebli_v2_apostila.typ": *

#discursiva("Q1",
  [Uma cultura bacteriana é acompanhada desde a semeadura até a morte da população, com o logaritmo do número de células registrado contra o tempo. Descreva as quatro fases obtidas, indicando em cada uma o que a célula está fazendo — e não apenas o que acontece com o número de células.],
  [Na lag não há divisão e o metabolismo é o mais intenso do cultivo: a célula fabrica transportadores, induz as enzimas da nova fonte de carbono e produz ribossomos; a duração depende de quão diferente é o meio novo. Na log o crescimento é equilibrado, o tempo de geração é constante e é o único trecho em que X = x₀ · 2ⁿ descreve a cultura. Na estacionária, esgotado o nutriente e acumulado o produto, a divisão iguala a perda de viabilidade e a célula troca o programa de crescimento pelo de sobrevivência. No declínio, a morte excede a divisão.])

#discursiva("Q2",
  [Duas culturas são semeadas no mesmo dia, cada uma em meio adequado ao seu agente: uma fornece colônias visíveis em 24 horas, a outra exige semanas de incubação. Justifique essa diferença recorrendo à aritmética do crescimento, e explique por que ela não se corrige com meio mais rico.],
  [Uma colônia só se torna visível a olho nu quando reúne cerca de 10⁸ células, o que exige em torno de 27 duplicações a partir de uma célula isolada. O número de duplicações é o mesmo para os dois agentes; o que difere é quanto tempo cada duplicação custa. A vinte minutos por geração, 27 duplicações levam menos de dez horas; a vinte horas por geração, levam mais de vinte dias. Enriquecer o meio não resolve porque o limite não é de nutriente disponível, e sim do tempo que aquela célula leva para duplicar seu conteúdo e erguer o septo.])

#discursiva("Q3",
  [Explique o mecanismo pelo qual uma cultura que fermenta um açúcar acidifica o meio, enquanto uma que respira tende a alcalinizá-lo, e indique como essa diferença é aproveitada na composição de um meio de cultura diferencial.],
  [A fermentação rende cerca de dois ATP por glicose, contra trinta e oito na respiração aeróbia. Para obter a mesma energia, quem fermenta consome dezenas de vezes mais açúcar e despeja no meio dezenas de vezes mais produto ácido — daí a acidificação. Quem respira oxida o açúcar até CO₂, que se dissipa, e depois cataboliza aminoácidos, cuja desaminação libera amônia e alcaliniza. O meio diferencial acrescenta um substrato e um indicador de pH: a colônia que fermenta acidifica o entorno e vira o indicador, tornando visível a diferença metabólica.])

#discursiva("Q4",
  [Um anaeróbio estrito perde viabilidade em poucas horas quando incubado em atmosfera ambiente. Descreva o mecanismo molecular responsável por isso e explique como um meio semissólido em que o oxigênio difunde a partir da superfície permite classificar uma bactéria quanto ao metabolismo de oxigênio.],
  [Na presença de oxigênio formam-se espontaneamente derivados parcialmente reduzidos — superóxido e peróxido de hidrogênio — que oxidam lipídeo de membrana, proteína e material genético. A superóxido-dismutase converte o superóxido em peróxido, e a catalase ou a peroxidase eliminam esse peróxido. O anaeróbio estrito não dispõe dessas enzimas: morre pelo acúmulo dos derivados, e não por lhe faltar algo que consuma oxigênio. No meio semissólido o oxigênio difunde de cima para baixo e forma um gradiente; cada espécie cresce na faixa de tensão que tolera e aproveita, de modo que a posição da faixa de crescimento revela a classe.])

#discursiva("Q5",
  [Paciente com infecção associada a material implantado recebe antimicrobiano ao qual o agente isolado se mostrou sensível no teste laboratorial, e ainda assim apresenta recidiva após o término do tratamento. Explique o mecanismo mais provável, diferenciando-o de resistência, e relacione-o ao estado fisiológico da população bacteriana no sítio da infecção.],
  [O teste de sensibilidade é feito com população em multiplicação ativa, condição em que a droga encontra o processo que precisa atacar — parede sendo sintetizada, proteína sendo fabricada. No sítio da infecção, boa parte da população vive aderida ao material, em matriz, com nutriente escasso e metabolismo reduzido, no estado fisiológico da fase estacionária. Essa célula não oferece o alvo em construção e sobrevive a concentrações que matariam a mesma bactéria em fase log. Trata-se de tolerância, não de resistência: não há gene novo nem enzima que degrade a droga, e a descendência volta a ser sensível quando recupera o crescimento. Por isso o teste indica sensibilidade e o quadro recidiva ao fim do tratamento.])
