#import "../typst-template/nebli_v2_apostila.typ": *

#intro-box[
  Até agora o embrião era um disco parado de duas camadas de células empilhadas — uma folha por cima (o epiblasto) e uma folha por baixo (o hipoblasto). Não havia frente nem trás, nem esquerda nem direita, nem nada que lembrasse um corpo. Nas próximas três semanas, esse disco vira um animal com cabeça, cauda, tubo nervoso, coluna e um intestino por dentro. E nada disso acontece porque células novas "aparecem" no lugar certo: acontece porque células que já existem *se movem*, atravessam camadas, se dobram e mudam de forma numa coreografia rigorosamente cronometrada. Esse capítulo é sobre esses movimentos. Primeiro a #termo-nota[gastrulação][reorganização da blástula que gera as três camadas germinativas e define o plano corporal], que transforma o disco de duas camadas em três e estabelece os eixos do corpo. Depois a neurulação, que ergue a placa nervosa e a fecha num tubo. Por fim o dobramento, que pega o disco achatado e o enrola num corpo tridimensional com um intestino dentro. Como escreveu o embriologista Lewis Wolpert, "não é o nascimento, o casamento ou a morte — é a gastrulação o momento mais importante da sua vida". Vamos entender por quê.
]

#parte-title("PARTE I — Gastrulação: do disco de duas camadas ao de três", primeira: true)

#subtopico("1.1 — O problema que a gastrulação resolve")

O corpo humano inteiro — pele, cérebro, coração, ossos, rins, intestino — deriva de apenas três folhetos de células, formados todos numa mesma janela de poucos dias na terceira semana. Antes disso, o embrião é um #termo-nota[disco bilaminar][disco embrionário de duas camadas: epiblasto dorsal e hipoblasto ventral, presente antes da gastrulação]: duas folhas de células epiteliais, o *epiblasto* voltado para a cavidade amniótica e o *hipoblasto* voltado para o saco vitelino. Duas camadas não bastam para construir um animal. Falta a camada do meio, e falta, acima de tudo, uma organização espacial — uma definição de onde é a cabeça, onde é a cauda, o que fica no dorso e o que fica no ventre.

A gastrulação é o processo que resolve esses dois problemas ao mesmo tempo. Ela é, antes de tudo, um evento de #termo-nota[morfogênese][geração da forma do corpo a partir de movimentos e rearranjos celulares coordenados] — literalmente, a "geração da forma". As células do epiblasto adquirem novas posições, migram para dentro do disco e passam a ocupar três níveis distintos, estabelecendo o *plano corporal* do embrião. Junto com o movimento vem a sinalização: as células que se movem trocam sinais químicos que dizem umas às outras quem vira o quê. É por isso que a gastrulação marca o *início da morfogênese* — a partir daqui o embrião deixa de ser uma pilha de camadas e começa a ter forma de corpo.

Vale fixar quem é o protagonista. Todos os três folhetos germinativos nascem do *epiblasto* — a folha de cima. O hipoblasto, apesar de estar ali embaixo, não vira nenhuma das três camadas do corpo: ele é empurrado para as laterais e contribui para tecidos extraembrionários, como o revestimento da vesícula vitelínica. Guardar isso desde já evita a confusão mais comum do tema, que veremos adiante: hipoblasto não é sinônimo de endoderma.

Vale reparar, de passagem, que as duas bolsas que ladeiam o disco também têm origem definida: a cavidade amniótica se organiza a partir do epiblasto e o saco vitelino a partir do hipoblasto. São anexos *extraembrionários* — não entram no corpo do embrião —, mas é bom saber de onde vêm, porque é a mesma lógica que separa "quem vira corpo" (epiblasto) de "quem vira suporte" (hipoblasto).

#mini-resumo[A gastrulação transforma o disco bilaminar (epiblasto + hipoblasto) em trilaminar (ecto + meso + endoderma) por *movimento celular*, e ao fazê-lo estabelece os eixos do corpo. Todos os três folhetos vêm do epiblasto.]

#subtopico("1.2 — A linha primitiva: a costura que organiza o embrião")

Para que as células do epiblasto migrem para dentro, elas precisam de uma porta de entrada — e essa porta tem um endereço fixo. No dia 15, aproximadamente, surge no epiblasto um sulco alongado na linha média, correndo no sentido do que será o eixo cabeça-cauda: a #termo-nota[linha primitiva][sulco no epiblasto por onde as células migram para dentro na gastrulação; define o eixo crânio-caudal e a simetria bilateral]. Pense nela como uma costura aberta no meio do disco, por onde o tecido de cima vai se enfiando para baixo.

A linha primitiva não é apenas uma passagem: ela é o primeiro sinal de organização do corpo. No instante em que ela aparece, o embrião ganha uma linha média — e com ela um lado direito e um lado esquerdo (simetria bilateral), uma extremidade cranial e uma caudal. Antes da linha primitiva, o disco era simétrico como um prato; depois dela, tem eixos definidos.

Na extremidade mais anterior da linha primitiva existe um espessamento especial, o #termo-nota[nó primitivo][organizador na extremidade cranial da linha primitiva; fonte da notocorda e centro sinalizador do embrião]. O nó é o centro de comando da gastrulação — é dele que sairão as células que formam a notocorda, a estrutura que, mais adiante, vai induzir todo o sistema nervoso. Uma imagem ajuda a fixar a geografia: o nó fica na ponta *cranial* da costura, e a linha se estende dele em direção à futura cauda.

O nó guarda ainda um truque que decide um eixo inteiro do corpo. Suas células têm #termo-nota[cílios][prolongamentos móveis; no nó primitivo, seu batimento coordenado gera um fluxo de líquido para a esquerda que define o eixo esquerda-direita] que batem de forma coordenada e empurram líquido para o lado esquerdo do embrião. Esse fluxo assimétrico é o primeiro sinal que distingue esquerda de direita — é o que, lá na frente, coloca o coração à esquerda e o fígado à direita. Quando esses cílios não funcionam, a assimetria pode se inverter e os órgãos se dispõem em espelho (situs inversus). Ou seja: a mesma estrutura que inicia a notocorda também escreve a lateralidade do corpo.

#figura-nebli("/figuras/embrio-gastrulacao-neurulacao/slide-07.png",
  largura: 70%,
  legenda: [Em cima: o disco embrionário em corte, com a *linha primitiva* e o *nó primitivo* (na extremidade anterior). As setas mostram células do epiblasto convergindo para o sulco e mergulhando para dentro. Embaixo: o detalhe do movimento — a célula epitelial do epiblasto vira uma "célula em garrafa" (bottle cell), solta-se da folha e assume forma de mesênquima migratório. É a transição epitélio-mesênquima em ação.])

#subtopico("1.3 — A ingressão: a célula que atravessa e escolhe seu destino")

O momento decisivo da gastrulação é o instante em que uma célula do epiblasto para de ser parte de uma folha e mergulha para dentro do embrião. Enquanto está no epiblasto, a célula é *epitelial*: firmemente aderida às vizinhas, polarizada, imóvel. Para migrar, ela precisa desfazer essas amarras — dissolver as junções que a prendem, perder a polaridade e ganhar a capacidade de rastejar. Essa conversão de célula-de-folha em célula-viajante tem nome: #sigla("EMT", [transição epitélio-mesenquimal — célula epitelial aderida perde junções e vira célula mesenquimal migratória]). A EMT é o motor de todo o processo — sem ela, nenhuma célula sairia do lugar. Vale registrar que essa mesma maquinaria de "soltar a célula da folha" é reativada, de forma patológica, no câncer: células epiteliais de um tumor reeditam a EMT para perder adesão e migrar, e é esse o primeiro passo de uma metástase. O programa que constrói o embrião é o mesmo que, mal-usado, espalha o tumor.

O destino de cada célula depende de *onde ela para* depois de atravessar a linha primitiva. As primeiras células que ingressam empurram o hipoblasto e ocupam o seu lugar, formando a camada mais profunda: o *endoderma*. As células que vêm em seguida não descem tão fundo — estacionam no espaço entre o epiblasto e o endoderma recém-formado, e constituem a camada do meio: o *mesoderma*. E as células do epiblasto que *não* migram, que permanecem na folha de cima, tornam-se por definição o *ectoderma*. Assim, das mesmas células de partida saem os três folhetos, distinguidos apenas pela posição final: quem foi mais fundo é endoderma, quem ficou no meio é mesoderma, quem ficou em cima é ectoderma.

#figura-nebli("/figuras/embrio-gastrulacao-neurulacao/slide-08.png",
  largura: 62%,
  legenda: [O mesmo evento visto de outro ângulo. Células do epiblasto migram: as que vão para o *espaço do meio* formam o mesoderma; as que se inserem na camada profunda (deslocando o hipoblasto) formam o endoderma. O hipoblasto, empurrado lateralmente, contribui para a vesícula vitelínica — tecido extraembrionário, não um dos três folhetos.])

Fixada a origem, o folheto define a família de órgãos que virá dele — e essa correspondência é um dos pontos mais cobrados de toda a embriologia. O *ectoderma* dá o revestimento externo (epiderme) e, surpreendentemente, todo o sistema nervoso. O *endoderma* forra os tubos internos: o revestimento do tubo digestório, do sistema respiratório e das glândulas associadas (fígado, pâncreas). O *mesoderma* preenche o meio e vira quase tudo que é "estrutura de sustentação e movimento": músculos, ossos, sangue, rins, gônadas. Nas próximas partes veremos cada um desses destinos de perto.

#confusao-prevista(
  titulo: "Hipoblasto não é o endoderma",
  aluno_acha: [que o endoderma é simplesmente o hipoblasto, já que ambos são a camada "de baixo".],
  mecanismo: [o endoderma se forma quando células *do epiblasto* migram para baixo e *substituem* o hipoblasto. O hipoblasto original é deslocado para a periferia e vira tecido extraembrionário (vesícula vitelínica). Os três folhetos do corpo são todos derivados do epiblasto — o hipoblasto não entra em nenhum deles.],
)

#subtopico("1.4 — A notocorda: o bastão que vai comandar a próxima etapa")

Entre as células mesodérmicas que ingressam pelo nó primitivo, um grupo tem um destino singular e central. Elas migram para a linha média, exatamente sob o futuro sistema nervoso, e se organizam num cordão maciço que corre no eixo do embrião: a #termo-nota[notocorda][bastão de mesoderma axial na linha média; induz a placa neural e origina o núcleo pulposo dos discos intervertebrais]. Ela é feita de *mesoderma axial* — o mesoderma da linha do eixo. O processo começa como um tubo (o processo notocordal), que por volta do 20º dia atinge sua extensão máxima e por volta do 24º dia se consolida num bastão sólido.

A notocorda tem três funções que vale separar. A primeira é *estrutural*: ela age como um eixo rígido, um esqueleto provisório que dá firmeza ao embrião antes que exista qualquer osso. A segunda é ser *precursora da coluna vertebral* — mas de um jeito muito específico. A notocorda não vira os corpos das vértebras; ela vira apenas o *núcleo pulposo*, o miolo gelatinoso no centro de cada disco intervertebral. Os ossos das vértebras virão de outro tecido (o mesoderma paraxial), que veremos na Parte III. A terceira função é a mais importante para o que vem a seguir: a notocorda é *indutora*. Ela emite sinais químicos para o ectoderma que está logo acima dela e o instrui a mudar de destino — a virar tecido nervoso. Sem esse sinal, não há sistema nervoso. Esse sinal tem nome próprio: uma proteína chamada #sigla("SHH", [sonic hedgehog — proteína sinalizadora secretada pela notocorda; induz e ventraliza o tubo neural]), que a notocorda secreta e que se difunde para cima. A célula "lê" a concentração de SHH que recebe — quanto mais perto da notocorda, mais SHH — e decide seu destino conforme essa dose. É um mesmo mensageiro dando ordens diferentes segundo a distância à fonte, um princípio que se repete em quase todo o desenvolvimento.

#figura-nebli("/figuras/embrio-gastrulacao-neurulacao/slide-12.png",
  largura: 60%,
  legenda: [A notocorda formando-se na linha média (cortes transversais do processo notocordal, dias 16–22). É um bastão de mesoderma axial logo abaixo do ectoderma. Guardar as três funções: eixo rígido de apoio, futuro núcleo pulposo dos discos, e indutor da placa neural — o gatilho da neurulação.])

É essa última função que costura a Parte I na Parte II. A gastrulação terminou seu trabalho essencial: temos três folhetos e temos eixos. Mas o último ato da gastrulação — colocar a notocorda no lugar — é, ao mesmo tempo, o primeiro ato da neurulação. A notocorda, mal se forma, já começa a conversar com o ectoderma acima dela. O que essa conversa produz é o assunto da próxima parte.

#parte-title("PARTE II — Neurulação: erguendo e fechando o tubo neural")

#subtopico("2.1 — Indução neural: a notocorda manda o ectoderma virar nervo")

A neurulação começa com uma ordem. A notocorda, recém-instalada na linha média, sinaliza para a faixa de ectoderma diretamente acima dela, e essa faixa responde mudando de identidade: em vez de virar epiderme, como faria o ectoderma comum, ela se espessa e vira tecido nervoso primordial. Esse espessamento é a #termo-nota[placa neural][faixa espessada de ectoderma na linha média, induzida pela notocorda, que origina todo o sistema nervoso], e ela aparece por volta do 18º dia. A partir daqui, aquela porção de ectoderma passa a se chamar *neuroectoderma*, e todo o sistema nervoso — cérebro, medula, nervos — vai sair dela.

Repare no encadeamento causal, porque ele é a espinha dorsal do tema: notocorda (mesoderma axial) induz → placa neural (neuroectoderma) → sistema nervoso. É um exemplo limpo de *indução embrionária*, em que um tecido determina o destino do vizinho por sinalização química. O ectoderma sozinho não sabe que deve virar nervo; é a notocorda por baixo que lhe dá a instrução. Essa dependência explica por que problemas na formação da notocorda ou nos seus sinais repercutem diretamente na formação do sistema nervoso.

Há uma sutileza que vale entender, porque inverte a intuição. Virar nervo é, na verdade, o caminho "natural" do ectoderma — o que o empurra para virar epiderme são sinais (proteínas da família #sigla("BMP", [bone morphogenetic protein — sinais que empurram o ectoderma a virar epiderme; a indução neural os bloqueia])) que agem como um freio sobre o programa neural. O que o organizador do nó faz não é "ligar" o nervo do zero, e sim liberar moléculas que *bloqueiam esse freio* na faixa central. Onde o freio (BMP) é neutralizado, o ectoderma segue para placa neural; onde o freio continua ativo, vira epiderme. Induzir, aqui, é tirar o pé do freio.

#figura-nebli("/figuras/embrio-gastrulacao-neurulacao/slide-13.png",
  largura: 58%,
  legenda: [A indução neural por volta do 18º dia: a notocorda, na linha média, sinaliza para o ectoderma acima e o converte em *placa neural* (setas). O ectoderma que recebe o sinal deixa de ser destinado a virar epiderme e passa a ser neuroectoderma — a origem de todo o sistema nervoso.])

#subtopico("2.2 — Da placa ao tubo: pregas que se erguem e se fecham")

Tendo a placa neural plana, o próximo passo é transformá-la num tubo. O mecanismo é geométrico e vale visualizar em vez de decorar. As bordas laterais da placa neural começam a se elevar, formando duas cristas paralelas — as *pregas neurais* (ou dobras neurais). Entre elas se aprofunda um sulco central, o sulco neural. As pregas continuam subindo, se aproximam uma da outra na linha média, e por fim se encontram e se fundem no topo. Quando se fundem, o que era uma calha aberta vira um cano fechado: o *tubo neural*.

Há um detalhe que costuma escapar e que é conceitualmente importante. Ao se fecharem, as pregas neurais também *se desconectam* do ectoderma de revestimento que ficou nas laterais. Ou seja, o tubo neural mergulha para dentro do embrião e o ectoderma superficial se fecha por cima dele, restabelecendo uma superfície contínua de epiderme. O sistema nervoso, portanto, nasce na superfície e depois se internaliza — ele começa como parte da "pele" e se separa dela ao fechar.

#figura-nebli("/figuras/embrio-gastrulacao-neurulacao/slide-15.png",
  largura: 72%,
  legenda: [Em cima, vista dorsal do embrião em quatro tempos: a placa neural (alongada), as pregas neurais que se elevam nas bordas, o sulco que se aprofunda, e o tubo que se fecha do meio para as pontas. Embaixo, o corte transversal: a *placa neural* no centro, a *futura crista neural* nas bordas das pregas, e a *futura epiderme* nas laterais — que voltam a se unir por cima do tubo.])

O fechamento não acontece de uma vez ao longo de todo o comprimento. Ele começa na região do meio (a futura região cervical) e avança como um zíper para as duas pontas — em direção à cabeça e em direção à cauda. Enquanto o zíper não termina, sobram duas aberturas temporárias nas extremidades, chamadas #termo-nota[neuroporo][abertura temporária em cada extremidade do tubo neural antes do fechamento completo; o rostral fecha ~dia 25, o caudal ~dia 28]s: o neuroporo rostral (anterior) e o neuroporo caudal (posterior). O rostral se fecha por volta do 25º dia e o caudal por volta do 28º. Guardar que existem essas duas aberturas, e que elas fecham por último, é a chave para entender os defeitos que veremos a seguir. Com o fechamento completo, entre os dias 24 e 26, o tubo neural está pronto para dar origem ao #sigla("SNC", [sistema nervoso central — encéfalo e medula espinhal]): a extremidade cranial se dilata em vesículas encefálicas (o futuro cérebro) e o resto do tubo vira a medula espinhal. E a luz do tubo — o buraco de dentro do cano — não some: ela vira o sistema de cavidades internas do SNC, os ventrículos cerebrais na porção dilatada da cabeça e o canal central fininho ao longo da medula. Vale carregar essa imagem: o líquido que banha o cérebro por dentro circula, no fim das contas, dentro do que já foi a calha da placa neural.

#subtopico("2.3 — Quando o zíper falha: ácido fólico e os defeitos do tubo neural")

Se o fechamento do tubo neural depende de dois neuroporos se fecharem por último, então é justamente ali, nas extremidades, que as coisas dão errado com mais frequência. Quando um neuroporo não se fecha no prazo, o tecido neural permanece exposto e não se desenvolve normalmente — surge um #sigla("DTN", [defeito do tubo neural — falha no fechamento do tubo neural, como anencefalia e espinha bífida]). O *onde* a falha ocorre define o *que* resulta. Se o neuroporo rostral (anterior) não fecha, o encéfalo não se forma adequadamente: é a *anencefalia*, incompatível com a vida. Se o neuroporo caudal (posterior) não fecha, a falha é na medula e nas vértebras da região lombossacra: é a *espinha bífida*, de gravidade variável.

O elo com a clínica é direto e tem um mecanismo bioquímico concreto. As extremidades livres do tubo neural, durante o fechamento, expressam proteínas que se ligam ao *ácido fólico* (folato, a vitamina B9). O folato é indispensável para a síntese de DNA e, portanto, para a proliferação celular intensa que fecha o tubo. Quando falta folato no período em que o tubo está se fechando — as primeiras quatro semanas —, o fechamento fica comprometido e o risco de DTN aumenta. Como essa janela é tão precoce (muitas vezes antes de a mulher saber que está grávida), a suplementação de folato precisa começar *antes* da concepção.

Esse mesmo mecanismo — tubo aberto, tecido neural exposto — explica como o defeito é detectado antes do nascimento. Quando o tubo fica aberto, o tecido neural exposto deixa vazar para o líquido amniótico e para o sangue materno uma proteína fetal, a #sigla("AFP", [alfafetoproteína — proteína fetal cujo nível materno sobe quando há um defeito aberto do tubo neural]); um nível materno elevado dela levanta a suspeita de um defeito aberto. Na anencefalia há ainda uma pista indireta: sem o encéfalo funcionando, o feto não deglute o líquido amniótico como faria normalmente, e o líquido se acumula em excesso (poli-hidrâmnio). São consequências previsíveis do mesmo evento — o tubo que não fechou.

#clinica-box("Ácido fólico e a prevenção da espinha bífida", [
  O tubo neural fecha entre a 3ª e a 4ª semana de gestação — frequentemente antes do diagnóstico da gravidez. As bordas do tubo em fechamento captam folato ativamente, e o folato alimenta a síntese de DNA da proliferação celular que sela os neuroporos. Falta de folato nessa janela → fechamento incompleto → tecido neural exposto → anencefalia (neuroporo rostral) ou espinha bífida (neuroporo caudal). Por isso a recomendação de suplementar ácido fólico no *período periconcepcional* — começando antes de engravidar e mantendo nas primeiras semanas. É uma das intervenções de saúde pública mais custo-efetivas conhecidas: uma vitamina barata que previne uma malformação grave, atacando exatamente o passo bioquímico limitante do fechamento.
])

#subtopico("2.4 — A crista neural: o quarto folheto que sai viajando")

Quando as pregas neurais se elevam e se fundem, sobra na junção entre elas um grupo de células com um comportamento único. Em vez de entrar no tubo neural (virar SNC) ou permanecer na epiderme, essas células — a #termo-nota[crista neural][população de células na borda das pregas neurais que sofre EMT e migra por todo o embrião, originando derivados diversos] — fazem algo diferente: sofrem uma nova transição epitélio-mesênquima, soltam-se e *migram* por todo o embrião. Sua importância é tão grande e seus derivados tão variados que a crista neural é apelidada de "quarto folheto germinativo".

A migração é ordenada. As células partem do dorso (de onde o tubo se fechou) e viajam em direção ventrolateral, agrupadas em quatro grandes contingentes ao longo do eixo cabeça-cauda: *cranial*, *vagal*, *tronco* e *lombossacral*. Cada contingente coloniza uma região e origina estruturas diferentes. O contingente cranial é o mais versátil: dele saem os tecidos conjuntivos, cartilagens e ossos da face (via arcos branquiais), os ossículos da orelha média, melanócitos, alguns tecidos do olho e neurônios. Dos outros contingentes vêm os gânglios do sistema nervoso periférico, a medula da glândula adrenal e os melanócitos do resto do corpo. A lição de fundo é que uma boa parte da face, da pigmentação da pele e do sistema nervoso periférico tem uma origem comum e móvel — não nasce onde acaba, mas migra até lá.

E porque esses derivados dependem de uma viagem longa, uma falha de migração produz doenças bem específicas. O caso mais ilustrativo liga a crista ao intestino: as células que deveriam formar os gânglios nervosos ao longo de todo o tubo digestório migram de cima para baixo, e se elas não chegam até o final do cólon, aquele segmento fica *sem* os gânglios que comandam o relaxamento e o peristaltismo — é a doença de Hirschsprung, em que o trecho sem inervação não relaxa e o intestino a montante se dilata. Guardar esse elo (crista neural que não migrou → intestino sem gânglios) já adianta o encontro entre esta parte e o tubo digestório que fecharemos na Parte III.

#figura-nebli("/figuras/embrio-gastrulacao-neurulacao/slide-19.png",
  largura: 58%,
  legenda: [As células da crista neural partem do dorso (onde o tubo neural se fechou) e migram para a região ventrolateral, em quatro divisões no sentido crânio-caudal (cranial, vagal, tronco, lombossacral). A mesma população que sobra ao fechar o tubo neural vira melanócitos, gânglios periféricos, medula adrenal e boa parte do esqueleto da face.])

Vale contrastar as três populações que saem do neuroectoderma para não confundi-las: o *tubo neural* fica no centro e vira o SNC; a *crista neural* fica nas bordas e migra para virar o SNP, os melanócitos e a face; e a *epiderme* fecha por cima. Três destinos, uma origem comum na placa neural.

#parte-title("PARTE III — Derivados do mesoderma e o dobramento do corpo")

#subtopico("3.1 — As três faixas do mesoderma e o que cada uma constrói")

Enquanto o tubo neural se fecha no dorso, o mesoderma — a camada do meio formada na gastrulação — se organiza em três faixas longitudinais paralelas, de dentro para fora, cada uma com um destino próprio. Colada à notocorda, na linha média, está a faixa mais espessa: o *mesoderma paraxial*. Ao seu lado, uma faixa estreita: o *mesoderma intermediário*. E mais lateralmente, uma faixa ampla que se estende até as bordas do disco: o *mesoderma lateral*. Saber qual faixa gera qual órgão é, junto com os derivados dos folhetos, o conteúdo mais cobrado do assunto.

O *mesoderma paraxial* se segmenta em blocos repetidos ao longo do eixo, os #termo-nota[somito][blocos segmentares de mesoderma paraxial que originam vértebras, costelas, músculo esquelético e derme do dorso]s. Cada somito é um pequeno bloco que dará origem a uma vértebra e suas costelas, ao músculo esquelético daquele segmento e à derme do dorso. É a segmentação dos somitos que explica por que a coluna, as costelas e os músculos do tronco têm aquele padrão repetido, vértebra após vértebra. (Lembre da Parte I: a notocorda vira só o núcleo pulposo do disco; o corpo ósseo da vértebra vem daqui, do somito.)

Vale abrir o somito mais um nível, porque cada um se reparte em três destinos com nome próprio: o *esclerótomo*, que forma a vértebra e a costela; o *miótomo*, que forma o músculo esquelético daquele segmento; e o *dermátomo*, que forma a derme do dorso. Essa mesma lógica segmentar deixa uma marca que persiste no adulto: a faixa de pele inervada por uma única raiz nervosa — o dermátomo — é herança direta da segmentação dos somitos, e é por isso que a dor de uma raiz comprimida se distribui em faixas bem definidas no corpo.

O *mesoderma intermediário*, a faixa estreita do meio, tem um destino enxuto e fácil de guardar: o sistema urinário (rins) e o sistema genital (gônadas). O *mesoderma lateral* se divide em duas folhas — uma somática (parietal) e outra visceral (esplâncnica) — e o espaço entre elas vira as cavidades do corpo (o celoma, futuro pleura/pericárdio/peritônio). Dele saem também o sistema cardiovascular e as células do sangue (sistema hematopoiético), além de anexos extraembrionários. Uma forma de fixar: paraxial faz o "esqueleto e músculo do eixo", intermediário faz "xixi e reprodução", lateral faz "cavidades, coração e sangue".

#figura-nebli("/figuras/embrio-gastrulacao-neurulacao/slide-23.png",
  largura: 66%,
  legenda: [O leque de derivados do mesoderma, de medial para lateral. *Paraxial* → somitos → músculo, esqueleto e derme. *Intermediário* → rins e gônadas. *Lateral* → sistema vascular e hematopoiético, membranas serosas (pleura/peritônio) e anexos extraembrionários. No centro, a notocorda. Guardar este mapa vale por vários parágrafos de texto.])

#subtopico("3.2 — Dobramento céfalo-caudal: o disco vira um corpo curvado")

Até agora tudo aconteceu num disco achatado. Um embrião de verdade, porém, é tridimensional, com uma barriga fechada e um intestino por dentro. A transição do disco plano para o corpo em 3D é o *dobramento embrionário*, e ele ocorre em dois planos ao mesmo tempo, de forma concomitante ao fechamento do tubo neural. O primeiro é o dobramento céfalo-caudal.

O motor do dobramento é o crescimento desigual das estruturas. O tubo neural e os somitos crescem muito mais rápido do que as bordas do disco, e a cavidade amniótica, que se expande por cima (dorsalmente) do embrião, empurra as extremidades para baixo. O resultado é que as pontas do disco — a cranial e a caudal — se curvam ventralmente, para baixo e para dentro, formando a *prega cranial* e a *prega caudal*. O embrião, que era uma folha plana, adquire a forma de um "C" fechando sobre o próprio ventre. Esse encurvamento é o que confere tridimensionalidade na direção cabeça-cauda: a cabeça se projeta para a frente sobre o coração em formação, e a cauda se dobra por baixo.

O dobramento não só encurva o corpo: ele *reposiciona órgãos*. O coração e o septo transverso (a placa de mesoderma que vira o diafragma) começam à frente da cabeça, na região mais cranial do disco; conforme a prega cranial se dobra ventralmente, essas estruturas são levadas para baixo, para dentro do futuro tórax. Isso deixa uma pegada anatômica que dura a vida toda: o nervo que inerva o diafragma nasce lá em cima, nos segmentos cervicais (o nervo frênico, das raízes cervicais 3 a 5), e "desce" acompanhando o diafragma na sua viagem — a inervação vem de onde a estrutura *estava*, não de onde ela terminou.

#figura-nebli("/figuras/embrio-gastrulacao-neurulacao/slide-27.png",
  largura: 68%,
  legenda: [Corte sagital do dobramento céfalo-caudal em três tempos. As pregas cranial e caudal se curvam ventralmente (a cavidade amniótica, dorsal, expande e "abraça" o embrião). O disco plano vira um corpo em forma de C — a tridimensionalidade no eixo cabeça-cauda.])

#subtopico("3.3 — Dobramento lateral: fechando o ventre e criando o intestino")

O segundo plano de dobramento acontece de lado. As bordas laterais do disco, empurradas pela expansão da cavidade amniótica, também se curvam ventralmente — são as *pregas laterais*. Elas avançam uma em direção à outra por baixo do embrião até se encontrarem na linha média ventral, fechando a parede do corpo como quem fecha um pacote. É o dobramento lateral que sela o ventre e dá ao embrião sua forma cilíndrica fechada.

O evento mais consequente do dobramento lateral acontece com o endoderma. Enquanto as pregas laterais se fecham, elas arrastam consigo a folha de endoderma, que estava aberta e achatada por baixo. Ao se encontrarem no ventre, elas enrolam esse endoderma num *tubo*: o tubo intestinal primitivo, futuro *tubo digestório*. O endoderma, que forra esse tubo por dentro, fica assim aprisionado no interior do embrião, ventral ao mesoderma. Uma parte do endoderma continua conectada à vesícula vitelínica por fora, mas o essencial já é um cano interno, correndo da cabeça à cauda. A extremidade anterior desse tubo será a *boca* e a posterior será o *ânus*.

#figura-nebli("/figuras/embrio-gastrulacao-neurulacao/slide-32.png",
  largura: 62%,
  legenda: [O dobramento lateral enrola o endoderma num tubo — o tubo digestório primitivo. Ele corre da extremidade anterior (futura *boca*) à posterior (futuro *ânus*), com as regiões de intestino anterior, médio e posterior já esboçadas. O endoderma fica ventral ao mesoderma, aprisionado dentro do corpo agora fechado.])

Há dois pontos, um em cada ponta do tubo, onde o mesoderma nunca se interpôs entre o ectoderma e o endoderma — e é por isso que ali as duas camadas ficam em contato direto, formando membranas finas que depois se rompem para abrir a boca e o ânus. Na frente, a *placa precordal* origina a #termo-nota[membrana bucofaríngea][membrana anterior de ecto + endoderma, sem mesoderma entre elas; rompe-se para formar a abertura da boca]: é onde a boca vai se abrir. Atrás, a região cloacal origina a membrana cloacal: é onde o ânus vai se abrir. Nessas duas regiões — e só nelas — não há mesoderma no meio, o que explica por que são pontos frágeis, destinados a se romper e criar as aberturas do tubo digestório para o exterior. E se a membrana cloacal não se rompe na hora certa, o ânus simplesmente não se perfura — é o ânus imperfurado, uma malformação que se entende direto a partir daqui: a abertura depende da ruptura da membrana.

Esse tubo endodérmico, além de ter duas pontas, já nasce dividido em três regiões ao longo do comprimento — o intestino anterior, o médio e o posterior —, e cada uma será irrigada por uma artéria própria que sai da aorta. Essa divisão precoce não é detalhe cosmético: o mapa "qual artéria irriga qual pedaço do intestino" que se usa na clínica do adulto é herança direta dessas três porções esboçadas ainda no embrião.

#confusao-prevista(
  titulo: "Os dois dobramentos fazem coisas diferentes",
  aluno_acha: [que o dobramento céfalo-caudal e o lateral são a mesma coisa vista de ângulos diferentes.],
  mecanismo: [são dois movimentos em planos distintos. O *céfalo-caudal* curva as pontas cranial e caudal ventralmente (visto em corte sagital) e dá a forma de C. O *lateral* fecha as paredes do corpo pelos lados (visto em corte transversal) e, ao fazê-lo, enrola o endoderma no tubo digestório. Os dois ocorrem juntos e, somados, transformam o disco plano num corpo cilíndrico fechado com intestino por dentro.],
)

#conclusao-box[
  Se há um princípio único que atravessa este capítulo inteiro, é este: *o corpo se constrói por movimento, não por aparecimento*. Nenhuma das estruturas que vimos surgiu do nada no lugar certo — todas nasceram de células que já existiam e que migraram, atravessaram camadas, se dobraram ou mudaram de forma na hora exata. O mecanismo nuclear que amarra tudo é a sequência de indução e migração deflagrada na gastrulação: o epiblasto ingressa pela linha primitiva (via EMT) e gera os três folhetos; do mesoderma axial nasce a notocorda; a notocorda induz a placa neural; a placa se fecha no tubo neural (SNC) e libera a crista neural migratória; o mesoderma se reparte em paraxial, intermediário e lateral, cada um com seus órgãos; e o dobramento em dois planos enrola o disco num corpo 3D com o endoderma aprisionado como tubo digestório. A clínica retomada mostra por que isso importa na prática: como o fechamento do tubo neural depende de proliferação celular ávida por folato numa janela precocíssima, a falta de ácido fólico periconcepcional trava exatamente esse passo e resulta em anencefalia ou espinha bífida — uma malformação grave prevenível com uma vitamina barata. Daqui em diante, cada folheto e cada tubo que formamos vira o ponto de partida da *organogênese*: os somitos viram coluna e músculo, o tubo neural vira encéfalo e medula, o tubo digestório se especializa em faringe, estômago e intestino. A forma do corpo está pronta; o próximo capítulo é sobre transformá-la em órgãos.
]
