#import "../typst-template/nebli_v2_apostila.typ": *

#discursiva("Q1",
  [Um homem de 72 anos é operado por vólvulo de sigmoide. Explique, encadeando a anatomia com a mecânica do quadro, por que o sigmoide é o segmento colônico mais sujeito à torção e por que essa torção ameaça a viabilidade da alça, e não apenas a passagem do conteúdo.],
  [O sigmoide reúne duas condições: alça longa e raiz de mesocolo curta. Alça comprida presa por base estreita pode girar sobre o próprio eixo. O giro fecha a luz nas duas pontas e o gás bacteriano fica retido, distendendo a alça. Como o mesocolo conduz os vasos, o mesmo giro os estrangula: a drenagem venosa cede antes da entrada arterial, a parede ingurgita e a pressão intramural acaba barrando também o fluxo arterial. Daí em diante a evolução é isquêmica — necrose e perfuração. O vólvulo é obstrução com os vasos dentro do nó.])

#discursiva("Q2",
  [Descreva os componentes da válvula ileocecal e explique por que a competência dessa válvula muda o comportamento de uma obstrução instalada no colo distal, indicando qual segmento corre o maior risco de perfurar e por quê.],
  [O íleo terminal projeta-se para dentro do ceco formando a papila ileal, constituída pelo lábio ileocólico, superior, e pelo lábio ileocecal, inferior, com o óstio ileal entre eles. O fechamento é geométrico: a pressão do ceco aperta um lábio contra o outro, criando passagem de sentido único. Se a válvula é competente, o conteúdo do delgado não reflui e o colo fica fechado nas duas pontas — alça fechada. A pressão sobe rápido e, como o ceco é o segmento de maior calibre, a tensão de parede fica crítica primeiro nele: ele perfura longe do obstáculo.])

#discursiva("Q3",
  [Caracterize as tênias do colo — o que são, de onde a onde vão e como se chamam — e explique por que a existência delas produz as saculações e por que o reto não apresenta nem tênias nem saculações.],
  [As tênias são a camada muscular longitudinal do colo concentrada em três faixas espessas, que correm do ceco até a junção retossigmoide. Chamam-se mesocólica, na borda de inserção do mesocolo; omental, na linha de fixação dos apêndices omentais; e livre, na face exposta, onde nada está preso. Como as três faixas são mais curtas que o tubo, mantêm-no franzido, e cada bolsa desse franzimento é uma saculação. Na junção com o reto as tênias se abrem e refazem uma lâmina contínua: sem faixas curtas puxando a parede, acabam o franzimento e as saculações.])

#discursiva("Q4",
  [Explique por que uma única linha do canal anal — a linha pectinada — separa territórios diferentes de artéria, veia, linfático e inervação, e mostre como esse fato explica a diferença clínica entre hemorroida interna e hemorroida externa.],
  [A porção do canal acima da linha deriva do intestino posterior, de origem endodérmica; a porção abaixo deriva do proctodeu, de origem ectodérmica. As duas se fundem na pectinada, e cada uma trouxe a irrigação, a drenagem e a inervação do território de onde veio. Acima: artéria retal superior, plexo interno para o sistema porta, linfa para ilíacos internos, inervação visceral. Abaixo: artéria retal inferior, plexo externo para a cava, linfa para inguinais superficiais, inervação somática do pudendo. Por isso a hemorroida interna sangra sem doer e a externa trombosada dói muito.])

#discursiva("Q5",
  [Cite as relações anatômicas do reto e caracterize o canal anal, explicando como as estruturas descritas se combinam para produzir continência e como essa mesma máquina se inverte durante a defecação.],
  [O reto tem 15 cm, faz a flexura sacral e termina na flexura anorretal. Só o terço superior é peritonizado à frente e nas laterais; o médio, apenas à frente; o inferior é extraperitoneal. À frente relaciona-se com bexiga e próstata no homem, útero e vagina na mulher, formando as escavações retovesical e retouterina; atrás, com sacro e cóccix. A ampola é reservatório complacente e sensor de enchimento. O canal anal, de 4 cm, tem colunas, seios, linha pectinada e linha branca, fechado pelo esfíncter interno liso e involuntário, pelo externo estriado e voluntário e pela alça do puborretal. A continência soma tônus do interno, ângulo do puborretal, contração do externo e coxim vascular; na defecação o puborretal relaxa, retifica o ângulo e a prensa abdominal empurra.])
