#import "../typst-template/nebli_v2_apostila.typ": *

#pre-aula-page[
A aula de hoje responde a uma pergunta prática do laboratório e uma pergunta conceitual da biologia com o mesmo conjunto de ideias. A pergunta prática é por que a cultura de uma amostra clínica demora vinte e quatro horas para dar resultado, e às vezes semanas. A conceitual é o que exatamente uma bactéria faz com o que ela come. As duas se encontram no mesmo lugar, porque o que a bactéria come determina em quanto tempo ela dobra de número, e é o número que se vê na placa.

O professor vai começar separando duas palavras que na linguagem comum se confundem. *Nutrição* é o fornecimento de substâncias ao microrganismo; *crescimento bacteriano* não é a célula ficar maior, é a população aumentar em número, e ela aumenta por *divisão binária*, em que a célula duplica o cromossomo e se parte em duas filhas idênticas. Guardar essa diferença desde o início evita metade das confusões do resto da aula. Em seguida vem o inventário do que a célula precisa: carbono, nitrogênio, enxofre e fósforo formam quase todo o *peso seco*, e íons como potássio, magnésio e ferro entram em quantidade muito menor como cofatores de enzimas.

Daí sai a *classificação nutricional*, que costuma assustar pelo tamanho das palavras e é apenas a soma de três respostas. O prefixo diz de onde vem a energia, e separa *fototrófico*, que usa luz, de *quimiotrófico*, que usa a energia liberada por uma reação química. O trecho do meio diz quem doa os elétrons dessa reação, separando *litotrófico*, que arranca elétrons de composto inorgânico, de *organotrófico*, que os arranca de composto orgânico. O sufixo diz de onde vem o carbono, separando *autotrófico*, que fixa gás carbônico, de *heterotrófico*, que precisa de molécula orgânica pronta. Toda bactéria de interesse médico é *quimiorganoheterotrófica*, e essa é a razão de todo meio de cultura começar por proteína hidrolisada.

A parte seguinte da aula percorre as condições físico-químicas, e vale chegar sabendo que cada uma age por um mecanismo diferente. O *pH* mexe na forma da enzima, e a maioria das espécies é *neutrófila*, com ótimo perto de sete; o citoplasma, porém, é mantido próximo da neutralidade mesmo quando o meio muda, o que explica por que o meio de cultura leva *tampão*. A *temperatura* tem curva assimétrica, com subida gradual e queda abrupta logo depois do ótimo, porque a subida é cinética e a queda é desnaturação; os patógenos humanos são *mesófilos*, com ótimo em torno de trinta e sete graus, ao lado de *psicrófilos*, *termófilos* e *hipertermófilos*. A concentração de sal age por desidratação osmótica, e daí saem os termos *halotolerante* e *halófilo*.

O oxigênio recebe atenção separada e é onde mora a inversão mais comum. Existem *aeróbios estritos*, *microaerófilos*, *anaeróbios estritos* e *anaeróbios facultativos*, e a chave não é preferência, é sobrevivência: o oxigênio gera espontaneamente derivados reativos, e quem não tem *superóxido dismutase* e *catalase* morre no ar em vez de simplesmente deixar de crescer. Logo depois entra o *ferro*, que o professor trata como micronutriente crítico. O hospedeiro guarda quase todo o seu ferro dentro de *transferrina*, *lactoferrina*, *ferritina* e *hemoglobina*, estratégia chamada de *imunidade nutricional*, e as bactérias patogênicas respondem com *sideróforos*, com *hemolisinas* e com receptores que arrancam o metal diretamente dessas proteínas.

A segunda metade da aula é energética. A *glicólise* aparece em três estágios, com o primeiro gastando ATP para fosforilar a glicose, o segundo produzindo NADH e ATP por *fosforilação em nível de substrato*, e o terceiro existindo apenas para regenerar o NAD mais. Esse terceiro estágio é a definição de *fermentação*, um processo de oxirredução em que o aceptor final de elétrons é uma molécula orgânica produzida pela própria via, com rendimento baixo e independência total do ambiente. Quando há aceptor externo, a bactéria muda para *respiração*, e o piruvato passa a alimentar o *ciclo de Krebs* enquanto o NADH entrega elétrons à *cadeia respiratória*. Aqui há um detalhe anatômico que costuma escapar e que o professor vai dizer de passagem: como não existe mitocôndria, essa cadeia fica na *membrana plasmática* da própria bactéria. A distinção final é entre *respiração aeróbia*, com oxigênio como aceptor, e *respiração anaeróbia*, com nitrato, sulfato ou carbonato ocupando esse papel.

O bloco seguinte é o coração da aula. A *curva de crescimento* tem quatro trechos, e cada nome carrega um mecanismo. A *fase lag* é adaptação, sem divisão e com intensa atividade metabólica. A *fase logarítmica* é divisão em velocidade máxima e constante, governada pelo *tempo de geração* da espécie. A *fase estacionária* é o equilíbrio entre células que nascem e células que morrem, imposto pelo esgotamento de nutriente e pelo acúmulo de produto tóxico. A *fase de declínio* é a queda do número de viáveis. Vale chegar já sabendo que a diferença de *tempo de duplicação* entre espécies é enorme, de vinte minutos numa enterobactéria a quase um dia numa micobactéria, e que essa diferença é o que explica o prazo do laboratório e também a fase em que cada antibiótico é mais eficaz.

A aula fecha na bancada. Os *meios de cultura* têm composição previsível, com hidrolisado de proteína, carboidrato, tampão, *indicador de pH*, inibidor e ágar, e se dividem em *não seletivos*, como o ágar sangue, em *seletivos e diferenciais*, como o *ágar MacConkey* e o *ágar Salmonella-Shigella*, e em meios de *enriquecimento*, como os caldos tetrationato e selenito. O *ágar chocolate* aparece como caso especial, porque o aquecimento libera o *fator X* e o *fator V* de que algumas espécies dependem. Por fim vêm a *técnica de esgotamento do inóculo*, que produz a *colônia isolada*, as condições de incubação e os *meios cromogênicos*, que identificam a espécie pela cor sem bateria de confirmação. Chegue com esse mapa na cabeça: nutrição define quem cresce, metabolismo define quanto rende, e a curva define quando aparece.
]
