#import "../typst-template/nebli_v2_apostila.typ": *

#pre-aula-page[
A aula de hoje tem uma pergunta única por trás de tudo o que vai ser dito, e ela é mais interessante do que o título sugere. Uma população bacteriana precisa fazer duas coisas incompatíveis ao mesmo tempo: copiar-se com fidelidade suficiente para continuar sendo a mesma espécie, e variar o bastante para que alguém sobreviva quando o ambiente mudar. A professora vai declarar cedo que só existem dois caminhos para essa variação — *mutação*, que é alteração da sequência de bases do DNA que a bactéria já tinha, e *recombinação*, que é a chegada de material genético vindo de fora. Essa dicotomia é o esqueleto da aula inteira, e vale chegar sabendo que ela não é uma classificação decorativa: metade do tempo será gasto num ramo, metade no outro.

A abertura é de arrumação. Antes de discutir variação, é preciso saber onde o material genético fica. Na bactéria ele fica solto no citoplasma, condensado numa região sem membrana chamada *nucleoide* — não há núcleo, e é dessa ausência que decorrem várias particularidades. O cromossomo é geralmente único, de fita dupla e circular, e mede cerca de mil vezes o comprimento da célula que o abriga; ele só cabe ali porque está torcido sobre si mesmo num estado chamado *superenovelamento*, mantido ativamente por enzimas. A principal delas é a *DNA girase*, uma topoisomerase que corta as duas fitas, passa um segmento do anel pela abertura e religa — e que interessa muito além da genética, porque é o alvo das quinolonas.

Ao lado do cromossomo aparece a segunda molécula da aula, o *plasmídeo*: um anel de DNA muito menor, fisicamente separado, com origem de replicação própria. Ter origem própria é o que faz dele um *replicon* independente, capaz de se duplicar no seu ritmo. O conteúdo do plasmídeo é sempre acessório — resistência a antibiótico, adesão, invasão, toxina — e essa é a distinção que a professora vai insistir: o cromossomo diz quem a bactéria é, o plasmídeo diz o que ela consegue fazer. Aparecem aí dois adjetivos que voltarão depois: um plasmídeo é *conjugativo* quando codifica a maquinaria que o transfere, e é *epissomal* quando consegue se integrar ao cromossomo.

A partir daí a aula entra no primeiro ramo, a mutação, e ela vem em duas modalidades. A *mutação espontânea* ocorre sem agente externo, o que não quer dizer sem causa: as bases estão hidratadas, oscilam entre duas formas químicas, e a forma rara engana a polimerase no momento do pareamento. Mesmo com a atividade revisora da enzima, sobra cerca de um erro a cada cem milhões de bases. A *mutação induzida* vem de um *agente mutagênico*, também chamado genotóxico, e cada agente produz um tipo característico de lesão. A radiação ultravioleta forma o *dímero de pirimidina*, uma ligação covalente entre duas pirimidinas vizinhas da mesma fita que dobra a hélice e trava a replicação sem trocar informação nenhuma. A *radiação ionizante* faz outra coisa: quebra o esqueleto, de uma fita ou das duas. Entre os agentes químicos aparecem as moléculas planares, que se intercalam e deslocam a fase de leitura, e os *agentes alquilantes*, que grudam um radical numa base e mudam a preferência de pareamento dela. Dois termos de nomenclatura passam rápido: *transição* é troca de uma base por outra da mesma categoria química, *transversão* é troca entre categorias.

O bloco seguinte é o mais denso da aula, e é onde vale prestar mais atenção. Diante de um DNA lesado há três desfechos, não um: reparo correto, com restauração da sequência; ausência de reparo, com morte da célula; e reparo que não restaura, que é a origem da mutação induzida. Os sistemas fiéis são três. A *fotorreativação* usa a enzima *DNA fotoliase*, que absorve energia de luz visível e desfaz o dímero de pirimidina — e só ele. O *reparo por excisão* corta o trecho danificado dos dois lados e ressintetiza usando a fita oposta como molde. O *reparo recombinacional* resolve a quebra de dupla fita buscando a informação na cópia irmã já replicada. E quando a carga de lesão supera a capacidade desses sistemas, entra a *tolerância a lesões*: a célula suprime deliberadamente a revisão da polimerase e deixa que ela insira uma base qualquer, apenas para a forquilha avançar. Ela sobrevive mutada em vez de morrer íntegra, e essa troca é a frase mais importante da primeira metade da aula.

Duas aplicações fecham o ramo. Uma é obter mutantes de propósito, que foi como se chegou às linhagens industriais que produzem penicilina em quantidade útil. A outra é usar bactéria como sentinela de substâncias perigosas — o *teste de Ames*, em que uma linhagem incapaz de sintetizar histidina só cresce se a substância testada induzir mutação reversora, e o *cromoteste*, em que o dano ao DNA é lido como cor amarela quantificável.

O segundo ramo, a recombinação, tem três rotas que se distinguem pelo veículo. Na *transformação*, DNA nu boiando no meio atravessa a membrana sem intermediário — foi o que Griffith descreveu em 1928 sem saber o que era, chamando de *princípio transformante*, e o que Avery, MacLeod e McCarty identificaram como DNA em 1944. Entrar exige um estado fisiológico chamado *competência*. Na *conjugação*, o material passa entre duas células em contato, através de um *pilus de conjugação*; quando o *fator F* está integrado ao cromossomo, a célula se chama *Hfr* e é capaz de arrastar o cromossomo inteiro atrás dele. Na *transdução*, o veículo é um vírus: o fago empacota por engano DNA da bactéria anterior. Quando o vírus se integra e fica silencioso, chama-se *profago*, e a bactéria passa a expressar genes dele — é a *conversão lisogênica*, o mecanismo pelo qual o bacilo da difteria adquire a capacidade de produzir toxina.

O fecho é sobre elementos que se movem dentro da célula. O *transposon* é um trecho de DNA ladeado por *repetições invertidas*, com o gene de uma *transposase* no meio, que salta de uma molécula para outra — e é ele que tira o gene de resistência do plasmídeo perdível e o fixa no cromossomo, formando o que se chama *ilha de patogenicidade*. Ao lado dele existe o *integron*, uma plataforma que captura cassetes de resistência em fila sob um promotor único. E a aula termina no *CRISPR*, o arquivo de fragmentos de vírus que a bactéria guarda no próprio genoma e usa para reconhecer e cortar invasores conhecidos.

Chegue com esse mapa na cabeça: dois ramos, três destinos para o DNA lesado, três rotas de transferência, e um desfecho comum a tudo — a resistência a antibiótico.
]
