#import "../typst-template/nebli_v2_apostila.typ": *

#pre-aula-page[
A aula de hoje descreve uma única resposta do organismo, da primeira molécula que sinaliza dano até a forma que o tecido inflamado assume quando o patologista o corta e olha ao microscópio. O professor vai chamar essa resposta de *inflamação aguda*, e vai tratá-la como um processo com etapas fixas: primeiro o vaso muda, depois o líquido sai, depois as células saem, depois elas trabalham, e no fim sobra uma morfologia. Vale entrar na sala já sabendo que essa ordem existe, porque cada bloco de slides corresponde a um degrau dela.

A abertura é a definição e os cinco *sinais flogísticos* — calor, rubor, tumor, dor e perda funcional. O professor não vai apresentá-los como lista clínica a decorar, e sim como leitura externa de eventos vasculares: calor e rubor são a mesma coisa vista de dois jeitos, o aumento de sangue arterial na área; tumor é líquido acumulado no interstício; dor tem um componente químico e outro mecânico. Logo em seguida vêm os desencadeantes, e aqui aparece o primeiro ponto que costuma pegar quem estuda por decoreba: infecção é apenas um deles. *Necrose tecidual* de origem isquêmica ou traumática, corpo estranho, reações de hipersensibilidade e agentes químicos e físicos disparam a mesma resposta sem micróbio nenhum.

O bloco seguinte se chama alterações iniciais e é o mais molecular da aula. Ele responde como o tecido percebe que houve dano. Os termos que o professor vai usar como se já fossem conhecidos são *PAMP*, os padrões moleculares que só existem em micro-organismos, e *DAMP*, as moléculas do próprio hospedeiro que vazam quando uma célula morre. Quem lê esses padrões são os *receptores do tipo Toll*, distribuídos na membrana, no endossomo e no citosol, e o *inflamassoma*, um complexo citosólico que ativa a *caspase-1* e com ela libera a *interleucina-1β* madura. Guarde que o inflamassoma precisa de dois sinais separados para funcionar — é esse detalhe que explica por que cristais, como o urato da gota, inflamam sem infecção.

Depois disso a aula entra nas alterações vasculares, que ocupam a maior parte dos slides. Três palavras organizam o bloco. A *vasodilatação* é o relaxamento da arteríola, que aumenta o fluxo local e produz calor e rubor. O *aumento de permeabilidade* é a abertura da parede da *vênula pós-capilar*, que deixa sair proteína plasmática. E a *estase* é a lentificação do fluxo que se instala quando o sangue perde plasma e fica mais viscoso — um fenômeno que parece defeito e é, na verdade, a condição que empurra o leucócito contra a parede do vaso.

Dentro desse bloco vêm quatro mecanismos de permeabilidade que o professor vai nomear rapidamente: *contração endotelial*, a mais comum e a mais breve; *lesão endotelial direta*, que é necrose da parede e dura dias; lesão mediada por leucócito, que é tardia; e *transcitose*, transporte através da própria célula endotelial. Junto vem a distinção que a patologia mais cobra: *exsudato* contra *transudato*. O exsudato é rico em proteína e células porque a barreira foi aberta; o transudato é pobre em ambos porque a barreira está íntegra e o que mudou foram as forças hidrostática e coloidosmótica. Os números que acompanham essa tabela — três gramas por decilitro de proteína, densidade de 1020, duzentas unidades de *desidrogenase láctica* — valem ser vistos antes da aula, porque o professor os trata como conhecidos. O bloco fecha com a resposta linfática, onde aparecem *linfangite* e linfadenopatia.

A metade seguinte da aula trata das alterações celulares, e aqui há uma sequência de cinco etapas que se repete slide após slide: *marginação*, *rolamento*, *adesão*, *transmigração* e *quimiotaxia*. Cada etapa tem a sua molécula. No rolamento, *selectinas* do endotélio ligam o *Sialyl-Lewis X* do leucócito com afinidade baixa, o que faz a célula rolar em vez de parar. Na adesão, *integrinas* mudam de conformação e se ligam a *ICAM-1* e *VCAM-1*, prendendo firme. Na *diapedese*, o leucócito passa entre as células endoteliais com auxílio da *PECAM-1* e digere a membrana basal com *metaloproteinases*. E na quimiotaxia ele caminha por um gradiente formado por *C5a*, *leucotrieno B₄*, *interleucina-8* e peptídeos bacterianos. Acima de tudo isso estão duas citocinas que o professor vai repetir muitas vezes, o *TNF* e a *interleucina-1*, produzidas por macrófagos e responsáveis tanto pela ativação do endotélio quanto pelos efeitos sistêmicos — febre, leucocitose e proteínas de fase aguda.

O terceiro bloco chama-se mecanismos efetores e tem três palavras-chave: reconhecimento, remoção e efeitos regulatórios. Reconhecimento é a *opsonização*, o revestimento do alvo por imunoglobulina G e por *C3b*, que dá ao fagócito uma alça para segurar. Remoção é a fagocitose até o *fagolisossomo*, seguida do *burst respiratório* — a *NADPH oxidase* produzindo superóxido, que vira peróxido de hidrogênio e, pela *mieloperoxidase*, hipoclorito. Efeitos regulatórios são o desligamento: mediadores de meia-vida curta, a troca da via do ácido araquidônico para *lipoxinas* anti-inflamatórias, e a mudança do macrófago do programa microbicida para o programa de reparo.

A aula fecha com desdobramentos e padrões morfológicos, e é aqui que a patologia entrega o produto. Os desdobramentos são quatro — *resolução*, *abscesso*, *fibrose* e progressão para inflamação crônica — e o que decide entre eles é a combinação de agente removido ou persistente, extensão do dano e capacidade de regeneração do tecido. Os padrões morfológicos são os nomes que o patologista dá ao que vê: inflamação *serosa*, *fibrinosa*, *supurativa* com *pus*, *úlcera* e *flegmão*. O ponto que vale carregar para a aula é que esses nomes não são etiquetas arbitrárias: o abscesso é delimitado porque o organismo consegue construir uma parede em torno dele, e o flegmão é difuso porque o agente produz enzimas que dissolvem a matriz e impedem essa parede de existir.

Chegue com esse mapa na cabeça: vaso que abre, líquido que sai, célula que atravessa, efetor que mata e machuca, e uma morfologia final que conta a história inteira de trás para frente.
]
