#import "../typst-template/nebli_v2_apostila.typ": *

#resumindo-page((
  ("Fígado × músculo",
   [O fígado (≈10% da massa em glicogênio) regula a *glicemia sistêmica* e tem glicose-6-fosfatase, exportando glicose. O músculo (≈2%) guarda para si e, sem essa enzima, retém a glicose como glicose-6-fosfato.]),
  ("Fosforólise",
   [A glicogênio fosforilase corta a ligação α(1→4) com fosfato (não água), liberando *glicose-1-fosfato* já fosforilada — economiza ATP e prende o carbono na célula. Usa piridoxal-fosfato (vitamina B6).]),
  ("Enzima desramificadora",
   [A fosforilase para 4 resíduos antes do galho. A desramificadora bifuncional *transfere* um bloco de 3 e *hidrolisa* o resíduo α(1→6), soltando glicose livre (~10% do total; ~90% sai como glicose-1-fosfato).]),
  ("UDP-glicose ativa",
   [Na síntese, glicose-1-fosfato + UTP formam *UDP-glicose* (forma ativada); a hidrólise do pirofosfato torna o passo irreversível. Descoberta de Leloir, Nobel de 1970.]),
  ("Sintase, glicogenina, ramificadora",
   [A glicogênio sintase alonga em α(1→4) mas precisa de primer; a *glicogenina* fornece esse primer e fica presa à extremidade redutora. A *enzima ramificadora* abre os galhos α(1→6).]),
  ("Custo energético",
   [Sintetizar glicogênio gasta *2 ATP por glicose*: um para fosforilar a glicose em glicose-6-fosfato, outro para regenerar o UTP a partir do UDP. Guardar energia é investimento.]),
  ("Regulação recíproca",
   [A *fosforilação ativa a fosforilase e inativa a sintase* — um sinal, efeitos opostos, para as vias nunca correrem juntas. A desfosforilação (PP1) faz o inverso.]),
  ("Cascata do glucagon/adrenalina",
   [Hormônio → proteína G → adenilato-ciclase → *AMPc* → *PKA* → fosforilase-quinase → fosforilase a. Cada nível amplifica: um hormônio libera milhões de glicoses.]),
  ("Insulina e desligamento",
   [A insulina ativa a *PP1*, que desfosforila as enzimas (inativa a fosforilase, ativa a sintase). A *fosfodiesterase* degrada o AMPc, encerrando o sinal da PKA.]),
  ("Sensor de glicose hepático",
   [No fígado, a *fosforilase a é sensor de glicose*: glicemia alta a empurra ao estado T e à desfosforilação pela PP1. No músculo não há esse sensor — ele responde ao AMP.]),
  ("Doenças de depósito",
   [Autossômicas recessivas, glicogênio cora ao PAS. von Gierke (I): glicose-6-fosfatase → hipoglicemia, hepatomegalia, ↑lactato/ácido úrico. Pompe (II): maltase ácida lisossomal → cardiomegalia. Cori (III): desramificadora. Andersen (IV): ramificadora. McArdle (V): fosforilase muscular → intolerância ao exercício. Hers (VI): fosforilase hepática.]),
))
