#import "../typst-template/nebli_v2_apostila.typ": *

#resumindo-page((
  ("Reconhecimento hierárquico",
   [A primeira pergunta do sistema imune não é “que molécula é esta?”, e sim “existe homeostasia?”. Quem responde são os PRR; só depois os receptores clonais leem o antígeno.]),
  ("Resposta ou tolerância",
   [O mesmo antígeno pode gerar eliminação ou aceitação. O que decide é o estado homeostático do tecido de onde ele veio — contexto, não identidade química. Ambos os desfechos deixam memória.]),
  ("PAMP e DAMP",
   [PAMP é assinatura de micro-organismo; DAMP é assinatura de dano do próprio tecido. Por incluir DAMP, a inata dispara sem infecção — queimadura, infarto, trauma.]),
  ("Endereço prediz ligante",
   [Membrana plasmática lê superfície microbiana; endolisossomo lê ácido nucleico internalizado; citosol lê replicação viral e peptidoglicano; núcleo lê DNA. Segregação topológica evita autorreatividade.]),
  ("TLR de superfície",
   [TLR1 lipoproteína triacilada, TLR2 lipoproteína, TLR4 LPS, TLR5 flagelina, TLR6 lipoproteína diacilada, TLR11 profilina de protozoário.]),
  ("TLR endolisossomais",
   [TLR3 lê dsRNA, TLR7 (TLR8 no humano) lê ssRNA e TLR9 lê DNA CpG não metilado. Todo sensor de ácido nucleico está dentro de compartimento — é trava contra reagir ao próprio.]),
  ("RLR, NLR e CLR",
   [RIG-I lê dsRNA curto e 5′-trifosfato, MDA5 lê dsRNA longo; NOD1 lê iE-DAP e NOD2 lê MDP; Dectina-1 e Dectina-2 leem β-glucano de fungo.]),
  ("Ligação do TLR",
   [O ligante ou força a dimerização de receptores isolados, ou muda a conformação de um dímero pré-formado. Em ambos os casos, o que muda é a geometria da cauda citoplasmática.]),
  ("MyD88 e TRIF",
   [MyD88 leva a NF-κB e AP-1 → citocinas inflamatórias e quimiocinas. TRIF leva aos IRF → interferons do tipo I, antivirais. As vias se cruzam; há ainda AKT, caspase-8 e inflamassoma.]),
  ("Inflamassoma",
   [Plataforma montada por NLRP, IPAF e AIM2 que ativa caspase-1 e cliva pró-IL-1β e pró-IL-18 em citocinas maduras. Os NOD não montam plataforma: ativam NF-κB.]),
  ("NLRP3 em dois sinais",
   [Priming (TLR/TNF via NF-κB) sintetiza a pró-IL-1β; o segundo sinal — ATP/P2X7 com efluxo de K⁺, ruptura lisossômica por cristais, ROS — monta NLRP3 + ASC + caspase-1.]),
  ("Interferon do tipo I",
   [A célula infectada libera IFN antes de morrer e induz estado antiviral nas vizinhas: elas bloqueiam a replicação, ela não se salva. Efeitos sistêmicos explicam os sintomas de gripe.]),
  ("Citotoxicidade celular",
   [Não é destruição de fora: é suicídio induzido. Reconhecimento clonal ou inato aproxima FasL–Fas, ou há desgranulação; a alvo entra em apoptose e a efetora parte para outro alvo.]),
  ("Fagocitose em etapas",
   [Quimiotaxia (complemento é PRR solúvel) → adesão com opsonização → zíper de receptores → fagossoma → fusão lisossômica → enzimas e explosão respiratória.]),
  ("Citocinas e receptor",
   [São pleiotrópicas; o efeito depende de quem expressa o receptor. Nomes são históricos (IL, GF, CSF, IFN) — só as quimiocinas usam classificação estrutural: CXC, CC, CX3C, XC.]),
  ("Plasticidade da inata",
   [A ativação libera produtos estocados, modificados após ativação, recém-sintetizados e de degradação celular. A diversidade não está no repertório, está na combinação.]),
))
