import hashlib, json
from pathlib import Path

def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()

def lesson(tmp_path: Path):
    e1 = tmp_path / "etapa1.typ"
    e1.write_text('#import "../../typst-template/nebli_v2_apostila.typ": *\n#intro-box[Introdução completa.]\n#parte-title("PARTE I — Fluxo", primeira: true)\n#subtopico("1.1 — Bomba")\nA água entra na câmara e o aumento da pressão abre a válvula de saída. Esse encadeamento produz fluxo unidirecional.\n#conclusao-box[A pressão organiza o fluxo.]\n', encoding='utf-8')
    (tmp_path/'main.typ').write_text('#import "../../typst-template/nebli_v2_apostila.typ": *\n#show: pagina-padrao\n#capa("Aula", "Teste", ())\n#sumario(())\n#etapa-header("Etapa 1")\n#include "etapa1.typ"\n#include "resumindo.typ"\n', encoding='utf-8')
    (tmp_path/'resumindo.typ').write_text('#import "../../typst-template/nebli_v2_apostila.typ": *\n#resumindo-page((("Síntese", [A pressão abre a válvula e produz fluxo unidirecional.]),))\n', encoding='utf-8')
    pdf = tmp_path/'Aula - E1.pdf'; pdf.write_bytes(b'%PDF-1.4\nE1 de varias paginas revisada\n')
    image = tmp_path/'fluxo.png'; image.write_bytes(b'\x89PNG\r\n\x1a\nGOLDEN_MEDIA')
    review = {"ambiguity":"A causa e o efeito delimitam uma resposta única.","anti_induction":"A resposta depende do mecanismo médico, não da gramática.","duplicate_check":"Nenhum outro card recupera esta mesma relação."}
    quality = {"portuguese_reviewed":True}
    def cue(role, ambiguity):
        return {"cloze_role":role,"knowledge_required":True,"blind_review_passed":True,"grammar_only_solvable":False,"lexical_leak":False,"answer_visible_elsewhere":False,"plausible_alternatives":[],"confounders_checked":[],"ambiguity_review":ambiguity}
    visual = {"labels_masked_not_structures":True,"question_preview":True,"answer_preview":True,"legible":True,"no_leak":True,"didactic_value":True}
    evidence = {"question_preview":"io-fluxo-pergunta.png","question_preview_sha256":"a"*64,"answer_preview":"io-fluxo-resposta.png","answer_preview_sha256":"b"*64,"crop_ratio":0.42,"text_scan":"ocr","forbidden_terms":["entrada","saída"],"leaked_terms":[]}
    cards = [
      {"card_key":"pressao-valvula","concept_id":"c1","tier":"nucleo","source":"authored","text":"O aumento da pressão abre a {{c1::válvula}} de saída.","extra":"A abertura permite que a água avance sem retornar.","e1_anchor":"o aumento da pressão abre a válvula de saída","retrieval_target":"Identificar a estrutura aberta pela pressão.","semantic_review":review,"authored_quality":quality,"cue_quality":cue("discriminador","Somente uma peça responde ao gradiente descrito."),"memory_gain":"Qual peça cede ao gradiente e libera a passagem.","ablation_loss":"Sem ele o aluno não reconstrói qual peça cede ao gradiente e confunde essa etapa com o fechamento na entrada.","why_not_e1_only":"É a decisão que precisa ser tomada sozinho, não um detalhe derivável.","confusion_target":"Impede trocar a peça que se abre pela que se fecha."},
      {"card_key":"io-fluxo","concept_id":"c2","tier":"nucleo","source":"io","mode":"hide_two_guess_two","prompt":"Identifique os dois rótulos ocultos no esquema de fluxo.","answers":["entrada","saída"],"masks":[{"x":.1,"y":.2,"w":.2,"h":.1},{"x":.65,"y":.2,"w":.2,"h":.1}],"pair_rationale":"Os dois pontos delimitam o mesmo trajeto hidráulico, então formam par funcional.","visual_evidence":evidence,"image_path":"fluxo.png","source_credit":"Esquema sintético público do teste Nebli.","cognitive_purpose":"Reconhecer visualmente a direção do fluxo.","visual_review":visual,"extra":"O par mostra a direção unidirecional.","e1_anchor":"Esse encadeamento produz fluxo unidirecional"},
      {"card_key":"fluxo-opcional","concept_id":"c3","tier":"optional","source":"authored","text":"O encadeamento descrito produz fluxo {{c1::unidirecional}}.","extra":"O fechamento impede o retorno do líquido.","e1_anchor":"Esse encadeamento produz fluxo unidirecional","retrieval_target":"Recuperar a direção resultante do fluxo.","semantic_review":review,"authored_quality":quality,"cue_quality":cue("consequencia","O sentido único é a única saída compatível com o fechamento."),"memory_gain":"O sentido único que resulta do fechamento valvular.","ablation_loss":"Sem ele perde-se a ligação entre o fechamento valvular e a impossibilidade de retorno do líquido.","why_not_e1_only":"Sustenta o raciocínio clínico sobre regurgitação, então merece revisão.","confusion_target":"Impede supor que o líquido possa voltar pela mesma via."}
    ]
    data={"metadata":{"uc":"UC99","prova":"P1","componente":"Fisiologia","nome_curto":"Aula sintética"},"release_gate":{"schema":"nebli-e1-deck-release-v1","e1_source":"etapa1.typ","e1_source_sha256":sha(e1),"e1_pdf":"Aula - E1.pdf","e1_pdf_sha256":sha(pdf),"card_budget_hard_max":4,"retention_kernel_review":{"slots_fixed_before_authorship":True,"compression_review_passed":True,"ablation_review_passed":True,"estimated_seconds_per_card_max":10,"summary":"O núcleo foi congelado, comprimido e testado por ablação."},"e1_review":{"slide_inventory_complete":True,"objectives_covered":True,"core_coverage_complete":True,"mechanisms_explicit":True,"visual_information_explained":True,"core_study_without_slides":True,"step1_depth_reviewed":True,"card_content_anchored":True,"independent_review_passed":True,"source_to_e1_matrix_complete":True,"beginner_zero_baseline_passed":True,"stepwise_explanation_passed":True,"didactic_flow_passed":True,"uc02_exemplars_applied":True,"rhetorical_questions_absent":True,"visual_asset_hygiene_passed":True,"rendered_pdf_visual_review_passed":True,"notes_review_status":"unavailable","unresolved_core_omissions":[],"unresolved_ambiguities":[],"unresolved_beginner_gaps":[],"visual_figure_ledger":[{"file":"fluxo.png","origin":"material sintético público","cognitive_task":"reconhecer direção","crop":"conteúdo útil","resolution":"legível","caption_match":"confirmada","rendered_page":"2","visual_approval":"aprovada"}],"summary":"Quatro passadas concluídas sem pendências."},"e1_format_review":{"canonical_template_used":True,"all_pages_rendered":True,"layout_reviewed":True,"paragraph_hierarchy_preserved":True,"images_legible_and_integrated":True,"no_clipping_or_overflow":True,"independent_visual_review_passed":True,"unresolved_visual_defects":[],"summary":"Todas as páginas foram renderizadas e revisadas."},"source_to_e1_matrix":[{"origin":"objetivo 1","decision":"ensinar","anchor":"aumento da pressão abre a válvula"},{"origin":"informação visual 1","decision":"visual","anchor":"fluxo unidirecional"}],"concepts":[{"concept_id":"c1","importance":"nuclear","retention_class":"must_recall","e1_anchor":"o aumento da pressão abre a válvula de saída","coverage_quality":3,"card_keys":["pressao-valvula"],"step1":{"decision":"not_applicable"}},{"concept_id":"c2","importance":"nuclear","retention_class":"must_recall","e1_anchor":"Esse encadeamento produz fluxo unidirecional","coverage_quality":3,"card_keys":["io-fluxo"],"step1":{"decision":"not_applicable"}},{"concept_id":"c3","importance":"optional","retention_class":"optional","e1_anchor":"Esse encadeamento produz fluxo unidirecional","coverage_quality":1,"card_keys":["fluxo-opcional"],"step1":{"decision":"not_applicable"}}]},"cards":cards}
    path=tmp_path/'deck-data.json'; path.write_text(json.dumps(data,ensure_ascii=False),encoding='utf-8'); return path,data
