RUN_ID = 'uc03-imuno31-20260930-codex'

SHORT = 'imuno31'

LESSON = '2026-uc03-imunologia-31-sistema-complemento'

DECK = 'NEBLI::UC03::P2::Imunologia::Sistema complemento'

CRITERIOS = 'MEMORY + FEEDBACKS até F-20260930-CLAUDE-15; continuação Codex 30/09. Só decks.'

AUTHOR = 'uc03'

MEDIA = {}

CARDS = [{'key': 'figado',
  'kind': 'text',
  'src': 1487640142103,
  'flags': {1: 4},
  'bloco': 'A-geral',
  'alvo': 'Complemento é sintetizado no fígado',
  'evid': 'Slide 3 (produção: fígado e outras células)',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Azul.'},
 {'key': 'inato-crp-complemento',
  'kind': 'text',
  'src': 1520299391760,
  'flags': {1: 4},
  'bloco': 'A-geral',
  'alvo': 'Complemento e PCR são imunidade inata',
  'evid': 'Slides 1–2 (reconhecimento inato)',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Azul.'},
 {'key': 'fragmentos-a-b',
  'kind': 'autoral',
  'flags': {1: 4, 2: 3},
  'bloco': 'A-geral',
  'text': 'Cleavage of C3 releases soluble {{c1::C3a}}, which promotes inflammation, and {{c2::C3b}}, which covalently '
          'tags nearby surfaces for opsonization.',
  'extra': 'C3b exposes a reactive thioester that can bind microbial surfaces. C4b also binds covalently, but this is '
           'not a property of every fragment named “b”. C2 naming varies between references; the lecture uses C4b2a, '
           'while this AnKing version uses C4b2b.',
  'alvo': 'Fragmento a solúvel × b que gruda',
  'evid': "Slides 6, 13–15 ('solúvel' × 'Gruda!')",
  'uso': 'Imunologia; provas UC03.',
  'motivo': 'c2 verde; c1 azul.',
  'busca': 'AnKing só tem convertases por nome; princípio a/b ausente; lacuna.'},
 {'key': 'classica-igg-igm',
  'kind': 'text',
  'src': 1487640144801,
  'flags': {1: 3, 2: 3},
  'bloco': 'B-vias',
  'alvo': 'Via clássica: IgG e IgM',
  'evid': 'Slides 7–10',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.'},
 {'key': 'classica-c1',
  'kind': 'text',
  'src': 1487640151914,
  'flags': {1: 3},
  'bloco': 'B-vias',
  'alvo': 'Via clássica começa em C1',
  'evid': 'Slides 9–12',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.'},
 {'key': 'c1q-igm-igg',
  'kind': 'autoral',
  'flags': {1: 4, 2: 3},
  'bloco': 'B-vias',
  'text': 'C1q must bind at least {{c1::two}} IgG Fc regions close together, but a single antigen-bound {{c2::IgM '
          'pentamer}} is enough, so IgM is the most efficient activator of the classical pathway',
  'extra': 'C1q binds the CH2 domain of IgG and the CH3 domain of IgM. Once C1q is anchored, C1r activates C1s, which '
           'cleaves C4 and C2.',
  'alvo': 'C1q exige 2 IgG ou 1 IgM',
  'evid': "Slides 8–10 (IgG CH2 × IgM CH3; '2 anticorpos IgG')",
  'uso': 'Imunologia; provas UC03.',
  'motivo': 'c2 verde; c1 azul.',
  'busca': 'AnKing: via clássica por IgG/IgM sem a diferença quantitativa; lacuna.'},
 {'key': 'c1r-c1s',
  'kind': 'autoral',
  'flags': {1: 4, 2: 4},
  'bloco': 'B-vias',
  'text': 'After C1q binds antibody, {{c1::C1r}} activates {{c2::C1s}}, which cleaves C4 and C2 to assemble the '
          'classical C3 convertase',
  'extra': 'C1 = C1q + 2 C1r + 2 C1s. C1-inhibitor (C1-INH) shuts this step off by binding C1r and C1s.',
  'alvo': 'C1r ativa C1s',
  'evid': 'Slides 10–13',
  'uso': 'Imunologia; provas UC03.',
  'motivo': 'Azul.',
  'busca': "AnKing só 'começa em C1'; lacuna."},
 {'key': 'alternativa-espontanea',
  'kind': 'text',
  'src': 1487640158306,
  'flags': {1: 3},
  'bloco': 'B-vias',
  'alvo': 'Via alternativa: espontânea ou produtos microbianos',
  'evid': 'Slides 21–22',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.'},
 {'key': 'alternativa-c3',
  'kind': 'text',
  'src': 1487640163185,
  'flags': {1: 4},
  'bloco': 'B-vias',
  'alvo': 'Via alternativa começa em C3',
  'evid': 'Slide 22',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Azul.'},
 {'key': 'tickover-b-d-properdina',
  'kind': 'autoral',
  'flags': {1: 3, 2: 4, 3: 4},
  'bloco': 'B-vias',
  'text': 'Alternative-pathway tickover begins with spontaneous {{c1::hydrolysis}} of C3; {{c2::factor D}} cleaves '
          'bound factor B, and {{c3::properdin}} stabilizes the surface convertase C3bBb.',
  'extra': 'First, C3(H2O) binds B and D cleaves B, making fluid-phase C3(H2O)Bb. This enzyme cleaves C3; deposited '
           'C3b then binds B, and D forms surface C3bBb. Properdin stabilizes this surface enzyme, amplifying C3 '
           'cleavage without antibody.',
  'alvo': 'Hidrólise do C3, fator B, fator D, properdina',
  'evid': 'Slides 22–23 (C3(H2O), fator B, fator D, properdina)',
  'uso': 'Imunologia; provas UC03.',
  'motivo': 'c1 verde; c2–c3 azul.',
  'busca': "AnKing: só 'espontânea' e 'começa em C3'; fatores B/D/properdina ausentes (busca 'factor B/D', 'properdin' "
           'vazia); lacuna.'},
 {'key': 'lectinas-manose',
  'kind': 'text',
  'src': 1487640169311,
  'flags': {1: 3, 2: 4},
  'bloco': 'B-vias',
  'alvo': 'Via das lectinas: manose',
  'evid': 'Slides 28–30',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'c1 verde; c2 azul.'},
 {'key': 'mbl-masp',
  'kind': 'autoral',
  'flags': {1: 4, 2: 4},
  'bloco': 'B-vias',
  'text': 'In the lectin pathway, mannose-binding lectin plays the role of {{c1::C1q}} and its MASPs play the role of '
          'C1r/C1s, cleaving {{c2::C4 and C2}} to build the same C3 convertase as the classical pathway',
  'extra': 'Only the trigger differs: MBL recognizes mannose and N-acetylglucosamine on microbial surfaces instead of '
           'antibody.',
  'alvo': 'MBL/MASP análogos de C1q/C1r/C1s',
  'evid': "Slides 28–30 ('MBP ~ C1q', MASP-1/2)",
  'uso': 'Imunologia; provas UC03.',
  'motivo': 'Azul.',
  'busca': "AnKing só manose e 'C1-like complex'; MASP ausente (busca vazia); lacuna."},
 {'key': 'vias-inicio-infeccao',
  'kind': 'autoral',
  'flags': {1: 3, 2: 4},
  'bloco': 'B-vias',
  'text': 'Early in a first infection, before specific antibodies exist, complement is activated mainly by the '
          '{{c1::alternative and lectin}} pathways; the classical pathway becomes important once {{c2::IgM and IgG}} '
          'are produced',
  'extra': 'Antibody-independent alternative and lectin activation can act immediately. Natural IgM and C-reactive '
           'protein may also activate the classical pathway early. As specific IgM/IgG accumulate, classical '
           'activation becomes more important; persistence of infection does not mean other pathways were never '
           'activated.',
  'alvo': 'Qual via atua no início da infecção',
  'evid': 'Slides 5, 7, 60; provas P2 2017 1.11 e P2 2018 3.6',
  'uso': 'Imunologia; provas UC03.',
  'motivo': 'c1 verde; c2 azul.',
  'busca': 'Raciocínio cobrado em prova sem card AnKing; lacuna.'},
 {'key': 'lps-complemento',
  'kind': 'text',
  'src': 1500572318680,
  'flags': {1: 3, 2: 3},
  'bloco': 'B-vias',
  'alvo': 'LPS ativa complemento → C3a e C5a',
  'evid': 'Slide 21 (LPS, ácido teicoico ativam via alternativa)',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.',
  'extra_tags': ['NEBLI::2026-uc03-imunologia-37-inflamacao-inicio-resolucao', 'NEBLI::compartilhado::imuno31']},
 {'key': 'c3-convertase',
  'kind': 'text',
  'src': 1487640180743,
  'flags': {1: 3},
  'bloco': 'C-convertases',
  'alvo': 'Todas as vias geram C3 convertase',
  'evid': 'Slides 14–20',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.'},
 {'key': 'c3conv-classica',
  'kind': 'text',
  'src': 1487640184312,
  'flags': {1: 4},
  'bloco': 'C-convertases',
  'alvo': 'C3 convertase clássica/lectinas = C4b2b',
  'evid': 'Slides 19–20',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Azul.',
  'extra_prefix': 'In the lecture this convertase is written C4b2a (older naming); it is the same enzyme.<br><br>'},
 {'key': 'c3conv-alternativa',
  'kind': 'text',
  'src': 1487640188409,
  'flags': {1: 3},
  'bloco': 'C-convertases',
  'alvo': 'C3 convertase alternativa = C3bBb',
  'evid': 'Slide 23',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.'},
 {'key': 'c5-convertase',
  'kind': 'text',
  'src': 1487640191924,
  'flags': {1: 3},
  'bloco': 'C-convertases',
  'alvo': 'Todas as vias geram C5 convertase',
  'evid': 'Slides 24–25',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.'},
 {'key': 'c5conv-classica',
  'kind': 'text',
  'src': 1487640197206,
  'flags': {1: 4},
  'bloco': 'C-convertases',
  'alvo': 'C5 convertase clássica = C4b2b3b',
  'evid': 'Slide 24',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Azul.',
  'extra_prefix': 'In the lecture this convertase is written C4b2a3b (older naming); it is the same enzyme.<br><br>'},
 {'key': 'c5conv-alternativa',
  'kind': 'text',
  'src': 1487640200798,
  'flags': {1: 4},
  'bloco': 'C-convertases',
  'alvo': 'C5 convertase alternativa = C3bBb3b',
  'evid': 'Slide 24',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Azul.'},
 {'key': 'mac',
  'kind': 'text',
  'src': 1487640204292,
  'flags': {1: 3},
  'bloco': 'D-mac',
  'alvo': 'C5b + C6–C9 = MAC',
  'evid': 'Slides 24–27',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.'},
 {'key': 'mac-proteinas',
  'kind': 'text',
  'src': 1487640207727,
  'flags': {1: 4},
  'bloco': 'D-mac',
  'alvo': 'MAC = C5b–C9',
  'evid': 'Slides 25–27',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Azul (recuperação inversa).'},
 {'key': 'imunocomplexos-c3b',
  'kind': 'text',
  'src': 1487640222923,
  'flags': {1: 3},
  'bloco': 'E-funcoes',
  'alvo': 'C3b remove imunocomplexos',
  'evid': 'Slides 33, 45 (remoção via CR1)',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.'},
 {'key': 'anafilatoxinas',
  'kind': 'text',
  'src': 1487640139590,
  'flags': {1: 3},
  'bloco': 'E-funcoes',
  'alvo': 'C3a, C4a, C5a ativam mastócitos',
  'evid': 'Slides 38–42',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.',
  'extra_tags': ['NEBLI::2026-uc03-imunologia-37-inflamacao-inicio-resolucao', 'NEBLI::compartilhado::imuno31']},
 {'key': 'receptores-cr1-cr3',
  'kind': 'autoral',
  'flags': {1: 4, 2: 4},
  'bloco': 'E-funcoes',
  'text': '{{c1::CR1 (CD35)}} binds C3b/C4b and helps clear immune complexes; {{c2::CR3 (CD11b/CD18)}} binds iC3b and '
          'promotes phagocytosis.',
  'extra': 'Erythrocyte CR1 carries immune complexes to liver and spleen for removal by phagocytes; red cells do not '
           'phagocytose. CR1 also assists factor I. CR4 (CD11c/CD18) recognizes iC3b; C5aR mediates leukocyte '
           'recruitment/activation.',
  'alvo': 'CR1 × CR3',
  'evid': 'Slides 36, 44 (tabela de receptores)',
  'uso': 'Imunologia; provas UC03.',
  'motivo': 'Azul.',
  'busca': "AnKing só CD21–C3d; CR1/CR3 ausentes (busca 'CR1', 'CD35' sem card de complemento); lacuna."},
 {'key': 'cr2-c3d',
  'kind': 'text',
  'src': 1503855271322,
  'flags': {1: 4},
  'bloco': 'E-funcoes',
  'alvo': 'CD21 (CR2) é receptor de C3d',
  'evid': 'Slide 43 (correceptor do linfócito B)',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Azul.',
  'extra_prefix': 'On B cells, CR2 forms a co-receptor with CD19/CD81: an antigen coated with C3d engages BCR and CR2 '
                  'together, lowering the activation threshold (complement as "co-stimulus" of B cells).<br><br>'},
 {'key': 'fator-i-h',
  'kind': 'autoral',
  'flags': {1: 3, 2: 4},
  'bloco': 'F-regulacao',
  'text': '{{c1::Factor I}} proteolytically inactivates C3b, using cofactors such as {{c2::factor H}} or CR1.',
  'extra': 'Factor H accelerates decay of C3bBb and serves as a cofactor for factor I. iC3b cannot form convertases, '
           'but remains an opsonin for CR3/CR4. Factor I also cleaves C4b, with appropriate cofactors such as C4BP, '
           'MCP or CR1; factor H regulates the alternative pathway.',
  'alvo': 'Fator I cliva C3b com cofator H',
  'evid': 'Slides 50–52 (fatores I e H)',
  'uso': 'Imunologia; provas UC03.',
  'motivo': 'c1 verde; c2 azul.',
  'busca': "AnKing: busca 'factor H' só traz proteína M; fator I ausente; lacuna."},
 {'key': 'acido-sialico',
  'kind': 'autoral',
  'flags': {1: 4},
  'bloco': 'F-regulacao',
  'text': 'Host-cell {{c1::sialic acid}} favors factor H binding, helping limit alternative-pathway amplification on '
          'the host surface.',
  'extra': 'Factor H promotes C3b inactivation and convertase decay. DAF/CD55 also accelerates convertase decay; '
           'MCP/CD46 supports factor I. CD59 acts later by preventing MAC assembly, not by inactivating C3b. Some '
           'microbes recruit factor H to evade complement.',
  'alvo': 'Proteção das células do hospedeiro',
  'evid': 'Slides 47–53; prova P2 2018 3.6 (ácido siálico/fator H)',
  'uso': 'Imunologia; provas UC03.',
  'motivo': 'Azul.',
  'busca': "Sem card AnKing (busca 'sialic acid' só vírus/gangliosídeos); lacuna."},
 {'key': 'proteina-m-fator-h',
  'kind': 'text',
  'src': 1500570825309,
  'flags': {1: 4, 2: 4},
  'bloco': 'F-regulacao',
  'alvo': 'Proteína M sequestra fator H',
  'evid': 'Prova P2 2018 3.6 (evasão por fator H)',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Azul: ponte com Patogenicidade.'},
 {'key': 'daf',
  'kind': 'text',
  'src': 1478986720423,
  'flags': {1: 3, 2: 4},
  'bloco': 'F-regulacao',
  'alvo': 'DAF/CD55 inibe C3 convertase',
  'evid': 'Slides 47–49',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'c1 verde; c2 azul.'},
 {'key': 'gpi-ancora',
  'kind': 'text',
  'src': 1478994988572,
  'flags': {1: 4},
  'bloco': 'F-regulacao',
  'alvo': 'DAF e CD59 ancorados por GPI',
  'evid': 'Slides 49, 53',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Azul.'},
 {'key': 'gpi-ausente',
  'kind': 'text',
  'src': 1478994993913,
  'flags': {1: 3},
  'bloco': 'F-regulacao',
  'alvo': 'Sem GPI → lise por complemento',
  'evid': 'Slides 53, 55 (CD59 → HPN)',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.'},
 {'key': 'hpn-defeito',
  'kind': 'text',
  'src': 1478995000657,
  'flags': {1: 4, 2: 3, 3: 4},
  'bloco': 'F-regulacao',
  'alvo': 'HPN: defeito adquirido de GPI',
  'evid': 'Slide 55 (CD59 → hemoglobinúria paroxística noturna)',
  'uso': 'Clínica direta (Q044).',
  'motivo': 'c2 verde; c1, c3 azul.'},
 {'key': 'hpn-intravascular',
  'kind': 'text',
  'src': 1478995010616,
  'flags': {1: 4},
  'bloco': 'F-regulacao',
  'alvo': 'HPN: hemólise intravascular',
  'evid': 'Slide 55',
  'uso': 'Clínica direta (Q044).',
  'motivo': 'Azul: consequência direta do MAC.'},
 {'key': 'c1inh-angioedema',
  'kind': 'text',
  'src': 1487727789545,
  'flags': {1: 3, 2: 3},
  'bloco': 'F-regulacao',
  'alvo': 'Deficiência de C1-INH → angioedema hereditário',
  'evid': 'Slides 47, 55, 57',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.',
  'extra': 'C1-INH inhibits C1r/C1s and the contact/kinin system. Deficiency permits excessive kallikrein activity and '
           'bradykinin formation, causing vascular leakage and angioedema. The edema is not driven by histamine.'},
 {'key': 'c1inh-c4',
  'kind': 'text',
  'src': 1487727803414,
  'flags': {1: 3},
  'bloco': 'F-regulacao',
  'alvo': 'C4 baixo na deficiência de C1-INH',
  'evid': 'Slide 57; provas (interpretação de C3/C4)',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.'},
 {'key': 'c1inh-bradicinina',
  'kind': 'text',
  'src': 1517068230955,
  'flags': {1: 3},
  'bloco': 'F-regulacao',
  'alvo': 'C1-INH deficiente → ↑ bradicinina',
  'evid': 'Slide 47 (C1-INH regula calicreína); ponte com Inflamação',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.'},
 {'key': 'aeh-ieca',
  'kind': 'text',
  'src': 1474686417807,
  'flags': {1: 4, 2: 4, 3: 3},
  'bloco': 'F-regulacao',
  'alvo': 'IECA contraindicado no angioedema hereditário',
  'evid': 'Slide 57 (AEH)',
  'uso': 'Clínica direta (Q044).',
  'motivo': 'c3 verde (HY: IECA eleva bradicinina); c1–c2 azul.'},
 {'key': 'aeh-sem-urticaria',
  'kind': 'text',
  'src': 1517365171251,
  'flags': {1: 4},
  'bloco': 'F-regulacao',
  'alvo': 'AEH sem urticária (bradicinina, não histamina)',
  'evid': 'Slide 57',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Azul: contraste com histamina.',
  'extra': 'Bradykinin increases vascular permeability without the mast-cell histamine response responsible for '
           'typical itchy wheals. This contrasts with histaminergic angioedema.'},
 {'key': 'terminal-neisseria',
  'kind': 'text',
  'src': 1501968263352,
  'flags': {1: 3},
  'bloco': 'G-deficiencias',
  'alvo': 'C5–C9 sem MAC → Neisseria',
  'evid': 'Slides 55, 59',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde (1-HighYield).'},
 {'key': 'terminal-quais',
  'kind': 'text',
  'src': 1487727812574,
  'flags': {1: 4},
  'bloco': 'G-deficiencias',
  'alvo': 'Quais deficiências → Neisseria',
  'evid': 'Slide 59',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Azul (recuperação inversa).'},
 {'key': 'precoces-sinopulmonares',
  'kind': 'text',
  'src': 1487727814679,
  'flags': {1: 3},
  'bloco': 'G-deficiencias',
  'alvo': 'C1–C4: infecções piogênicas sinopulmonares',
  'evid': 'Slides 55–56',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.',
  'extra': 'Complement deficiency impairs bacterial defense; severe recurrent pyogenic infection is especially '
           'characteristic of C3 deficiency. C1q/C2/C4 deficiencies are also strongly associated with defective '
           'immune-complex clearance and autoimmunity.'},
 {'key': 'precoces-les',
  'kind': 'text',
  'src': 1487727820979,
  'flags': {1: 3},
  'bloco': 'G-deficiencias',
  'alvo': 'C1–C4 → LES/glomerulonefrite',
  'evid': 'Slides 55–56; prova P3 2024 3.1',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Verde.',
  'extra_prefix': 'Why: C1q, C4 and C2 help clear immune complexes and apoptotic debris; when they are missing, '
                  'nuclear antigens persist and drive autoimmunity (lupus).<br><br>',
  'text': 'Deficiency of early classical complement components (especially {{c1::C1q, C2 or C4}}) increases the risk '
          'of lupus and immune-complex disease.'},
 {'key': 'deficiencia-c3',
  'kind': 'autoral',
  'flags': {1: 3},
  'bloco': 'G-deficiencias',
  'text': 'Because all three pathways converge on C3, C3 deficiency causes the most severe recurrent {{c1::pyogenic '
          '(encapsulated) bacterial}} infections',
  'extra': 'Without C3 there is no C3b opsonization, no C5 convertase (so no C5a chemotaxis and no MAC), and poor '
           'immune-complex clearance.',
  'alvo': 'Deficiência de C3',
  'evid': 'Slides 55–56; provas P1 2015 2.2–2.3, P2 2025 6.2',
  'uso': 'Imunologia; provas UC03.',
  'motivo': 'Verde.',
  'busca': "AnKing só 'C1–C4 precoces'; C3 isolado ausente; lacuna."},
 {'key': 'fator-h-deficiencia',
  'kind': 'autoral',
  'flags': {1: 3, 2: 3},
  'bloco': 'G-deficiencias',
  'text': 'Severe factor H or factor I deficiency can cause uncontrolled alternative-pathway consumption: serum C3 is '
          '{{c1::low}}, while C4 may remain {{c2::normal}}.',
  'extra': 'Failure to control C3 convertase consumes C3 and weakens opsonization. Some complement-regulatory defects '
           'also injure renal microvascular endothelium, producing atypical hemolytic uremic syndrome; normal C3 does '
           'not exclude that disorder.',
  'alvo': 'Fator H/I: C3 baixo com C4 normal',
  'evid': 'Slide 55 (fH, fI, SHU); provas P2 2025 6.1, P1 2015 2.4',
  'uso': 'Imunologia; provas UC03.',
  'motivo': 'Verde.',
  'busca': 'Sem card AnKing de fator H/I; lacuna.'},
 {'key': 'padrao-c3-c4',
  'kind': 'autoral',
  'flags': {1: 3, 2: 3},
  'bloco': 'G-deficiencias',
  'text': 'In immune-complex disease, low C3 plus low C4 suggests {{c1::classical}} pathway consumption; low C3 with '
          'preserved C4 suggests {{c2::alternative}} pathway consumption.',
  'extra': 'C4 is used by classical and lectin pathways, but not by the alternative pathway. These patterns guide '
           'investigation; they do not establish an individual protein deficiency by themselves.',
  'alvo': 'Interpretar C3 e C4',
  'evid': 'Provas P2 2025 6.1–6.2',
  'uso': 'Imunologia; provas UC03.',
  'motivo': 'Verde.',
  'busca': 'Interpretação cobrada em prova, sem card AnKing; lacuna.'},
 {'key': 'ch50-ah50',
  'kind': 'autoral',
  'flags': {1: 3, 2: 3, 3: 4},
  'bloco': 'G-deficiencias',
  'text': '{{c1::CH50}} screens classical-pathway hemolytic function and {{c2::AH50}} screens alternative-pathway '
          'function; normal CH50 with absent AH50 suggests a defect in {{c3::factor B, factor D or properdin}}.',
  'extra': 'Both assays also require intact C3 and terminal components. Absent CH50 with preserved AH50 suggests C1, '
           'C2 or C4 deficiency. Low/absent results in both suggest a shared-component defect or complement '
           'consumption. Abnormal samples require confirmation.',
  'alvo': 'CH50 × AH50',
  'evid': 'Prova P2 2025 1.7',
  'uso': 'Imunologia; provas UC03.',
  'motivo': 'c1–c2 verde; c3 azul.',
  'busca': "AnKing só 'LES com CH50 baixo'; lacuna."},
 {'key': 'les-ch50',
  'kind': 'text',
  'src': 1487815366607,
  'flags': {1: 4},
  'bloco': 'G-deficiencias',
  'alvo': 'LES: CH50 diminuído (consumo)',
  'evid': 'Slides 55–56; prova P2 2025 1.7 (CH50)',
  'uso': 'Imunologia; Step 1.',
  'motivo': 'Azul.',
  'text': 'Active immune-complex disease in SLE may cause {{c1::decreased}} CH50 through complement consumption.',
  'extra': 'CH50 reflects functional classical-to-terminal pathway activity, not simply the concentration of one '
           'component. SLE does not invariably produce a low CH50.'},
 {'key': 'cd59-c9',
  'kind': 'autoral',
  'flags': {1: 3},
  'bloco': 'F-regulacao',
  'text': '{{c1::CD59}} protects host membranes by preventing C9 polymerization and completion of the membrane attack '
          'complex.',
  'extra': 'CD55/DAF acts earlier, accelerating convertase decay. CD59 blocks the final pore. Loss of GPI-linked '
           'CD55/CD59 explains complement-mediated hemolysis in PNH.',
  'alvo': '{{c1::CD59}} protects host membranes by preventing C9 polymerization and completion of the membrane attack '
          'complex.',
  'evid': 'Slide CD59 e regulação; Abbas cap. 13, figura 13-16',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'cr2-costimulo',
  'kind': 'autoral',
  'flags': {1: 3},
  'bloco': 'E-funcoes',
  'text': 'When an antigen binds the B-cell receptor and its attached C3d engages CR2, the threshold for B-cell '
          'activation {{c1::decreases}}.',
  'extra': 'CR2/CD21 works with CD19 and CD81 as a B-cell co-receptor. Complement therefore supports antibody '
           'responses as well as directly opsonizing and lysing microbes.',
  'alvo': 'When an antigen binds the B-cell receptor and its attached C3d engages CR2, the threshold for B-cell '
          'activation {{c1::decreases}}.',
  'evid': 'Slide co-estímulo de linfócito B; Abbas cap. 13',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'mbl-deficiencia',
  'kind': 'autoral',
  'flags': {1: 4},
  'bloco': 'G-deficiencias',
  'text': 'Mannose-binding lectin deficiency impairs the {{c1::lectin}} complement pathway and can increase '
          'susceptibility to infection.',
  'extra': 'The effect is variable because classical and alternative pathways remain available. MBL deficiency does '
           'not imply that all complement activation is absent.',
  'alvo': 'Mannose-binding lectin deficiency impairs the {{c1::lectin}} complement pathway and can increase '
          'susceptibility to infection.',
  'evid': 'Slide deficiências da via das lectinas; Abbas cap. 13',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'}]

COMPARTILHADOS = {1790253143896: 'Inflamação aguda · quimiotáticos de neutrófilo, incluindo C5a — slides 38–42',
 1790253143998: 'Inflamação aguda · C3b e IgG são as opsoninas — slides 33–36'}

EXCLUIDOS = [(1487815316366, 'Deficiência precoce e LES — equivalente ao 1487727820979, sem ganho (Q025)'),
 (1478995034893, 'HPN: citometria CD55/CD59 — diagnóstico clínico lateral'),
 (1478995016809, 'HPN: acidose do sono — fisiopatologia clínica além do slide'),
 (1478995007169, 'HPN: anemia normocítica — clínica lateral'),
 (1478995013918, 'HPN: episódios noturnos — clínica lateral'),
 (1478995020091, 'HPN: teste da sacarose — diagnóstico lateral'),
 (1478995028457, 'HPN: NO scavenger — clínica lateral'),
 (1478995038587, 'HPN: mnemônico clínico — fora do recorte'),
 (1478995038588, 'HPN: mnemônico — idem'),
 (1478995055944, 'HPN: trombose venosa — clínica lateral'),
 (1478995063743, 'HPN: anemia ferropriva — clínica lateral'),
 (1478995072125, 'HPN: LMA — fora do recorte'),
 (1478995078338, 'Eculizumabe — terapêutica fora do recorte'),
 (1497203766572, 'Eculizumabe — idem'),
 (1497203670771, 'Eculizumabe anti-C5 — idem'),
 (1578248124988, 'AEH: sintomas GI — clínica lateral'),
 (1517365303958, 'AEH: morte por edema de via aérea — clínica lateral'),
 (1578248499297, 'AEH: herança AD — fora do recorte'),
 (1503855029259, 'EBV–CD21 — Microbiologia/virologia, outra aula'),
 (1478916025067, 'Asplenia e encapsulados — outra aula'),
 (1487640175721, 'Substituído pelo alvo preciso MBL/MASP; C1-like é rótulo vago.'),
 (1578248007976,
  'Formulação não confiável para AEH: edema por bradicinina, não por aumento generalizado de anafilatoxinas.'),
 (1563496864933, 'Repete C4 baixo e C1-INH já recuperados; subtipos clínicos laterais.')]

FORA_DO_RECORTE = ['Clínica e tratamento de HPN (trombose, LMA, sacarose, eculizumabe) e do angioedema hereditário além do elo '
 'C1-INH/bradicinina/C4',
 'Glomerulonefrites (GNPE, MPGN/fator nefrítico C3), hipersensibilidade II/III: aulas futuras',
 'Sinalização intracelular do correceptor B (Btk, Vav, PI3K) e estrutura atômica do CD59: ilustração',
 'Venenos e polímeros como ativadores da via alternativa, COVID-19, degeneração macular: exemplos do slide']
