#import "../typst-template/nebli_v2_apostila.typ": *

#discursiva("Q1",
  [Explique o modelo semiconservativo de replicação do DNA. Por que cada dupla-hélice filha herda exatamente uma fita parental e uma fita nova, e como o experimento de Meselson e Stahl demonstrou isso?],
  [Na replicação semiconservativa, as duas fitas da hélice parental são separadas e cada uma serve de molde para a síntese de uma fita complementar nova. O resultado são duas duplas-hélices filhas, cada uma com uma fita parental intacta e uma fita recém-sintetizada. Meselson e Stahl confirmaram isso marcando o DNA de _E. coli_ com ¹⁵N (pesado), transferindo para meio com ¹⁴N e centrifugando em gradiente de CsCl. Após uma geração, toda a população formou uma única banda de densidade intermediária — exatamente o esperado se cada hélice filha carregasse uma fita pesada e uma leve. O modelo conservativo preveria duas bandas separadas; o dispersivo, bandas difusas. Apenas o semiconservativo é compatível com a banda única intermediária observada.])

#discursiva("Q2",
  [Por que as DNA-polimerases não conseguem iniciar a síntese de DNA sem um primer? Explique o papel bioquímico do primer e quem o sintetiza e remove durante a replicação bacteriana.],
  [DNA-polimerases só adicionam nucleotídeos a uma extremidade 3′-OH livre preexistente — elas estendem, não iniciam. Por isso a célula precisa da primase, uma RNA-polimerase que, ao contrário das DNA-polimerases, consegue iniciar do zero. A primase sintetiza um primer curto de RNA (~10 nt) com extremidade 3′-OH livre, que serve de ponto de partida para a Pol III estender o DNA. Após a replicação, a Pol I remove cada primer usando sua exonuclease 5′→3′ (nick translation) e preenche a lacuna com DNA. A DNA ligase sela o nick final usando NAD⁺ como cofator. Sem primase, nenhuma polimerase poderia iniciar a síntese e a replicação seria impossível.])

#discursiva("Q3",
  [Diferencie o papel da helicase do papel da DNA girase (topoisomerase II bacteriana) na replicação. Por que ambas são necessárias, e qual é o alvo clínico das fluoroquinolonas?],
  [A helicase (DnaB) hidrolisa ATP para translocar ao longo de uma fita e quebrar as pontes de hidrogênio entre as bases, separando ativamente as duas fitas no avanço da forquilha. À medida que ela avança, porém, o DNA à frente acumula superenrolamento positivo — torção que, não aliviada, travaria a progressão. É aí que entra a DNA girase: ela cliva transitoriamente a dupla-fita, passa um segmento pelo corte e religa, absorvendo o superenrolamento gerado. Helicase abre; girase alivia a torção à frente. As fluoroquinolonas (ciprofloxacino, levofloxacino) aprisionam a girase no estado com a fita cortada, acumulando quebras de dupla-fita letais para a bactéria. A girase humana tem estrutura diferente, conferindo seletividade ao antibiótico.])

#discursiva("Q4",
  [A síntese da fita retardada produz fragmentos de Okazaki. Descreva a sequência de eventos que converte esses fragmentos numa fita contínua, identificando cada enzima envolvida e sua atividade específica.],
  [Cada fragmento de Okazaki começa com a primase sintetizando um primer de RNA. A Pol III se liga ao primer e estende em direção 5′→3′ até encontrar o primer do fragmento anterior. Nesse ponto, a Pol III para e cede lugar à Pol I, que usa sua exonuclease 5′→3′ para degradar o primer de RNA enquanto simultaneamente sintetiza DNA no lugar — processo chamado nick translation. Quando o primer é completamente removido e a lacuna preenchida, resta apenas um nick (quebra no esqueleto fosfodiéster). A DNA ligase sela esse nick usando NAD⁺ como doador de adenilato em bactérias (ou ATP em eucariotos), formando a ligação fosfodiéster que une os dois fragmentos numa fita contínua.])

#discursiva("Q5",
  [A telomerase é descrita como uma transcriptase reversa com RNA-molde interno. Explique como ela resolve o problema do encurtamento telomérico, por que células somáticas normais a reprimem, e qual a consequência de sua reativação em tumores.],
  [Cromossomos lineares encurtam a cada divisão porque a maquinaria replicativa não consegue copiar o extremo 5′ da fita retardada — o primer mais distal é removido sem que a polimerase possa preencher o gap (problema da replicação terminal). A telomerase resolve isso carregando consigo uma subunidade de RNA (hTR) com sequência complementar à repetição telomérica (TTAGGG). Ela usa essa sequência como molde e sintetiza novas repetições na extremidade 3′ do telômero, estendendo-o. Depois, a maquinaria de replicação convencional copia essa extensão. Células somáticas normais reprimem a telomerase para limitar o número de divisões (barreira antitumoral); o encurtamento progressivo leva à senescência — o chamado limite de Hayflick. Em 85–90% dos tumores, a telomerase é reativada, os telômeros são mantidos, e as células adquirem imortalidade replicativa, característica fundamental da malignidade.])
