#import "../../typst-template/nebli_v2_apostila.typ": *

#discursiva("Q1",
  [Diferencie acidose respiratória, acidose metabólica, alcalose respiratória e alcalose metabólica. Aplicando esses conceitos, classifique cada uma das três gasometrias de Catarina (dia 16-02 UPA, dia 18-02 UPA, dia 18-02 UTI) e explique o que mudou entre elas em termos do sistema bicarbonato.],
  [*Acidose respiratória*: pH↓ por pCO\u{2082}↑ (hipoventilação). *Alcalose respiratória*: pH↑ por pCO\u{2082}↓ (hiperventilação). *Acidose metabólica*: pH↓ por HCO\u{2083}\u{207B}↓ (perda de base ou ganho de ácido). *Alcalose metabólica*: pH↑ por HCO\u{2083}\u{207B}↑. Gasometria 1 (pH 7,50, pCO\u{2082} 26, HCO\u{2083}\u{207B} 21): alcalose respiratória aguda por hiperventilação (dor, febre, receptores J). Gasometria 2 (pH 7,35, pCO\u{2082} 40, HCO\u{2083}\u{207B} 20): pseudo-equilíbrio — paciente perdeu compensação respiratória (pCO\u{2082} subiu) e começou a consumir HCO\u{2083}\u{207B}. Gasometria 3 (pH 7,14, pCO\u{2082} 62, HCO\u{2083}\u{207B} 15): acidose mista — componente respiratório (retenção de CO\u{2082} por shunt + fadiga) + metabólico (lactato consumindo HCO\u{2083}\u{207B}).])

#discursiva("Q2",
  [Integre as Leis de Fick e La Place com a função do surfactante para explicar a evolução fisiopatológica do pulmão da Catarina entre os dias 16 e 18 de fevereiro. Relacione com os achados histológicos descritos no caso (figura 3B).],
  [O exsudato fibrino-purulento que preencheu os alvéolos (figura 3B) afeta três variáveis de Fick simultaneamente: A↓ (alvéolo cheio sai do recrutamento), T↑ (líquido proteináceo adiciona dezenas de µm à barreira) e ΔP local↓ (PAO\u{2082} cai dentro do alvéolo consolidado). A inflamação também destrói pneumócitos II e degrada surfactante; com T (tensão superficial) elevada e r pequeno, P = 2T/r dispara nos alvéolos vizinhos, que colabam. Alvéolos colabados perfundidos viram shunt. Resultado: V_gás para O\u{2082} despenca, gerando a hipoxemia progressiva (Sat 95→88→82%) e o componente respiratório da acidose final.])

#discursiva("Q3",
  [Descreva os principais mecanismos de defesa pulmonar (clearance mucociliar, células e fatores anatômicos) e justifique por que esses mecanismos estavam comprometidos em Catarina, explicando como isso contribuiu para a infecção pneumocócica e sua evolução grave.],
  [A defesa pulmonar tem camadas: filtro nasal, reflexo da tosse, clearance mucociliar (muco em duas camadas + cílios batendo 12–15 Hz, empurrando partículas para a faringe), macrófago alveolar (fagocitose no alvéolo) e imunidade adaptativa. Em Catarina, tabagismo de 10 a/m (cessado há 5 anos) deixa metaplasia escamosa persistente e clearance ciliar reduzido — o pneumococo inalado não é mais empurrado para fora. A diabetes (mesmo "controlada com dieta") gera AGEs que reduzem fagocitose neutrofílica e microangiopatia que reduz perfusão local. As duas defesas falharam: bactéria que num pulmão saudável seria contida na via aérea chegou ao alvéolo, replicou-se sem oposição inicial e gerou consolidação extensa em 48h.])

#discursiva("Q4",
  [Considerando a hipoxemia grave da gasometria 3 (pO\u{2082} 55, Sat 82%, pH 7,14), explique o déficit de ATP intracelular e suas consequências moleculares e clínicas, em particular a confusão mental que a paciente apresenta na UTI.],
  [Sem O\u{2082} suficiente, a cadeia respiratória mitocondrial para e a célula vira para glicólise anaeróbica — rendimento de 2 ATP por glicose (contra 32–36 da via aeróbica), déficit energético severo. A bomba Na\u{207A}/K\u{207A}-ATPase, que mantém o gradiente iônico, falha por falta de ATP; Na\u{207A} entra na célula, água segue por osmose, célula incha (edema citotóxico). No cérebro, isso vira encefalopatia hipóxica — manifestada como confusão mental e sonolência. Adicionalmente, pH \< 7,2 satura resíduos de histidina das proteínas, dessensibiliza receptores β-adrenérgicos (risco de choque refratário) e move K\u{207A} para fora da célula (hipercalemia com risco de arritmia).])

#discursiva("Q5",
  [Avalie a conduta do médico que atendeu Catarina no dia 16-02 sob a perspectiva da Medicina Centrada no Paciente (MCP), da estratificação de complexidade assistencial e da ética profissional. A atitude do médico feriu a autonomia da paciente? A solicitação de atestado pela filha é legítima? A ouvidoria é instância apropriada?],
  [A conduta apresenta múltiplas falhas. *Estratificação*: paciente com semiologia positiva para consolidação (macicez, crepitantes, pectorilóquia), febre, tabagismo prévio e diabetes já configurava necessidade de atenção 2ária com avaliação hospitalar próxima — não 1ária com retorno em 1 semana. *MCP*: o médico não explorou a queixa subjetiva ("não estou bem para ir para casa", que era dado clínico), não considerou o contexto social, não compartilhou a decisão e não orientou sinais de alarme — feriu a autonomia. *Atestado*: qualquer médico pode atestar incapacidade temporária para o trabalho; a recusa do plantonista é tecnicamente incorreta. *Ouvidoria*: é mecanismo legítimo do SUS (Lei 8.142/1990) para garantia de direito do usuário; a queixa da filha é apropriada e pode levar à investigação ética pelo CEM. A falha do médico foi clínica antes de ser ética.])
