#import "../typst-template/nebli_v2_apostila.typ": *

#intro-box[
A peça de mastectomia que chega ao laboratório de anatomia patológica não é um pedaço de tecido isolado — é o ponto final de uma cadeia clínica que começou na mamografia de rastreio, passou pela biópsia core, ditou a indicação de quimioterapia neoadjuvante e agora precisa ser lida pelo patologista como mapa do que sobrou da doença. Este resumo segue exatamente essa cadeia: o que o cirurgião manda, como o macroscopista pinta margens e corta, o que a microscopia revela que a macroscopia esconde, qual o papel da #sigla("IHQ", [imuno-histoquímica]) na escolha terapêutica, e como o índice de carga residual (#sigla("RCB", [residual cancer burden — índice de carga tumoral residual])) traduz o efeito da neoadjuvância em prognóstico. A espinha pedagógica é #sigla("CDI", [carcinoma ductal invasivo]) — o padrão histológico mais frequente — mas o método se aplica a qualquer carcinoma mamário invasor.
]

#parte-title("PARTE I — Da cirurgia ao patologista", primeira: true)

#subtopico("1.1 — Procedimentos cirúrgicos da mama")

A escolha do procedimento cirúrgico nasce do cruzamento entre tamanho tumoral, relação volume-tumor/volume-mama, status linfonodal axilar e perfil molecular do tumor. Em vez de tratar "mama operada" como categoria única, é mais útil ler a peça que chega ao laboratório como assinatura cirúrgica de uma decisão clínica anterior: peça pequena com margem de tecido normal indica cirurgia conservadora; peça que contém toda a mama, complexo aréolo-papilar e pele indica mastectomia radical modificada; peça volumosa e fibrosada com tumor pequeno ou ausente costuma indicar mastectomia pós-neoadjuvância. Reconhecer essa assinatura no momento do exame macroscópico orienta o tipo de descrição, o protocolo de amostragem e a interpretação do que será visto no microscópio.

A cirurgia conservadora — também chamada de tumorectomia, segmentectomia ou quadrantectomia conforme o volume ressecado — remove o tumor com uma margem de tecido mamário macroscopicamente normal ao redor. Indica-se quando o tumor é único, suficientemente pequeno em relação ao volume da mama e quando a paciente aceita radioterapia adjuvante, etapa obrigatória para reduzir recidiva local. A peça chega ao laboratório orientada por fios cirúrgicos: por convenção, fio curto marca a margem cranial, fio longo a margem lateral e fio médio a margem medial. Sem essa orientação, qualquer margem comprometida vira margem "alguma" — perde-se a possibilidade de reabordagem cirúrgica direcionada.

A mastectomia simples retira toda a glândula mamária mais o complexo aréolo-papilar e parte da pele; preserva os músculos peitorais e não inclui esvaziamento axilar. A mastectomia radical modificada acrescenta o esvaziamento dos linfonodos axilares dos níveis I e II — é a operação clássica para carcinomas invasores localmente avançados. Já a mastectomia radical à Halsted, que ressecava também os peitorais maior e menor, foi praticamente abandonada porque os ensaios mostraram que retirar músculo não muda sobrevida e aumenta morbidade. Existem ainda variantes "poupadoras": mastectomia poupadora de pele (skin-sparing) e poupadora do complexo aréolo-papilar (nipple-sparing), usadas quando há reconstrução imediata e o tumor não envolve a pele nem o mamilo. #termo-nota[skin-sparing][técnica em que pele e envelope mamário são preservados para reconstrução imediata; tecido glandular é integralmente removido por dentro]

A linfonodectomia obedece a outra lógica. Antes, todo carcinoma invasor levava a esvaziamento axilar completo — operação morbosa, associada a linfedema crônico do membro superior. A pesquisa do linfonodo sentinela inverteu essa rotina: injeta-se contraste (azul patente, radiofármaco) na região peri-areolar e identifica-se cirurgicamente o primeiro linfonodo de drenagem; se ele é negativo para metástase, o esvaziamento é evitado. O sentinela é o sentinela porque é estatisticamente o mais provável de receber primeiro a célula tumoral que escapou — drenagem linfática da mama segue gradientes anatômicos previsíveis em direção à axila ipsilateral.

A peça da paciente do relatório é compatível com mastectomia radical modificada: chega ao laboratório com glândula mamária inteira, complexo aréolo-papilar preservado externamente, pele em fuso por sobre a área de incisão e linfonodos axilares anexados em bloco separado. Esse formato anatômico já antecipa que o tumor era localmente avançado e que a equipe optou por controle locorregional amplo — provavelmente associado a esvaziamento axilar formal porque a #sigla("BLS", [biópsia de linfonodo sentinela]) era inviável (linfonodos clinicamente positivos antes da cirurgia, ou peça pós-neoadjuvância com axila previamente abordada).

#figura-nebli("/figuras/patologia-mama/img-p001-06.jpeg", largura: 70%, legenda: [Pergunta 1 — esquema dos tipos de mastectomia. A peça enviada ao laboratório carrega a assinatura anatômica do procedimento: presença ou não de pele em fuso, complexo aréolo-papilar, fáscia peitoral e linfonodos axilares em bloco.])

#clinica-box("Quando a peça muda de nome", [Tumor localmente avançado significa: fixação à parede torácica, envolvimento extenso da pele com edema ou ulceração (peau d'orange), linfonodos axilares clinicamente fusionados ou comprometimento de fossa supraclavicular ipsilateral. Nesses casos, indica-se quimioterapia neoadjuvante antes da cirurgia — o objetivo é diminuir o estadiamento, viabilizar mastectomia com margens livres e, idealmente, converter linfonodos positivos em negativos. A peça que chega ao laboratório depois disso é fisicamente distinta da peça virgem de tratamento: leito tumoral fibrosado, pouca celularidade neoplásica residual, calcificações distróficas. Saber que a peça é pós-neoadjuvância muda completamente a leitura — voltaremos a isso na PARTE III.])

#mini-resumo[A peça cirúrgica é a assinatura física de uma decisão clínica anterior. Reconhecer o procedimento (conservadora, mastectomia simples, radical modificada, poupadora ou pós-neoadjuvância) pelo aspecto externo da peça orienta o exame macroscópico e prepara o patologista para o que virá na microscopia.]

#subtopico("1.2 — Protocolo de envio e pintura de margens")

O que acontece com a peça nas primeiras horas após sair do bloco cirúrgico decide a qualidade de todo o laudo subsequente. Tecido mal fixado autolisa: enzimas lisossômicas degradam membrana, núcleos perdem detalhe, antígenos para imuno-histoquímica deixam de ser detectáveis. Fixação adequada, portanto, não é detalhe burocrático — é pré-requisito para ler tudo o que vem depois. A formalina a 10% tamponada (formaldeído diluído em tampão fosfato) é o fixador padrão; o tampão evita a formação de pigmento ácido (hematina formólica) que confunde a microscopia, e a concentração de 10% garante penetração uniforme em volume razoável de tecido.

A regra prática de volume é direta: o recipiente precisa conter formalina em quantidade cinco a dez vezes o volume da peça. Volume menor satura a formalina rapidamente — a porção central da peça permanece sem fixar e autolisa. O tempo mínimo de fixação varia com o tamanho: pequenas biópsias core fixam em seis horas; peças de mastectomia podem exigir vinte e quatro a quarenta e oito horas. Para peças volumosas, recomenda-se que o patologista seccione a peça em fatias paralelas o mais rapidamente possível após o recebimento, expondo o interior à formalina — caso contrário, a porção central pode chegar à microscopia com núcleos borrados e estroma desfeito, dando falso "achado" de necrose tumoral que não existia em vida.

A orientação topográfica das margens é o segundo pilar e depende inteiramente do cirurgião. Em biópsia excisional ou ressecção segmentar, três fios marcam três planos: por convenção brasileira, fio curto na margem cranial, fio longo na margem lateral, fio médio na margem medial. As margens posterior (base) e anterior são deduzidas pela posição relativa. Sem essa marcação, o patologista recebe um cubo de tecido sem norte — uma margem positiva qualquer se torna informação inútil porque não se pode reabordar cirurgicamente uma direção que não se sabe qual é. Por isso, peças que chegam desorientadas devem ser comunicadas ao cirurgião e, idealmente, registradas em laudo como limitação técnica.

A pintura das margens é feita antes do primeiro corte da peça. Procedimento clássico: a peça é seca delicadamente com gaze, e cada uma das seis margens (anterior, posterior, superior, inferior, medial, lateral) recebe uma cor de tinta indiana ou nanquim distinta — ou, alternativamente, uma cor única se cada margem é submetida em um cassete separado e identificado. A tinta penetra superficialmente no tecido e permanece visível ao microscópio mesmo após processamento; permite afirmar com segurança que "células neoplásicas alcançam a margem pintada de azul" significa "margem lateral comprometida". Sem pintura, a porção mais externa da fatia histológica é apenas "a borda do corte" — e borda de corte não é margem cirúrgica.

#figura-nebli("/figuras/patologia-mama/img-p002-05.png", largura: 55%, legenda: [Pergunta 2 — esquema da pintura de margens. As seis margens recebem cores distintas (ou cor única em cassetes separados); a tinta sobrevive ao processamento histológico e identifica inequivocamente, no microscópio, qual margem está comprometida.])

#figura-nebli("/figuras/patologia-mama/img-p003-02.png", largura: 50%, legenda: [Orientação topográfica por fios cirúrgicos: fio curto na margem cranial, fio longo na lateral, fio médio na medial. Sem essa marcação, qualquer margem comprometida vira informação cirurgicamente inútil.])

#atencao-box("Hematina formólica e artefato de fixação", [Formalina não tamponada (sem fosfato) tende a oxidar a pH ácido e produz pigmento marrom-escuro chamado hematina formólica, depositado em interstício e ao redor de eritrócitos. No microscópio simula hemossiderina ou pigmento melanótico e atrapalha leitura, principalmente em casos suspeitos de melanoma metastático ou doença de Paget. Por isso a formalina tamponada não é luxo — é exigência técnica. A segunda armadilha clássica é a peça volumosa não seccionada: a porção central permanece sem fixar por dias, autolisa, e a microscopia mostra "necrose" que é apenas degradação post-mortem do tecido.])

#mini-resumo[Fixação em formalina tamponada a 10% com volume cinco a dez vezes superior ao da peça; secção precoce de peças volumosas; orientação por fios cirúrgicos (curto cranial, longo lateral, médio medial); pintura das seis margens antes do primeiro corte. Esse protocolo é pré-requisito de tudo o que vem depois.]

#subtopico("1.3 — Descrição macroscópica e estadiamento T")

A descrição macroscópica é a primeira leitura diagnóstica da peça. Antes da microscopia, antes da imuno-histoquímica, antes do molecular, o patologista olha a peça desnuda e formula uma hipótese morfológica. Em mama, essa hipótese se constrói sobre cinco eixos: dimensões da peça, dimensões e localização do tumor, aspecto do tumor (cor, consistência, contornos), distância às margens pintadas e relação com pele/mamilo/fáscia peitoral. Cada eixo aporta uma informação prognóstica que sobreviverá ao laudo final.

O carcinoma ductal invasivo clássico tem aspecto macroscópico tão característico que serve de protótipo. À fatia, aparece como nódulo único, branco-acinzentado a amarelado, de consistência firme a pétrea (consistência "de cartilagem dura"), com bordas espiculadas que invadem o tecido adiposo circundante em raios irregulares. Essa firmeza extrema vem da #termo-nota[reação desmoplásica][resposta estromal exuberante com proliferação de fibroblastos e deposição densa de colágeno tipo I ao redor das células tumorais; responsável pela consistência pétrea e pela espiculação radiográfica/macroscópica do CDI] — não é o tumor que é duro, é o estroma reativo ao redor das células neoplásicas que enrijece a peça inteira. A espiculação macroscópica é o equivalente físico da imagem mamográfica em "estrela" e da retração mamilar que pode aparecer no exame clínico: tudo é a mesma desmoplasia puxando estruturas vizinhas.

A descrição modelo de uma peça A típica pode ser assim formulada: "peça de mastectomia radical modificada à direita medindo 18 × 14 × 5 cm, com pele em fuso de 15 × 4 cm, complexo aréolo-papilar centralmente preservado. Ao corte seriado, identifica-se nódulo único no quadrante superolateral, branco-acinzentado, firme, espiculado, medindo 3,2 × 2,8 × 2,5 cm, distando 0,8 cm da margem profunda (fáscia peitoral) e 4 cm da pele. Sem comprometimento macroscópico de pele, mamilo ou fáscia. Linfonodos axilares anexados em bloco separado." A hipótese principal — carcinoma ductal invasivo — se justifica pela tríade: nódulo único firme, branco-acinzentado, espiculado.

#figura-nebli("/figuras/patologia-mama/img-p005-01.jpeg", largura: 60%, legenda: [Pergunta 3 — peça A à macroscopia: nódulo único firme, branco-acinzentado, espiculado, infiltrando o tecido adiposo circundante. Tríade clássica do CDI; a consistência pétrea reflete a reação desmoplásica peritumoral.])

#figura-nebli("/figuras/patologia-mama/img-p006-02.jpeg", largura: 65%, legenda: [Pergunta 4 — peça B: outro padrão macroscópico possível, com nódulo menos delimitado e infiltração em chumaços; padrão compatível com carcinoma lobular invasivo, que cresce em fila indiana sem formar massa coesa. A macroscopia já antecipa a hipótese histológica.])

O estadiamento T (tumor primário) é construído sobre a maior dimensão do nódulo medida na macroscopia, eventualmente refinada pela microscopia se a relação com pele ou parede torácica precisar de confirmação. A categorização TNM segue uma escada simples: T1 abrange tumores de até 2 cm (com subcategorias T1a até 0,5 cm, T1b entre 0,5 e 1 cm, T1c entre 1 e 2 cm); T2 cobre tumores maiores que 2 cm e até 5 cm; T3 indica tumor maior que 5 cm; T4 sai do critério de tamanho e entra em critério de extensão — T4a com invasão de parede torácica (costelas, intercostais ou serrátil anterior; músculo peitoral não conta), T4b com edema ou ulceração da pele ou nódulos cutâneos satélites, T4c combinando T4a e T4b, T4d sendo o carcinoma inflamatório.

#termo-nota[carcinoma inflamatório][forma clínica caracterizada por eritema, edema e pele em "casca de laranja" sobre a mama, causada por embolização maciça de linfáticos dérmicos por células tumorais; não é subtipo histológico, é apresentação clínica T4d com prognóstico ruim]

No exemplo da peça A com nódulo de 3,2 cm sem comprometimento de pele ou parede, o estadiamento é T2. Se a peça A medisse 5,5 cm, viraria T3. Se houvesse retração de pele com nódulos satélites palpáveis ao redor do tumor principal, seria T4b independentemente do tamanho. Esse é o ponto-chave: T4 não é continuidade de tamanho de T3 — é mudança de critério, do volume do tumor para a extensão local da invasão.

#confusao-prevista(titulo: "Invasão de músculo peitoral não é T4", aluno_acha: [Se o tumor cresceu para trás e tocou o músculo peitoral maior, então é T4a por "invasão de parede torácica".], mecanismo: [Parede torácica, na definição TNM da mama, é especificamente: costelas, músculos intercostais e músculo serrátil anterior. Músculo peitoral maior e menor não fazem parte da definição. Tumor que invade peitoral pode ser pT2 ou pT3 dependendo do tamanho, mas o envolvimento do peitoral não eleva o T por si. A lógica é prognóstica: o peitoral é facilmente ressecado em bloco com a mama; parede torácica óssea/intercostal já significa doença irressecável sem morbidade grave.])

#figura-nebli("/figuras/patologia-mama/img-p016-01.jpeg", largura: 75%, legenda: [Pergunta 7 — estadiamento T do carcinoma de mama. T1 até 2 cm (subdividido em T1a/b/c), T2 entre 2 e 5 cm, T3 acima de 5 cm, T4 com critério de extensão local (parede, pele, inflamatório). A passagem de T3 para T4 é mudança de critério, não continuidade de tamanho.])

#mini-resumo[A descrição macroscópica do CDI clássico — nódulo único, firme, branco-acinzentado, espiculado — é a primeira hipótese diagnóstica. A medida da maior dimensão alimenta diretamente o T. T1 até 2 cm, T2 entre 2 e 5 cm, T3 acima de 5 cm, T4 quando a invasão de pele, parede torácica ou padrão inflamatório toma o lugar do critério de tamanho.]

#parte-title("PARTE II — Carcinoma mamário invasivo")

#subtopico("2.1 — Achados macro e micro do CDI")

A microscopia do carcinoma ductal invasivo confirma e expande a hipótese macroscópica. O que se vê no aumento panorâmico é uma proliferação epitelial maligna que rompeu a membrana basal do ducto e invade o estroma circundante em ninhos, cordões ou trabéculas mal definidas, mergulhada em estroma denso fibroso — a desmoplasia já antecipada à mão. Esse é o critério definitivo de "invasivo": presença de células neoplásicas fora dos limites da membrana basal das estruturas ductais ou lobulares originais.

Aproximando o aumento, as células do CDI clássico são poligonais, de citoplasma eosinofílico moderado, com núcleos vesiculosos e nucléolos proeminentes. O grau de pleomorfismo (variação de tamanho e forma nuclear), a tendência a formar túbulos com lúmen central e a contagem de mitoses por dez campos de grande aumento alimentam o sistema de graduação de Nottingham (Scarff-Bloom-Richardson modificado, #sigla("SBR", [sistema de graduação de Scarff-Bloom-Richardson modificado, também chamado de Nottingham])). Cada um dos três parâmetros recebe pontuação de 1 a 3, e a soma define o grau histológico final: 3-5 pontos é grau 1 (bem diferenciado), 6-7 é grau 2 (moderadamente diferenciado), 8-9 é grau 3 (pouco diferenciado). Grau 1 forma túbulos abundantes, núcleos pequenos uniformes e raras mitoses; grau 3 não forma túbulos, tem pleomorfismo marcado e mitoses frequentes incluindo formas atípicas.

#figura-nebli("/figuras/patologia-mama/img-p018-02.jpeg", largura: 60%, legenda: [Pergunta 8 — microscopia do CDI: ninhos e cordões de células epiteliais malignas invadindo estroma desmoplásico denso. Critério definitivo de invasão: células ultrapassaram a membrana basal do ducto original. Graduação Nottingham combina formação tubular + grau nuclear + contagem mitótica.])

Ao lado do componente invasivo, a microscopia frequentemente revela um componente in situ — carcinoma ductal in situ (#sigla("CDIS", [carcinoma ductal in situ — proliferação maligna intraductal, com membrana basal preservada])) — que é a lesão precursora e remanesce ao redor do tumor invasivo. Diferenciar in situ de invasivo é a função central da microscopia mamária: ambos podem ter células malignas de morfologia praticamente idêntica, mas o in situ permanece confinado dentro do ducto, contornado por uma camada de células mioepiteliais íntegra e por membrana basal preservada. Quando a microscopia tem dúvida — focos pequenos, distorção arquitetural — a imuno-histoquímica entra em cena para resolver. Marcadores mioepiteliais (p63 nuclear, calponina e actina de músculo liso citoplasmáticas) confirmam a presença da camada mioepitelial ao redor de estruturas duvidosas: se há camada mioepitelial íntegra, é in situ; se ela está ausente em parte do contorno, é invasivo.

A distinção entre carcinoma ductal e carcinoma lobular invasivo também é feita no microscópio. O #sigla("CLI", [carcinoma lobular invasivo]) tem padrão de crescimento radicalmente diferente: células pequenas, monomórficas, dispostas em "fila indiana" (single-file) entre fibras colágenas, sem formar massa coesa. Macroscopicamente, o CLI é traiçoeiro porque pode não formar nódulo bem definido — a peça parece apenas mais firme em uma região, sem nódulo palpável claro. A microscopia revela a fila indiana e o diagnóstico se firma. A diferenciação molecular subjacente é a perda da E-caderina, proteína de adesão célula-célula: sem E-caderina, as células não conseguem agrupar-se em ninhos e crescem isoladas — daí o padrão em fila indiana e a ausência de massa coesa.

#termo-nota[E-caderina][proteína transmembrana de adesão célula-célula nos epitélios; perda funcional caracteriza o CLI e justifica o crescimento em fila indiana; usada como marcador IHQ negativo (CLI E-caderina-negativo) versus CDI (E-caderina-positivo)]

#mini-resumo[O critério de invasão é ultrapassar a membrana basal. O CDI forma ninhos e cordões em estroma desmoplásico; o CLI cresce em fila indiana por perda de E-caderina. A graduação Nottingham combina formação tubular, pleomorfismo nuclear e índice mitótico em três faixas: grau 1, 2 e 3 — que se traduzem diretamente em diferença prognóstica.]

#subtopico("2.2 — Imuno-histoquímica: RE, RP, HER2 e Ki-67")

A imuno-histoquímica é a tecnologia que transforma o diagnóstico morfológico em decisão terapêutica. Em mama, quatro marcadores formam o painel mínimo obrigatório de todo carcinoma invasor: receptor de estrógeno (#sigla("RE", [receptor de estrógeno; alvo direto da hormonioterapia])), receptor de progesterona (#sigla("RP", [receptor de progesterona; co-marcador hormonal])), receptor 2 do fator de crescimento epidérmico humano (#sigla("HER2", [human epidermal growth factor receptor 2; oncoproteína amplificada em 15-20% dos CDI, alvo do trastuzumabe])) e índice de proliferação Ki-67. Cada um responde a uma pergunta clínica distinta.

RE e RP são receptores nucleares hormonais expressos no carcinoma quando ele mantém a "memória" do tecido mamário normal hormonossensível. A IHQ marca o núcleo das células neoplásicas em marrom; o patologista quantifica a proporção de núcleos corados e a intensidade. Convenção atual: positivo quando ≥ 1% dos núcleos tumorais corados. Tumores RE-positivos respondem a hormonioterapia (tamoxifeno em pré-menopausa, inibidores de aromatase em pós-menopausa), e a hormonioterapia adjuvante reduz substancialmente a recidiva nesses casos. Ou seja, "RE positivo" é simultaneamente categoria prognóstica e prescrição terapêutica imediata.

HER2 é proteína de membrana cuja superexpressão (por amplificação do gene ERBB2) ativa cascatas proliferativas via PI3K/AKT e MAPK. A IHQ é semiquantitativa: 0 e 1+ são negativos; 2+ é equívoco e exige confirmação por hibridização in situ (#sigla("ISH", [in situ hybridization — hibridização in situ; quantifica cópias do gene ERBB2 quando IHQ HER2 é 2+ equívoco]), tipicamente FISH); 3+ é positivo. O critério morfológico para 3+ é coloração de membrana completa, intensa e circunferencial em mais de 10% das células. Tumores HER2-positivos respondem a trastuzumabe (anticorpo monoclonal anti-HER2) e congêneres — terapia-alvo que transformou prognóstico de um subgrupo que antes era de péssima evolução.

Ki-67 marca proteína nuclear expressa em todas as fases ativas do ciclo celular (G1, S, G2, M) e ausente em G0. A IHQ marca o núcleo das células em ciclo e o resultado é expresso em porcentagem de núcleos positivos sobre o total de núcleos tumorais contados. Ki-67 baixo (\<14%) indica tumor pouco proliferativo, frequentemente Luminal A, prognóstico favorável; Ki-67 alto (\>20%) indica tumor altamente proliferativo, comportamento mais agressivo e maior resposta a quimioterapia citotóxica (que ataca células em ciclo).

#figura-nebli("/figuras/patologia-mama/img-p017-01.png", largura: 70%, legenda: [Pergunta 8 — painel IHQ obrigatório em CDI: RE e RP nucleares quantificados em porcentagem de núcleos corados; HER2 de membrana semiquantitativo (0 a 3+); Ki-67 nuclear como índice proliferativo. Os quatro marcadores definem subtipo molecular e direcionam tratamento.])

#clinica-box("Por que o painel é obrigatório, não opcional", [Antes da era da IHQ rotineira, todo carcinoma de mama recebia quimioterapia adjuvante uniforme. Hoje, o painel RE/RP/HER2/Ki-67 estratifica em subgrupos de prognóstico e tratamento radicalmente diferentes: um Luminal A com RE+, HER2-, Ki-67 baixo pode receber apenas hormonioterapia adjuvante após cirurgia; um triplo-negativo (RE-, RP-, HER2-) exige quimioterapia agressiva porque não tem alvo terapêutico hormonal nem anti-HER2; um HER2-enriquecido se beneficia de trastuzumabe que mudou sua história natural. Sem IHQ, é impossível escolher tratamento racionalmente — o painel não é exame complementar, é exame definidor.])

#atencao-box("Receptor positivo de 1% existe e conta", [Critério atual brasileiro/ASCO: tumor é RE-positivo quando pelo menos 1% dos núcleos tumorais estão corados (faixa "low-positive" entre 1-10%; positividade clínica plena ≥ 10%). Mesmo na faixa 1-10%, há benefício mensurável de hormonioterapia. O patologista precisa reportar o exato percentual, não apenas "positivo" — porque tumores no limite inferior têm prognóstico intermediário e podem influenciar decisão sobre quimioterapia adicional.])

#mini-resumo[Painel IHQ obrigatório do CDI: RE e RP nucleares (positivo ≥ 1%), HER2 de membrana (0/1+ negativo, 2+ confirmar por ISH, 3+ positivo), Ki-67 nuclear como proliferação. Cada marcador responde a uma pergunta clínica direta: o tumor responde a hormonioterapia? Tem alvo anti-HER2? É altamente proliferativo? Sem esse painel, não há decisão terapêutica racional.]

#subtopico("2.3 — Subtipos moleculares e graduação")

A combinação dos quatro marcadores IHQ define o subtipo molecular surrogate — chamado "surrogate" porque é a aproximação imuno-histoquímica do que originalmente foi descrito por perfis de expressão gênica (microarrays). Na prática clínica, a IHQ substitui o teste molecular caro e dá a mesma estratificação prognóstica e terapêutica para a maioria dos casos.

#table(
  columns: 4,
  fill: (col, row) => if row == 0 { rgb("#1f3551") } else { none },
  stroke: 0.5pt + rgb("#5a6c84"),
  inset: 7pt,
  [#text(white, weight: "bold")[Subtipo]],
  [#text(white, weight: "bold")[Perfil IHQ]],
  [#text(white, weight: "bold")[Comportamento]],
  [#text(white, weight: "bold")[Tratamento sistêmico principal]],
  [Luminal A], [RE+ forte, RP+, HER2-, Ki-67 baixo (\<14%)], [Mais indolente, melhor prognóstico, recorrência tardia possível], [Hormonioterapia; quimioterapia raramente necessária],
  [Luminal B], [RE+, RP variável, HER2- ou HER2+, Ki-67 alto (\>20%)], [Mais agressivo que Luminal A; pior sobrevida livre de doença], [Hormonioterapia + quimioterapia; trastuzumabe se HER2+],
  [HER2-enriquecido], [RE-, RP-, HER2+ (3+ ou ISH amplificado)], [Agressivo sem terapia-alvo; bom prognóstico com trastuzumabe], [Quimioterapia + trastuzumabe (geralmente neoadjuvante)],
  [Triplo-negativo], [RE-, RP-, HER2-], [Mais agressivo, recorrência precoce, sem alvo hormonal/HER2], [Quimioterapia citotóxica; imunoterapia em subgrupos],
)

A graduação histológica Nottingham roda paralelamente ao subtipo molecular e refina o prognóstico dentro de cada subtipo. Formação tubular pontua 1 (\>75% do tumor forma túbulos), 2 (10-75%) ou 3 (\<10%). Grau nuclear pontua 1 (núcleos pequenos uniformes, semelhantes a ducto normal), 2 (núcleos intermediários) ou 3 (núcleos grandes, pleomórficos, com nucléolos proeminentes). Índice mitótico pontua 1 a 3 conforme contagem em dez campos de grande aumento (limites dependem do diâmetro do campo do microscópio). Soma 3-5: grau 1. Soma 6-7: grau 2. Soma 8-9: grau 3.

A graduação tem valor prognóstico independente do subtipo molecular. Um Luminal A grau 1 tem prognóstico excelente; um Luminal B grau 3 tem comportamento mais próximo de triplo-negativo. Por isso o laudo final do CDI sempre carrega as duas camadas: subtipo molecular surrogate por IHQ + grau histológico Nottingham.

#confusao-prevista(titulo: "Triplo-negativo não é igual a basal-like", aluno_acha: [Triplo-negativo e basal-like são sinônimos.], mecanismo: [Triplo-negativo é definição IHQ — RE-, RP-, HER2-. Basal-like é definição molecular por expressão gênica (microarray ou nanostring), caracterizada por expressão de citoqueratinas basais (CK5/6, CK14) e EGFR. A maioria (~70-80%) dos triplos-negativos é basal-like por expressão gênica, mas existe sobreposição imperfeita. O termo clínico-patológico operacional continua sendo "triplo-negativo" porque é o que se mede com IHQ; "basal-like" é categoria de pesquisa que ocasionalmente entra em laudo refinado.])

#mini-resumo[Subtipos moleculares surrogate por IHQ: Luminal A (indolente, hormonioterapia), Luminal B (agressivo, hormonioterapia + quimioterapia), HER2-enriquecido (alvo trastuzumabe), Triplo-negativo (sem alvo, quimioterapia). Graduação Nottingham por formação tubular + grau nuclear + índice mitótico refina prognóstico dentro de cada subtipo.]

#parte-title("PARTE III — Pós-neoadjuvância e laudo")

#subtopico("3.1 — Mastectomia após quimioterapia neoadjuvante")

Quando a paciente foi submetida a quimioterapia neoadjuvante antes da cirurgia, a peça que chega ao laboratório é fisicamente diferente da peça virgem de tratamento. O leito tumoral fica fibrosado, frequentemente menor do que o tumor original visto na mamografia ou ressonância pré-quimioterapia, com áreas amareladas de necrose, hemorragia em organização e calcificações distróficas. O patologista precisa saber, antes de abrir a peça, que se trata de mastectomia pós-neoadjuvância — caso contrário, pode interpretar fibrose como "ausência de tumor", deixar de procurar células residuais e subestimar a doença residual.

O exame macroscópico segue protocolo modificado. O leito tumoral é identificado por correlação com mamografia pré-tratamento, por marcador metálico (clip) implantado durante a biópsia core diagnóstica que permanece visível em radiografia da peça, ou por aspecto macroscópico da área fibrosada. Todo o leito tumoral macroscopicamente identificável é submetido em fatias contíguas — não apenas amostragem aleatória — porque células neoplásicas residuais podem persistir em focos isolados dentro de tecido predominantemente fibroso. A regra é amostrar generosamente: para tumores que mediam até 5 cm pré-quimioterapia, submeter um cassete a cada centímetro do maior diâmetro do leito; para tumores maiores, amostragem mais densa.

A descrição macroscópica anota o tamanho do leito tumoral fibrosado (não o tamanho do tumor original) e qualquer nódulo residual macroscopicamente identificável. O estadiamento muda de prefixo: passa de "pT" para "ypT" — y indica tratamento prévio, p indica patológico. ypT0 significa ausência de tumor invasivo residual; ypT1mi significa microinvasão (≤ 1 mm); ypT1a/b/c, ypT2, ypT3 e ypT4 seguem os mesmos cortes de tamanho do estadiamento clássico, agora aplicados ao maior foco de tumor invasivo residual encontrado, não ao leito tumoral fibrosado inteiro.

#figura-nebli("/figuras/patologia-mama/img-p019-01.jpeg", largura: 50%, legenda: [Pergunta 9 — leito tumoral pós-neoadjuvância: fibrose extensa, calcificações distróficas, áreas de necrose em organização. Células neoplásicas residuais (quando presentes) ficam dispersas em meio ao tecido fibroso; amostragem generosa é obrigatória.])

#clinica-box("Por que neoadjuvância antes da cirurgia", [Quimioterapia neoadjuvante é indicada principalmente em tumores localmente avançados (T3, T4, axila clinicamente positiva), triplos-negativos, HER2-positivos e em casos onde se busca conservação mamária em tumores de tamanho médio. A lógica tem três frentes: (1) reduzir o tumor para viabilizar cirurgia conservadora; (2) tratar precocemente a doença micrometastática sistêmica; (3) avaliar in vivo a resposta à quimioterapia, informação prognóstica que orienta tratamento adjuvante. A resposta patológica completa (ypT0/ypN0) é o desfecho mais favorável e correlaciona-se com sobrevida muito melhor — daí a centralidade do índice RCB que veremos a seguir.])

#mini-resumo[A peça pós-neoadjuvância é fisicamente diferente: leito tumoral fibrosado com células residuais dispersas. Amostragem generosa (cassete por centímetro do leito) é obrigatória. Estadiamento usa prefixo "ypT" e mede o maior foco invasivo residual, não o leito fibrosado inteiro.]

#subtopico("3.2 — Resposta patológica e índice RCB")

A resposta patológica à quimioterapia neoadjuvante distribui-se em um espectro contínuo, mas o laudo a categoriza para uso clínico. A categoria mais favorável é a resposta patológica completa, dividida em dois cenários: ausência total de carcinoma residual (sem invasivo, sem in situ) — pCR estrita — ou ausência de carcinoma invasivo residual mas presença de carcinoma ductal in situ (pCR ampliada). Ambos têm prognóstico excelente, especialmente nos subtipos HER2-positivo e triplo-negativo.

Abaixo da resposta completa, o espectro de resposta parcial subdivide-se em três faixas qualitativas: doença residual mínima ou efeito quase total (\<10% do tumor original permanece), evidência de resposta com 10-50% remanescente, ou mais de 50% de celularidade tumoral persistente. A quarta categoria é ausência de evidência de resposta — tumor virtualmente inalterado em comparação com a biópsia core pré-tratamento. Aos linfonodos aplica-se gradação análoga: sem doença metastática residual e sem alteração; sem metástase mas com sinais de regressão (fibrose nodal); metástase residual com sinais de resposta; metástase residual sem evidência de resposta.

O índice RCB (Residual Cancer Burden) traduz essa avaliação qualitativa em escore numérico reprodutível e prognosticamente validado. O cálculo combina quatro parâmetros: as duas maiores dimensões do leito tumoral residual (geram a área bidimensional), a porcentagem de celularidade tumoral invasiva dentro do leito, a proporção de carcinoma in situ no leito, o número de linfonodos positivos e o tamanho da maior metástase nodal. Um algoritmo padronizado combina os parâmetros em um índice numérico que se categoriza em quatro classes: RCB-0 (resposta patológica completa, escore zero), RCB-I (doença residual mínima), RCB-II (doença residual moderada), RCB-III (doença residual extensa).

#figura-nebli("/figuras/patologia-mama/img-p020-01.jpeg", largura: 50%, legenda: [Pergunta 9 — espectro de resposta patológica à neoadjuvância: da pCR (RCB-0) à doença residual extensa sem evidência de resposta (RCB-III). A categorização guia decisão sobre terapia adjuvante adicional.])

A potência prognóstica do RCB foi validada em coortes grandes: pacientes com RCB-0 têm sobrevida livre de doença em 10 anos próxima a 95% em subtipos favoráveis; RCB-III tem sobrevida significativamente pior, frequentemente exigindo intensificação terapêutica adjuvante (capecitabina em triplo-negativo, trastuzumabe-emtansina em HER2+ residual). Por isso o laudo pós-neoadjuvância não pode se contentar com "tumor residual presente" — precisa quantificar segundo RCB para que o oncologista module o tratamento adjuvante.

#confusao-prevista(titulo: "Tamanho do leito não é o ypT", aluno_acha: [Se o leito tumoral fibrosado mede 4 cm, então ypT2.], mecanismo: [ypT é definido pela maior dimensão de tumor invasivo residual — o foco viável de carcinoma encontrado dentro do leito. Se um leito fibrosado de 4 cm contém apenas um foco invasivo residual de 0,8 cm, o ypT é ypT1b. Se contém vários focos dispersos, regra atual é medir o maior foco contíguo, não somar. O leito fibrosado é referência para amostragem e para cálculo do RCB; o ypT é a maior dimensão do invasivo viável.])

#mini-resumo[Resposta patológica completa (RCB-0) é o desfecho ideal e o mais forte preditor de sobrevida em HER2+ e triplo-negativo pós-neoadjuvância. O índice RCB combina dimensões do leito, celularidade invasiva, in situ e doença nodal em escore numérico que classifica em RCB-0 a III. ypT mede o maior foco invasivo residual, não o leito fibrosado inteiro.]

#subtopico("3.3 — Arquivamento e cadeia de custódia")

O fluxo da peça não termina com o laudo. Após a clivagem (amostragem em fragmentos representativos para processamento) e a redação do laudo final, vários componentes precisam ser arquivados por períodos definidos por norma — a peça deixou de ser apenas tecido e virou documento médico-legal com cadeia de custódia rastreável.

O remanescente macroscópico da peça (porções não amostradas) é mantido em formalina por um período mínimo, tipicamente entre quatro semanas e três meses, conforme protocolo institucional. Esse intervalo cobre a possibilidade de o clínico solicitar amostragem adicional após receber o laudo, eventualmente exigindo nova coloração ou novo marcador IHQ em área não inicialmente representada. Passado o prazo, o remanescente é descartado conforme legislação de resíduos biológicos hospitalares.

A requisição original do exame — documento físico ou eletrônico contendo dados clínicos, hipóteses, identificação do material e identificação do solicitante — é arquivada por no mínimo cinco anos. O laudo final, em duas vias (uma para o serviço solicitante, uma para o arquivo do laboratório), é arquivado pelo período exigido pela legislação local, frequentemente vinte anos ou indefinidamente em meio digital. As lâminas histológicas (vidros com cortes corados em hematoxilina-eosina e IHQ) são arquivadas por no mínimo cinco anos; os blocos de parafina (que contêm tecido fixado processado, fonte permanente de novos cortes e novas colorações) são arquivados por no mínimo dez anos no Brasil — e na prática, indefinidamente sempre que possível, porque permitem revisão diagnóstica anos depois, testes moleculares emergentes não disponíveis à época, e perícia médico-legal.

#figura-nebli("/figuras/patologia-mama/img-p022-03.jpeg", largura: 55%, legenda: [Pergunta 10 — fluxo de arquivamento: requisição (≥5 anos), laudo (≥20 anos, frequentemente indefinido), lâminas (≥5 anos), blocos de parafina (≥10 anos, idealmente indefinidos). Cadeia de custódia é exigência médico-legal e técnica — o bloco preservado permite revisão diagnóstica e testes moleculares futuros.])

#atencao-box("Bloco de parafina é patrimônio diagnóstico", [O bloco de parafina contendo o tecido tumoral é o único componente do exame que permite, anos depois, refazer cortes adicionais, repetir IHQ com novos anticorpos, realizar testes moleculares emergentes (FISH, sequenciamento de painéis), reavaliar diagnóstico em segunda opinião e responder a perícia médico-legal. Perder o bloco significa perder a possibilidade de qualquer reanálise — daí a recomendação institucional crescente de arquivamento indefinido sempre que infraestrutura permitir, ultrapassando o mínimo legal de dez anos.])

#mini-resumo[O remanescente macroscópico fica em formalina por semanas a meses para amostragem adicional eventual. Requisição: 5 anos. Laudo: 20 anos ou mais. Lâminas: 5 anos. Blocos: 10 anos no mínimo, idealmente indefinidos. O bloco é patrimônio diagnóstico — fonte de novos cortes, novos marcadores e perícia.]

#conclusao-box[
A patologia mamária se organiza em uma espinha clínica única que ressurge em quase todo caso: rastreio por mamografia identifica lesão suspeita (BI-RADS 4 ou 5); biópsia core confirma carcinoma e fornece tecido para IHQ inicial; o painel RE/RP/HER2/Ki-67 define subtipo molecular e indica neoadjuvância em tumores localmente avançados, HER2-positivos ou triplos-negativos; quimioterapia neoadjuvante reduz a carga tumoral e gera resposta in vivo quantificável; mastectomia (ou conservadora) remove a peça residual; o patologista descreve macroscopia, pinta margens, amostra generosamente o leito fibrosado, mede o maior foco invasivo viável para gerar ypT, aplica IHQ no residual e calcula RCB. O laudo final entrega ao oncologista as informações que orientam terapia adjuvante: hormonioterapia em RE-positivo, trastuzumabe em HER2-positivo, capecitabina em triplo-negativo com doença residual extensa. Cada passo da cadeia é tecnicamente exigente — fixação, pintura, orientação, amostragem, IHQ, cálculo RCB, arquivamento — mas a lógica subjacente é simples e coerente: ler a peça é ler o histórico clínico inscrito no tecido, e devolver ao clínico um documento que muda a próxima decisão.
]
