#import "../../typst-template/nebli_v2_apostila.typ": *

#pre-aula-page[
A aula de hoje trata de líquido fora do lugar. Ela começa por três palavras que o professor usa como se você já as dominasse, e vale chegar com elas firmes. *Edema* é o acúmulo anormal de líquido no espaço entre as células ou numa cavidade do corpo. *Hiperemia* é o excesso de sangue num tecido porque as arteríolas se dilataram e deixaram entrar mais sangue arterial, vermelho vivo. *Congestão* é o excesso de sangue num tecido porque a saída venosa está dificultada, com sangue parado e escuro. A primeira lâmina de imagens mostra as três coisas ao mesmo tempo: um glomérulo com capilares abarrotados de hemácias, um olho vermelho e uma perna inchada.

Logo depois vêm os nomes das coleções. O líquido de edema, quando se junta numa cavidade revestida por membrana serosa, ganha o nome do lugar. *Hidrotórax* é líquido na cavidade pleural, *hidropericárdio* é líquido no saco que envolve o coração, e *ascite* é líquido na cavidade peritoneal, dentro do abdome. *Anasarca* é o edema grave e generalizado do tecido subcutâneo, com o corpo inteiro infiltrado. Esses nomes dizem onde o líquido está e não por que ele chegou lá, e a aula vai passar o resto do tempo explicando o porquê.

Para isso o professor mostra um esquema do leito capilar, e esse esquema é a peça central. Ali atuam as *forças de Starling*, o conjunto de pressões que decide se a água sai do capilar ou fica nele. A *pressão hidrostática* é a pressão do sangue contra a parede do vaso e empurra líquido para fora. A *pressão oncótica*, também chamada coloidosmótica, é a força osmótica das proteínas que ficam presas dentro do vaso e segura a água no lugar. A proteína que mais contribui para ela é a *albumina*, fabricada pelo fígado. O líquido que sobra no tecido é recolhido pelos *vasos linfáticos*, uma rede de canais de fundo cego que devolve esse excedente ao sangue pelo *ducto torácico*. Com essas peças, a regra do capítulo inteiro fica simples: aparece edema quando sai mais líquido do capilar do que a linfa consegue recolher.

A partir daí a aula lista as maneiras de desequilibrar o esquema, e cada uma vem com uma doença que serve de exemplo. A primeira é a pressão hidrostática alta, que acontece quando o sangue não consegue voltar pelas veias. O exemplo local é uma veia da perna entupida por um trombo. O exemplo generalizado é a *insuficiência cardíaca*, a situação em que o coração não bombeia o que recebe. Nela entra um segundo personagem, o rim. Quando o coração manda pouco sangue adiante, o rim entende que falta volume e ativa o *sistema renina-angiotensina-aldosterona*, uma cadeia de hormônios que faz o rim guardar sódio, e a água segue o sódio. O slide desenha isso como um círculo: o volume guardado sobrecarrega o coração que já falhava, e o edema piora. Vale saber também que a falência do lado esquerdo do coração represa sangue nos pulmões, enquanto a do lado direito represa sangue no fígado e nas pernas.

A segunda maneira é a pressão oncótica baixa, por falta de albumina. O exemplo da aula é a *síndrome nefrótica*, uma doença do rim em que o filtro dos glomérulos passa a deixar escapar grandes quantidades de proteína na urina, a chamada *proteinúria*, com albumina baixa no sangue. O esquema desse slide é mais denso do que parece: além da falta de albumina, ele mostra o próprio rim doente guardando sódio por conta própria, o que se chama *retenção primária de sódio*, em contraste com a retenção secundária, que é a resposta de um rim sadio a um volume percebido como baixo.

A cirrose vem em seguida, numa sequência em caixas, e junta várias dessas maneiras num mesmo doente. A cirrose endurece o fígado e dificulta a passagem do sangue que vem do intestino, o que se chama *hipertensão portal*. Essa pressão dilata as artérias do intestino, o sangue disponível passa a parecer pouco para um leito tão largo, e o rim de novo guarda sódio. O resultado é a ascite. No mesmo esquema aparece a *síndrome hepatorrenal*, uma perda de função dos rins que nasce dessa mesma cascata, com rins que parecem normais ao microscópio.

Duas outras causas aparecem mais rápido, em fotografias. A obstrução dos vasos linfáticos produz o *linfedema*, um inchaço localizado e endurecido de um membro ou da mama. E o aumento da *permeabilidade vascular*, que é a parede do vaso deixando passar o que antes retinha, acontece na inflamação. Aqui entram dois termos que a aula usa para classificar o líquido. *Transudato* é o líquido claro e pobre em proteína que sai de um vaso de parede íntegra. *Exsudato* é o líquido turvo, rico em proteína e em células de defesa, que sai de um vaso de parede lesada.

A última parte da aula é a mais visual, e o professor projeta pulmão e fígado. O pulmão com *edema pulmonar* aparece pesado, com espuma saindo da superfície de corte, numa radiografia esbranquiçada e, ao microscópio, com os alvéolos cheios de um material rosado. O fígado da congestão crônica aparece como *fígado em noz-moscada*, com pontos escuros e claros que lembram a semente cortada, exibida ao lado da foto. Por fim entra a *síndrome do desconforto respiratório agudo*, uma lesão grave do pulmão em que células de defesa destroem a barreira entre o alvéolo e o capilar. O esquema mostra *neutrófilos* liberando substâncias tóxicas, e as lâminas finais mostram as *membranas hialinas*, faixas rosadas de fibrina que forram as paredes dos alvéolos lesados. Elas são a diferença visível entre o pulmão que encheu de líquido por pressão e o pulmão que encheu porque a barreira foi destruída.

Chegue com esse mapa na cabeça: três forças e um dreno, cinco maneiras de desequilibrar, e dois órgãos onde o desequilíbrio fica marcado.
]
