#import "../typst-template/nebli_v2_apostila.typ": *

#intro-box[
  Um adulto respira cerca de dez mil litros de ar por dia, e não tem escolha sobre a composição desse ar. É essa combinação — volume enorme, exposição involuntária, todos os dias da vida — que transforma a qualidade do ambiente numa causa de doença tão real quanto um vírus ou uma mutação, só que distribuída sobre populações inteiras em vez de indivíduos isolados. A patologia ambiental estuda exatamente isso: como agentes químicos e físicos do meio entram no corpo, o que fazem quando chegam, e por que o dano aparece muito antes de alguém morrer. Este resumo persegue a ideia por três caminhos. Primeiro, o quadro geral — o que conta como doença ambiental, por que a mortalidade é apenas a ponta visível do estrago, e como uma molécula estranha vira lesão celular. Depois, o ar poluído levado a sério: do que ele é feito, por que o tamanho de uma partícula decide até onde ela chega, e o que acontece no pulmão quando ela chega. Por fim, o que a maior parte das pessoas não espera — que o desfecho mais numeroso da poluição do ar não seja respiratório, e sim cardiovascular. A régua de fundo é uma só: o ambiente age por mecanismo, e mecanismo se explica.
]

#parte-title("PARTE I — O ambiente como causa de doença", primeira: true)

#subtopico("1.1 — Da Revolução Industrial ao nevoeiro de 1952")

Durante quase toda a história da medicina o ar não figurou na lista de agentes etiológicos. Isso mudou por acúmulo de evidência, e a Revolução Industrial foi o ponto de virada: a queima de carvão em escala urbana concentrou, em poucas décadas e em poucos quilômetros quadrados, quantidades de fumaça e de enxofre que nenhuma população humana havia respirado antes. A partir daí, o adoecimento deixou de ser explicável só pelo que a pessoa comia, bebia ou pegava de outra pessoa — passou a incluir o que ela simplesmente não tinha como deixar de inalar.

O vocabulário técnico dessa área começa numa palavra. #termo-nota[Xenobiótico][qualquer substância estranha ao metabolismo do organismo — poluentes, fármacos, aditivos, produtos industriais] é o nome genérico da substância estranha ao metabolismo. Não é sinônimo de veneno: se um xenobiótico causa dano depende da dose, da via de entrada, do tempo de exposição e — este é o ponto que a próxima seção vai abrir — do que o próprio organismo faz com ele depois de absorvê-lo. Doença ambiental, por sua vez, é a doença causada por exposição a agentes químicos ou físicos do meio, do ar, da água, do solo ou do local de trabalho.

O episódio que consolidou o campo aconteceu em Londres, em dezembro de 1952. Uma massa de ar frio e parado se instalou sobre a cidade e produziu uma #termo-nota[inversão térmica][situação em que uma camada de ar quente se sobrepõe ao ar frio junto ao solo, funcionando como tampa e impedindo a dispersão vertical dos poluentes] — uma tampa de ar quente sobre o ar frio junto ao solo, impedindo que a fumaça subisse e se dispersasse. Repare que a inversão não fabricou poluente nenhum; ela apenas impediu a dispersão do que já vinha sendo emitido pelas chaminés domésticas e industriais. A concentração de fumaça e de dióxido de enxofre disparou, e a mortalidade diária da cidade acompanhou a curva quase em paralelo: cerca de quatro mil mortes a mais em uma semana, e mais de oito mil no acumulado de três semanas. *Foi a primeira vez que uma curva de poluente e uma curva de óbitos foram desenhadas lado a lado no mesmo gráfico* — e é por isso que essa figura vale mais do que a história que ela conta.

#figura-nebli("/figuras/patologia-ambiental/slide-05.png",
  largura: 66%,
  legenda: [Londres, dezembro de 1952. A curva de concentração de fumaça e a curva de mortes por dia sobem e descem praticamente juntas, com o pico de óbitos acompanhando o pico de poluição. A inversão térmica não criou o poluente — impediu que ele se dispersasse, e a dose respirada explodiu.])

Vale registrar que Londres não foi um acidente isolado, e sim o caso mais visível de um padrão: o vale do Meuse, na Bélgica, em 1930, e a cidade de Donora, na Pensilvânia, em 1948, já haviam mostrado a mesma sequência de inversão térmica seguida de excesso de mortes. *O que Londres acrescentou foi escala suficiente para tornar o argumento irrecusável.*

#subtopico("1.2 — O iceberg dos efeitos")

A imagem que o professor usa para organizar o campo é a de um iceberg, e ela merece ser levada a sério porque corrige uma distorção que atravessa toda a saúde ambiental. No topo, acima da linha d'água, estão as mortes — o desfecho mais grave e o menos numeroso. Logo abaixo vêm as internações hospitalares; abaixo delas, o aumento de consultas médicas; mais abaixo ainda, o aumento do consumo de medicamentos, como o broncodilatador que o asmático usa mais vezes em dias de ar ruim. E na base, submersa e invisível, a inflamação subclínica: milhões de pessoas com marcadores inflamatórios alterados, sem sintoma nenhum, sem procurar serviço de saúde, sem aparecer em registro algum.

#figura-nebli("/figuras/patologia-ambiental/slide-06.png",
  largura: 56%,
  legenda: [Dois eixos correm em sentidos opostos. À esquerda, a gravidade cresce de baixo para cima; à direita, o número de afetados cresce de cima para baixo. Morte é o desfecho mais grave e o mais raro; inflamação subclínica é o mais leve e o que atinge quase todo mundo — e é justamente a faixa que nenhum registro de saúde captura.])

Os dois eixos correm em sentidos opostos, e é isso que dá potência à figura: *quanto mais grave o desfecho, menos gente o alcança; quanto mais leve, mais gente*. A consequência prática é direta. Se medirmos o impacto da poluição só pela mortalidade, estaremos medindo a ponta de um problema cuja massa está embaixo — e subestimando por muito o que ele custa. E há uma consequência conceitual ainda mais importante: efeito subclínico não é efeito desprezível. Inflamação sem sintoma, mantida por anos, é justamente o combustível da doença crônica que aparecerá décadas depois, e é ela que desloca o risco de uma população inteira em vez de adoecer alguns indivíduos.

#mini-resumo[A mortalidade é o topo do iceberg. Abaixo dela, internação, consulta e medicamento; na base submersa, inflamação subclínica em muita gente. Medir só óbito subestima o problema e perde exatamente a faixa que alimenta doença crônica.]

#subtopico("1.3 — Do xenobiótico à lesão celular")

Entre inalar uma substância e adoecer por causa dela existe uma sequência de etapas, e conhecê-la organiza tudo o que vem depois. A substância precisa ser absorvida, distribuída pelo sangue, metabolizada e excretada — e é no metabolismo que mora a surpresa.

O fígado processa xenobióticos em duas fases. Na *fase I*, enzimas do sistema citocromo P-450 introduzem ou expõem um grupo reativo na molécula, geralmente inserindo oxigênio. Na *fase II*, a molécula assim modificada é conjugada a glutationa, glicuronídeo ou sulfato, tornando-se solúvel em água e pronta para sair pela urina ou pela bile. O esquema parece uma linha de montagem de destoxificação, e frequentemente é. *Só que a fase I nem sempre desativa — muitas vezes ela ativa.* Quando o produto da primeira fase é um eletrófilo reativo, capaz de atacar proteínas e o próprio DNA, e a segunda fase não dá conta de conjugá-lo, o resultado é uma molécula mais perigosa do que a original. Esse fenômeno tem nome próprio: #termo-nota[bioativação][transformação metabólica que torna um xenobiótico mais reativo e mais tóxico do que a molécula original, em vez de desativá-lo]. O exemplo que interessa a esta aula é justamente um dos poluentes que aparecerão na PARTE II: os hidrocarbonetos policíclicos aromáticos, produtos de combustão incompleta, são convertidos pelo citocromo P-450 em epóxidos que se ligam covalentemente ao DNA, formando #termo-nota[adutos de DNA][ligação covalente entre um metabólito reativo e uma base do DNA; se a replicação passar pelo aduto antes do reparo, ele se converte em mutação]. Se a célula replicar antes de reparar o aduto, ele vira mutação — e é assim que fumaça de combustão se conecta a câncer de pulmão.

A segunda via final, e a mais universal, é o estresse oxidativo. Radical livre é toda molécula com elétron desemparelhado: instável, ela rouba elétron do vizinho, e o vizinho oxidado vira radical por sua vez, propagando a lesão em cadeia por membranas lipídicas, proteínas e DNA. Poluentes chegam a esse ponto por caminhos diferentes — o ozônio é oxidante direto, o particulado carrega metais que catalisam a formação de radicais, a inflamação recrutada gera espécies reativas pelas próprias células de defesa. *Guarde essa convergência: por mais diferentes que sejam as fontes, o dano molecular quase sempre desemboca aqui.*

#subtopico("1.4 — Clima e megacidades: o pano de fundo da exposição")

Antes de descer ao mecanismo pulmonar, vale situar a escala do problema, porque ela explica por que este assunto ganhou espaço curricular. Dois processos globais redesenharam a exposição humana no último século: a mudança climática e a urbanização acelerada.

#figura-nebli("/figuras/patologia-ambiental/slide-08.png",
  largura: 42%,
  legenda: [Projeções de mudança da temperatura global de superfície em relação a 1850-1900, por cenário de emissão. O leque que se abre depois de 2015 mostra o que está em jogo: a diferença entre os cenários não é acadêmica, é a diferença entre desfechos de saúde distintos ao longo do século.])

O aquecimento não é assunto de outra disciplina que por acaso apareceu aqui: ele redistribui exposição. Onda de calor mata diretamente idosos e cardiopatas; temperatura mais alta amplia a área e a estação de vetores como o mosquito da dengue; seca e incêndio despejam material particulado sobre regiões inteiras. Cada um é um mecanismo de doença com fisiopatologia própria, agora operando em novas latitudes.

#figura-lateral("/figuras/patologia-ambiental/slide-18.png",
  lado: "right",
  largura-figura: 34%,
  texto: [A urbanização produz o segundo eixo. A população brasileira, majoritariamente rural até meados do século passado, inverteu-se em poucas décadas: hoje a maior parte vive em cidade, e uma parcela expressiva em regiões metropolitanas muito densas. Isso concentra no mesmo espaço as fontes de emissão — frota de veículos, indústria, resíduo — e as pessoas expostas a elas. E o resultado é mensurável: as três regiões metropolitanas anotadas no mapa ao lado marcam 16, 20 e 28 µg/m³ de material particulado, esta última São Paulo — de uma vez e meia a quase três vezes a diretriz da Organização Mundial da Saúde vigente à época, de 10 µg/m³ como média anual.],
  legenda: [Concentrações em regiões metropolitanas brasileiras contra o alvo da OMS.])

O número da diretriz merece um comentário que a PARTE III vai retomar. A Organização Mundial da Saúde recomendava, até 2021, média anual de 10 µg/m³ para o material particulado fino; naquele ano, com evidência de dano em concentrações mais baixas, endureceu a recomendação para 5 µg/m³. *Isso diz algo sobre a natureza do problema:* a diretriz é alvo de política pública, não limiar biológico de segurança — não existe degrau abaixo do qual o pulmão deixa de responder. Montado o quadro, o passo seguinte é abrir o que exatamente está nesse ar.

#parte-title("PARTE II — O ar poluído e o pulmão")

#subtopico("2.1 — Poluentes primários e secundários")

Ar poluído não é uma substância, é uma mistura — e a mistura tem origens identificáveis. Quatro grandes fontes dominam o cenário urbano brasileiro: a indústria, os veículos leves movidos a gasolina ou álcool, os veículos pesados movidos a diesel, e a queima de biomassa, que inclui desde a palha de cana até o incêndio florestal. Cada uma tem um perfil de emissão característico. A indústria libera sobretudo dióxido de enxofre e material particulado. Os veículos leves emitem particulado, monóxido de carbono, óxidos de nitrogênio, hidrocarbonetos e metais. Os pesados a diesel repetem essa lista com muito mais particulado e óxidos de nitrogênio. A biomassa acrescenta dióxido de carbono e uma carga alta de hidrocarbonetos e de partículas finas.

#figura-nebli("/figuras/patologia-ambiental/slide-19.png",
  largura: 72%,
  legenda: [As quatro fontes e seus perfis de emissão. Ao centro, a coluna do meio mostra o que a atmosfera *fabrica* a partir do que recebeu: ozônio, dióxido de nitrogênio, trióxido de enxofre, ácido sulfúrico e sulfato de amônio. Os raios indicam a energia solar que dispara essas reações — daí o nome poluição fotoquímica.])

Tudo o que sai direto da chaminé ou do escapamento é chamado de poluente primário. Mas a atmosfera não é um recipiente inerte: sob luz solar, os primários reagem entre si e produzem moléculas novas, os #termo-nota[poluentes secundários][poluentes não emitidos diretamente, mas formados na atmosfera pela reação entre poluentes primários, geralmente sob ação da luz solar]. É assim que óxidos de nitrogênio e hidrocarbonetos, sob radiação ultravioleta, geram ozônio de nível do solo; é assim que o dióxido de enxofre é oxidado a trióxido, hidrata-se a ácido sulfúrico e termina como sulfato de amônio particulado.

*O ponto fino é que "secundário" descreve a origem, não a importância.* O ozônio troposférico, que é secundário por definição, está entre os poluentes mais lesivos ao epitélio respiratório. E há uma armadilha de nomenclatura embutida aqui: o ozônio da estratosfera, que filtra a radiação ultravioleta e cuja perda é problema ambiental conhecido, é a mesma molécula que ao nível do solo é agressora inalada. Mesma fórmula, papéis opostos — o que muda é onde ela está.

#subtopico("2.2 — Os gases, um a um: solubilidade decide profundidade")

Entre os gases poluentes, o que determina onde cada um causa dano não é toxicidade intrínseca, e sim uma propriedade físico-química simples: a solubilidade em água. A via aérea é úmida do nariz aos bronquíolos, e um gás muito solúvel se dissolve na primeira mucosa que encontra. Isso o torna intensamente irritante em nariz, faringe e traqueia — e, ao mesmo tempo, faz com que pouco dele sobre para alcançar o alvéolo. Um gás pouco solúvel atravessa esse trecho sem ser retido e vai depositar sua agressão lá no fundo. *Vale fixar isso agora, porque contraria a intuição:* o gás que mais faz arder o nariz não é o que mais lesa o alvéolo, e sim justamente o que menos chega lá.

Aplicada aos quatro gases da aula, a regra organiza tudo. O *dióxido de enxofre* é muito solúvel: hidrata-se nas mucosas altas formando ácido sulfuroso e sulfúrico, e é o ácido que agride. Produz irritação de olhos e vias superiores e broncoconstrição, com efeito desproporcional em asmáticos, cuja via aérea já é hiper-reativa. O *ozônio* e o *dióxido de nitrogênio* são pouco solúveis: escapam da retenção proximal e alcançam bronquíolos terminais e alvéolos, onde agem como oxidantes diretos, gerando radicais livres que lesam a membrana das células epiteliais e disparam inflamação. Ozônio em concentração ambiental já reduz mensuravelmente a função pulmonar de adultos saudáveis fazendo exercício ao ar livre — a exposição sobe porque o volume ventilado sobe e porque a respiração passa a ser bucal, perdendo o filtro nasal.

O *monóxido de carbono* é um caso à parte, porque não lesa o pulmão: ele atravessa a barreira e vai agir no sangue. Sua afinidade pela hemoglobina é da ordem de duzentas vezes maior que a do oxigênio, de modo que mesmo concentrações baixas no ar deslocam o oxigênio do sítio de ligação e formam #termo-nota[carboxiemoglobina][hemoglobina ligada ao monóxido de carbono; não transporta oxigênio e ainda dificulta a liberação do oxigênio ligado às demais subunidades]. E há um segundo golpe, mais sutil e mais grave: a subunidade ocupada por monóxido aumenta a afinidade das subunidades vizinhas pelo oxigênio, deslocando a curva de dissociação para a esquerda — ou seja, o pouco oxigênio que ainda está sendo transportado é entregue com mais dificuldade ao tecido.

#atencao-box("Intoxicação por monóxido de carbono não dá cianose", [A confusão aqui é destruidora porque inverte o sinal de alarme. O aluno associa hipóxia a cianose e procura o paciente azulado; só que cianose exige hemoglobina *desoxigenada* acumulada, e na intoxicação por monóxido a hemoglobina não está desoxigenada — está ocupada por monóxido, formando um complexo de cor vermelho-viva. O paciente fica rosado, às vezes descrito como cor de cereja, enquanto os tecidos asfixiam. A oximetria de pulso comum também engana, porque não distingue carboxiemoglobina de oxiemoglobina e pode mostrar saturação normal. Diante de várias pessoas da mesma casa com cefaleia, náusea e confusão em ambiente fechado com aquecedor ou motor ligado, a ausência de cianose não afasta nada — ela é esperada.])

#subtopico("2.3 — Material particulado: o tamanho decide o destino")

Se um único conceito desta aula precisa ser levado inteiro, é este. Material particulado é o conjunto de partículas sólidas e líquidas suspensas no ar, e sua composição é heterogênea por natureza: nitratos, sulfatos, metais pesados e metais de transição, hidrocarbonetos policíclicos aromáticos adsorvidos na superfície. As fontes são naturais — solo, oceano, vulcão, floresta — e antropogênicas: transporte, indústria, combustão incompleta.

#figura-nebli("/figuras/patologia-ambiental/slide-20.png",
  largura: 60%,
  legenda: [Composição e fontes do material particulado. Repare que a lista de componentes é o que importa toxicologicamente: metais de transição catalisam formação de radicais, e hidrocarbonetos adsorvidos na superfície da partícula são carregados junto para dentro do pulmão.])

A classificação, no entanto, não é feita por composição — é feita por tamanho, e por um tamanho específico. O #termo-nota[diâmetro aerodinâmico][diâmetro de uma esfera de densidade unitária que sedimenta na mesma velocidade que a partícula real; incorpora forma e densidade, e é o que prevê onde a partícula vai depositar] não é o diâmetro geométrico medido ao microscópio, e sim o diâmetro de uma esfera de densidade unitária que sedimentaria na mesma velocidade. A escolha faz sentido justamente porque é o comportamento aerodinâmico, não a forma, que decide até onde a partícula viaja dentro da árvore respiratória. Daí as três faixas: PM10 reúne tudo abaixo de 10 µm, PM2,5 tudo abaixo de 2,5 µm, e ultrafinas o que está abaixo de 0,1 µm. *São faixas encaixadas, não categorias exclusivas* — toda PM2,5 é também PM10, do mesmo modo que toda ultrafina é também PM2,5.

#figura-nebli("/figuras/patologia-ambiental/slide-21.png",
  largura: 76%,
  legenda: [À esquerda, as faixas encaixadas: PM2,5 está contida em PM10, e as ultrafinas dentro de PM2,5. À direita, os três regimes físicos que decidem o destino — impactação inercial nas bifurcações proximais (10 a 5 µm), sedimentação gravitacional nas vias de pequeno calibre (5 a 1 µm) e difusão browniana no alvéolo (abaixo de 1 µm). A física, não a toxicidade, escolhe o andar do pulmão em que cada partícula pousa.])

Três mecanismos físicos distribuem as partículas, e cada um domina numa faixa. Partículas entre 10 e 5 µm carregam inércia suficiente para não conseguir fazer as curvas: em cada bifurcação brônquica, elas seguem reto e batem na parede — é a *impactação inercial*, que as retém nas vias aéreas de maior calibre, onde o tapete mucociliar as remove. Entre 5 e 1 µm o fluxo já é lento e o trajeto mais longo, e o que domina é a *sedimentação gravitacional*: a partícula simplesmente cai sobre a parede das vias de pequeno calibre. Abaixo de 1 µm a massa é tão pequena que a gravidade deixa de importar e o que move a partícula é o esbarrão das moléculas de gás ao redor — *difusão browniana* —, e é assim que ela alcança o alvéolo e ali se deposita por contato aleatório com a parede.

#atencao-box("A partícula maior não é a mais perigosa", [O raciocínio intuitivo é que mais massa significa mais dano, e ele leva o aluno a temer a poeira visível e a ignorar o que não se vê. O mecanismo diz o contrário. A partícula grande é barrada logo na entrada por impactação e removida pelo #termo-nota[clearance mucociliar][transporte contínuo do muco em direção à faringe pelo batimento ciliar, que remove partículas retidas nas vias aéreas condutoras] em horas. A partícula fina escapa desses dois filtros, alcança o alvéolo — onde não há cílio nenhum — e depende de macrófago para ser removida, o que leva muito mais tempo. E a ultrafina não para no alvéolo: seu tamanho permite atravessar a barreira alvéolo-capilar e alcançar a circulação sistêmica, com efeitos que a PARTE III vai desdobrar. *A regra a fixar é que quanto menor o diâmetro aerodinâmico, mais fundo a partícula chega e mais tempo ela permanece* — e é por isso que o indicador que melhor se correlaciona com mortalidade é PM2,5, não PM10.])

#subtopico("2.4 — Do macrófago à inflamação crônica")

Chegar ao alvéolo é só o começo da história. A partícula depositada é reconhecida e fagocitada pelo macrófago alveolar, a sentinela residente daquele espaço — e numa exposição pontual isso resolve o problema. O que muda tudo é a repetição. Com exposição diária, o macrófago fagocita mais do que consegue digerir, entra num estado de ativação persistente e passa ele próprio a ser fonte de mediadores e de espécies reativas de oxigênio, em vez de solução.

A partir daí a cadeia é reconhecível de qualquer capítulo de inflamação. O macrófago ativado libera interleucina-6, interleucina-8 e fator de necrose tumoral; a interleucina-8 recruta neutrófilos, que chegam ao espaço alveolar e degranulam, liberando proteases e mais oxidantes. O epitélio, agredido dos dois lados, responde com secreção aumentada de muco e com alteração do batimento ciliar, o que compromete justamente o mecanismo de limpeza que deveria remover o agente — um círculo que se fecha sobre si mesmo. A partícula ainda contribui por conta própria, e aqui entra o detalhe químico que o Robbins cobra: os *metais de transição* adsorvidos na sua superfície, sobretudo ferro, vanádio e níquel, catalisam a conversão de peróxido de hidrogênio em radical hidroxila pela reação de Fenton. O radical hidroxila é a espécie reativa mais agressiva da série, e ele é gerado dentro do tecido, a partir de um peróxido que a própria resposta inflamatória produziu.

*Ou seja:* a partícula não lesa por ocupar espaço. Ela lesa pelo que carrega e pelo que provoca. Mantida a exposição por anos, o infiltrado deixa de ser neutrofílico e passa a mononuclear, o interstício deposita colágeno, a pequena via aérea se estreita por remodelamento e a parede alveolar se rarefaz. O desfecho funcional dessa história tem nome: #sigla("DPOC", [doença pulmonar obstrutiva crônica — obstrução ao fluxo aéreo, pouco reversível, por inflamação crônica com remodelamento brônquico e destruição alveolar]). A ligação entre exposição inalatória crônica e obstrução ao fluxo aéreo não depende de cigarro — o cigarro é apenas a fonte mais concentrada e mais estudada.

#subtopico("2.5 — Biomassa e poluição intradomiciliar")

Existe uma imagem mental que atrapalha o entendimento deste tema, e é a de que poluição do ar é um problema de rua movimentada. Para uma fração enorme da população mundial, a maior exposição acontece dentro de casa, na cozinha, todos os dias, e é produzida pela própria família.

#figura-nebli("/figuras/patologia-ambiental/slide-32.png",
  largura: 58%,
  legenda: [Proporção da população que usa #termo-nota[biomassa][material orgânico usado como combustível — lenha, carvão vegetal, resíduo agrícola, esterco] como combustível doméstico. As faixas mais escuras cobrem o sul da Ásia e a África subsaariana, onde mais de três em cada quatro domicílios cozinham assim — e a exposição ocorre em ambiente fechado, várias horas por dia.])

A combustão da lenha em fogão sem exaustão adequada é incompleta por natureza, e a combustão incompleta é justamente a que gera mais material particulado fino, monóxido de carbono e hidrocarbonetos policíclicos aromáticos. As concentrações medidas dentro dessas casas superam com folga as da via pública de cidades grandes, e quem passa mais horas ali — mulheres cozinhando e crianças pequenas ao colo — recebe a maior dose.

#figura-nebli("/figuras/patologia-ambiental/slide-34.png",
  largura: 76%,
  legenda: [O fluxograma completo da lesão por biomassa, e ele serve de mapa para toda a PARTE. Gases irritantes produzem lacrimejamento, coriza e alteração mucociliar, que abre caminho para infecção respiratória. O material particulado consome antioxidantes, dispara reações oxidativas e eleva interleucina-6, interleucina-8 e granulócitos, convergindo para inflamação crônica, queda de função pulmonar e doença obstrutiva. À esquerda, a seta que mais importa: parte do particulado transpõe a barreira epitelial e produz efeitos sistêmicos.])

Repare que esse fluxograma não é exclusivo da lenha — ele é o mecanismo geral da PARTE II desenhado de uma vez. E o desfecho epidemiológico que ele produz é o achado que costuma surpreender: uma parcela expressiva dos casos de doença pulmonar obstrutiva crônica no mundo ocorre em mulheres que nunca fumaram um cigarro na vida. A obstrução não pergunta a origem da fumaça.

#mini-resumo[O ar poluído tem fontes identificáveis e fabrica poluentes secundários sob luz solar. Entre os gases, solubilidade decide profundidade; entre as partículas, o diâmetro aerodinâmico decide o andar do pulmão. No alvéolo, macrófago cronicamente ativado e metais de transição convergem em estresse oxidativo, inflamação crônica e doença obstrutiva — com ou sem cigarro.]

#parte-title("PARTE III — Além do pulmão: artéria, população e método")

#subtopico("3.1 — Do alvéolo à parede arterial")

A última seta do fluxograma anterior — a transposição da barreira epitelial e os efeitos sistêmicos — é a porta desta PARTE, e é também o achado que reorganiza o campo inteiro. Quando se pergunta qual o desfecho mais numeroso da exposição crônica ao material particulado, a resposta intuitiva é respiratória. A resposta correta é cardiovascular.

Há duas rotas que ligam o alvéolo ao vaso. A primeira é indireta e vale para partículas de qualquer tamanho: a inflamação instalada no pulmão libera mediadores na circulação, e esses mediadores recrutam órgãos distantes. A interleucina-6 alcança o fígado e dispara a resposta de fase aguda, com aumento de proteína C-reativa e de fibrinogênio; a medula óssea responde liberando mais leucócitos e mais plaquetas. O resultado é um estado inflamatório sistêmico de baixo grau, mantido enquanto durar a exposição. A segunda rota é direta e exclusiva das ultrafinas: partículas abaixo de 0,1 µm atravessam a barreira alvéolo-capilar e alcançam o sangue, podendo agir sobre o endotélio sem intermediário nenhum.

#figura-nebli("/figuras/patologia-ambiental/slide-30.png",
  largura: 72%,
  legenda: [O modelo que integra os três compartimentos. No pulmão, estresse oxidativo e inflamação reduzem a função pulmonar e levam a doença respiratória crônica. Fígado e medula traduzem isso em inflamação sistêmica. Nas artérias, disfunção endotelial e inflamação espessam a parede arterial e produzem doença cardiovascular. As setas verticais mostram que os três compartimentos conversam — a função pulmonar e a espessura da parede arterial são marcadores do mesmo processo contínuo, que vai da saúde à doença.])

O alvo vascular dessa inflamação é o endotélio, e vale precisar o que "disfunção endotelial" significa, porque o termo costuma ser usado vagamente. Não é obstrução nem estenose: é a perda das duas funções que o endotélio saudável exerce continuamente — a capacidade de vasodilatar em resposta à demanda, mediada por óxido nítrico, e a manutenção de uma superfície antitrombótica. Um endotélio disfuncional vasodilata mal, o que eleva a resistência periférica e a pressão arterial, e favorece adesão de plaquetas e leucócitos, o que prepara o terreno para trombose. Some-se a isso um efeito autonômico: a estimulação de receptores das vias aéreas por partículas altera o equilíbrio simpático-vagal, com aumento da frequência cardíaca e queda da variabilidade — um padrão associado a arritmia.

*O que torna essa cadeia clinicamente séria é a escala de tempo dupla.* Há o efeito crônico, que se acumula por anos e aparece como aterosclerose acelerada, e há o efeito agudo, mensurável em dias: em períodos de pico de poluição, sobem internações por infarto e por arritmia dentro da mesma semana.

#subtopico("3.2 — Aterosclerose acelerada: o que exatamente cresce na placa")

O elo entre poluição e aterosclerose foi demonstrado experimentalmente, e o desenho do experimento é instrutivo justamente porque separa o que aumenta do que não aumenta.

Animais mantidos em ar filtrado foram comparados a animais expostos a ar poluído, com análise da aorta. A exposição potencializou a oxidação do #sigla("LDL", [lipoproteína de baixa densidade — carrega colesterol do fígado para os tecidos e é a partícula que se acumula na íntima arterial]), aumentou a produção de autoanticorpos contra a LDL oxidada e aumentou a espessura da placa aterosclerótica. E aqui vem a parte que precisa ser lida com atenção: *a exposição não aumentou o teor lipídico da placa.*

#figura-nebli("/figuras/patologia-ambiental/slide-28.png",
  largura: 64%,
  legenda: [Aorta corada por Oil Red, que marca lipídio em vermelho, no experimento de exposição controlada. O que a comparação estabelece está listado ao lado: a poluição potencializa a oxidação da LDL, induz autoanticorpos anti-LDL oxidada e engrossa a placa — sem aumentar seu conteúdo de gordura. O que cresce é o componente inflamatório e matricial, não o lipídico.])

Essa dissociação é o achado, e ela diz como o mecanismo opera. A poluição não age fazendo o animal acumular mais gordura na parede; ela age *modificando quimicamente* o lipídio que já está lá. A LDL oxidada deixa de ser reconhecida pelo receptor normal e passa a ser capturada pelos receptores scavenger do macrófago, que não têm retroalimentação negativa — o macrófago engole indefinidamente e vira célula espumosa. Ao mesmo tempo, a oxidação cria neoepítopos que o sistema imune reconhece como estranhos, gerando os autoanticorpos detectados. O resultado é uma placa mais volumosa por conteúdo inflamatório e matricial, e a leitura clínica disso é direta: placa que cresce por inflamação, e não por lipídio, é placa com componente instável.

#clinica-box("Por que isso muda a conversa de consultório", [O paciente com risco cardiovascular recebe orientação sobre dieta, exercício, tabagismo e controle de pressão e de lipídios — todos fatores individuais e modificáveis pela própria pessoa. A exposição ambiental entra nessa lista com uma diferença incômoda: ela não é escolhida individualmente e não se corrige por conselho. O que a evidência sustenta é modesto no plano individual — evitar exercício ao ar livre em horário e local de pico de tráfego, cuidar da ventilação e da fonte de combustão dentro de casa, atenção redobrada em cardiopata, pneumopata, criança e gestante nos dias de qualidade de ar ruim. No plano populacional, porém, a alavanca é enorme: mudança de matriz energética, controle de emissão veicular e planejamento urbano deslocam a curva de risco de milhões de pessoas de uma vez, o que nenhuma consulta consegue fazer. É por isso que este capítulo aparece num curso de patologia e não só num de saúde pública — o mecanismo é individual, a intervenção eficaz é coletiva.])

#subtopico("3.3 — Dose-resposta sem limiar e o experimento da pandemia")

Falta responder à pergunta que sustenta tudo: como se sabe que a associação entre poluição e morte é causal, e não apenas coincidência estatística entre cidades que diferem em mil coisas.

O estudo que consolidou a resposta acompanhou cidades norte-americanas relacionando a concentração de material particulado fino à mortalidade ajustada por idade, sexo e raça. O resultado foi uma reta ascendente: quanto maior a concentração média de PM2,5, maior a mortalidade — e o gradiente se mantém ao longo de toda a faixa observada.

#figura-nebli("/figuras/patologia-ambiental/slide-24.png",
  largura: 64%,
  legenda: [Mortalidade ajustada por idade, sexo e raça em cidades dos Estados Unidos contra a concentração de material particulado fino. A relação é monotônica e não mostra um degrau abaixo do qual o efeito desapareça. As linhas verticais marcam o padrão regulatório americano e a diretriz da Organização Mundial da Saúde; à direita de ambas, muito acima da faixa das cidades americanas, a posição de São Paulo naquele período.])

Duas leituras saem daí. A primeira é *a ausência de limiar identificável*: não existe, na faixa estudada, uma concentração abaixo da qual a curva fica plana. Isso significa que reduzir a poluição de um nível já baixo para outro mais baixo ainda evita óbitos — foi exatamente esse tipo de evidência que levou a Organização Mundial da Saúde a endurecer sua diretriz de 10 para 5 µg/m³ em 2021. A segunda é a lógica de escala. Um deslocamento pequeno de risco individual, aplicado a uma população de milhões, produz um número grande de mortes evitáveis; e é essa aritmética, não o tamanho do efeito em cada pessoa, que coloca a poluição do ar entre os principais fatores de risco de mortalidade no mundo.

Sobre a causalidade propriamente dita, o argumento se apoia em quatro pilares que já foram construídos ao longo deste resumo: existe *gradiente dose-resposta*, existe *mecanismo plausível* e demonstrado em modelo experimental, existe *coerência* entre o que se vê na bancada e o que se vê na população, e existe *reversibilidade* — quando a exposição cai, o desfecho melhora.

#figura-nebli("/figuras/patologia-ambiental/slide-35.png",
  largura: 70%,
  legenda: [Coluna troposférica de dióxido de nitrogênio antes e durante as restrições de circulação de 2020, na Europa e na China. O poluente cai onde o tráfego parou, e volta quando ele retorna — a demonstração mais visível de que a fonte é identificável e a exposição é reversível.])

O último pilar ganhou, involuntariamente, sua demonstração mais nítida durante a pandemia. Com a circulação de veículos interrompida em grandes regiões, as concentrações de dióxido de nitrogênio despencaram em semanas e voltaram a subir quando o tráfego retornou. É um *experimento natural* — uma situação em que a exposição muda por um motivo alheio ao desfecho estudado, permitindo observar o efeito sem que ninguém a tenha manipulado deliberadamente. Vale a honestidade metodológica: durante aquele período mudaram simultaneamente circulação, atividade econômica, acesso a serviço de saúde e comportamento, de modo que atribuir variações de mortalidade apenas à queda de poluentes seria leviano. O que o episódio demonstra com solidez é o elo mais básico da cadeia — que a fonte é identificável, que a exposição responde rápido à intervenção, e que a reversibilidade não é hipótese teórica.

#conclusao-box[
  O princípio que unifica este capítulo é que o ambiente adoece por mecanismo, e o mecanismo se explica passo a passo como qualquer outro em patologia. Uma substância estranha é inalada, é depositada num ponto que a física decide, é processada por um metabolismo que tanto pode desativá-la quanto torná-la mais reativa, e produz lesão por uma via final comum — o estresse oxidativo e a inflamação que ele dispara. Nada aí é diferente, em natureza, do que acontece numa infecção ou numa intoxicação; o que muda é que a exposição é involuntária, contínua e compartilhada por populações inteiras.

  O mecanismo nuclear a levar embora tem duas metades encaixadas. A primeira é que *a física escolhe o alvo*: entre os gases, a solubilidade decide a profundidade, e o gás que mais irrita o nariz é justamente o que menos alcança o alvéolo; entre as partículas, o diâmetro aerodinâmico decide o andar do pulmão, com impactação inercial retendo as grandes nas bifurcações, sedimentação levando as médias às vias de pequeno calibre e difusão browniana depositando as finas no alvéolo — de onde as ultrafinas ainda atravessam para a circulação. A segunda metade é que *a biologia amplifica o dano*: o macrófago cronicamente ativado deixa de ser solução e vira fonte de mediadores, os metais de transição carregados pela partícula geram radical hidroxila pela reação de Fenton, interleucina-6 e interleucina-8 recrutam neutrófilo e mantêm inflamação, e o fígado e a medula convertem o processo pulmonar num estado inflamatório sistêmico. Daí sai o desfecho que contraria a intuição de todo mundo: o efeito mais numeroso da poluição do ar não é respiratório, é cardiovascular, por disfunção endotelial, aterosclerose acelerada e trombose. A clínica retomada fecha nos mesmos trilhos — a doença pulmonar obstrutiva crônica de uma mulher que nunca fumou e cozinhou a vida inteira em fogão a lenha, a intoxicação por monóxido de carbono num paciente rosado e sem cianose, o infarto que aumenta na semana seguinte ao pico de particulado.

  A projeção adiante é natural. Este capítulo abriu, sem esgotar, o bloco das doenças por agentes ambientais e nutricionais: o tabagismo, que é a mesma toxicologia inalatória em dose concentrada e voluntária; o álcool e os fármacos, que percorrem exatamente as fases I e II que estudamos aqui; a exposição ocupacional a poeiras minerais, cujas pneumoconioses são a versão profissional do que vimos no alvéolo; e os metais pesados, com o chumbo à frente. Todos eles reaproveitam integralmente a caixa de ferramentas montada aqui — dose e tempo, bioativação, estresse oxidativo, inflamação crônica, e uma curva dose-resposta que raramente tem o limiar seguro que gostaríamos de encontrar.
]
