#import "../typst-template/nebli_v2_apostila.typ": *

#discursiva("Q1",
  [Explique por que a célula precisa fracionar a oxidação da glicose em uma cadeia de transferências de elétrons em vez de realizar uma combustão direta em uma única reação. Use o argumento termodinâmico e o argumento prático do bombeamento de prótons.],
  [A oxidação completa de 1 mol de glicose libera 2.870 kJ. Se essa energia fosse liberada de uma vez só, viraria calor catastrófico — proteínas desnaturariam, lipídeos derreteriam. A célula precisa de algo que enzimas conseguem usar como trabalho: cada bombeamento de próton através de uma membrana custa cerca de 20 kJ/mol. A cadeia respiratória fraciona a queda de potencial total (NADH a O₂, ΔG ≈ -220 kJ/mol) em degraus de ~20 kJ cada — exatamente o tamanho que cabe num bombeamento de H⁺. O gradiente acumulado vira ATP via ATP sintase. Sem fracionamento, sem trabalho útil; sem fracionamento, fogo intracelular.])

#discursiva("Q2",
  [Compare quantitativamente o saldo de ATP gerado por NADH versus FADH₂ na cadeia respiratória humana, justificando a diferença a partir do número de prótons bombeados em cada complexo da cadeia.],
  [NADH entra no Complexo I, que bombeia 4 H⁺ por par de elétrons. Os elétrons descem para CoQ → Complexo III (bombeia 4 H⁺ via ciclo Q) → cit c → Complexo IV (bombeia 2 H⁺). Total: 10 H⁺ por NADH. FADH₂ (succinato) entra direto na CoQ pelo Complexo II — que NÃO bombeia prótons. Daí passa pelo Complexo III (4 H⁺) e Complexo IV (2 H⁺). Total: 6 H⁺ por FADH₂. Como cada ATP exige ~4 H⁺ (3 H⁺ para a sintase + 1 H⁺ para transporte ADP/ATP/Pi), o P/O é 10÷4 ≈ 2,5 para NADH e 6÷4 ≈ 1,5 para FADH₂. Diferença de 1 ATP por equivalente redutor.])

#discursiva("Q3",
  [Paciente intoxicado por cianeto chega à emergência com sangue venoso vermelho-cereja, taquicardia, taquipneia, rebaixamento de consciência. Saturação de O₂ medida = 99%. Explique mecanisticamente por que cianeto causa colapso energético apesar da saturação preservada, e descreva o tratamento principal.],
  [Cianeto liga-se ao Fe do citocromo a3 do Complexo IV com afinidade superior à do O₂, bloqueando a transferência final de elétrons. Sem aceptor terminal, toda a cadeia para; o gradiente colapsa; ATP cai a zero em segundos. O oxigênio chega via hemoglobina (sat 99%) mas a célula não consegue usá-lo — quadro de hipóxia histotóxica. O sangue venoso fica vermelho-cereja porque o O₂ não é consumido pelos tecidos. Tratamento: nitrito de sódio gera metemoglobina (que sequestra cianeto livre), seguida de tiossulfato que acelera a conversão a tiocianato eliminado pelo rim. Hidroxicobalamina (vitamina B12a) é alternativa moderna — liga-se ao cianeto formando cianocobalamina (B12) atóxica eliminada na urina.])

#discursiva("Q4",
  [Em oximetria com mitocôndrias isoladas em estado 4 (sem ADP, gradiente máximo, consumo basal), adiciona-se primeiro oligomicina e depois DNP. Descreva o que acontece com o consumo de O₂ em cada momento e justifique mecanisticamente.],
  [Estado 4: cadeia rodando devagar porque o gradiente alto retroinibe os complexos. Adição de oligomicina: liga-se ao F₀ da ATP sintase impedindo passagem de prótons; gradiente permanece alto, complexos continuam retroinibidos, consumo de O₂ NÃO muda significativamente (já estava baixo). Adição subsequente de DNP: o desacoplador lipossolúvel atravessa a membrana carregando H⁺ do espaço intermembrana para a matriz, dissipando o gradiente. A retroinibição é removida; os complexos voltam a bombear no máximo tentando recompor o gradiente que vaza. Consumo de O₂ aumenta drasticamente. Mas como F₀ está bloqueado por oligomicina E o gradiente vaza por DNP, nenhum ATP é sintetizado — toda a energia oxidativa vira calor.])

#discursiva("Q5",
  [Criança de 6 anos com encefalomiopatia tem biópsia muscular com fibras vermelhas rasgadas. Exames mostram redução de 60% da atividade do Complexo I, com Complexos II, III, IV preservados. Lactato sérico elevado. Descreva: (a) por que o lactato está elevado; (b) por que cérebro e músculo esquelético são especialmente afetados; (c) duas estratégias terapêuticas disponíveis e seus mecanismos.],
  [a) NADH não entra na cadeia em ritmo normal (Complexo I deficiente); piruvato não é oxidado eficientemente, é desviado para lactato pela LDH (que regenera NAD⁺ para manter a glicólise rodando) — acúmulo de lactato é o resultado. b) Cérebro consome ~20% do O₂ total apesar de ser 2% da massa corporal — depende quase exclusivamente da fosforilação oxidativa. Músculo esquelético em demanda alta também tem dependência mitocondrial intensa. Tecidos com baixa demanda toleram melhor a deficiência. c) Suplementação de CoQ10 (pode reforçar transferência de elétrons em rotas residuais via Complexo II), riboflavina (precursor do FMN/FAD), e tiamina (cofator da piruvato desidrogenase) — todas com evidência marginal em casos selecionados. Não há terapia curativa; transplante mitocondrial e edição gênica do mtDNA estão em pesquisa pré-clínica.])
