#import "../typst-template/nebli_v2_apostila.typ": *

#intro-box[
  Quase dois terços do seu peso são água, e essa água não fica parada: ela atravessa a parede dos capilares para fora, volta para dentro, e o pouco que sobra é recolhido por um sistema de drenagem que a devolve ao sangue. Esse vaivém acontece o tempo todo, em todo capilar do corpo, e é tão bem equilibrado que passa despercebido. Edema é o nome que damos ao momento em que esse equilíbrio se rompe e o líquido fica onde não deveria — encharcando o tecido entre as células ou enchendo uma cavidade do corpo. Congestão é um problema aparentado, mas de outro compartimento: é o sangue que não consegue sair de um órgão e se acumula dentro dos vasos. Este resumo persegue os dois por três caminhos. Primeiro, o espaço onde a água mora e as quatro forças que decidem para que lado ela vai. Depois, os cinco mecanismos capazes de quebrar esse equilíbrio, cada um com sua doença típica. Por fim, o que o patologista vê quando abre o corpo e o que o líquido acumulado faz de mal a quem o carrega. A régua de fundo é uma só: edema nunca é uma doença, é a assinatura visível de qual dessas forças saiu da faixa.
]

#parte-title("PARTE I — O interstício, as forças de Starling e o vocabulário das coleções", primeira: true)

#subtopico("1.1 — Onde a água do corpo mora")

A água corresponde a cerca de 60% do peso de um adulto, e ela está repartida em compartimentos de tamanhos muito desiguais. Num homem de 70 kg são aproximadamente 42 litros de água no total. Dois terços disso — cerca de 28 litros — estão *dentro* das células. O terço restante, uns 14 litros, é o líquido extracelular, e é aqui que a distribuição surpreende: só uns 3 litros circulam como plasma dentro dos vasos; todo o resto, mais de 10 litros, ocupa o espaço entre as células, o interstício. O interstício não é um vazio nem uma poça: é um gel de matriz extracelular, feito de colágeno e de glicosaminoglicanos que prendem água, atravessado pelos capilares de um lado e pelos vasos linfáticos do outro.

Guardar essa proporção muda a forma de pensar o problema. *O compartimento intersticial é três vezes maior que o plasma*, o que significa que ele funciona como um reservatório generoso: dá para transferir vários litros do sangue para o interstício antes que qualquer coisa fique clinicamente visível. É por isso que um paciente pode ganhar dois, três quilos de água retida sem que ninguém repare no inchaço — o interstício absorve em silêncio até saturar. Quando o edema finalmente aparece ao olho, já se acumularam alguns litros.

Com esse mapa na cabeça, a definição fica precisa. Edema é o acúmulo anormal de líquido no *interstício* ou nas *cavidades* revestidas por serosa. Não é excesso de água dentro da célula — esse é outro fenômeno, governado por gradientes osmóticos, e recebe outro nome. A distinção parece detalhe e não é: as duas situações têm causas diferentes, morfologias diferentes e condutas diferentes.

#subtopico("1.2 — As quatro forças e o dreno que fecha a conta")

Pense num capilar como uma mangueira de parede porosa correndo dentro de uma esponja encharcada. Duas forças opostas disputam a água nessa parede, e uma terceira estrutura recolhe o que sobrar. A primeira força é a *pressão hidrostática* do sangue dentro do capilar: é o sangue empurrando líquido para fora pelos poros da parede, e ela é mais alta na extremidade arteriolar (perto de 32 a 35 mmHg) e cai ao longo do trajeto até a extremidade venular (perto de 12 a 15 mmHg), porque a resistência do próprio capilar consome pressão. A segunda força é a *pressão coloidosmótica*, ou oncótica, do plasma — em torno de 25 a 28 mmHg e praticamente constante ao longo do capilar. Ela existe porque as proteínas plasmáticas, sobretudo a albumina, são grandes demais para atravessar a parede e ficam retidas dentro do vaso, puxando água de volta por osmose. As duas restantes são os espelhos dessas: a pressão hidrostática do próprio líquido intersticial, que empurra de volta para dentro, e a pressão oncótica do interstício, exercida pela pouca proteína que escapou, que puxa para fora. Nos tecidos normais, essas duas últimas são pequenas.

O resultado dessa disputa é elegante. Na entrada arteriolar, a hidrostática vence a oncótica e o líquido é filtrado para fora. Na saída venular, a hidrostática já caiu abaixo da oncótica e a maior parte desse líquido é reabsorvida. Só que a conta não fecha exatamente: somando todos os capilares do corpo, filtra-se ao redor de 20 litros por dia e reabsorve-se ao redor de 17. *Sobram uns 2 a 3 litros de líquido por dia no interstício* — e é exatamente esse excedente que os vasos linfáticos recolhem. O linfático começa em fundo cego dentro do tecido, com paredes tão frouxas que aceitam água e proteína grandes, coleta o excedente e o devolve ao sangue pelas veias grandes da base do pescoço, à esquerda pelo ducto torácico.

#figura-nebli("/figuras/patologia-edema-congestao/slide-04.png",
  largura: 72%,
  legenda: [O leito capilar visto de lado: a pressão hidrostática empurra líquido para fora (seta vermelha, extremidade arterial) e a pressão coloidosmótica do plasma puxa de volta (seta azul, extremidade venosa). Acima, a rede linfática de fundo cego recolhe o excedente e o conduz ao ducto torácico. Três estruturas, um só balanço.])

Esse terceiro elemento é o que costuma passar batido, e ele é decisivo. *O linfático não é uma via acessória — é o terceiro termo da equação.* Além de carregar volume, ele remove do interstício a pouca proteína que vazou do plasma, e isso é o que mantém a pressão oncótica intersticial baixa, preservando o gradiente que puxa água de volta para o vaso. Um sistema linfático competente é capaz de aumentar bastante seu fluxo quando a filtração sobe, e essa margem de manobra é a razão pela qual pequenos aumentos de pressão hidrostática não produzem edema nenhum. O edema aparece quando a filtração excede essa capacidade de reserva, ou quando o próprio dreno é obstruído.

#mini-resumo[Hidrostática empurra para fora, oncótica puxa para dentro; sobra um excedente diário de 2 a 3 litros que a linfa devolve ao sangue. Edema é o que acontece quando a filtração ultrapassa a capacidade desse dreno — ou quando o dreno é bloqueado.]

#subtopico("1.3 — Transudato e exsudato: a parede do vaso decide")

Todo o raciocínio acima presume uma coisa que é fácil esquecer: a parede do capilar está íntegra e funcionando como peneira seletiva, deixando passar água e sais pequenos e retendo proteína. É essa seletividade que produz duas qualidades muito diferentes de líquido acumulado — e diferenciá-las é diferenciar o mecanismo por trás.

Quando o desequilíbrio é puramente de forças e a peneira continua intacta, o que sai é um ultrafiltrado do plasma: água e eletrólitos, com pouquíssima proteína e praticamente nenhuma célula. Chamamos isso de #termo-nota[transudato][líquido de edema pobre em proteína e em células, com densidade abaixo de 1,012, produzido por desequilíbrio das forças de Starling com endotélio íntegro] — líquido claro, quase incolor, com densidade abaixo de 1,012. É o líquido da insuficiência cardíaca, da síndrome nefrótica, da cirrose. Quando, em vez disso, a própria parede se torna permeável, a peneira deixa passar o que antes retinha: proteínas grandes, fibrinogênio, e junto vêm leucócitos. O resultado é o #termo-nota[exsudato][líquido de edema rico em proteína e em células inflamatórias, com densidade acima de 1,020, produzido por aumento da permeabilidade vascular], líquido turvo, denso, com densidade acima de 1,020. É o líquido da inflamação e das neoplasias.

*O ponto fino é que a pressão, por maior que seja, não fabrica exsudato.* Uma insuficiência cardíaca gravíssima pode empurrar litros de líquido para a pleura e ainda assim aquele líquido será pobre em proteína, porque a barreira continua fazendo seu trabalho de retenção. Inverta o raciocínio e ele fica ainda mais útil: encontrar líquido rico em proteína numa cavidade é encontrar evidência de que o endotélio foi comprometido, o que aponta imediatamente para inflamação, infecção ou tumor — e não para falência de bomba. Na prática do laboratório, a separação é refinada comparando o líquido com o sangue do próprio paciente: uma razão entre a proteína do líquido e a proteína do plasma acima de 0,5, ou uma desidrogenase láctica desproporcionalmente alta no líquido, empurra o diagnóstico para o lado do exsudato mesmo em casos limítrofes.

#confusao-prevista(
  titulo: "Transudato não é 'edema leve' e exsudato não é 'edema grave'",
  aluno_acha: [aluno acha que os dois termos medem intensidade — pouco líquido seria transudato, muito líquido seria exsudato],
  mecanismo: [os dois nomes descrevem a *composição* do líquido, e a composição denuncia o *mecanismo*, não o volume. Um transudato pode encher três litros de cavidade pleural numa insuficiência cardíaca descompensada e continuar sendo transudato, porque a parede do capilar nunca deixou a proteína passar. Um exsudato pode ser um dedal de líquido numa pleurite inicial e já ser exsudato, porque a permeabilidade aumentou. Volume mede gravidade; composição revela o porquê.],
)

#subtopico("1.4 — Hiperemia, congestão e o nome de cada coleção")

Até aqui, o assunto foi o líquido que sai do vaso. A congestão trata do problema oposto: sangue que fica retido *dentro* do vaso. E ela vem sempre em par com um fenômeno vizinho, do qual precisa ser separada com cuidado, porque os dois deixam o tecido vermelho e aumentado de volume.

A #termo-nota[hiperemia][aumento local do volume de sangue por dilatação arteriolar ativa, com influxo aumentado de sangue oxigenado] é um processo *ativo*: as arteríolas se dilatam, mais sangue entra no leito, e como esse sangue vem do lado arterial, ele é rico em oxigênio. O tecido fica vermelho vivo — é o rubor do músculo em exercício, é o eritema ao redor de uma ferida inflamada, é o olho vermelho de uma conjuntivite. A #termo-nota[congestão][acúmulo passivo de sangue num tecido por dificuldade de drenagem venosa, com sangue desoxigenado e coloração azulada] é um processo *passivo*: o sangue não consegue sair, seja porque uma veia está obstruída, seja porque o coração direito não dá conta de recebê-lo. Como esse sangue está parado no lado venoso, sua hemoglobina já entregou o oxigênio, e a cor que aparece é azulada, cianótica. A distinção não é de grau, é de sentido do problema — numa entra sangue demais pela porta da frente, na outra sai sangue de menos pela porta dos fundos.

#figura-nebli("/figuras/patologia-edema-congestao/slide-03.png",
  largura: 60%,
  legenda: [Três faces do mesmo capítulo. À esquerda, o glomérulo ao microscópio, órgão-chave nos edemas de origem renal. À direita, hiperemia conjuntival — vermelho vivo, arterial, ativo. Abaixo, o membro inferior edemaciado, o achado que abre o raciocínio à beira do leito.])

Essa diferença tem consequência morfológica direta, e é aqui que a congestão deixa de ser um detalhe de cor. Sangue parado é sangue que não traz oxigênio novo. Quando a congestão se arrasta por meses ou anos, o tecido servido por aqueles capilares vive em hipóxia crônica: as células mais distantes da chegada arterial degeneram e morrem, capilares distendidos se rompem e deixam pequenos focos de hemorragia, os macrófagos fagocitam essas hemácias extravasadas e acumulam pigmento de ferro, e a longo prazo o interstício responde com fibrose. Um órgão cronicamente congesto acaba menor, mais firme e mudado de cor — e nada disso é reversível pelo simples esvaziamento do sangue.

Falta ainda o vocabulário das coleções, que é o que o slide desta aula cobra de saída. Quando o líquido de edema se acumula numa cavidade revestida por serosa, ele ganha nome próprio conforme a cavidade: na pleura é *hidrotórax*, no saco pericárdico é *hidropericárdio*, e na cavidade peritoneal é hidroperitônio, quase sempre chamado de #termo-nota[ascite][acúmulo de líquido na cavidade peritoneal; a causa mais comum é a hipertensão portal da cirrose]. Quando o edema subcutâneo é grave e generalizado, deixando o corpo inteiro intumescido, o nome é #termo-nota[anasarca][edema subcutâneo grave e generalizado, típico de estados avançados de retenção como a insuficiência cardíaca terminal e a síndrome nefrótica]. Note que esses termos descrevem *onde* o líquido está, não *por que* ele chegou lá — o mecanismo continua sendo uma das cinco alavancas que a próxima PARTE vai abrir uma a uma.

#figura-nebli("/figuras/patologia-edema-congestao/slide-07.png",
  largura: 66%,
  legenda: [Três apresentações do mesmo processo: edema assimétrico de membro inferior (à esquerda o membro comprometido, à direita o normal), abdome tenso por ascite volumosa numa criança, e, à direita, o líquido citrino acumulado na cavidade pleural visto na autópsia — hidrotórax.])

#mini-resumo[Hiperemia é ativa, arteriolar e vermelho-viva; congestão é passiva, venosa e cianótica, e quando crônica leva a hipóxia, hemorragia, pigmento de ferro e fibrose. O líquido acumulado em cavidade se chama hidrotórax, hidropericárdio ou ascite conforme o lugar; anasarca é o edema generalizado do subcutâneo.]

Fechada a mecânica, o que resta é perguntar quais defeitos concretos conseguem desequilibrá-la. São exatamente cinco, e cada um deles corresponde a mexer num dos termos da equação que acabamos de montar.

#parte-title("PARTE II — Os cinco mecanismos que produzem edema")

#subtopico("2.1 — Pressão hidrostática aumentada: quando o sangue não escoa")

O primeiro mecanismo é o mais intuitivo dos cinco: se a pressão dentro do capilar sobe, a força que empurra líquido para fora vence com folga a que puxa de volta, e a filtração passa a superar a capacidade do dreno linfático. A pressão capilar sobe quase sempre pelo mesmo motivo — dificuldade de escoamento no lado *venoso*, que se transmite retrogradamente até o capilar. E aqui o alcance do problema depende de onde está o obstáculo.

Quando a obstrução é local, o edema é local. Uma trombose venosa profunda de membro inferior bloqueia o retorno daquela perna e só daquela perna: o membro incha, fica tenso, e o outro permanece normal — foi exatamente isso que a imagem de abertura da PARTE anterior mostrou. A mesma lógica explica o edema de um braço comprimido por um tumor mediastinal ou o inchaço das pernas de quem passa horas de pé sem contração muscular, quando a coluna de sangue venoso pesa sobre os capilares dos tornozelos. Nenhum desses casos tem qualquer coisa a ver com o corpo inteiro.

Quando a obstrução é sistêmica, o edema é generalizado — e o exemplo canônico é a insuficiência cardíaca congestiva. Aqui a cadeia é mais rica do que parece, e vale desmontá-la devagar. O ventrículo falho ejeta menos sangue por batimento, e o sangue que não foi ejetado se acumula atrás dele, elevando a pressão de enchimento e, retrogradamente, a pressão venosa e capilar — esse é o braço direto, mecânico, da história. Só que existe um segundo braço, e ele é o que transforma um problema de bomba num problema de volume corporal inteiro. Com menos sangue sendo lançado por minuto, a perfusão renal cai; o rim interpreta a queda de fluxo como hipovolemia e faz o que faria se o corpo tivesse perdido sangue: libera renina, ativa a cascata que termina em angiotensina II e aldosterona, e passa a reter sódio avidamente — e água atrás do sódio. Esse é o #sigla("SRAA", [sistema renina-angiotensina-aldosterona — cascata renal que retém sódio e água quando o rim detecta queda de perfusão]).

#figura-nebli("/figuras/patologia-edema-congestao/slide-08.png",
  largura: 74%,
  legenda: [O círculo vicioso da insuficiência cardíaca. A queda do volume ejetado ativa o SRAA, que retém sódio e água; o volume circulante aumentado eleva a pressão de enchimento ventricular e sobrecarrega justamente o miocárdio que já falhava — remodelamento, maior consumo de oxigênio e mais disfunção. O edema é a face visível desse anel.])

*O que amarra a cadeia é o círculo vicioso.* O volume retido aumenta o retorno venoso e, num coração sadio, isso melhoraria o débito. Num coração falho, aumenta a pressão de enchimento sem melhorar a ejeção — de modo que a resposta renal, correta em si mesma, só agrava a congestão que a disparou. É por isso que o tratamento da insuficiência cardíaca ataca justamente esses dois pontos: restringe sal, elimina volume com diurético e bloqueia farmacologicamente a cascata da renina. O organismo tem um freio próprio para isso, os peptídeos natriuréticos liberados pelo átrio e pelo ventrículo distendidos, que promovem excreção de sódio e vasodilatação; na insuficiência avançada esse freio existe mas é insuficiente para vencer a ativação do SRAA — e a concentração sanguínea desses peptídeos, justamente por subir com a distensão das câmaras, virou marcador laboratorial de descompensação.

Vale ainda separar as duas metades do coração, porque elas produzem quadros diferentes. Quando falha o ventrículo *esquerdo*, o sangue represa no território que o precede, que é a circulação pulmonar: o resultado é congestão pulmonar e edema de pulmão. Quando falha o ventrículo *direito*, o represamento acontece nas veias sistêmicas: o resultado é edema de membros inferiores, ingurgitamento das jugulares, fígado congesto e, com o tempo, ascite. Como a causa mais comum de falência direita é a própria falência esquerda de longa data, o quadro avançado combina os dois.

#subtopico("2.2 — Pressão oncótica reduzida: o paradoxo do vaso vazio")

O segundo mecanismo mexe no outro termo da equação, e ele produz a situação mais contraintuitiva do capítulo: um paciente encharcado de líquido cujo compartimento vascular está, na prática, *vazio*.

A albumina responde por cerca de metade da proteína do plasma e pela maior parte da pressão oncótica, por ser a mais abundante em número de moléculas. Quando a albumina plasmática cai, a força que segura água dentro do vaso enfraquece, e o líquido escoa para o interstício em todos os leitos capilares ao mesmo tempo — daí o edema ser generalizado. Há quatro maneiras de perder albumina do plasma. A mais expressiva é a *perda renal*: na síndrome nefrótica, a barreira de filtração do glomérulo — endotélio fenestrado, membrana basal e os pés interdigitados dos podócitos — é danificada e deixa escapar proteína na urina, tipicamente mais de 3,5 gramas por dia. A segunda é a *síntese reduzida*, que acontece na doença hepática difusa, já que o hepatócito é a fábrica de albumina do corpo. A terceira é a *carência de matéria-prima*, na desnutrição proteica grave. A quarta é a *perda intestinal*, nas enteropatias que perdem proteína pela mucosa.

#figura-nebli("/figuras/patologia-edema-congestao/slide-10.png",
  largura: 74%,
  legenda: [A síndrome nefrótica por dentro. A proteinúria age por duas frentes: gera hipoalbuminemia (à direita), que derruba a pressão oncótica, e provoca lesão tubulointersticial e glomerular (à esquerda), que aumenta a reabsorção de sódio no próprio túbulo. As duas retenções — primária e secundária — convergem para o mesmo desfecho: os mecanismos de remoção de líquido são sobrepujados e o edema aparece.])

Independentemente da porta de saída, o desfecho segue o mesmo trilho e é aqui que está o nó do subtópico. Com albumina baixa, o líquido escapa do vaso; com líquido escapando, o volume que efetivamente circula pelas artérias cai; com esse volume caindo, o rim de novo interpreta hipovolemia e liga o SRAA, retendo sódio e água. *Só que o líquido retido não tem como ficar dentro do vaso* — falta exatamente a proteína que o seguraria lá. Ele atravessa a parede e vai reforçar o edema. O resultado é um paciente que retém sal e água sem parar, engorda de líquido, e mesmo assim mantém o compartimento arterial subenchido. Essa é a razão de o edema por hipoalbuminemia ser tão resistente ao diurético isolado: sem corrigir a perda de proteína, cada litro drenado é reposto pelo mesmo mecanismo.

#clinica-box("Síndrome nefrótica", [Uma criança amanhece com as pálpebras inchadas, e nos dias seguintes o edema desce e generaliza. O exame de urina mostra proteinúria maciça, acima de 3,5 g em 24 horas, e o sangue mostra albumina baixa. A cadeia é direta: lesão dos podócitos → barreira de filtração permeável a proteína → albumina perdida na urina → pressão oncótica do plasma reduzida → líquido escapa para o interstício → volume arterial efetivo cai → SRAA ativado → retenção de sódio e água que realimenta o edema. Duas consequências vêm junto e não são detalhe: o fígado responde à perda proteica aumentando a síntese de lipoproteínas, o que produz a hiperlipidemia característica, e a perda urinária inclui também imunoglobulinas e proteínas anticoagulantes, deixando o paciente mais suscetível a infecção e a trombose. O tratamento persegue a causa glomerular; o diurético isolado alivia sem resolver.])

#subtopico("2.3 — Obstrução linfática: o dreno entupido")

Se o interstício é uma esponja e a linfa é o ralo por onde escorre o excedente, o terceiro mecanismo é o ralo entupido. Note que aqui nenhuma das forças de Starling mudou: a filtração continua exatamente igual à de uma pessoa saudável. O que falha é a remoção daquele excedente fisiológico de 2 a 3 litros diários — e como o excedente não some, ele se acumula. É um edema que se instala devagar, ao longo de meses, e que tem uma característica química própria: como o linfático era também quem removia a proteína escapada, o líquido represado é *rico em proteína*.

Essa riqueza proteica muda o comportamento do tecido. Proteína no interstício estimula fibroblastos e deposição de colágeno, de modo que o #termo-nota[linfedema][edema por obstrução da drenagem linfática, rico em proteína, de instalação lenta e evolução fibrosante, tipicamente sem sinal do cacifo] crônico endurece: o membro fica volumoso, firme, com pele espessada, e deixa de afundar quando se aperta com o dedo — comportamento oposto ao do edema mole da insuficiência cardíaca. As causas clássicas percorrem a patologia inteira. Na filariose, o verme adulto se aloja nos linfáticos e linfonodos inguinais, provoca inflamação e fibrose, e a obstrução crônica de todo o membro inferior e da genitália externa chega ao extremo conhecido como elefantíase. No câncer de mama, o esvaziamento cirúrgico dos linfonodos axilares somado à irradiação da região destrói as vias de drenagem do braço, e o linfedema do membro superior é uma complicação frequente do tratamento. Quando o próprio tumor infiltra os linfáticos da derme, a pele fica edemaciada mas permanece ancorada nos ligamentos que a prendem à fáscia profunda, e essas âncoras criam pequenas depressões pontuais no meio do inchaço — o aspecto de casca de laranja descrito na mama.

#subtopico("2.4 — Retenção primária de sódio e água: quando o rim é a causa, não a resposta")

Nos dois primeiros mecanismos, a retenção de sódio pelo rim entrou como *consequência* — o rim respondendo a uma queda de perfusão real ou aparente. O quarto mecanismo inverte esse papel: aqui é o rim que, doente, retém sódio de saída, e a expansão de volume que se segue é a causa do edema, não a sua tentativa de compensação.

Isso acontece de forma exemplar na glomerulonefrite aguda, sobretudo a que se instala uma a duas semanas depois de uma faringite estreptocócica. O glomérulo inflamado filtra menos, a excreção de sódio despenca, e o sódio retido arrasta água por osmose. A expansão do volume produz o edema por dois caminhos ao mesmo tempo, e é essa dupla ação que dá peso ao mecanismo: o volume aumentado eleva a pressão hidrostática dentro dos capilares, e o mesmo volume *dilui* as proteínas do plasma, reduzindo a pressão oncótica. Os dois lados da equação de Starling são empurrados na mesma direção. A insuficiência renal aguda de qualquer causa produz o mesmo efeito pela mesma via.

O padrão de distribuição desse edema tem um detalhe anatômico que o torna reconhecível: ele costuma começar pelas pálpebras e ao redor dos olhos. A explicação é que o tecido conjuntivo periorbital é excepcionalmente frouxo, com pouca resistência mecânica à expansão, de modo que é o primeiro lugar a acomodar líquido quando ele sobra no corpo inteiro. Isso contrasta com o edema da insuficiência cardíaca, que obedece à gravidade e se acumula onde a coluna de sangue pesa mais — tornozelos em quem anda, região sacral em quem está acamado.

#subtopico("2.5 — Permeabilidade aumentada: a peneira rasgada")

Os quatro mecanismos anteriores compartilham uma premissa: a parede do capilar continuou íntegra, e o líquido que saiu foi um ultrafiltrado pobre em proteína. O quinto mecanismo quebra essa premissa — e por isso é o único que produz exsudato.

Há mais de uma maneira de tornar um capilar permeável, e elas diferem em reversibilidade. A mais comum e mais suave é a *retração endotelial*: mediadores liberados na inflamação, especialmente a histamina dos mastócitos, a bradicinina e os leucotrienos, ligam-se a receptores da célula endotelial e disparam contração do seu citoesqueleto. A célula encolhe, as junções entre células vizinhas se afastam e abrem-se fendas — sobretudo nas vênulas pós-capilares — por onde plasma inteiro escapa. É um fenômeno rápido, começa em minutos e costuma ser reversível quando o mediador some. A segunda maneira é a *lesão direta* do endotélio, por queimadura, toxina bacteriana, radiação ou infecção grave: aqui a célula não retrai, ela morre ou descola, e o vazamento é prolongado. A terceira é *mediada por leucócitos*: neutrófilos aderidos ao endotélio liberam enzimas proteolíticas e espécies reativas de oxigênio que danificam a parede a partir de dentro do vaso. Uma variação instrutiva desse mecanismo é o angioedema hereditário, em que a falta de um inibidor de proteases plasmáticas permite acúmulo de bradicinina e crises de edema súbito de face e vias aéreas — o mesmo mediador de sempre, agora sem freio.

#figura-nebli("/figuras/patologia-edema-congestao/slide-13.png",
  largura: 76%,
  legenda: [O mecanismo levado ao extremo no pulmão. Um agente lesivo ativa macrófagos alveolares, que liberam fator de necrose tumoral e interleucinas; neutrófilos são recrutados e, ao degranular, liberam proteases, leucotrienos e fator ativador de plaquetas que lesam o endotélio e o pneumócito. Com a barreira alvéolo-capilar destruída (à direita, alvéolo normal contra alvéolo lesado), plasma rico em proteína inunda o alvéolo e a fibrina precipita como membrana hialina.])

Quando esse mecanismo acontece no pulmão em escala difusa, ele deixa de ser um edema entre outros e vira uma síndrome de risco de vida. É o quadro da lesão pulmonar aguda, cuja expressão morfológica se chama dano alveolar difuso e cuja tradução clínica é a #sigla("SARA", [síndrome da angústia respiratória aguda — insuficiência respiratória por dano alveolar difuso, com edema pulmonar de alta permeabilidade]). A cadeia que a figura acima desenha vale a pena ser lida como uma sequência: agente agressor → ativação de macrófagos alveolares → liberação de citocinas → recrutamento maciço de neutrófilos → destruição do endotélio capilar e do pneumócito → barreira alvéolo-capilar rompida → plasma inunda o alvéolo. E como o plasma que entrou é rico em fibrinogênio, esse se polimeriza em fibrina, que junto com restos de células necróticas se deposita revestindo a parede alveolar — a membrana hialina que a PARTE III vai reencontrar ao microscópio.

#atencao-box("Edema de alta pressão e edema de alta permeabilidade não se tratam igual", [O aluno tende a agrupar todo alvéolo cheio de líquido sob o rótulo genérico de edema pulmonar, e essa fusão apaga a distinção que mais importa à beira do leito. No edema cardiogênico o capilar está íntegro e sob pressão elevada por represamento atrás do ventrículo esquerdo — o líquido é transudato, pobre em proteína, e baixar a pressão de enchimento com diurético e vasodilatador resolve o quadro. No edema da lesão pulmonar aguda a pressão de enchimento do coração está *normal*: o que falhou foi a barreira, e o líquido é exsudato rico em proteína e fibrina. Diurético aqui não corrige o vazamento, e retirar volume demais de um paciente com pressão de enchimento normal reduz o débito cardíaco sem secar o alvéolo. O tratamento persegue a causa da lesão e sustenta a troca gasosa com ventilação protetora enquanto o epitélio se refaz.])

#mini-resumo[Cinco alavancas, cinco doenças-modelo: hidrostática alta (insuficiência cardíaca, trombose venosa), oncótica baixa (síndrome nefrótica, cirrose, desnutrição), dreno linfático obstruído (filariose, esvaziamento axilar), retenção primária de sódio (glomerulonefrite aguda, injúria renal) e permeabilidade aumentada (inflamação, lesão pulmonar aguda). Só a última produz exsudato.]

#parte-title("PARTE III — Morfologia, órgãos-alvo e o preço do líquido acumulado")

#subtopico("3.1 — O que se vê: a morfologia do edema e da congestão")

Os mecanismos deixam marcas, e reconhecê-las é o trabalho do patologista — mas também é o que permite, à beira do leito, ler o mecanismo a partir do achado. Comecemos pelo edema no exame externo. O edema subcutâneo aparece como aumento difuso de volume, com pele lisa e esticada e as pregas naturais apagadas. Ao comprimir com o polegar contra uma superfície óssea, a água é deslocada lateralmente e demora a voltar, deixando uma depressão que persiste alguns segundos — é o #termo-nota[sinal do cacifo][depressão que persiste após compressão digital do tecido edemaciado, característica do edema pobre em proteína], também chamado de sinal do godet. Esse sinal é típico do edema pobre em proteína, aquele das forças de Starling desequilibradas. Ele tende a estar *ausente* no linfedema crônico, onde a proteína retida já organizou fibrose e o tecido não se deixa deprimir com a mesma facilidade.

A distribuição do edema é informativa por si só, e vale tratá-la como pista de mecanismo. Quando a causa é hemodinâmica sistêmica, a gravidade manda: o líquido se acumula onde a coluna de sangue venoso pesa mais, o que significa tornozelos e dorso dos pés em quem caminha e região sacral e face posterior das coxas em quem está acamado — é o chamado edema dependente. Quando a causa é renal, o edema costuma abrir pela face e pelas pálpebras, pela frouxidão do tecido conjuntivo periorbital. Quando é linfático, o edema é assimétrico e respeita o território de drenagem interrompido, comprometendo um membro e poupando o contralateral.

Ao microscópio, o edema é discreto — quase decepcionante para quem espera algo dramático. O que se vê é um clareamento do tecido e um afastamento entre os elementos da matriz extracelular, que ficam separados por espaços opticamente vazios, mais evidente ao redor dos capilares e das fibras conjuntivas. Não há infiltrado, não há necrose, não há reação: só distância aumentada entre estruturas que deveriam estar próximas. A congestão, por contraste, é visualmente óbvia: capilares e vênulas ingurgitados de hemácias, distendidos, dando ao corte um aspecto avermelhado difuso. Macroscopicamente, o órgão congesto está aumentado, pesado, com superfície de corte úmida da qual escorre sangue — na congestão aguda a cor é vermelho-azulada; na crônica ela escurece e se soma a endurecimento pela fibrose que se instalou.

#subtopico("3.2 — Congestão crônica em dois órgãos: pulmão e fígado")

Os dois órgãos que melhor demonstram o custo da congestão de longa data são justamente aqueles que ficam imediatamente atrás de cada metade do coração — e a lógica retoma a divisão feita no subtópico 2.1. O pulmão sofre com a falência esquerda; o fígado, com a direita.

No pulmão, a congestão aguda mostra capilares alveolares ingurgitados, edema no septo alveolar e, com frequência, hemorragias focais dentro dos alvéolos. Se o quadro se cronifica, o desenho muda de forma característica. Os septos alveolares se espessam e se tornam fibróticos, o que já basta para dificultar a difusão de oxigênio. E as hemácias que escaparam para dentro do alvéolo ao longo dos anos são fagocitadas por macrófagos alveolares, que degradam a hemoglobina e acumulam #termo-nota[hemossiderina][pigmento castanho-dourado derivado da degradação da hemoglobina, acumulado em macrófagos após hemorragia] no citoplasma. Esses macrófagos carregados de pigmento castanho recebem o nome de células da insuficiência cardíaca — nome enganoso, porque não se trata de uma linhagem celular própria, e sim de um macrófago alveolar comum fazendo faxina de hemorragias repetidas. A soma de fibrose septal com pigmento de ferro difuso dá ao pulmão crônicamente congesto um aspecto firme e acastanhado descrito como induração parda.

#figura-nebli("/figuras/patologia-edema-congestao/slide-06.png",
  largura: 54%,
  legenda: [Achados de autópsia num quadro de congestão sistêmica. À esquerda, líquido citrino ocupando a cavidade torácica com o pulmão retraído acima dele; à direita, vísceras ingurgitadas de sangue escuro — a face macroscópica da drenagem venosa que não escoa.])

No fígado, o padrão é ainda mais didático porque a arquitetura do lóbulo o organiza. O sangue chega ao lóbulo pela periferia, pelos ramos da veia porta e da artéria hepática, atravessa os sinusóides e sai pela veia centrolobular no meio. Isso significa que o hepatócito da região *centrolobular* é o último da fila a receber oxigênio — vive normalmente com a menor tensão de oxigênio do lóbulo. Quando a congestão eleva a pressão na veia centrolobular e o sangue estaciona nos sinusóides, é justamente essa região que sofre primeiro: os hepatócitos centrolobulares degeneram e podem necrosar, enquanto os periportais, mais bem servidos, sobrevivem — muitas vezes acumulando gordura por hipóxia moderada. O resultado no corte macroscópico é um mosqueado de áreas escuras, congestas e deprimidas, alternadas com áreas pálidas ou amareladas preservadas, cujo desenho lembra a superfície cortada da noz-moscada. Daí o nome consagrado de #termo-nota[fígado em noz-moscada][aspecto mosqueado do fígado na congestão passiva crônica, com centros lobulares escuros e congestos alternando com periferia pálida]. Se a congestão persiste por anos, o interstício centrolobular deposita colágeno e o fígado desenvolve fibrose — um quadro que, no extremo, chega a arremedar uma cirrose, mas cuja origem é hemodinâmica, não tóxica nem viral.

#figura-nebli("/figuras/patologia-edema-congestao/slide-12.png",
  largura: 64%,
  legenda: [À esquerda, o abdome globoso da ascite volumosa num paciente emagrecido. À direita, de cima para baixo: a superfície nodular do fígado cirrótico, a superfície de corte mosqueada que dá nome ao fígado em noz-moscada, e o correlato microscópico — sinusóides centrolobulares distendidos e hepatócitos vizinhos rarefeitos, enquanto a periferia do lóbulo permanece preservada.])

#subtopico("3.3 — Edema pulmonar: dois líquidos, dois alvéolos")

O pulmão merece um subtópico próprio porque é onde o edema deixa de ser sinal e passa a ser causa direta de morte — e porque nele os dois grandes mecanismos que a PARTE II separou aparecem lado a lado com morfologias distintas.

No edema pulmonar de origem cardíaca, a pressão nos capilares alveolares sobe por represamento atrás do ventrículo esquerdo, e o líquido filtrado passa a exceder o que os linfáticos pulmonares conseguem remover. Ele primeiro encharca o interstício dos septos, depois transborda para dentro dos alvéolos. Os pulmões ficam pesados e úmidos, e a compressão da superfície de corte faz escorrer líquido espumoso, às vezes rosado — a espuma é simplesmente esse transudato batido com o ar durante a respiração, e o tom rosado vem de algumas hemácias que escaparam junto. Ao microscópio, o alvéolo aparece preenchido por um material granular róseo, homogêneo, sem células inflamatórias significativas: é plasma ultrafiltrado, pobre em proteína. Como o líquido acumulado se distribui por gravidade, o comprometimento é mais intenso nas bases dos pulmões.

#figura-nebli("/figuras/patologia-edema-congestao/slide-09.png",
  largura: 64%,
  legenda: [Edema pulmonar em três registros. Acima, a superfície de corte do pulmão com líquido espumoso escorrendo. Abaixo à esquerda, a radiografia com opacificação difusa e derrame associado (setas). À direita, o correlato histológico: capilares septais ingurgitados e alvéolos ocupados por material róseo homogêneo — o transudato.])

#figura-nebli("/figuras/patologia-edema-congestao/slide-14.png",
  largura: 50%,
  legenda: [Maior aumento do mesmo processo: o espaço alveolar tomado por material eosinofílico granular, sem infiltrado inflamatório relevante. Um alvéolo cheio desse líquido é um alvéolo que não troca gás, ainda que sua parede esteja intacta.])

O quadro muda inteiramente quando a causa é lesão da barreira. No dano alveolar difuso, o que preenche o alvéolo não é ultrafiltrado, e sim plasma inteiro atravessando um endotélio e um epitélio lesados. Com o plasma vem fibrinogênio, que polimeriza em fibrina; a fibrina se mistura a restos de pneumócitos necróticos e se deposita revestindo a parede alveolar numa faixa eosinofílica densa e contínua — a #termo-nota[membrana hialina][faixa eosinofílica de fibrina e restos celulares que reveste a parede alveolar no dano alveolar difuso, marca morfológica da lesão da barreira alvéolo-capilar]. Essa membrana é a assinatura morfológica do mecanismo de permeabilidade, e não aparece no edema cardiogênico puro. Na sequência, os pneumócitos do tipo II proliferam para repor o epitélio destruído, e se a agressão foi extensa, a fase de reparo deposita colágeno e deixa fibrose residual.

#figura-nebli("/figuras/patologia-edema-congestao/slide-15.png",
  largura: 56%,
  legenda: [Dano alveolar difuso. Repare na diferença em relação à figura anterior: além de material dentro do alvéolo, há faixas eosinofílicas espessas *revestindo* a parede alveolar — membranas hialinas — e o septo está alargado e celularizado. Aqui a barreira não está apenas sob pressão, está destruída.])

#subtopico("3.4 — Ascite na cirrose: quatro forças somadas")

A ascite da cirrose merece atenção separada porque é o exemplo mais completo do capítulo: nela, quase todos os mecanismos que estudamos operam juntos, e entender a soma explica por que o quadro é tão difícil de controlar.

Tudo começa na arquitetura. A fibrose e os nódulos de regeneração da cirrose distorcem os sinusóides e obstruem o fluxo através do fígado, elevando a pressão no sistema porta. Essa hipertensão portal aumenta a pressão hidrostática nos capilares do território esplâncnico e empurra líquido para a cavidade peritoneal — primeiro mecanismo, puramente hidrostático. Ao mesmo tempo, o fígado doente sintetiza menos albumina, e a queda da pressão oncótica facilita a saída de líquido em todos os leitos — segundo mecanismo. Um terceiro elemento é a própria linfa hepática: com os sinusóides sob pressão, o fígado passa a produzir muito mais linfa do que o ducto torácico consegue drenar, e o excesso extravasa pela cápsula direto para o peritônio.

#figura-nebli("/figuras/patologia-edema-congestao/slide-11.png",
  largura: 60%,
  legenda: [A cascata que transforma hipertensão portal em ascite. A vasodilatação esplâncnica reduz o volume circulante *efetivo*, o SRAA é ativado, e daí saem dois desfechos: avidez renal por sódio, que alimenta a ascite, e vasoconstrição renal intensa, que produz a síndrome hepatorrenal.])

O quarto elemento é o menos intuitivo e o mais importante clinicamente. A hipertensão portal induz liberação de vasodilatadores, especialmente o óxido nítrico, na circulação esplâncnica. As arteríolas do território intestinal se dilatam, e o leito arterial como um todo se torna maior do que o volume de sangue disponível para preenchê-lo. Os sensores de pressão do corpo leem isso como subenchimento — o *volume arterial efetivo* caiu, ainda que o volume total de sangue não tenha diminuído. E o rim, mais uma vez, responde ao que lê: ativa o SRAA, libera hormônio antidiurético e retém sódio e água com avidez. Esse líquido retido não corrige o subenchimento arterial, porque continua escapando para o peritônio pelas três primeiras forças — de modo que o ciclo se reforça e a ascite cresce.

#clinica-box("Duas complicações que nascem da mesma cascata", [A ascite não é só desconforto abdominal, e as duas complicações que mais matam derivam diretamente do mecanismo. A primeira é a peritonite bacteriana espontânea: o líquido ascítico é pobre em proteínas de defesa e funciona como meio de cultura; bactérias intestinais que atravessam a parede e alcançam a cavidade encontram pouca oposição, e a infecção se instala sem nenhuma perfuração para explicá-la — daí "espontânea". Febre, dor abdominal difusa e piora da função hepática num cirrótico com ascite são motivo para puncionar o líquido e contar suas células. A segunda é a síndrome hepatorrenal: a vasoconstrição renal disparada pela mesma ativação neuro-humoral reduz progressivamente a filtração glomerular até a insuficiência renal — e o ponto essencial é que o rim está *estruturalmente normal*. Transplantado para um receptor com fígado sadio, ele volta a funcionar. A lesão é hemodinâmica, não parenquimatosa, e é por isso que a única correção definitiva é o transplante de fígado.])

#subtopico("3.5 — O preço do líquido acumulado")

Fechado o mapa dos mecanismos e das morfologias, resta a pergunta que dá sentido a tudo: o que exatamente o líquido acumulado faz de mal. A resposta varia radicalmente conforme o lugar, e essa variação define a urgência.

No subcutâneo, o edema é sobretudo um sinal — ele denuncia insuficiência cardíaca ou doença renal antes que outros achados apareçam, e por isso vale ouro no exame físico. Mas ele não é inteiramente inocente: o líquido aumenta a distância entre o capilar e a célula que precisa ser nutrida, e essa distância maior atrasa a chegada de oxigênio e de células de defesa. Ferida em tecido edemaciado cicatriza mais devagar, e infecção em tecido edemaciado é mais difícil de conter.

No pulmão, o edema deixa de ser sinal e vira ameaça imediata. Alvéolo cheio de líquido é alvéolo que não troca gás, por mais íntegra que esteja sua parede, e centenas de mililitros de líquido bastam para comprometer gravemente a oxigenação. O líquido acumulado ainda serve de meio de cultura, favorecendo pneumonia secundária. No encéfalo, o problema ganha outra dimensão porque o crânio é uma caixa rígida de volume fixo: qualquer aumento de volume do tecido nervoso só pode ser acomodado às custas de compressão. O encéfalo edemaciado tem giros alargados e sulcos estreitados, e o tecido acaba sendo empurrado através das aberturas naturais do crânio — a herniação. Quando o tronco encefálico é comprimido nesse deslocamento, os centros que controlam a respiração e a circulação param de funcionar. É o desfecho mais rápido e mais letal de todo este capítulo.

*Vale notar antes de fechar:* nada disso se trata tratando o edema. Retirar líquido alivia o sintoma, e às vezes salva a vida no curto prazo, mas o líquido volta enquanto a alavanca que o produziu continuar puxada. É por isso que o raciocínio deste resumo termina sempre na mesma pergunta prática — qual dos cinco mecanismos está operando aqui —, porque é a resposta a ela que define a conduta.

#conclusao-box[
  O princípio que unifica todo este capítulo é que o líquido do corpo obedece a um balanço de forças, e esse balanço tem folga estreita. A pressão hidrostática empurra água para fora do capilar, a pressão oncótica das proteínas plasmáticas puxa de volta, e o sistema linfático recolhe o pequeno excedente que sobra todo dia. Edema é o nome que damos a qualquer situação em que um desses três termos sai da faixa: pressão alta demais, proteína de menos, dreno obstruído — aos quais se somam a retenção renal primária de sódio, que age nos dois primeiros termos ao mesmo tempo, e o aumento de permeabilidade, o único que rompe a peneira e produz líquido rico em proteína. Congestão é o mesmo problema visto do outro lado da parede: sangue que não escoa e se acumula dentro do vaso, deixando o tecido cianótico, hipóxico e, com o tempo, fibrótico.

  Esse é o mecanismo nuclear a levar embora: *cada doença deste capítulo é uma dessas alavancas puxada, e a morfologia entrega qual foi*. A insuficiência cardíaca eleva a pressão retrógrada e liga o SRAA, produzindo transudato dependente da gravidade, pulmão de induração parda e fígado em noz-moscada. A síndrome nefrótica perde albumina pelo glomérulo e produz edema periorbital e generalizado que resiste ao diurético isolado, porque o líquido reposto escapa de novo. A cirrose soma hipertensão portal, hipoalbuminemia, extravasamento de linfa hepática e vasodilatação esplâncnica, e o subenchimento arterial que essa vasodilatação cria explica tanto a avidez renal por sódio quanto a síndrome hepatorrenal de rins estruturalmente sadios. A obstrução linfática retém proteína no interstício e evolui para fibrose, edema firme e sem cacifo. E a lesão alveolar difusa rompe a barreira, inunda o alvéolo de plasma e deposita membrana hialina — o achado que separa, ao microscópio, o edema de pressão do edema de permeabilidade.

  A projeção adiante é curta e direta. Os distúrbios hemodinâmicos formam um bloco encadeado, e a congestão que estudamos aqui é a porta de entrada do próximo elo: sangue estagnado dentro do vaso é sangue com fluxo lento, e fluxo lento é uma das três condições clássicas que favorecem a formação de trombos. O mesmo membro edemaciado por trombose venosa profunda que abriu a PARTE II é, na verdade, o encontro dos dois assuntos. Do trombo formado saem a embolia, o infarto e, no extremo da falência circulatória, o choque — e todos eles voltam a passar exatamente pelas forças de Starling e pela integridade do endotélio que este resumo montou.
]
