"""Build a new X1 selection solely from the live inventory and current sources."""
import hashlib
import json
import re
from pathlib import Path

HERE = Path(__file__).parent
INV = json.loads((HERE / "inventory.json").read_text(encoding="utf-8"))
BY_ID = {n["nid"]: n for n in INV["notes"]}
BY_ID.update({n["nid"]: n for n in json.loads((HERE / "inventory-rectal-lymph.json").read_text(encoding="utf-8"))["notes"]})
LESSON = "2026-uc08-anatomia-07-vascularizacao-das-visceras"
DECK = "NEBLI::UC08::P1::Anatomia::Vascularização das vísceras"
HY = "#AK_Step1_v12::#Low/HighYield::1-HighYield"

# Independent curation from 24 Sep. The source note IDs are looked up in the
# new search inventory. They are never loaded from a previous plan or receipt.
ANKING = [
    1486767159823, 1486767263733, 1486767276770, 1486767287058,
    1486767295417, 1486767304293, 1486767314237, 1486767323251,
    1486767327881, 1486767330571, 1486767333068, 1486767335503,
    1486767337959, 1486767341284, 1486767346792, 1486767349883,
    1486767352903, 1486767364212, 1486767367274, 1486767395683,
    1486945231564, 1486945235222, 1521079313083, 1486767143966,
    1486767163689, 1486945239368, 1486945243332, 1486945247167,
    1486767150807, 1486767179344, 1486771346144, 1486771359798,
    1486945252224, 1486771343412, 1486771372707, 1486771374861,
    1486771390217, 1486771351448, 1486771380083,
]
DOPE_CLOZE = [
    1461962027190, 1461962581720,
    1461962333435, 1461962601941, 1461962631680, 1461966031438,
]
DORIAN = [1527683179954]
ATLAS = {
    1349477488373: ["2a", "10a", "11a", "13a"],
    1349477488376: ["2a", "5a", "6a", "7a", "8a", "9a", "10a", "11a", "12a"],
    1349477488369: [f"{i}a" for i in range(1, 13)],
    1349477488443: ["2a", "3a", "4a", "5a", "6a", "7a", "10a", "11a", "12a", "13a", "14a"],
    1349477488690: ["5a", "6a", "8a", "10a", "12a"],
}
PINK = {
    1486767323251, 1486767327881, 1486767330571, 1486767333068,
    1486767335503, 1486767337959, 1486767341284, 1486767346792,
    1486767349883, 1486767352903, 1461962027190,
    1486767143966, 1486767150807,
}

def digest(v):
    return hashlib.sha256(json.dumps(v, ensure_ascii=False, sort_keys=True).encode()).hexdigest()

def main():
    selected = ANKING + DOPE_CLOZE + DORIAN + list(ATLAS)
    assert len(selected) == len(set(selected))
    missing = sorted(set(selected) - BY_ID.keys())
    if missing:
        raise ValueError(f"Selected candidates absent from fresh inventory: {missing}")
    entries = []
    for nid in selected:
        row = BY_ID[nid]
        fields = dict(row["fields"])
        source_deck = row["cards"][0]["deck"]
        if nid in ATLAS:
            for i in range(1, 21):
                if f"{i}a" not in ATLAS[nid]:
                    fields[f"{i}a"] = ""
            fields["Clinical"] = ""
            fields["Comment"] = ""
            count = len(ATLAS[nid])
            source = "Dope Anatomy"
        else:
            # Video/resource panels in AnKing are deliberately omitted.
            for name in list(fields):
                if name not in {"Text", "Extra"}:
                    fields[name] = ""
            count = len(set(re.findall(r"\{\{c(\d+)::", fields["Text"])))
            source = "AnKing" if nid in ANKING else ("Dorian" if nid in DORIAN else "Dope Anatomy")
        if not count:
            raise ValueError(f"No card generated by {nid}")
        entries.append({"source_nid": nid, "source_deck": source_deck,
                        "source_model": row["model"], "source_fields_hash": digest(row["fields"]),
                        "source_tags": row["tags"], "origin": source,
                        "fields": fields, "selected_fields": ATLAS.get(nid, []),
                        "expected_cards": count, "high_yield": source == "AnKing" and HY in row["tags"],
                        "pink": nid in PINK, "pink_reason": "variant/detail for post-exam review" if nid in PINK else ""})
    sample_anking = BY_ID[ANKING[0]]
    authored_fields = {name: "" for name in sample_anking["fields"]}
    authored_fields["Text"] = (
        "From the pelvic sidewall, the {{c1::internal iliac artery}} "
        "sends a middle rectal branch toward the rectum."
    )
    authored_fields["Extra"] = (
        'This lateral route complements the superior rectal artery descending from the IMA.'
        '<br><img src="nebli_uc08_rectal_arteries_slide22.jpeg" width="430">'
    )
    entries.append({"source_nid": None, "source_deck": None,
                    "source_model": sample_anking["model"], "source_fields_hash": None,
                    "source_tags": [], "origin": "Autoral", "key": "middle-rectal-origin",
                    "fields": authored_fields, "selected_fields": [], "expected_cards": 1,
                    "high_yield": False, "pink": False, "pink_reason": ""})
    plan = {"lesson_id": LESSON, "target_deck": DECK, "profile": INV["profile"],
            "source_folder": "https://drive.google.com/drive/folders/1anr09zp44SG100cQsQ-4jMVk6b0rcM2W",
            "source_inventory": "inventory.json", "entries": entries,
            "totals": {"notes": len(entries), "cards": sum(x["expected_cards"] for x in entries),
                       "by_source": {s: sum(x["expected_cards"] for x in entries if x["origin"] == s)
                                     for s in {x["origin"] for x in entries}},
                       "pink": sum(x["expected_cards"] for x in entries if x["pink"]),
                       "green": sum(x["expected_cards"] for x in entries if x["high_yield"] and not x["pink"]),
                       "authorial": 1}}
    (HERE / "plan.json").write_text(json.dumps(plan, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(plan["totals"], ensure_ascii=False))

if __name__ == "__main__":
    main()
