#import "../typst-template/nebli_v2_apostila.typ": *

#discursiva("Q1",
  [Explique por que a remodelação contínua, longe de ser um desperdício metabólico, é a condição da força do osso adulto. Use a osteopetrose como prova invertida do seu argumento. (≤100 palavras)],
  [O osso adulto continua sendo desmontado por osteoclastos e remontado por osteoblastos não para crescer, e sim para manter a microarquitetura adaptada à carga corrente. Cada ciclo dissolve matriz antiga e deposita matriz nova orientada pelo vetor de força ativo naquele momento. Quando esse ciclo é interrompido — como na osteopetrose, em que o osteoclasto está bloqueado e não consegue reabsorver — o osso acumula mineral velho, mantém microarquitetura desadaptada e fica paradoxalmente frágil apesar do excesso. A osteopetrose prova invertida: sem renovação, mais mineral não significa mais força.])

#discursiva("Q2",
  [Por que ossos formados por ossificação endocondral têm placa epifisial e ossos chatos formados por ossificação intramembranosa não? Conecte a rota embriológica ao mecanismo de crescimento longitudinal. (≤100 palavras)],
  [Na endocondral, o organismo primeiro faz um molde cartilaginoso do osso futuro e depois substitui esse molde por osso. Centros de ossificação se abrem em pontos discretos do molde — primário na diáfise, secundários nas epífises — e entre eles permanece uma faixa de cartilagem ainda não substituída, a placa epifisial. É nessa placa que o osso cresce em comprimento. Na intramembranosa, não há molde cartilaginoso intermediário: o mesênquima vira osso direto em frentes que avançam até se encontrar. Sem cartilagem residual, não há substrato para alongamento — o osso cresce só em espessura, por aposição.])

#discursiva("Q3",
  [A explicação tradicional para a função da patela é "proteger o tendão patelar contra atrito". Por que essa explicação é insuficiente e qual é o papel biomecânico mais importante? Por que paciente patelectomizado tem perda persistente de força de extensão? (≤100 palavras)],
  [Proteger contra atrito é só parte da história. O papel mecânico nuclear da patela é atuar como polia: ela empurra o tendão do quadríceps para fora da articulação do joelho, aumentando o ângulo entre o tendão e a tíbia. Com ângulo maior, o componente da força do quadríceps que efetivamente extende a perna aumenta — o braço de alavanca cresce. Sem patela, o tendão fica colado à articulação, o ângulo cai, e a mesma força muscular gera menos torque extensor. Por isso patelectomizado mantém o quadríceps treinável mas perde eficiência mecânica permanente.])

#discursiva("Q4",
  [Descreva como o ósteon resolve o problema da nutrição em uma matriz mineralizada onde nada pode se difundir por bloco. Inclua canal central, lamelas, lacunas, canalículos e canais de Volkmann no seu argumento. (≤100 palavras)],
  [Matriz mineralizada é praticamente impermeável a soluto. O ósteon contorna isso construindo uma microcirculação dentro da própria matriz. Cada ósteon tem um canal central com um vaso sanguíneo; em volta dele, lamelas concêntricas de matriz; entre as lamelas, lacunas onde moram osteócitos; e ligando todas as lacunas e o canal central, canalículos finíssimos cheios de líquido extracelular. Nutriente sai do vaso, percorre os canalículos por difusão local e alcança cada osteócito. Ósteons vizinhos se conectam por canais perfurantes (de Volkmann), horizontais, ligando os canais centrais entre si e com vasos do periósteo.])

#discursiva("Q5",
  [Por que o uso prolongado de glicocorticoide (prednisona, dexametasona) leva previsivelmente à osteoporose? Conecte o mecanismo celular ao saldo da remodelação e justifique por que paciente em corticoterapia crônica recebe suplementação preventiva. (≤130 palavras)],
  [A massa óssea adulta é o saldo entre reabsorção feita pelo osteoclasto e deposição feita pelo osteoblasto. O glicocorticoide bate nos dois lados ao mesmo tempo, e na mesma direção desfavorável: inibe a deposição pelo osteoblasto (menos matriz nova) e estimula a atividade do osteoclasto (mais matriz velha removida). O saldo fica negativo de maneira sustentada enquanto a droga estiver presente. Em uso prolongado, esse déficit se acumula e a microarquitetura trabecular do esponjoso — especialmente das vértebras — começa a desabar, gerando osteoporose iatrogênica previsível. Cálcio, vitamina D e às vezes bifosfonato são prescritos preventivamente para empurrar o saldo de volta: cálcio repõe o substrato, vitamina D melhora absorção intestinal, bifosfonato segura o osteoclasto contrabalançando o estímulo do corticoide.])
