#import "../typst-template/nebli_v2_apostila.typ": *

#discursiva("Q1",
  [Duas bactérias são submetidas ao mesmo protocolo de coloração de Gram, com os mesmos reagentes e nos mesmos tempos. Ao final, uma aparece roxa e a outra rosa. Explique, do ponto de vista estrutural, o que determina esse desfecho, indicando em que etapa do procedimento a diferenciação ocorre de fato.],
  [Todas as células recebem os quatro reagentes na mesma ordem; a parede decide o resultado. O cristal violeta cora tudo, e o iodo, como mordente, forma com ele um complexo grande demais para atravessar malha apertada. A diferenciação acontece na descoloração pelo álcool: na Gram-negativa, o álcool dissolve os lipídios da membrana externa e, com apenas uma ou poucas camadas de peptidoglicano, o complexo escapa e a célula fica incolor; na Gram-positiva, o álcool desidrata a malha espessa, que se fecha e retém o pigmento. A safranina entra nas duas, mas só aparece onde não há roxo.])

#discursiva("Q2",
  [O escarro de um paciente com suspeita de tuberculose é corado pelo Gram e nenhum bacilo é evidenciado. Justifique esse resultado com base na estrutura da parede do agente e explique o fundamento da técnica alternativa empregada.],
  [A micobactéria tem arquitetura de parede de Gram-positiva, mas recoberta por uma camada espessa e cerosa de ácido micólico, que impede a entrada dos corantes do Gram — não corar é diferente de corar de rosa. Na coloração de Ziehl-Neelsen, a fucsina fenicada é aquecida até emitir vapores, o que amolece a cera e permite a entrada do pigmento. Em seguida, descolora-se com álcool-ácido, agente bem mais agressivo que o álcool: a mesma cera impede a saída, e o bacilo retém a fucsina. Daí o nome álcool-ácido resistente, com bacilos vermelhos sobre fundo azul.])

#discursiva("Q3",
  [Um paciente com bacteriemia por bacilo Gram-negativo apresenta febre alta e hipotensão, e piora nas primeiras horas após a dose inicial de um antibiótico bactericida adequado. Descreva o mecanismo molecular responsável pelo quadro e explique por que o tratamento correto pode agravá-lo transitoriamente.],
  [O componente responsável é o lipídio A, porção lipídica do lipopolissacarídeo ancorada na folha externa da membrana externa. Receptores da imunidade inata o reconhecem como assinatura de bactéria Gram-negativa e disparam liberação maciça de citocinas inflamatórias, que produzem febre, vasodilatação e aumento da permeabilidade capilar; a queda de pressão e de perfusão fecha o quadro de choque. Como o lipídio A é peça estrutural e não toxina secretada, ele só é apresentado em massa quando a bactéria se rompe — e um bactericida que lisa grande número de células de uma vez libera justamente essa carga.])

#discursiva("Q4",
  [Flagelo e fímbria são apêndices de superfície frequentemente tratados como equivalentes. Aponte as diferenças estruturais e funcionais entre eles e indique qual dos dois explica a colonização ascendente do trato urinário por _Escherichia coli_.],
  [O flagelo é longo e ondulado, composto de flagelina, ancorado num corpo basal que funciona como motor rotatório movido pelo gradiente de prótons; ele gera motilidade orientada por gradiente. A fímbria é curta, rígida, numerosa e sem motor: na ponta carrega uma adesina que reconhece receptor específico do epitélio do hospedeiro. Quem explica a infecção urinária ascendente é a fímbria. A urina flui de dentro para fora e varreria a bactéria; a adesina fixa a célula ao urotélio contra esse fluxo, permitindo que ela suba da uretra à bexiga e, pelo ureter, ao rim.])

#discursiva("Q5",
  [Instrumental cirúrgico contaminado por _Clostridium_ é submetido a fervura em água a 100 °C e, ainda assim, permanece capaz de transmitir infecção. Explique o mecanismo estrutural dessa resistência, justifique por que a autoclave resolve o problema e comente por que a estrutura envolvida não deve ser considerada forma de reprodução.],
  [A forma persistente é o endósporo, produzido quando faltam nutrientes ou o meio se torna hostil. A resistência ao calor vem de três fatores somados: desidratação profunda do núcleo, que remove a água necessária às reações de degradação; acúmulo de dipicolinato de cálcio, que ocupa o lugar da água e estabiliza as macromoléculas; e proteínas pequenas que revestem o DNA e o protegem de calor e radiação. Água fervente a 100 °C não vence esse núcleo desidratado; a autoclave, com vapor sob pressão a 121 °C, alcança temperatura suficiente. Não é reprodução porque uma célula gera um endósporo e um endósporo germina em uma célula — o número de indivíduos nunca aumenta.])
