#import "../typst-template/nebli_v2_apostila.typ": *

#intro-box[
Uma bactéria é uma célula com poucos micrômetros de comprimento, sem núcleo, sem mitocôndria e sem retículo endoplasmático — e mesmo assim ela precisa resolver os mesmos problemas que qualquer célula viva resolve: não estourar, produzir energia, copiar o próprio material genético, chegar aonde tem comida e escapar de quem quer destruí-la. Como ela não tem organelas para dividir esse trabalho, tudo é resolvido por poucas estruturas que acumulam funções. É por isso que esta aula tem uma lógica única do começo ao fim: *cada estrutura da bactéria é a resposta física a um problema de sobrevivência* — e é também, por consequência direta, o que permite identificá-la no laboratório, o que explica por que ela adoece o hospedeiro, e o que o antibiótico vai atacar.

Guarde essa ordem, porque ela organiza as três PARTES. A PARTE I mostra o que a bactéria revela quando você simplesmente olha para ela — a olho nu na placa de cultura e ao microscópio na lâmina. A PARTE II abre o envelope: membrana e parede, a estrutura que divide praticamente todas as bactérias de interesse médico em dois grandes grupos e que decide o resultado da coloração mais usada da microbiologia. A PARTE III percorre as demais estruturas, que não estão em todas as bactérias e por isso mesmo são as que diferenciam comportamento: material genético móvel, motilidade, adesão, disfarce e resistência.
]

#parte-title("PARTE I — A bactéria e o que ela mostra", primeira: true)

#subtopico("1.1 Procarioto: o que viver sem núcleo obriga")

A separação mais profunda entre os seres vivos não é entre planta e animal, nem entre micróbio e organismo grande. É entre três linhagens que se afastaram há bilhões de anos: *Bactéria*, *Arqueia* e *Eucarioto*. Essa divisão em três domínios foi proposta por Carl Woese em 1977 e não veio de olhar formas ao microscópio — veio de comparar sequências de #sigla("rRNA", [RNA ribossomal — o RNA que compõe o ribossomo, presente em todo ser vivo]). O raciocínio é elegante e vale entender, porque a mesma ferramenta reaparece o tempo todo no laboratório: o gene do rRNA existe em absolutamente todo organismo celular e muda muito devagar ao longo do tempo evolutivo. Duas linhagens que se separaram há pouco acumularam poucas diferenças nessa sequência; duas que se separaram há muito acumularam muitas. Contar diferenças, portanto, é medir tempo.

Na prática o procedimento é curto: extrai-se o #sigla("DNA", [ácido desoxirribonucleico — molécula que guarda a informação genética]) das células, amplifica-se por #sigla("PCR", [reação em cadeia da polimerase — técnica que produz milhões de cópias de um trecho definido de DNA]) o gene que codifica o rRNA, sequencia-se esse gene e alinha-se a sequência obtida com as de outros organismos. Um algoritmo compara base a base e desenha a árvore. Foi assim que se descobriu algo contraintuitivo: a arqueia, que a olho de microscópio parece uma bactéria qualquer, é geneticamente mais próxima de nós do que da bactéria. *O ponto fino é que semelhança de aparência e parentesco evolutivo são coisas diferentes* — e a molécula, não a forma, é quem arbitra.

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-04.png",
  largura: 66%,
  legenda: [Os três domínios da vida e a tecnologia que os revelou. À esquerda, a árvore que separa Bactéria, Arqueia e Eucarioto a partir de um ancestral comum. À direita, o caminho concreto: extrair DNA, amplificar o gene do rRNA, sequenciar e alinhar. As bases destacadas em amarelo são as diferenças acumuladas — quanto mais diferenças entre dois organismos, mais tempo desde que se separaram.])

O que interessa clinicamente vem do prefixo "pro-cario": *antes do núcleo*. A bactéria não tem envoltório nuclear, e essa ausência única encadeia uma série de consequências. Sem membrana separando o material genético do citoplasma, o ribossomo alcança o #sigla("RNA", [ácido ribonucleico — cópia de trabalho da informação genética]) mensageiro enquanto ele ainda está sendo transcrito: transcrição e tradução acontecem acopladas, no mesmo lugar e ao mesmo tempo. É por isso que uma bactéria responde a uma mudança do meio em minutos, fabricando a enzima nova quase junto com a decisão de fabricá-la. Sem mitocôndria, a cadeia transportadora de elétrons e a produção de #sigla("ATP", [adenosina trifosfato — a moeda energética da célula]) migram para a membrana citoplasmática, que assim acumula uma função que em nós é terceirizada. Sem retículo nem complexo de Golgi, a síntese e a exportação de macromoléculas também passam por essa mesma membrana.

O material genético em si é um cromossomo circular, único, sem histonas e sem envoltório, concentrado numa região do citoplasma que se chama nucleoide. Ele mede cerca de mil vezes o comprimento da célula que o abriga, e só cabe ali porque está torcido sobre si mesmo em superenovelamento. *Nada disso é curiosidade de taxonomia:* toda a farmacologia antibacteriana nasce dessas diferenças. Um antibiótico útil é aquele que ataca uma peça que a bactéria tem e nós não — a parede, o ribossomo de tipo bacteriano, a enzima que desenrola o cromossomo circular.

#mini-resumo[Sem núcleo e sem organelas, a bactéria concentra na membrana e em poucas estruturas funções que o eucarioto distribui — e é justamente cada uma dessas peças exclusivas que vira alvo de antibiótico.]

#subtopico("1.2 Da amostra ao grupo: por que a estrutura abre o diagnóstico")

Tudo o que vem nas próximas páginas — espessura de parede, presença de cápsula, tipo de apêndice — ganha sentido prático num único cenário: um paciente com suspeita de infecção bacteriana, e um médico que precisa decidir o tratamento hoje. O caminho do laboratório tem duas velocidades muito diferentes, e entender essa diferença é entender por que morfologia e estrutura ainda são as primeiras coisas que se olha, num tempo de sequenciamento genômico.

A primeira etapa é rápida. Colhe-se o material do sítio suspeito — escarro, urina, líquor, sangue, secreção de ferida — e prepara-se um esfregaço numa lâmina. Uma coloração e alguns minutos ao #sigla("M.O.", [microscópio óptico — o microscópio de luz visível do laboratório de rotina]) já entregam duas informações: a *forma* da bactéria e a *resposta dela à coloração de Gram*. Cruzando as duas, o material sai da lâmina classificado em um de quatro grandes grupos — coco Gram-positivo, coco Gram-negativo, bacilo Gram-positivo, bacilo Gram-negativo. Não é o nome da espécie, mas é um recorte enorme: cada um desses quatro grupos tem um repertório previsível de agentes e uma sensibilidade previsível a classes de antimicrobianos. É com essa informação, e só com ela, que se escolhe o tratamento inicial.

A segunda etapa é lenta e específica. A mesma amostra vai para cultura em meio sólido, e daí para testes bioquímicos que identificam a espécie, teste de sensibilidade a antimicrobianos, pesquisa de anticorpos, amplificação de ácido nucleico por PCR e, quando necessário, sequenciamento de trechos ou do genoma inteiro. Esse conjunto entrega o nome exato e o perfil de sensibilidade — mas cobra de um a vários dias, porque quase tudo depende de a bactéria crescer primeiro. *O preço dessa espera é clínico:* numa meningite ou numa sepse, o intervalo entre a coleta e o resultado da cultura é exatamente o intervalo em que o paciente pode morrer sem tratamento.

Vale registrar as limitações de cada velocidade, porque elas são simétricas. A leitura da lâmina é barata, imediata e universal, mas não dá espécie nem sensibilidade, e precisa de uma carga bacteriana razoável na amostra — abaixo de dezenas de milhares de bactérias por mililitro, simplesmente não se vê nada, e não ver não é o mesmo que não haver. A cultura é específica e permite testar antimicrobianos, mas demora e falha quando a bactéria é de crescimento lento, exigente ou intracelular obrigatória. O método molecular é o mais sensível de todos e detecta até bactéria já morta pelo antibiótico — vantagem quando o paciente já foi medicado, desvantagem quando se quer saber se o agente ainda está vivo, e ele não informa sensibilidade a droga nenhuma.

#mini-resumo[Se você só lembrar de uma coisa: a morfologia e a coloração entregam em minutos o grupo que orienta o tratamento inicial; a cultura entrega em dias o nome e a sensibilidade que o ajustam.]

#subtopico("1.3 Morfologia macroscópica: a colônia como clone visível")

Pense numa única bactéria depositada sobre a superfície de um meio de cultura sólido, com nutrientes e temperatura adequados. Ela se divide em duas, as duas em quatro, as quatro em oito. Cada geração leva dezenas de minutos em espécies de crescimento rápido, e as células filhas não se afastam: ficam empilhadas onde a mãe estava. Ao fim de uma noite de incubação, aquela célula invisível virou um monte esbranquiçado de poucos milímetros, perfeitamente visível a olho nu. Esse monte é a *colônia*, e ele contém cerca de cem milhões de células.

A frase que importa aqui é que a colônia é um *clone*: todas aquelas células descendem de uma só e, salvo mutação, são geneticamente idênticas. É essa propriedade que faz da placa de cultura um instrumento e não apenas um cultivo. Semeando uma amostra clínica de modo que as bactérias fiquem separadas na superfície, cada bactéria original vira uma colônia própria, e uma amostra que era uma mistura de espécies vira um tabuleiro de populações puras, cada uma disponível para ser estudada isoladamente. *Esse é o gesto fundador da bacteriologia:* separar no espaço o que estava misturado no líquido.

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-08.png",
  largura: 58%,
  legenda: [Morfologia macroscópica. À esquerda, uma amostra de solo semeada em meio sólido — cada colônia veio de uma célula. À direita, meios diferenciais: as cores separam enterobactérias que fermentam lactose das que não fermentam, e os halos ao redor das colônias de estreptococo mostram graus distintos de destruição das hemácias do meio.])

A colônia também *fala*, e é aqui que o meio de cultura deixa de ser suporte passivo. Num meio diferencial, adiciona-se um açúcar e um indicador de pH. A bactéria que fermenta aquele açúcar acidifica o meio ao redor de si, o indicador vira de cor, e a colônia aparece colorida; a que não fermenta permanece incolor. A cor, portanto, não é a cor da bactéria — *é o metabolismo dela traduzido em pigmento*, e isso separa grupos inteiros de enterobactérias numa única placa. O mesmo princípio, com outra química, produz a leitura da hemólise: quando a espécie secreta uma toxina que perfura a membrana das hemácias incorporadas ao ágar, forma-se ao redor da colônia um halo transparente, e o tamanho e o aspecto desse halo distinguem grupos de estreptococos. Repare no encadeamento: a toxina difunde pelo gel, atinge hemácias a distância e as rompe — ou seja, o halo é a exotoxina tornada visível.

Uma distinção que costuma se embaralhar merece ser desfeita antes de seguir. Meio *seletivo* e meio *diferencial* não são a mesma coisa. O seletivo contém um inibidor — sal em alta concentração, um corante, um antibiótico — que impede o crescimento de tudo o que não interessa; ele filtra. O diferencial deixa todo mundo crescer e separa por aparência; ele revela. Muitos meios usados na rotina fazem as duas coisas ao mesmo tempo, o que ajuda a confundir, mas são propriedades independentes.

#subtopico("1.4 Morfologia microscópica: forma, arranjo e escala")

Sob o microscópio, a variedade morfológica das bactérias é surpreendentemente pequena, e a razão disso é estrutural: quem impõe a geometria não é a membrana, que é fluida e não sustenta nada, mas a malha rígida de peptidoglicano que a envolve. Retire essa malha e qualquer bactéria vira uma esfera, porque a esfera é a forma que a pressão interna produz quando não há nada para contrariá-la. Toda a classificação por forma que vem a seguir é, no fundo, uma classificação da parede.

Três formas básicas cobrem quase tudo. O *coco* é esférico ou ovalado, com cerca de um micrômetro de diâmetro. O *bacilo* é alongado, tipicamente dois a três micrômetros de comprimento por um de largura. E as *espiraladas* são curvas ou helicoidais, com uma subdivisão que vale separar com cuidado, porque as três subclasses se movem de maneiras diferentes. O *vibrião* tem uma única curvatura, em forma de vírgula, e o exemplo clássico é o agente do cólera. O *espirilo* tem corpo rígido em hélice e nada com flagelos externos, presos nas duas extremidades. A *espiroqueta* também é helicoidal, mas o corpo é flexível e a locomoção vem de filamentos internos que giram dentro do próprio envelope, deformando a célula em saca-rolha — é o desenho de *Treponema*, *Leptospira* e *Borrelia*, e ele permite avançar em meio viscoso onde uma bactéria de flagelo externo travaria.

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-10.png",
  largura: 72%,
  legenda: [Formas e arranjos. Em cima, os arranjos de cocos: isolados, em cadeia (estreptococos), em cacho (estafilococos) e aos pares (diplococos). À esquerda, bacilos isolados e em cadeia. À direita, as três subclasses de espiraladas com seus representantes — repare que espiroqueta, espirilo e vibrião diferem menos na forma do que no modo de se mover.])

O *arranjo* é a segunda camada de informação, e ele não descreve bactérias que se juntaram: descreve como elas se dividiram. Quando o coco se divide sempre no mesmo plano e as células filhas não se separam por completo, o resultado é uma cadeia — o estreptococo. Quando ele se divide em planos sucessivamente diferentes, forma-se um cacho irregular — o estafilococo. Quando as células se separam após um único par, tem-se o diplococo. *Dito de outro modo: o arranjo é o registro fóssil do plano de divisão*, e por isso é uma característica estável da espécie, útil na identificação. O mesmo vale para bacilos que permanecem enfileirados, os estreptobacilos.

Falta a escala, e ela decide o que é possível ver. O vírus influenza tem cerca de 200 nanômetros de diâmetro e está abaixo do limite de resolução da luz visível — nenhum microscópio óptico o mostra, é preciso microscópio eletrônico. A bactéria, com um a três micrômetros, é visível ao microscópio óptico, mas só no limite: exige objetiva de 100 vezes combinada à ocular de 10, um aumento total de mil vezes, e óleo de imersão. O fungo, com dez a quarenta micrômetros, é confortavelmente visto com objetiva de 40 e aumento total de 400 vezes. *O detalhe que se costuma perder é o papel do óleo:* ele não aumenta nada. Ao substituir a camada de ar entre a lâmina e a objetiva por um meio com índice de refração parecido com o do vidro, ele impede que os raios mais inclinados se desviem e se percam — recupera resolução, que é a capacidade de separar dois pontos vizinhos. Aumentar sem resolver apenas amplia o borrão.

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-09.png",
  largura: 62%,
  legenda: [As três escalas lado a lado. O vírus só aparece ao microscópio eletrônico; a bactéria exige mil vezes de aumento com óleo de imersão; o fungo é visto com 400 vezes. Repare na diferença de tamanho entre o coco de 1 µm e a levedura de dezenas de micrômetros — é a mesma distância que separa uma bola de tênis de um carro.])

Com forma, arranjo e escala na mão, falta a informação que divide o mundo bacteriano ao meio — e ela não está na aparência da célula, está na composição da parede que a envolve. É para lá que a PARTE II vai.

#parte-title("PARTE II — Membrana e parede: o envelope que divide o mundo bacteriano")

#subtopico("2.1 A membrana citoplasmática concentra o que o eucarioto distribui")

A PARTE I fechou com a ideia de que a forma da bactéria é imposta pela parede. Antes de chegar à parede, porém, é preciso passar pela camada que fica logo abaixo dela e que é, essa sim, universal: a membrana citoplasmática. Toda bactéria tem uma, sem exceção, e a composição dela já anuncia o desvio em relação ao que se conhece da célula humana. São cerca de 40% de fosfolipídios formando a bicamada — uma folha dupla com as caudas gordurosas voltadas para dentro e as cabeças com carga voltadas para a água — e cerca de 60% de proteínas mergulhadas nessa bicamada. É uma membrana *proteica* muito mais do que a nossa, e a razão é funcional.

#figura-lateral("/figuras/micro-01-morfologia-estrutura-bacterias/slide-12.png",
  lado: "right",
  largura-figura: 40%,
  texto: [A proporção invertida — mais proteína que lipídio — não é detalhe de composição. Ela existe porque essa única membrana carrega, sozinha, funções que na célula eucariótica estão espalhadas por mitocôndria, retículo endoplasmático e complexo de Golgi. Cada função extra significa mais proteínas ancoradas na bicamada.],
  legenda: [Membrana citoplasmática bacteriana: proteínas (60%) imersas numa bicamada de fosfolipídios (40%).])

Vale percorrer essas funções, porque cada uma reaparece adiante. A primeira é o *transporte de solutos*, e ela tem três modos. Na difusão facilitada, a molécula desce o gradiente por um poro proteico, sem gasto. No transporte ativo, a célula gasta energia para puxar a molécula contra o gradiente. E há um terceiro modo que não existe em nós e merece atenção: a *translocação de grupo*, em que a molécula é quimicamente modificada durante a travessia — a glicose entra já fosforilada. A vantagem é sutil e decisiva: a glicose fosforilada não é reconhecida pelo transportador e portanto não consegue sair, de modo que a modificação química funciona como catraca.

A segunda função é a *produção de energia*. É na membrana citoplasmática que se instala a cadeia transportadora de elétrons e a fosforilação oxidativa — o mesmo processo que em nós ocorre na membrana interna da mitocôndria. Elétrons descem por uma fila de proteínas, cada passagem bombeia prótons para fora da célula, e o gradiente de prótons acumulado é gasto para fabricar ATP. Guarde esse gradiente: ele vai reaparecer na PARTE III como o motor que gira o flagelo. A terceira função é a *biossíntese de macromoléculas* — os próprios lipídios da membrana, o peptidoglicano da parede, os ácidos teicoicos, os polissacarídeos que serão exportados — e é também na membrana que se ancora o complexo que duplica o DNA. A quarta é a *excreção de enzimas hidrolíticas*, que digerem no meio externo o que é grande demais para atravessar. E a quinta é a *taxia*: os sensores que detectam gradientes de nutriente ou de luz são proteínas de membrana.

#mini-resumo[Uma membrana só, carregando transporte, respiração, biossíntese de parede, secreção e sensoriamento — é por concentrar tudo isso que ela tem 60% de proteína.]

#subtopico("2.2 Peptidoglicano: a malha que segura a pressão osmótica")

O citoplasma bacteriano é uma solução concentradíssima de íons, açúcares, aminoácidos e proteínas, muito mais concentrada do que a água do meio em que a bactéria costuma viver. Pela osmose, a água entra sem parar, e a pressão interna que resulta disso chega a vários atmosferas — pressão comparável à de um pneu de caminhão. Uma bicamada de fosfolipídios não aguenta isso por um segundo. A solução bacteriana é envolver a membrana numa malha externa rígida, e essa malha é o #termo-nota[peptidoglicano][polímero misto de açúcares e peptídeos, exclusivo de bactéria; também chamado mureína], ou #termo-nota[mureína][sinônimo de peptidoglicano, do latim _murus_, muro].

A construção dela é simples de descrever e vale ser vista com cuidado, porque três antibióticos importantes atacam exatamente essa construção. O esqueleto é uma cadeia de açúcares alternados: #sigla("NAG", [N-acetilglicosamina — um dos dois açúcares alternados do peptidoglicano]) e #sigla("NAM", [N-acetilmurâmico — o outro açúcar, que carrega o peptídeo lateral]), NAG, NAM, NAG, NAM, indefinidamente. De cada NAM pende um peptídeo curto de quatro aminoácidos — em geral L-alanina, D-glutamato, um aminoácido básico e D-alanina. Essas cadeias paralelas de açúcar são então costuradas umas às outras por ligações entre os peptídeos laterais, e é essa costura, feita por uma enzima chamada transpeptidase, que transforma fios soltos numa rede tridimensional.

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-18.png",
  largura: 60%,
  legenda: [Peptidoglicano. Em cima, o esqueleto de NAG e NAM alternados, com o tetrapeptídeo pendendo de cada NAM e as pontes que ligam uma cadeia à vizinha. Embaixo, o monômero isolado. É essa costura entre cadeias — e só ela — que a penicilina impede de acontecer.])

Duas observações fecham o mecanismo. A primeira é que a malha ligada em rede é, funcionalmente, *uma única macromolécula* envolvendo a célula inteira, como uma sacola de náilon tecida sem costura. Isso explica por que quebrar relativamente poucas ligações já compromete o conjunto. A segunda é a presença de aminoácidos na forma D, que é rara na natureza: as proteases do hospedeiro e de outros micro-organismos reconhecem aminoácidos L, e usar D é uma defesa química contra digestão.

À primeira vista, parece natural pensar que a lisozima da lágrima e a penicilina fazem a mesma coisa, já que ambas destroem a parede. O caminho de cada uma, porém, é oposto — e a diferença tem consequência clínica direta.

#confusao-prevista(
  titulo: "Lisozima desmonta; penicilina impede montar",
  aluno_acha: [aluno junta as duas como "substâncias que destroem a parede"],
  mecanismo: [a *lisozima* é uma enzima que hidrolisa a ligação já existente entre NAG e NAM — ela corta o esqueleto pronto, e por isso age em bactéria parada. A *penicilina* e os demais beta-lactâmicos inibem a transpeptidase, impedindo que a ligação cruzada *nova* se forme. Como só se forma ligação nova em célula que está crescendo e dividindo, o beta-lactâmico só mata bactéria em multiplicação — e é inútil contra uma população dormente.],
)

#mini-resumo[O que ficou de pé: a parede existe para conter a entrada de água por osmose. Sem ela, a célula não murcha — ela estoura.]

#subtopico("2.3 Gram-positivas: parede espessa e ácidos teicoicos")

Se a parede é uma sacola tecida, a diferença entre os dois grandes grupos bacterianos é a espessura do tecido e o que existe por fora dele. Na bactéria Gram-positiva, o tecido é grosso: o peptidoglicano representa de 15% a 60% do peso seco da célula e se organiza em muitas camadas empilhadas e entrecruzadas, formando um bloco de dezenas de nanômetros. Por fora dessa parede não há mais nada — a parede é a superfície da célula, em contato direto com o meio.

Atravessando essa espessura toda, dois polímeros aparecem exclusivamente aqui e vale distingui-los com precisão, porque os nomes são quase iguais e a diferença é de ancoragem. O #termo-nota[ácido teicoico][polímero de ribitol ou glicerol ligado ao peptidoglicano, exclusivo de Gram-positivas] está preso ao próprio peptidoglicano. O #termo-nota[ácido lipoteicóico][variante do ácido teicoico ancorada por uma cauda lipídica na membrana citoplasmática] atravessa a parede toda e ancora-se, por uma cauda lipídica, na membrana citoplasmática abaixo — costurando parede e membrana num conjunto só.

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-19.png",
  largura: 58%,
  legenda: [Envelope Gram-positivo. As muitas camadas de peptidoglicano formam o bloco espesso; os ácidos teicoicos (presos à parede) e lipoteicoicos (ancorados na membrana) atravessam a malha como estacas. À direita, cocos Gram-positivos em cacho corados de roxo — a espessura desta parede é exatamente o que produz aquela cor.])

Esses polímeros não são enchimento estrutural. Eles carregam carga negativa densa, e cada uma das propriedades que decorre disso tem consequência prática. A carga retém cátions divalentes junto à superfície, o que mantém a concentração local de magnésio e cálcio de que várias enzimas de parede dependem. Ela regula a atividade das autolisinas — as enzimas que a própria bactéria usa para abrir brechas na malha e inserir material novo durante o crescimento, um processo que precisa ser controlado com precisão, já que autolisina descontrolada mata a célula. Os ácidos teicoicos funcionam também como adesinas, ajudando a bactéria a grudar no epitélio do hospedeiro, e servem de sítio de ancoragem para bacteriófagos. E, por serem moléculas de superfície variáveis entre espécies, são antígenos — a base da identificação sorológica de vários Gram-positivos.

Um esclarecimento antes de seguir, porque ele previne um erro comum de raciocínio: não ter membrana externa não significa não ter periplasma. A Gram-positiva tem sim um espaço periplasmático entre a membrana citoplasmática e a parede, apenas mais estreito e menos compartimentalizado que o da Gram-negativa. E, sobretudo, não ter endotoxina não significa ser inofensiva. O peptidoglicano e o ácido teicoico são potentes indutores de inflamação por conta própria, e várias Gram-positivas causam doença sobretudo por exotoxinas secretadas — o tétano, o botulismo e a gangrena gasosa são quadros de toxina, não de invasão.

#clinica-box("Gram-positivas e o que elas causam", [Vale ancorar os nomes nos quadros para que a classificação não fique abstrata. Entre os cocos, o *Staphylococcus aureus* — em cacho — causa infecções de pele e pneumonia; o *Streptococcus pneumoniae* — em par — causa pneumonia e meningite; o *Enterococcus* domina infecções do trato urinário em ambiente hospitalar. Entre os bacilos, o gênero *Clostridium* responde por tétano, botulismo e gangrena gasosa, o *Bacillus* por intoxicação alimentar e antraz, e a *Listeria* por infecção alimentar com predileção por gestante e imunossuprimido. Repare no padrão: nos cocos predomina a invasão do tecido; nos bacilos formadores de esporo, predomina o efeito de toxina — o que faz sentido, já que o esporo permite que a bactéria chegue ao alimento ou à ferida em estado latente, germine ali e secrete.])

#subtopico("2.4 Gram-negativas: parede fina, membrana externa e LPS")

Aqui a intuição costuma derrapar. Como se aprende que a Gram-negativa tem "parede fina", é natural concluir que o envelope dela seja mais simples. É o contrário: *o envelope Gram-negativo é o mais complexo dos dois*. O que é fino é apenas o peptidoglicano, que representa cerca de 5% do peso seco e se resume a uma ou poucas camadas. Em compensação, existe uma terceira estrutura que a Gram-positiva não tem — uma segunda membrana, por fora da parede, chamada membrana externa.

Isso cria três compartimentos em vez de dois. De dentro para fora: membrana citoplasmática, depois o *espaço periplasmático*, onde flutua a fina camada de peptidoglicano junto com enzimas de degradação e proteínas de ligação a nutrientes, e depois a membrana externa. O periplasma não é vazio — é um compartimento metabólico ativo, uma espécie de antecâmara onde a célula processa o que capturou antes de deixar entrar.

A membrana externa merece atenção porque ela é assimétrica, e a assimetria é o ponto decisivo. A folha voltada para o periplasma é de fosfolipídios comuns. A folha voltada para o meio externo é feita de #sigla("LPS", [lipopolissacarídeo — molécula exclusiva da folha externa da membrana externa de Gram-negativas]). Como o LPS é uma molécula grande e densamente empacotada, a membrana externa funciona como uma barreira seletiva bem mais fechada que uma bicamada comum: moléculas grandes e hidrofóbicas simplesmente não passam. A célula compensa isso com *porinas*, proteínas em forma de canal que deixam passar moléculas pequenas e hidrofílicas. *O preço dessa arquitetura é farmacológico:* vários antibióticos eficazes contra Gram-positivas não alcançam o alvo em Gram-negativas porque não atravessam a membrana externa — e mutações que fecham porinas são um mecanismo real de resistência.

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-23.png",
  largura: 70%,
  legenda: [Envelope Gram-negativo em detalhe. De baixo para cima: membrana citoplasmática, periplasma com a fina camada de peptidoglicano, e a membrana externa assimétrica — fosfolipídio na folha interna, LPS na externa. O LPS tem três partes: lipídio A ancorado na membrana, o núcleo de açúcares e o polissacarídeo O projetado para fora. A porina é o canal que deixa passar molécula pequena.])

O LPS tem três partes, e separá-las é o que evita o erro mais comum sobre endotoxina. A parte externa, projetada para o meio, é o *polissacarídeo O* — cadeias repetidas de açúcares, altamente variáveis entre cepas da mesma espécie. Ele é o antígeno O, e é sobre ele que se baseia a sorotipagem de salmonelas e escherichias. No meio vem o *núcleo* de açúcares, mais conservado. E ancorado na bicamada está o #termo-nota[lipídeo A][porção lipídica do LPS, responsável por toda a toxicidade da endotoxina], que é a *endotoxina* propriamente dita.

O mecanismo pelo qual o lipídio A adoece o hospedeiro vale ser percorrido inteiro, porque ele explica um quadro clínico completo. Receptores da imunidade inata nas células de defesa reconhecem o lipídio A como assinatura inequívoca de bactéria Gram-negativa. O reconhecimento dispara a liberação maciça de citocinas inflamatórias, que atuam no centro termorregulador produzindo febre, dilatam os vasos e aumentam a permeabilidade capilar. Vasodilatação difusa somada a extravasamento de líquido derruba a pressão arterial; a queda de perfusão leva a hipóxia tecidual, acidose e falência de órgãos. É o choque séptico, e ele nasce de uma molécula estrutural da bactéria.

#atencao-box("A endotoxina é estrutura, não secreção — e por isso pode piorar com o tratamento", [A distinção entre exotoxina e endotoxina não é vocabulário: ela muda o que se espera do paciente. A *exotoxina* é uma proteína que a bactéria fabrica e secreta ativamente; é específica, muito potente, e pode ser neutralizada por antitoxina. A *endotoxina* é o lipídio A, uma peça estrutural da membrana externa que a bactéria não secreta — ela só é apresentada em massa ao hospedeiro quando a bactéria se rompe. A consequência é contraintuitiva e clinicamente real: ao administrar um antibiótico que lisa bactérias Gram-negativas em grande número, libera-se de uma vez uma carga enorme de lipídio A, e o paciente pode piorar nas horas seguintes ao início do tratamento correto. Quem lê endotoxina como "toxina que a Gram-negativa produz" não consegue prever esse fenômeno.])

#clinica-box("Gram-negativas e o que elas causam", [Os representantes mais frequentes seguem uma lógica de porta de entrada. Do trato digestivo vêm a *Escherichia coli* — gastroenterite, intoxicação alimentar e, por via ascendente, infecção urinária —, a *Salmonella*, a *Shigella* e o *Vibrio cholerae* do cólera. Da via respiratória e das mucosas vêm a *Neisseria*, responsável por meningite e gonorreia, e a *Legionella*. Em todos, dois traços estruturais se repetem: o LPS que produz a resposta inflamatória sistêmica e apêndices de adesão que decidem qual mucosa a bactéria consegue colonizar. É por isso que, diante de um paciente com febre alta, hipotensão e bacilos Gram-negativos no material, o raciocínio pula direto para endotoxina.])

#subtopico("2.5 A coloração de Gram: a técnica que lê a parede")

Com as duas arquiteturas descritas, a coloração descrita por Christian Gram em 1884 deixa de ser um protocolo a decorar e vira consequência previsível. O ponto de partida é o que mais se perde: *todas as bactérias da lâmina recebem os mesmos quatro reagentes, na mesma ordem, pelo mesmo tempo*. Não existe um corante para Gram-positiva e outro para Gram-negativa. Quem decide a cor final é a parede.

O primeiro reagente é o *cristal violeta*, um corante básico que atravessa qualquer envelope e cora todas as células de roxo. Nesse momento, a lâmina inteira está roxa e nada foi distinguido ainda. O segundo é o *lugol*, solução de iodo — e ele não é corante, é *mordente*: o iodo reage com o cristal violeta dentro da célula formando um complexo muito maior que a molécula original. A lâmina continua toda roxa, mas agora o pigmento está aprisionado em partículas grandes demais para atravessar uma malha apertada. Sem essa etapa, o passo seguinte descoraria as duas.

O terceiro reagente é o *álcool*, e é aqui que a coloração acontece de fato. Nas duas paredes, ele age de modo oposto. Na Gram-negativa, o álcool dissolve os lipídios da membrana externa e a desorganiza, abrindo brechas; sem essa barreira, e com apenas uma ou poucas camadas de peptidoglicano, o complexo cristal-violeta–iodo escapa e a célula fica incolor. Na Gram-positiva, o álcool desidrata a espessa malha de peptidoglicano, o que a faz encolher e fechar os poros; o complexo, grande, fica preso lá dentro e a célula permanece roxa. *Este é o passo diferencial, e ele é o único cronometrado do procedimento*, porque descolorir por tempo demais arranca o pigmento também da Gram-positiva.

O quarto reagente é a *safranina*, ou fucsina, um contracorante rosa-avermelhado. Ele entra em todas as células, mas na Gram-positiva o roxo já instalado o encobre completamente. O resultado final, portanto, é: Gram-positiva roxa, Gram-negativa rosa — e a Gram-negativa é rosa porque *perdeu* o roxo, não porque recebeu um corante próprio.

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-16.png",
  largura: 72%,
  legenda: [A coloração de Gram passo a passo. Repare na coluna do meio: até a etapa do iodo, todas as células estão roxas. É a descoloração pelo álcool que separa — a Gram-negativa fica incolor e só reaparece com a safranina. À esquerda, o desenho do envelope que explica o resultado: a membrana externa vermelha da Gram-negativa é justamente o que o álcool dissolve.])

Duas armadilhas técnicas decorrem diretamente desse mecanismo e explicam a maioria dos resultados discordantes na rotina. A primeira já foi dita: descoloração excessiva transforma Gram-positiva em falso Gram-negativa. A segunda tem a ver com a idade da amostra — em cultura velha, a Gram-positiva sofre autólise, a parede perde integridade, e a célula deixa de reter o complexo. Nos dois casos, o erro é sempre na mesma direção: *Gram-positiva pode aparecer como negativa; o inverso praticamente não acontece*, porque não há mecanismo que faça uma parede fina reter o corante.

#subtopico("2.6 As quatro fugas do Gram")

A coloração de Gram cobre a grande maioria das bactérias de interesse médico, mas não todas — e as exceções não são caprichos taxonômicos. Cada uma escapa por um motivo estrutural distinto, e reconhecer o motivo é o que indica o método alternativo. São quatro situações, e vale percorrê-las porque cada uma corresponde a doenças importantes.

A primeira é a das *micobactérias*, agentes da tuberculose e da hanseníase. A arquitetura de parede delas é de Gram-positiva — peptidoglicano em quantidade razoável —, mas por cima dessa parede existe uma camada espessa e cerosa de #termo-nota[ácido micólico][ácido graxo de cadeia muito longa que forma a camada cerosa da parede das micobactérias], que impede o corante de entrar. A solução é forçar: na coloração de Ziehl-Neelsen, cobre-se a lâmina com fucsina fenicada e *aquece-se* até emitir vapores, o que amolece a cera e permite a entrada do corante. Em seguida vem a etapa que dá nome ao achado: descolora-se com álcool-ácido, um agente bem mais agressivo que o álcool do Gram. A micobactéria retém a fucsina mesmo assim, e por isso é chamada de #sigla("BAAR", [bacilo álcool-ácido resistente — bactéria que retém a fucsina após descoloração por álcool-ácido]). Contracora-se com azul de metileno, e o resultado é inconfundível: bacilos vermelhos sobre fundo azul. *O gesto conceitual é outro:* o Gram testa a espessura da parede, o Ziehl-Neelsen testa a impermeabilidade da cera.

A segunda é a das *espiroquetas* — *Treponema pallidum* da sífilis, *Leptospira* da leptospirose. O envelope delas é de Gram-negativa, e o corante até entra; o problema é a largura. São células longas mas finíssimas, abaixo do limite de resolução do microscópio óptico, de modo que a bactéria corada continua invisível. As saídas são três, e todas contornam o mesmo obstáculo. Pode-se *espessar* a célula por impregnação com íons de prata, que se depositam na superfície e engrossam o perfil. Pode-se mudar a iluminação para *microscopia de campo escuro*, bloqueando os raios centrais de modo que apenas luz oblíqua atinja a amostra — a bactéria aparece brilhante sobre fundo preto, como poeira num facho de luz. Ou pode-se marcá-la com anticorpo acoplado a fluoróforo, a #sigla("IFD", [imunofluorescência direta — marcação do agente com anticorpo específico ligado a um fluoróforo]).

A terceira é a da *Chlamydia trachomatis*, a bactéria sexualmente transmissível mais frequente e causa importante de infertilidade feminina. Ela tem morfologia de Gram-negativa, mas é *intracelular obrigatória* e muito pequena: não cresce fora da célula hospedeira e não é vista como bactéria livre. O que se observa é o efeito dela sobre a célula infectada — inclusões citoplasmáticas granulosas e densas, evidenciadas pela coloração de Giemsa, exatamente como se procede numa infecção viral. Na prática atual, o diagnóstico é molecular. E há um agravante epidemiológico que decorre da própria biologia: a infecção é frequentemente assintomática, de modo que a lesão tubária se instala sem aviso.

A quarta é a mais radical. *Mycoplasma* e *Ureaplasma* não se coram pelo Gram por uma razão simples: *não têm parede celular*. Não é perda recente nem defeito — a linhagem nunca teve, e a membrana é estabilizada por esteróis incorporados do hospedeiro. Duas consequências vêm juntas. Sem parede, não há forma definida: a célula é pleomórfica e muito pequena, com cerca de 0,3 µm, menor que a maioria das bactérias. E, mais importante, *não há alvo* para nenhum antibiótico que ataque a síntese de parede — o micoplasma é intrinsecamente insensível a beta-lactâmicos, e prescrever um deles nessa infecção é prescrever nada.

#mini-resumo[Em uma frase: micobactéria escapa por cera, espiroqueta por espessura, clamídia por viver dentro da célula, e micoplasma por não ter parede — quatro motivos diferentes, quatro soluções diferentes.]

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-29.png",
  largura: 52%,
  legenda: [Micobactéria e Ziehl-Neelsen. A parede rica em ácido micólico impede a entrada do corante do Gram; a fucsina fenicada aquecida atravessa a cera e, uma vez dentro, resiste à descoloração por álcool-ácido. Os bacilos vermelhos sobre fundo azul do escarro são a leitura do BAAR.])

Com o envelope descrito e os dois grandes grupos separados, o que resta são as estruturas que *nem toda* bactéria tem — e é exatamente por não serem universais que elas explicam por que espécies com o mesmo Gram e a mesma forma se comportam de maneiras tão diferentes.

#parte-title("PARTE III — As estruturas que definem o comportamento")

#subtopico("3.1 Nucleoide e plasmídeo: dois genomas com destinos diferentes")

Tudo o que vem nesta PARTE prepara um ponto que só fecha no fim dela: duas bactérias podem ter a mesma forma e o mesmo resultado no Gram e ainda assim causar doenças completamente diferentes. A diferença está nas estruturas *não universais* — e a primeira delas é genética.

O genoma principal da bactéria é o cromossomo, uma molécula de DNA de fita dupla, circular e única, concentrada na região chamada *nucleoide*. Vale insistir no que essa palavra não significa: não há envoltório, não há histonas organizando o DNA em nucleossomos, não há separação física do citoplasma. A compactação vem de superenovelamento — o DNA torcido sobre o próprio eixo — auxiliado por proteínas associadas. O detalhe importa porque a enzima que administra esse superenovelamento, a DNA girase, não tem equivalente em nós, e é justamente o alvo da classe das quinolonas.

Ao lado do cromossomo, muitas bactérias carregam *plasmídeos*: moléculas de DNA também circulares, muito menores, que se replicam de forma independente porque têm origem de replicação própria. A independência é o traço definidor. O plasmídeo não é um fragmento solto do cromossomo — ele é um genoma acessório, e a célula sobrevive perfeitamente sem ele. O que ele carrega é o que é útil em circunstância específica: genes de resistência a antimicrobianos, fatores de virulência, enzimas metabólicas incomuns.

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-34.png",
  largura: 46%,
  legenda: [Os dois genomas. O nucleoide, com o cromossomo circular único superenovelado, ocupa a região central; os plasmídeos são anéis muito menores, dispersos, que se replicam por conta própria e podem ser transferidos de uma célula a outra.])

A consequência mais pesada dessa arquitetura é que o plasmídeo é *móvel*. E aqui vale organizar os três modos pelos quais uma bactéria adquire DNA de fora, porque tratar tudo como "conjugação" é o erro mais comum do tema. Na *transformação*, a célula capta DNA livre no meio, liberado por outra bactéria que morreu. Na *transdução*, um bacteriófago carrega, por engano, um pedaço de DNA bacteriano de uma célula para a próxima que infectar. Na *conjugação*, duas células se conectam fisicamente por um apêndice e uma cópia do plasmídeo passa de uma para a outra. *A diferença que muda tudo é a última:* a conjugação transfere genes entre bactérias vivas, inclusive entre espécies diferentes, e é por isso que a resistência a antibiótico se espalha por uma população hospitalar numa velocidade que nenhuma mutação isolada explicaria.

#subtopico("3.2 Ribossomo 70S: a diferença que o antibiótico explora")

O ribossomo é a peça mais conservada da vida, presente em absolutamente todas as células, e mesmo assim ele difere entre bactéria e eucarioto o suficiente para sustentar classes inteiras de antibióticos. O ribossomo bacteriano é o *70S*, formado por duas subunidades — a maior de 50S, com rRNA 23S e 5S mais cerca de trinta proteínas, e a menor de 30S, com rRNA 16S mais cerca de vinte proteínas. O nosso é o *80S*, com subunidades de 60S e 40S.

Antes de seguir, um esclarecimento que evita uma conta errada e frequente: o "S" é o coeficiente de sedimentação de Svedberg, que mede a velocidade com que a partícula sedimenta numa ultracentrífuga. Ele depende de massa *e* de forma juntas, e por isso não é aditivo — 50S mais 30S dá 70S, e não 80S, sem que haja erro em lugar nenhum.

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-35.png",
  largura: 58%,
  legenda: [Ribossomo procariótico e eucariótico montados a partir de seus rRNA e proteínas. Em cima, 50S mais 30S formam o 70S bacteriano; embaixo, 60S mais 40S formam o 80S eucariótico. É essa diferença estrutural — não de eficiência — que dá seletividade a boa parte dos antibióticos.])

A diferença estrutural entre 70S e 80S é a base da *toxicidade seletiva*: um antibiótico que se encaixa no 70S trava a síntese proteica da bactéria e passa ao largo do nosso 80S. Os aminoglicosídeos ligam-se ao rRNA 16S da subunidade 30S e fazem o ribossomo ler o código incorretamente, produzindo proteínas defeituosas; os macrolídeos ligam-se à 50S e bloqueiam o avanço da cadeia peptídica. *A parte fina, que a estrutura explica, é o efeito adverso:* a mitocôndria humana tem ribossomos do tipo bacteriano, herança da origem dela, e por isso as reações tóxicas dessas drogas se concentram justamente em tecidos de alta demanda mitocondrial.

O mesmo 16S que serve de alvo é, como se viu na PARTE I, o marcador que desenha a árvore da vida. Uma molécula só, dois usos: régua evolutiva e alvo terapêutico.

#subtopico("3.3 Flagelo: motilidade e taxia")

Imagine um barco a motor com uma hélice na popa — não um remo que bate, mas uma hélice que gira continuamente. O flagelo bacteriano é literalmente isso, e a distinção não é estética: o flagelo do espermatozoide ondula, dobrando-se ao longo do comprimento com gasto direto de ATP, enquanto o flagelo bacteriano é rígido e *gira* em torno da base, empurrando a célula como uma hélice empurra o barco. Bactérias móveis atingem de 200 a 500 micrômetros por segundo — algo como cinquenta a cem vezes o próprio comprimento por segundo.

Três partes compõem a estrutura. O *corpo basal* é o motor, ancorado na membrana citoplasmática e atravessando as camadas do envelope; ele é movido não por ATP, mas pelo gradiente de prótons que a cadeia respiratória acumulou — os prótons voltando para dentro fazem o rotor girar, exatamente como água caindo faz girar uma roda-d'água. O *gancho* é a peça curva que acopla o motor ao filamento. E o *filamento* é o longo apêndice externo, feito de subunidades repetidas de uma única proteína, a *flagelina*.

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-37.png",
  largura: 62%,
  legenda: [Arranjos de flagelo. Monotríquio: um único flagelo em uma extremidade. Anfitríquio: um em cada polo. Lofotríquio: um tufo em um polo. Peritríquio: flagelos distribuídos por toda a superfície. O arranjo é característica estável da espécie e entra na identificação.])

O arranjo dos flagelos na superfície é constante dentro de cada espécie e por isso serve à identificação. São quatro padrões, cada um definido pela posição e pelo número: *monotríquio*, com um único flagelo polar; *anfitríquio*, com um flagelo em cada polo; *lofotríquio*, com um tufo de flagelos num dos polos; e *peritríquio*, com flagelos distribuídos por toda a superfície.

A função que o flagelo serve não é nadar por nadar — é *taxia*, o deslocamento orientado por um gradiente. Na quimiotaxia, a bactéria se move em direção a um nutriente ou para longe de uma substância nociva; na fototaxia, em relação à luz. O mecanismo é mais engenhoso do que parece e vale ser dito, porque a intuição erra aqui. A bactéria não é capaz de "apontar" para a direção certa: ela é pequena demais para comparar concentrações entre a frente e o fundo do próprio corpo. O que ela faz é alternar corridas em linha reta com giros aleatórios que a reorientam ao acaso — e, comparando a concentração *agora* com a de um instante atrás, prolongar a corrida sempre que a concentração estiver subindo. *Ou seja: a bactéria não escolhe a direção, ela apenas insiste mais quando está dando certo* — e o resultado líquido de milhares dessas decisões é um deslocamento eficiente rumo ao gradiente.

Há um segundo papel do flagelo que só aparece quando se pensa no hospedeiro. A flagelina é uma proteína de superfície abundante e altamente antigênica — é o *antígeno H* usado na sorotipagem de salmonelas e escherichias — e é também um dos padrões moleculares que a imunidade inata reconhece de imediato. Vale reter o duplo efeito: o flagelo ajuda a bactéria a alcançar a mucosa e, ao mesmo tempo, denuncia a chegada dela.

#subtopico("3.4 Pili e fímbrias: agarrar e trocar genes")

Se o flagelo resolve o problema de chegar, os pili resolvem o de ficar. E vale marcar bem a diferença, porque a semelhança visual — ambos são fios saindo da superfície — esconde estruturas e funções sem nenhuma sobreposição. O flagelo é longo, ondulado e motorizado; o *pilus*, também chamado *fímbria*, é curto, reto, rígido e não tem motor nenhum. Ele não move a célula; ele a prende.

As fímbrias de adesão são numerosas — centenas por célula — e curtas, e a ponta de cada uma carrega uma proteína chamada adesina, que reconhece um receptor específico na superfície da célula do hospedeiro. Essa especificidade é o que define *onde* uma bactéria consegue se instalar. Sem aderir, a bactéria é levada embora pelo fluxo de muco, de urina ou de conteúdo intestinal antes de conseguir se multiplicar; com a adesina certa, ela resiste ao fluxo e coloniza.

#clinica-box("Fímbria e infecção urinária ascendente", [O exemplo mais direto dessa lógica é a infecção urinária. A *Escherichia coli* é a bactéria mais comum do intestino grosso e, por proximidade anatômica, coloniza a região perineal. A urina flui de dentro para fora, o que deveria varrer qualquer bactéria que subisse pela uretra — e varre, na maioria das vezes. As cepas uropatogênicas, porém, carregam fímbrias específicas, entre elas a chamada fímbria P, cuja adesina reconhece um glicolipídio presente no epitélio urinário. Ancorada, a bactéria resiste ao fluxo e sobe: uretra, bexiga, e daí pelo ureter até a pelve e o parênquima renal, produzindo a pielonefrite. A uretra mais curta da mulher encurta esse trajeto e explica boa parte da diferença de incidência entre os sexos. Repare que *toda* a explicação do quadro está numa proteína de superfície de poucos nanômetros.])

O segundo tipo de pilus é estruturalmente parecido, mas serve a outra coisa inteiramente. O *pilus sexual* é longo e existe em número de um ou poucos por célula. Ele se estende até tocar uma célula receptora, adere e se retrai, aproximando as duas até que se forme uma ponte citoplasmática — e por essa ponte passa uma cópia do plasmídeo. É a conjugação descrita no subtópico 3.1, agora com a peça física à vista. *O ponto que fecha o raciocínio é este:* a resistência a antibiótico não precisa surgir em cada bactéria por mutação própria; basta que uma célula da população a tenha em plasmídeo e disponha de pilus sexual para distribuí-la.

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-39.png",
  largura: 66%,
  legenda: [Flagelo e pili lado a lado. À esquerda, flagelos longos e ondulados, para motilidade; ao centro, fímbrias curtas e numerosas, para adesão. À direita, os dois outros papéis do pilus: o bacteriófago que se ancora nele para infectar a célula, e a ponte de conjugação por onde um plasmídeo passa de uma _E. coli_ para outra.])

Há ainda um terceiro papel, e ele é involuntário: o pilus é *sítio de adesão de bacteriófagos*. Vários vírus de bactéria reconhecem especificamente essa estrutura como ponto de ancoragem para injetar o próprio genoma. A mesma peça que permite trocar genes com uma parceira permite que um vírus entre — e é essa especificidade de reconhecimento que determina quais bactérias um dado fago consegue infectar.

#subtopico("3.5 Cápsula, glicocálice e biofilme: a superfície que esconde e adere")

Por fora de tudo o que já foi descrito, muitas bactérias secretam uma camada de polímeros. O nome geral é *substâncias poliméricas extracelulares*, e vale organizar a terminologia antes de definir cada peça, porque os termos se sobrepõem na literatura. O critério é a organização do material. Quando ele forma uma camada densa, firmemente aderida e com limite nítido ao microscópio, chama-se *cápsula*. Quando é frouxo, difuso, sem contorno definido e se desprende facilmente, chama-se *camada mucosa* ou #termo-nota[glicocálice][revestimento polissacarídico difuso secretado pela bactéria, base estrutural do biofilme]. E quando esse material passa a unir muitas bactérias entre si e a uma superfície sólida, o conjunto vira *biofilme*.

A cápsula é quase sempre polissacarídica e resolve um problema específico: escapar da fagocitose. O mecanismo costuma ser mal compreendido, então vale ser explícito. *A cápsula não mata nem lesa o fagócito* — ela é quimicamente inerte e mecanicamente escorregadia. O que ela faz é impedir o contato: o sistema de defesa marca micro-organismos com opsoninas, moléculas que se depositam na superfície e funcionam como alça para o receptor do fagócito agarrar. Sob a cápsula, a parede fica inacessível, a opsonina não encosta, e sem ponto de agarre não há fagocitose. O hospedeiro só resolve um capsulado quando fabrica anticorpo específico *contra o polissacarídeo da cápsula* — e é exatamente por isso que as vacinas contra pneumococo e meningococo são feitas do polissacarídeo capsular, e não da bactéria inteira.

#confusao-prevista(
  titulo: "Cápsula não é privilégio de Gram-negativa",
  aluno_acha: [aluno associa cápsula a Gram-negativa porque os exemplos clássicos de sepse são Gram-negativos],
  mecanismo: [a cápsula é mais frequente em Gram-negativas — _Klebsiella pneumoniae_, _Neisseria meningitidis_, _Haemophilus influenzae_, _Pseudomonas aeruginosa_ —, mas Gram-positivas capsuladas existem e são clinicamente centrais: _Streptococcus pneumoniae_, _Streptococcus pyogenes_ e _Streptococcus agalactiae_. A cápsula é uma camada *adicional*, depositada por fora do envelope, e independe de o envelope ser de um tipo ou de outro.],
)

O glicocálice difuso resolve outro problema: aderir a superfícies inertes. Ele reveste a bactéria e permite fixação firme em pele, válvula cardíaca, cateter, prótese, dente. À medida que as células aderidas se multiplicam e continuam secretando matriz, forma-se o *biofilme* — uma comunidade organizada, embebida em polímero, grudada na superfície.

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-44.png",
  largura: 64%,
  legenda: [Da cápsula ao biofilme. Em (1), a cápsula definida e aderida; em (2), a camada mucosa difusa, o glicocálice; em (3), a comunidade grudada na superfície, embebida na própria matriz — o biofilme. À direita, as espécies capsuladas, Gram-negativas e Gram-positivas.])

O biofilme importa clinicamente por uma razão que não é resistência genética, e a distinção é fina o bastante para merecer nome próprio. A matriz polimérica dificulta a penetração do antimicrobiano e limita a difusão de oxigênio e nutrientes, de modo que as células do interior ficam em baixa atividade metabólica — quase dormentes. Como boa parte dos antibióticos depende de a bactéria estar crescendo para agir, essas células escapam sem ter nenhum gene de resistência. É *tolerância*, um estado fisiológico reversível, e não resistência herdável. A consequência prática é que infecção de dispositivo raramente se resolve só com antibiótico: costuma ser preciso retirar o dispositivo. *Pseudomonas aeruginosa* no pulmão do paciente com fibrose cística, *Staphylococcus epidermidis* e estreptococos do grupo viridans em válvula cardíaca, e *Streptococcus mutans* na superfície do dente, formando a placa que precede a cárie, são três faces do mesmo mecanismo.

#subtopico("3.6 Esporo e grânulos: sobreviver ao que mataria a célula")

Algumas bactérias resolvem o problema da adversidade de um modo que nenhuma das estruturas anteriores permite: elas desligam. Quando faltam nutrientes, quando o meio seca, quando a temperatura sobe acima do tolerável ou quando aparece um agente químico antibacteriano, parte da população inicia um programa genético de várias etapas chamado *esporulação*, ao fim do qual cada célula produz um *endósporo* — uma estrutura interna, desidratada e metabolicamente inerte, que pode permanecer viável por anos e voltar a germinar quando as condições melhorarem.

Antes de descrever o processo, vale desfazer a comparação que se faz automaticamente com o esporo dos fungos, porque as duas estruturas têm o mesmo nome e propósitos opostos.

#confusao-prevista(
  titulo: "Endósporo é resistência, não reprodução",
  aluno_acha: [aluno transporta a lógica do esporo de fungo, que é forma de dispersão e multiplicação],
  mecanismo: [uma célula vegetativa bacteriana forma *um* endósporo, e esse endósporo germina em *uma* célula. O número de indivíduos não aumenta em nenhum momento — não há reprodução. A esporulação é um estado de latência para atravessar o período ruim, e a bactéria formadora nem sequer se multiplica enquanto esporula: ela para tudo para construir a estrutura.],
)

O processo passa por estágios ordenados. O cromossomo se duplica e se alonga; a membrana invagina e separa uma porção menor do citoplasma, o pré-esporo, que é então *engolfado* pela célula-mãe e passa a existir como compartimento dentro dela. Ao redor dele deposita-se um córtex de peptidoglicano de estrutura modificada, e por fora vêm as capas proteicas do esporo e, em algumas espécies, um envoltório externo adicional. Por fim a célula-mãe se lisa e libera o endósporo maduro.

#figura-nebli("/figuras/micro-01-morfologia-estrutura-bacterias/slide-40.png",
  largura: 70%,
  legenda: [Esporulação e localização do endósporo. À esquerda, os estágios: duplicação do cromossomo, invaginação e engolfamento do pré-esporo, deposição do córtex e das capas, lise da célula-mãe. À direita, as três posições que a estrutura pode ocupar — terminal, subterminal e central —, característica estável de cada espécie.])

A resistência extraordinária do endósporo não vem da casca, e essa é a parte que merece ser entendida em mecanismo. Vem de três coisas somadas. Primeiro, a *desidratação profunda do núcleo*: sem água livre, as reações de degradação que o calor catalisa simplesmente não acontecem, e é isso que confere termorresistência. Segundo, o acúmulo de #termo-nota[ácido dipicolínico][composto que, complexado a cálcio, substitui a água no núcleo do esporo e estabiliza suas macromoléculas] complexado a cálcio, que ocupa o lugar da água e estabiliza as macromoléculas. Terceiro, um conjunto de proteínas pequenas — as #sigla("SASP", [small acid-soluble proteins — proteínas pequenas que revestem o DNA do esporo e o protegem de calor e radiação]) — que se ligam ao DNA, alteram a conformação dele e o protegem de calor, radiação ultravioleta e agentes químicos.

#clinica-box("Por que fervura não basta", [A consequência prática dessa arquitetura é direta e define a rotina de esterilização. Água fervente a 100 °C mata a forma vegetativa de praticamente qualquer bactéria em minutos, mas não mata o endósporo — no interior desidratado não há água livre para conduzir a desnaturação. Por isso a esterilização de material cirúrgico exige vapor *sob pressão*, tipicamente 121 °C, temperatura que só se alcança em autoclave. A mesma propriedade explica o perfil das doenças causadas por esporulados. O *Clostridium tetani* vive no solo como esporo, entra por ferimento perfurante, encontra tecido desvitalizado e pouco oxigênio, germina ali e secreta a toxina do tétano. O *Clostridium botulinum* germina em conserva mal processada. O *Bacillus cereus* sobrevive ao cozimento do arroz e germina enquanto o alimento esfria devagar — motivo pelo qual reaquecer não resolve, se a toxina já foi produzida. Repare que a estrutura, e não a virulência, é o que define a via de contágio.])

A posição do endósporo dentro da célula é constante para cada espécie — terminal, subterminal ou central — e por isso entra na identificação morfológica. E vale um registro final sobre quem esporula: a capacidade é restrita a poucos gêneros, quase todos Gram-positivos, sendo *Bacillus* e *Clostridium* os de interesse médico. Não é uma resposta que qualquer bactéria improvise sob estresse.

Fecham a lista os *grânulos citoplasmáticos*, depósitos de reserva que a célula acumula quando a fonte de energia sobra e o crescimento está limitado por outro nutriente. São inclusões de fósforo, de enxofre, de polímeros de carbono — reservas guardadas para o momento em que faltarem. Não são organelas: não têm bicamada verdadeira ao redor, e sua função é puramente de armazenamento.

#conclusao-box[
Um único princípio organiza tudo o que foi visto: *na bactéria, a estrutura é a função, e a função é o que se lê no laboratório e o que se ataca no tratamento*. Sem organelas para dividir tarefas, cada peça do envelope e cada apêndice de superfície resolve um problema de sobrevivência de forma direta e verificável — e é justamente por serem tão diretos que esses componentes servem simultaneamente de critério de classificação, de mecanismo de doença e de alvo terapêutico.

O mecanismo nuclear da aula é a *parede celular*. Ela existe porque o citoplasma hiperosmótico atrai água e a célula estouraria sem uma malha externa que contenha a pressão; a malha é o peptidoglicano, costurado em rede pela transpeptidase. A partir dessa peça única, tudo se ramifica. A espessura dessa malha e a presença ou ausência de uma membrana externa dividem as bactérias em dois grandes grupos, e essa mesma diferença — malha espessa que aprisiona o complexo cristal-violeta–iodo contra malha fina cuja membrana externa o álcool dissolve — é o que a coloração de Gram lê em minutos. Quem escapa do Gram escapa por um desvio estrutural nomeável: cera de ácido micólico, largura abaixo da resolução da luz, vida intracelular obrigatória, ou ausência total de parede.

Na clínica, essa cadeia aparece inteira. O lipídio A, âncora estrutural do LPS na folha externa da membrana externa, é reconhecido pela imunidade inata e dispara a cascata de citocinas que produz febre, vasodilatação e hipotensão — e, por ser estrutura e não secreção, é liberado em massa quando o antibiótico lisa a bactéria, o que explica a piora paradoxal nas primeiras horas do tratamento correto. A fímbria com a adesina certa é o que permite a uma bactéria intestinal subir contra o fluxo da urina até o rim. A cápsula bloqueia o contato entre opsonina e parede, e por isso a vacina contra capsulados é feita do polissacarídeo capsular. O endósporo desidratado com dipicolinato de cálcio atravessa a fervura, e por isso a autoclave existe.

O que vem a seguir é a continuação natural dessa lógica. Descrita a célula parada, o passo seguinte é vê-la em movimento: como uma população cresce em fases, quanto tempo cada espécie leva para dobrar, e por que essa cinética decide desde o tempo de espera de uma cultura até a razão pela qual o beta-lactâmico só age em bactéria que está se dividindo. Depois vem o controle — quais agentes matam qual estrutura, e por que a escolha entre calor, químico e radiação depende exatamente do que se descreveu aqui.
]
