#import "../typst-template/nebli_v2_apostila.typ": *

#pre-aula-page[
Esta é a primeira aula de bacteriologia, e ela tem uma ambição maior do que o título sugere. "Morfologia e estrutura" soa como um inventário de peças a decorar, mas o que a professora vai construir é outra coisa: um raciocínio que liga o formato de uma célula de poucos micrômetros à conduta clínica de um paciente com febre. Vale chegar sabendo que esse é o fio. Cada estrutura que aparecer no slide vai ser apresentada três vezes seguidas, em três papéis distintos — como solução física de um problema de sobrevivência, como critério que o laboratório usa para identificar a bactéria, e como alvo de antibiótico. Quem enxerga o fio guarda a aula inteira; quem só anota as peças sai com uma lista.

A aula abre longe da clínica, com a árvore da vida. A professora vai mostrar que os seres vivos se dividem em *três domínios* — Bactéria, Arqueia e Eucarioto —, uma classificação proposta por Woese em 1977 a partir da comparação de sequências do *rRNA*, o RNA que compõe o ribossomo e existe em todo organismo celular. O argumento é que essa molécula muda muito devagar, então contar diferenças entre duas sequências é medir o tempo desde que as duas linhagens se separaram. Guarde o *16S*, o rRNA da subunidade menor do ribossomo bacteriano: ele reaparece no fim da aula, agora como alvo de antibiótico, e essa dobra é uma das melhores da matéria. A palavra *procarioto* — "antes do núcleo" — vai ser usada como se você já soubesse o que ela obriga: sem envoltório nuclear, transcrição e tradução acontecem juntas; sem mitocôndria, a produção de energia migra para a membrana; sem retículo, a síntese e a exportação de macromoléculas também.

Do panorama a aula desce para o laboratório, e aqui aparece o motivo prático de estudar morfologia. O caminho do diagnóstico tem duas velocidades. A rápida é a *bacterioscopia*: um esfregaço, uma coloração, alguns minutos ao microscópio, e o material sai classificado em um de quatro grandes grupos pelo cruzamento de forma com resultado de coloração. A lenta é a cultura, seguida de testes bioquímicos, teste de sensibilidade a antimicrobianos e métodos moleculares — mais específica, e por isso mesmo mais demorada. É a leitura rápida que orienta o tratamento inicial, e essa é a razão de a aula inteira existir.

Em seguida vêm duas escalas de observação que a professora chama de morfologia macroscópica e microscópica. Na macroscópica o objeto é a *colônia*: o monte visível a olho nu formado quando uma única bactéria se multiplica sobre meio sólido até virar um clone de cerca de cem milhões de células. Vão aparecer os *meios diferenciais*, em que um indicador de pH traduz o metabolismo bacteriano em cor, e a *hemólise*, o halo transparente que uma toxina secretada deixa ao destruir hemácias do meio. Na microscópica entram os nomes de forma — *coco*, *bacilo* e as espiraladas, com a subdivisão em *espiroqueta*, *espirilo* e *vibrião* — e os nomes de arranjo, como *estreptococo* e *estafilococo*, que registram não como as células se juntaram, mas o plano em que se dividiram.

O núcleo da aula é a parte seguinte, e é onde vale investir atenção. Depois da *membrana citoplasmática*, que na bactéria acumula funções que em nós estão espalhadas por organelas, vem a *parede celular*. Ela é feita de *peptidoglicano*, também chamado *mureína* — cadeias dos açúcares *NAG* e *NAM* alternados, com peptídeos curtos costurando uma cadeia à vizinha. A parede existe porque o citoplasma é hiperosmótico e a água entra sem parar; sem essa malha, a célula estoura. É a espessura dessa malha que separa as bactérias em dois grandes grupos. Nas *Gram-positivas*, ela é espessa e atravessada por *ácido teicoico* e *ácido lipoteicóico*, dois polímeros que diferem pelo ponto de ancoragem. Nas *Gram-negativas*, ela é fina, fica num *espaço periplasmático* e é coberta por uma *membrana externa* cuja folha voltada para fora é feita de *LPS*, o lipopolissacarídeo. O LPS tem três segmentos, e o que interessa é o *lipídio A*: a *endotoxina*, peça estrutural que dispara febre e hipotensão quando reconhecida pela imunidade inata.

Com isso na mão, a *coloração de Gram* deixa de ser protocolo e vira consequência. Todas as células recebem os mesmos quatro reagentes na mesma ordem — cristal violeta, iodo, álcool, safranina. O iodo é *mordente*, não corante: ele aprisiona o cristal violeta num complexo grande demais para atravessar uma malha apertada. O álcool é o passo que separa. Preste atenção nesse ponto, porque a explicação inteira mora nele.

A professora fecha essa parte com as bactérias que escapam do Gram, e cada uma escapa por um motivo diferente. A micobactéria tem uma camada cerosa de *ácido micólico* que impede o corante de entrar, e por isso exige a coloração de *Ziehl-Neelsen*, que revela o *BAAR*, o bacilo álcool-ácido resistente. A espiroqueta é fina demais para a luz visível e pede impregnação por prata, *campo escuro* ou *imunofluorescência*. A clamídia é *intracelular obrigatória* e pequena demais para ser vista como bactéria livre. E o micoplasma simplesmente não tem parede.

A última parte percorre as estruturas que nem toda bactéria tem — e é por não serem universais que elas explicam diferenças de comportamento. Vão aparecer o *nucleoide*, região onde o cromossomo circular único se concentra, e o *plasmídeo*, genoma acessório que se replica sozinho e carrega genes de resistência. Vem o ribossomo *70S*, diferente do nosso 80S, e é essa diferença que dá seletividade a boa parte dos antibióticos. Vêm os *flagelos*, com o filamento de *flagelina* e os arranjos *monotríquio*, *anfitríquio*, *lofotríquio* e *peritríquio*, servindo à *taxia*. Vêm os *pili* ou *fímbrias*, que aderem ao epitélio e, no caso do pilus sexual, conduzem a *conjugação*. Vem a *cápsula*, o *glicocálice* e o *biofilme*, camadas de polímero que escondem a bactéria da fagocitose e a fixam em cateter, válvula e dente. E fecham os *endósporos*, formas de latência que atravessam a fervura.

Chegue com esse mapa na cabeça: uma parede que resolve a osmose, uma coloração que lê essa parede, e um punhado de estruturas acessórias que decidem se a bactéria adere, se move, se esconde ou espera.
]
