#import "../typst-template/nebli_v2_apostila.typ": *

#discursiva("Q1",
  [Explique, em termos termodinâmicos e estruturais, por que o NADH rende mais ATP que o FADH₂ ao ser oxidado pela cadeia respiratória. Sua resposta deve mencionar potenciais de redução, ponto de entrada na cadeia e estequiometria de bombeamento de prótons.],
  [O NADH (E°' = −0,32 V) é doador mais energético que o FADH₂ (E°' ≈ 0 V); cai por um trecho maior da escada eletroquímica. Entra pelo Complexo I, que bombeia 4 H⁺ por par de elétrons, e os elétrons seguem por III (4 H⁺ via ciclo Q) e IV (2 H⁺), totalizando 10 H⁺. O FADH₂ entra pelo Complexo II, que *não* bombeia prótons (degrau termodinâmico insuficiente), e os elétrons só geram bombeamento em III + IV = 6 H⁺. Pelo P/O moderno: NADH = 2,5 ATP; FADH₂ = 1,5 ATP. A diferença reflete diretamente a estequiometria de bombeamento.])

#discursiva("Q2",
  [Um paciente é trazido com convulsão e parada respiratória após ingestão de cianeto. Descreva o mecanismo bioquímico que explica por que o cianeto mata em minutos, por que o sangue venoso retorna vermelho-cereja, e por que a oferta de O₂ por máscara facial não reverte o quadro.],
  [O cianeto liga-se com altíssima afinidade ao Fe³⁺ do heme a#sub[3] do Complexo IV, impedindo a transferência terminal de elétrons ao O₂. Toda a cadeia para por cascata reversa: cit c não descarrega, III bombeia para, CoQ acumula reduzida, I e II travam. *Hipóxia histotóxica*: há O₂ no sangue, mas a célula não consegue usá-lo. O sangue venoso volta vermelho-cereja porque o O₂ não foi consumido pelos tecidos. Aumentar O₂ por máscara não resolve — o problema não é falta de O₂, é incapacidade de aceitá-lo. Tratamento: hidroxocobalamina ou nitrito + tiossulfato, que sequestram o CN⁻.])

#discursiva("Q3",
  [Por que a oligomicina, que bloqueia *apenas* a ATP sintase, faz a cadeia respiratória parar em seguida e o consumo de O₂ cessar? Explique o conceito de controle respiratório pelo ADP e o papel do gradiente saturado.],
  [Oligomicina liga-se a F#sub[0] e bloqueia a passagem de prótons pelo rotor. Sem retorno de H⁺, o gradiente eletroquímico cresce ao máximo. Os complexos da cadeia precisam vencer esse gradiente para continuar bombeando — quando a PMF está saturada, o custo termodinâmico de bombear contra ela torna-se proibitivo, e os complexos *param por retroinibição termodinâmica*. O consumo de O₂ no Complexo IV cessa porque os elétrons não fluem mais até lá. O controle respiratório fisiológico opera pelo mesmo princípio: sem ADP livre, a sintase não gira, o gradiente sobe, e a cadeia frena automaticamente. ADP é o sinal-chave da regulação.])

#discursiva("Q4",
  [Compare as lançadeiras malato-aspartato e glicerol-3-fosfato quanto a tecidos de uso, mecanismo, rendimento de ATP por NADH citosólico e justificativa fisiológica para a escolha tecidual.],
  [A malato-aspartato (fígado, rim, coração) preserva o equivalente redutor: o NADH citosólico reduz oxaloacetato a malato; malato cruza a membrana e é reoxidado a oxaloacetato dentro da matriz gerando NADH mitocondrial. Rendimento: 2,5 ATP. Saldo total da glicose: 32 ATP. A glicerol-3-P (músculo esquelético, cérebro) reduz diidroxiacetona-fosfato a glicerol-3-P, que é reoxidado por uma desidrogenase membranar entregando elétrons direto à CoQ como FADH₂ — bypassa o Complexo I. Rendimento: 1,5 ATP. Saldo: 30 ATP. Tecidos lentos e eficientes (fígado, coração) preferem a malato-aspartato (mais ATP); tecidos com turnover rápido (músculo em exercício, cérebro) preferem a glicerol-3-P, irreversível e veloz.])

#discursiva("Q5",
  [Explique o mecanismo da termogênese sem tremor em recém-nascidos: como o frio é detectado, qual tecido é mobilizado, qual proteína é a peça central, e por que esse mecanismo é essencial em neonatos mas em adultos foi historicamente subestimado. Inclua o conceito de desacoplamento controlado e contraste com o desacoplamento patológico do dinitrofenol.],
  [O frio ativa terminais simpáticos sobre o *tecido adiposo marrom* (abundante em neonatos em pescoço, escápulas e perirrenal). Norepinefrina liga-se a receptores β#sub[3]-adrenérgicos do adipócito marrom; estimula lipólise; ácidos graxos livres ativam a *UCP1 (termogenina)*, proteína da membrana mitocondrial interna. UCP1 cria um canal *regulado* para retorno de prótons sem passar pela ATP sintase: o gradiente é dissipado como calor controlado. A cadeia respiratória continua bombeando e até acelera — toda a energia química vira calor útil. Neonatos não tremem com eficiência (sistema motor imaturo), então dependem desse mecanismo para sobreviver às primeiras horas. Em adultos, foi tido por décadas como vestigial, até que imagem PET-CT mostrou tecido adiposo marrom funcional em pescoço/supraclavicular ativável por frio. O DNP é um desacoplador *patológico*: difusível, sem regulação, atinge mitocôndrias de todos os tecidos simultaneamente — daí hipertermia maligna e morte. A UCP1 é a versão fisiológica do mesmo princípio, restrita a um tecido específico e controlada hormonalmente.])
