#import "../typst-template/nebli_v2_apostila.typ": *

// =================================================================
// CONSOLIDAÇÃO (Q01–Q08) — fundamentos diretos do mecanismo
// =================================================================

#questao-mc("01", badge-consolidacao,
  [Sobre a razão termodinâmica pela qual a oxidação do NADH pelo O₂ é realizada em múltiplas etapas (fracionada), é correto afirmar:],
  (("A", [O fracionamento existe porque uma única transferência seria cineticamente lenta demais, e a célula precisa acelerar a reação dividindo-a em pequenos passos catalisados independentemente.]),
   ("B", [A divisão em complexos foi selecionada evolutivamente para permitir maior regulação alostérica em cada complexo, controlando finamente a velocidade da respiração.]),
   ("C", [O ΔG total da oxidação (cerca de −220 kJ/mol) não pode ser capturado em um único passo enzimático; o fracionamento permite que cada degrau de ~20 kJ/mol seja convertido em bombeamento de prótons em vez de calor.]),
   ("D", [A fragmentação da oxidação em quatro complexos distintos serve para distribuir os intermediários redox reativos por mais sítios enzimáticos ativos diferentes, diminuindo significativamente a chance de formação de espécies reativas de oxigênio durante a transferência sequencial de elétrons do NADH ao oxigênio molecular terminal.]),
   ("E", [Cada complexo da cadeia respiratória libera quantidade idêntica de energia (cerca de 55 kJ/mol por par de elétrons transferido), o que padroniza o bombeamento de prótons em cada degrau e simplifica enormemente o controle bioenergético global da via fosforilativa oxidativa em diferentes tecidos do organismo humano.])))

#questao-ce("02", badge-consolidacao,
  [Sobre potenciais de redução (E°') e a ordem dos componentes da cadeia respiratória, julgue os itens:],
  ((
    ("I", [Elétrons fluem espontaneamente do par redox com E°' mais negativo para o par com E°' mais positivo, porque o par mais positivo tem maior afinidade por elétrons.]),
    ("II", [O par NAD⁺/NADH (E°' = −0,32 V) doa elétrons mais "alto" na escada eletroquímica do que o par FAD/FADH₂ (E°' próximo de zero), o que explica em parte por que NADH rende mais ATP.]),
    ("III", [A ordem física dos complexos na membrana é determinada por proximidade geográfica de síntese ribossomal, e poderia ser invertida sem prejuízo funcional se a transferência de elétrons fosse rápida.]),
    ("IV", [O ΔG°' da transferência de elétrons depende diretamente da diferença de potenciais padrão (ΔE°') e do número de elétrons transferidos, pela relação ΔG°' = −nFΔE°'.])
  )))

#questao-mc("03", badge-consolidacao,
  [Sobre a anatomia da mitocôndria e a localização dos componentes da cadeia respiratória, é correto afirmar:],
  (("A", [Os quatro complexos da cadeia respiratória estão dissolvidos na matriz mitocondrial junto com as enzimas do ciclo de Krebs, formando um complexo solúvel multienzimático.]),
   ("B", [A membrana mitocondrial externa é responsável por manter o gradiente de prótons graças à sua impermeabilidade seletiva, enquanto a interna é porosa e permite trocas com o citosol.]),
   ("C", [Os quatro complexos estão cravados na membrana mitocondrial externa, e os transportadores CoQ e citocromo c se movimentam pelo espaço intermembranas.]),
   ("D", [Os complexos da cadeia respiratória estão cravados na membrana mitocondrial interna; a única enzima do ciclo de Krebs presente nessa membrana é a succinato desidrogenase, que também é o Complexo II.]),
   ("E", [A coenzima Q é uma proteína periférica solúvel localizada no espaço intermembranas, enquanto o citocromo c é uma quinona lipossolúvel que difunde dentro da bicamada lipídica.])))

#questao-mc("04", badge-consolidacao,
  [Comparando a coenzima Q (CoQ) e o citocromo c quanto à natureza química, localização e mobilidade na membrana mitocondrial interna, é correto afirmar:],
  (("A", [CoQ é uma proteína integral covalentemente fixa na membrana mitocondrial interna, enquanto citocromo c é uma proteína periférica fixa rigorosamente posicionada que conecta especificamente os Complexos III e IV pela bicamada lipídica sem se mover lateralmente.]),
   ("B", [CoQ é uma benzoquinona lipossolúvel que difunde lateralmente dentro da bicamada lipídica carregando 2 elétrons; citocromo c é uma proteína periférica hidrossolúvel que se move pela face externa da membrana interna carregando 1 elétron por vez.]),
   ("C", [Ambos são proteínas com grupo heme, sendo que CoQ tem heme do tipo a e citocromo c tem heme do tipo b, o que explica suas diferentes afinidades por elétrons.]),
   ("D", [CoQ é hidrossolúvel no espaço intermembranas e citocromo c é lipossolúvel cravado dentro da bicamada lipídica, e ambos carregam 2 elétrons simultaneamente por molécula, formando a base estequiométrica simétrica do funcionamento do ciclo Q em duas etapas.]),
   ("E", [CoQ recebe elétrons exclusivamente do Complexo I (NADH desidrogenase) e citocromo c entrega elétrons exclusivamente ao Complexo III (ubiquinol-citocromo c oxidorredutase), sem participação alguma em outros complexos da cadeia respiratória mitocondrial humana adulta.])))

#questao-ce("05", badge-consolidacao,
  [Sobre os Complexos I e II da cadeia respiratória, julgue os itens:],
  ((
    ("I", [O Complexo I (NADH:ubiquinona oxidorredutase) bombeia 4 prótons da matriz para o espaço intermembranas por par de elétrons transferido do NADH para a CoQ.]),
    ("II", [O Complexo II contém FAD covalentemente ligado e bombeia 2 prótons por par de elétrons, mecanismo que explica o saldo intermediário de ATP gerado pelo FADH₂ do succinato.]),
    ("III", [A succinato desidrogenase, que catalisa a oxidação do succinato a fumarato no ciclo de Krebs, é a mesma enzima que constitui o Complexo II da cadeia respiratória, e por isso é a única enzima do ciclo cravada na membrana.]),
    ("IV", [No Complexo I, o FMN aceita 2 elétrons e 2 prótons do NADH, e os elétrons então descem por uma série de centros ferro-enxofre que aceitam apenas elétrons, sem prótons.])
  )))

#questao-mc("06", badge-consolidacao,
  [Sobre o ciclo Q e o Complexo III, é correto afirmar:],
  (("A", [O ciclo Q é um mecanismo de duas etapas que utiliza duas moléculas de CoQH₂ em sítios diferentes do Complexo III (Q#sub[o] e Q#sub[i]) para casar a estequiometria entre CoQ (2 e⁻) e citocromo c (1 e⁻), bombeando 4 H⁺ por par de elétrons.]),
   ("B", [O ciclo Q ocorre exclusivamente no Complexo I da cadeia e serve para regenerar a CoQ oxidada a partir da CoQH₂ vinda do FADH₂ do Complexo II adjacente, permitindo que a CoQ entre novamente no Complexo II como aceptora basal em ciclos sucessivos de turnover enzimático.]),
   ("C", [O ciclo Q é um processo termodinamicamente desfavorável que requer hidrólise direta de ATP citosólico transportado pelo translocador para acoplar a transferência de elétrons entre CoQ e citocromo c, ocorrendo apenas em condições anaeróbicas ou de hipóxia tecidual aguda.]),
   ("D", [O Complexo III bombeia apenas 2 prótons por par de elétrons no fluxo basal, valor reduzido pela necessidade fisiológica do ciclo Q de manter o citocromo c periférico sempre completamente reduzido no estado de repouso celular para permitir resposta rápida ao estresse oxidativo agudo.]),
   ("E", [O ciclo Q transfere elétrons diretamente do Complexo II para o citocromo c periférico, sem participação da CoQ móvel da bicamada lipídica, o que explica fisiologicamente por que o FADH₂ pode bypassar parte considerável da cadeia respiratória em tecidos com alta demanda energética aguda.])))

#questao-mc("07", badge-consolidacao,
  [Sobre o Complexo IV (citocromo c oxidase) e a reação final da cadeia respiratória, é correto afirmar:],
  (("A", [O Complexo IV reduz o O₂ diretamente a peróxido de hidrogênio (H₂O₂) como produto bioquímico final normal da redução parcial, e em seguida o H₂O₂ é decomposto a H₂O e O₂ molecular por uma catalase periférica especificamente associada à face matricial da membrana mitocondrial interna humana adulta.]),
   ("B", [O Complexo IV bombeia 4 prótons por par de elétrons em condições basais de repouso celular e produz 4 moléculas de H₂O por O₂ molecular consumido na reação terminal, sendo responsável por aproximadamente metade do gradiente eletroquímico total da cadeia respiratória mitocondrial em todos os tecidos.]),
   ("C", [O cianeto bloqueia o Complexo I por ligação direta ao FMN da NADH desidrogenase, impedindo a transferência inicial dos elétrons do NADH para os centros ferro-enxofre internos do complexo e parando toda a cadeia respiratória em poucos segundos pela retroinibição em cascata sequencial.]),
   ("D", [O Complexo IV transfere elétrons diretamente da CoQ lipossolúvel ao O₂ molecular sem participação do citocromo c periférico, o que explica fisiopatologicamente por que a perda do citocromo c citoplasmático por apoptose interrompe seletivamente o Complexo III e não a redução do oxigênio terminal.]),
   ("E", [O Complexo IV reduz completamente o O₂ a 2 H₂O utilizando 4 elétrons e 4 H⁺ no centro binuclear heme a#sub[3]–CuB, bombeando 2 prótons por par de elétrons; sua inibição por cianeto causa hipóxia histotóxica.])))

#questao-ce("08", badge-consolidacao,
  [Sobre a ATP sintase F#sub[0]F#sub[1] e a teoria do binding change de Paul Boyer, julgue os itens:],
  ((
    ("I", [A subunidade F#sub[0] é cravada na membrana mitocondrial interna e contém o anel de subunidades c que gira pelo fluxo de prótons do espaço intermembranas para a matriz.]),
    ("II", [A subunidade F#sub[1], projetada para a matriz, contém 3 sítios catalíticos (subunidades β) que alternam entre as conformações Open (libera ATP), Loose (captura ADP+Pi) e Tight (forma ATP), gerando 3 ATPs por volta completa do rotor.]),
    ("III", [A energia da força próton-motriz é usada principalmente para formar a ligação química entre ADP e Pi no sítio T, que sem essa energia seria altamente endergônica.]),
    ("IV", [Oligomicina liga-se à subunidade F#sub[0] e bloqueia a passagem de prótons pelo rotor, inibindo a síntese de ATP e, indiretamente, parando a cadeia respiratória por retroinibição termodinâmica do gradiente saturado.])
  )))

// =================================================================
// INTEGRAÇÃO (Q09–Q25) — cruzamentos entre subtópicos
// =================================================================

#questao-mc("09", badge-integracao,
  [Considere um par de elétrons que entra na cadeia respiratória via NADH. Sobre a estequiometria de bombeamento de prótons em cada complexo e o total ao longo do trajeto até o O₂, é correto afirmar:],
  (("A", [O par bombeia 2 H⁺ no Complexo I, 2 H⁺ no Complexo II, 4 H⁺ no Complexo III e 2 H⁺ no Complexo IV, totalizando 10 H⁺ por par de elétrons que descem pela cadeia completa.]),
   ("B", [O par bombeia 4 H⁺ no Complexo I, zero no Complexo II (que é bypassado pelo NADH), 4 H⁺ no Complexo III pelo ciclo Q e 2 H⁺ no Complexo IV, totalizando 10 H⁺ por par de elétrons.]),
   ("C", [O par bombeia 6 H⁺ no Complexo I, 0 no Complexo II, 2 H⁺ no Complexo III sem ciclo Q e 4 H⁺ no Complexo IV, totalizando 12 H⁺ por par de elétrons que cruzam toda a cadeia.]),
   ("D", [O par bombeia 4 H⁺ no Complexo I, 2 H⁺ no Complexo II via FAD, 2 H⁺ no Complexo III e 4 H⁺ no Complexo IV reduzindo O₂, totalizando 12 H⁺ por par de elétrons.]),
   ("E", [O par bombeia quantidades iguais (2 H⁺) em cada um dos quatro complexos e ainda 2 H⁺ adicionais consumidos pela ATP sintase, totalizando 10 H⁺ por par de elétrons.])))

#questao-mc("10", badge-integracao,
  [Sobre o conceito moderno de P/O ratio (P/O = 2,5 para NADH e 1,5 para FADH₂) em comparação com o valor clássico (3 e 2 respectivamente), é correto afirmar:],
  (("A", [O P/O moderno foi reduzido principalmente porque experimentos recentes em mitocôndrias isoladas descobriram que o Complexo I bombeia apenas 2 prótons por par de elétrons (não os 4 historicamente atribuídos), o que ajustou matematicamente o cálculo estequiométrico para 2,5 ATP por NADH e 1,5 ATP por FADH₂ em todos os tecidos humanos.]),
   ("B", [Os valores modernos refletem o achado experimental de que o Complexo IV não bombeia prótons ativamente na realidade fisiológica, e apenas consome 4 prótons da matriz quimicamente para formar 2 H₂O na reação terminal com O₂, alterando significativamente o saldo final estequiométrico por par de elétrons que cruza a cadeia respiratória completa.]),
   ("C", [O P/O moderno levou em conta a presença do ciclo Q no Complexo III, que dobra o bombeamento de prótons nesse complexo central, mas ainda usa o valor antigo histórico de 3 H⁺ por ATP sintetizado na ATP sintase F#sub[0]F#sub[1], gerando assim os valores reduzidos por contabilidade conservadora dos custos celulares.]),
   ("D", [O P/O moderno (2,5 e 1,5) considera que o anel F#sub[0] da ATP sintase humana tem 8 subunidades c (não 9 ou 10) e os custos de transporte de ADP/ATP/Pi, totalizando ~3,7 H⁺ por ATP citosólico — daí a redução em relação aos valores históricos de 3 e 2.]),
   ("E", [Os valores P/O foram reduzidos exclusivamente devido a custos de bombeamento reverso de cálcio mitocondrial pelo uniportador MCU em todos os tecidos humanos, que consomem parte significativa do gradiente em condições fisiológicas normais de homeostase celular mas eram completamente ignorados nos cálculos clássicos pré-genômicos.])))

#questao-mc("11", badge-integracao,
  [Sobre as lançadeiras do NADH citosólico (malato-aspartato e glicerol-3-fosfato) e suas consequências sobre o saldo de ATP, é correto afirmar:],
  (("A", [A lançadeira malato-aspartato transfere os elétrons do NADH citosólico diretamente ao Complexo II via FAD ligado covalentemente à succinato desidrogenase, gerando 1,5 ATP por NADH original, enquanto a glicerol-3-P entrega ao Complexo I via NADH mitocondrial regenerado, gerando 2,5 ATP por NADH original, com saldo total da oxidação completa da glicose em 32 ATP no tecido muscular esquelético em exercício submáximo prolongado.]),
   ("B", [Ambas as lançadeiras citosólicas entregam o equivalente redutor final como NADH mitocondrial na matriz, rendendo 2,5 ATP por NADH original em todos os tecidos humanos saudáveis, mas a malato-aspartato é cineticamente mais lenta que a glicerol-3-P e por isso o cérebro humano prefere usar a glicerol-3-P, mesmo com saldo final energético equivalente entre as duas vias.]),
   ("C", [A malato-aspartato (fígado, rim, coração) preserva o NADH citosólico como NADH mitocondrial via transaminações e transporte de malato, rendendo 2,5 ATP por NADH original e saldo total de 32 ATP por glicose; a glicerol-3-P (músculo esquelético, cérebro) converte para FADH₂ via desidrogenase membranar, bypassa o Complexo I e rende 1,5 ATP por NADH original, com saldo de 30 ATP.]),
   ("D", [Tanto a lançadeira malato-aspartato quanto a glicerol-3-P transferem fisicamente a molécula de NADH inteira através da membrana mitocondrial interna por meio de transportadores específicos de coenzimas piridínicas, sem qualquer mudança no estado redox citoplasmático versus matricial, com rendimento estequiométrico idêntico de 2,5 ATP por NADH em ambos os casos teciduais.]),
   ("E", [A lançadeira do glicerol-3-P é a única efetivamente usada em todos os tecidos humanos adultos porque a malato-aspartato exige enzimas mitocondriais específicas que só existem em bactérias procariotas e leveduras unicelulares, sendo apenas um vestígio evolutivo discutido em livros didáticos mais antigos sem relevância fisiológica clínica.])))

#questao-ce("12", badge-integracao,
  [Sobre inibidores específicos da cadeia respiratória e seus mecanismos moleculares, julgue os itens:],
  ((
    ("I", [Rotenona é um inseticida natural que se liga ao Complexo I no sítio de transferência para a CoQ, bloqueando a oxidação do NADH e diminuindo drasticamente o consumo de O₂ pela via do NADH.]),
    ("II", [Antimicina A bloqueia o Complexo IV no sítio do citocromo a#sub[3], impedindo a redução do O₂ a água e gerando o mesmo quadro clínico do cianeto: hipóxia histotóxica com sangue venoso vermelho-cereja.]),
    ("III", [Cianeto (CN⁻) e monóxido de carbono (CO) ligam-se com altíssima afinidade ao Fe³⁺ do heme a#sub[3] do Complexo IV, paralisando toda a cadeia respiratória por cascata reversa em segundos.]),
    ("IV", [Oligomicina não é tecnicamente um inibidor da cadeia, mas sim da ATP sintase: liga-se à subunidade F#sub[0] e bloqueia o canal de prótons; secundariamente, o gradiente saturado retroinibe os complexos da cadeia.])
  )))

#questao-mc("13", badge-integracao,
  [Sobre o efeito da oligomicina na cadeia respiratória e a explicação do "controle respiratório", é correto afirmar:],
  (("A", [Oligomicina bloqueia a ATP sintase em F#sub[0]; com a sintase travada, os prótons não retornam à matriz, o gradiente eletroquímico cresce ao máximo e a cadeia respiratória para por retroinibição termodinâmica — bombear contra um gradiente saturado torna-se energeticamente proibitivo, e o consumo de O₂ cessa.]),
   ("B", [Oligomicina inibe diretamente o Complexo I da cadeia respiratória ao ligar-se irreversivelmente ao FMN da NADH desidrogenase em ponte iônica covalente, e o efeito secundário sobre a ATP sintase F#sub[0]F#sub[1] é apenas farmacológico residual, sem mecanismo molecular relevante para a fisiologia mitocondrial humana adulta normal.]),
   ("C", [Oligomicina aumenta paradoxalmente a velocidade global de transporte de elétrons pela cadeia respiratória ao desacoplar parcialmente os complexos da síntese de ATP, gerando mais calor metabólico que ATP químico utilizável — mecanismo fisiopatológico similar ao do dinitrofenol histórico mas com janela terapêutica clínica significativamente maior em fisiculturismo.]),
   ("D", [Oligomicina é um cofator essencial para a função catalítica normal da ATP sintase F#sub[0]F#sub[1] em todos os mamíferos placentários; sua ausência crônica circulante por deficiência alimentar (não sua presença farmacológica iatrogênica) trava progressivamente a sintase mitocondrial e para o consumo basal de O₂ em todos os tecidos.]),
   ("E", [Oligomicina ativa farmacologicamente a UCP1 do tecido adiposo marrom seletivamente em adultos e neonatos humanos, dissipando o gradiente eletroquímico como calor termogênico controlado sem afetar significativamente a cadeia respiratória em outros tecidos metabolicamente ativos com mitocôndria funcional.])))

#questao-mc("14", badge-integracao,
  [Sobre a diferença mecanística entre um inibidor da cadeia (por exemplo, cianeto) e um desacoplador (por exemplo, 2,4-dinitrofenol/DNP), com foco no consumo de O₂ e na produção de calor, é correto afirmar:],
  (("A", [Ambos param toda a cadeia respiratória simultaneamente e cessam o consumo periférico de O₂, com a única diferença de que o desacoplador também causa hipertermia maligna progressiva por ação direta no centro termorregulador do hipotálamo anterior, sem qualquer mecanismo mitocondrial intracelular envolvido em órgãos sistêmicos.]),
   ("B", [O inibidor acelera paradoxalmente a cadeia respiratória e aumenta drasticamente o consumo de O₂ enquanto dissipa o gradiente eletroquímico como calor descontrolado; o desacoplador, em contraste, trava completamente a cadeia e cessa o consumo de O₂ tecidual, gerando hipóxia histotóxica progressiva sem qualquer geração de calor extra perceptível.]),
   ("C", [Inibidor e desacoplador têm efeitos clínicos absolutamente idênticos em todas as variáveis observadas (hipóxia tecidual generalizada + ATP cronicamente baixo + acidose lática); a distinção semântica entre os termos é apenas histórica e pedagógica, sem implicação prática no manejo do paciente intoxicado nem na fisiopatologia diferencial laboratorial sistemática.]),
   ("D", [Inibidor (cianeto) para a cadeia: O₂ deixa de ser consumido, ATP cai, paciente entra em hipóxia histotóxica com sangue vermelho-cereja. Desacoplador (DNP) deixa a cadeia rodar mas dissipa o gradiente como calor: O₂ consumido sobe, ATP cai, paciente entra em hipertermia maligna com sudorese profusa.]),
   ("E", [Desacopladores são moléculas estruturalmente idênticas em mecanismo aos inibidores clássicos da cadeia, sendo apenas formas farmacêuticas isoladas comerciais derivadas da mesma droga base ativa; a divisão didática em duas classes mecanísticas distintas é resquício pedagógico histórico sem base molecular real ou implicação fisiopatológica detalhada relevante.])))

#questao-ce("15", badge-integracao,
  [Sobre a UCP1 (termogenina) do tecido adiposo marrom e a termogênese sem tremor, julgue os itens:],
  ((
    ("I", [UCP1 é uma proteína da membrana mitocondrial interna que cria um canal regulado para o retorno de prótons à matriz sem passar pela ATP sintase, dissipando o gradiente como calor.]),
    ("II", [A ativação da UCP1 é desencadeada pela ligação de norepinefrina a receptores β#sub[3]-adrenérgicos nos adipócitos brancos do panículo subcutâneo, e independe da lipólise local.]),
    ("III", [A UCP1 é abundante no tecido adiposo marrom, especialmente em neonatos, e tem papel crucial na manutenção da temperatura corporal em recém-nascidos, que não tremem como adultos.]),
    ("IV", [A redescoberta de tecido adiposo marrom funcional em adultos humanos abriu uma frente terapêutica para obesidade, com agonistas seletivos de β#sub[3]-adrenérgico capazes de aumentar o gasto energético basal pela ativação da UCP1.])
  )))

#questao-mc("16", badge-integracao,
  [Sobre as espécies reativas de oxigênio (ROS) geradas pela cadeia respiratória e seus mecanismos de origem e neutralização, é correto afirmar:],
  (("A", [ROS são gerados exclusivamente pela ação da enzima NADPH oxidase em neutrófilos circulantes e macrófagos teciduais durante a resposta imune inata aguda, sem qualquer contribuição mensurável da cadeia respiratória mitocondrial em condições fisiológicas basais nem patológicas em qualquer tecido humano adulto normal.]),
   ("B", [Uma fração pequena dos elétrons "vaza" da cadeia respiratória — principalmente nos Complexos I e III — e reduz parcialmente o O₂ a superóxido (O₂⁻), que é dismutado a H₂O₂ pela superóxido dismutase mitocondrial e neutralizado por catalase e glutationa peroxidase; o desequilíbrio entre geração e neutralização caracteriza o estresse oxidativo.]),
   ("C", [O Complexo IV produz peróxido de hidrogênio como produto final normal da redução do O₂, e a catalase ali presente decompõe esse H₂O₂ em H₂O e O₂ molecular sem geração de outras espécies reativas em condições fisiológicas normais.]),
   ("D", [ROS são produzidas exclusivamente pela ATP sintase F#sub[0]F#sub[1] quando ela opera em modo reverso patológico, hidrolisando ATP citosólico para bombear prótons de volta em vez de sintetizá-lo a partir do gradiente, e essa é mecanisticamente a única fonte mitocondrial relevante de espécies reativas em todos os tecidos humanos.]),
   ("E", [A geração mitocondrial de ROS depende exclusivamente da presença de íons metálicos livres difundidos na matriz mitocondrial e é diretamente proporcional à concentração de ferro plasmático sistêmico circulante, sem qualquer papel mecanístico relevante da cadeia respiratória ou seus complexos individuais no processo bioquímico de formação.])))

#questao-ce("17", badge-integracao,
  [Sobre a força próton-motriz (PMF) e seus dois componentes (químico e elétrico), julgue os itens:],
  ((
    ("I", [A PMF é a soma de dois componentes: o ΔpH (componente químico, devido à diferença de concentração de H⁺ entre os dois lados da membrana) e o Δψ (componente elétrico, devido ao desbalanço de cargas).]),
    ("II", [Em mitocôndrias humanas, o componente elétrico (Δψ) contribui com cerca de 140 mV e o químico (ΔpH) com cerca de 60 mV, totalizando aproximadamente 200 mV de PMF.]),
    ("III", [O componente químico (ΔpH) é o predominante na PMF mitocondrial, contribuindo com mais de 70% do total, e por isso desacopladores que alteram pH são tão eficazes em colapsar o gradiente.]),
    ("IV", [A PMF é o "intermediário energético" da teoria quimiosmótica proposta por Peter Mitchell: não há intermediário químico fosforilado entre transporte de elétrons e síntese de ATP, mas sim o gradiente eletroquímico de prótons.])
  )))

#questao-mc("18", badge-integracao,
  [Sobre o binding change de Paul Boyer (Nobel 1997) e a relação entre rotação física da ATP sintase e síntese química do ATP, é correto afirmar:],
  (("A", [A energia da PMF mitocondrial é usada diretamente pela ATP sintase F#sub[0]F#sub[1] para formar a ligação fosfoanidrídica covalente entre ADP e Pi no sítio Loose da subunidade β catalítica, em uma reação altamente endergônica que sem a rotação contínua do eixo γ seria absolutamente proibida termodinamicamente em qualquer condição celular fisiológica.]),
   ("B", [Cada um dos três sítios catalíticos da subunidade F#sub[1] tem função fixa estrutural e bioquímica específica imutável (um sempre capta ADP+Pi, um sempre sintetiza ATP, um sempre libera ATP final), e a rotação do eixo γ apenas sincroniza temporalmente o fluxo dos substratos sem alterar a conformação tridimensional dos sítios catalíticos β individuais.]),
   ("C", [Boyer demonstrou experimentalmente que a síntese de ATP no sítio T ocorre exclusivamente quando há gradiente máximo de prótons disponível através da membrana mitocondrial interna; sem gradiente eletroquímico saturado, nenhuma síntese química ocorre no sítio T mesmo na presença abundante de substratos ADP e Pi citosólicos adequadamente concentrados.]),
   ("D", [O modelo do binding change foi proposto teoricamente por Boyer antes da estrutura cristalográfica completa da ATP sintase ter sido resolvida em alta resolução, mas posteriormente foi totalmente refutado por experimentos eletrofisiológicos que demonstraram que os três sítios catalíticos da subunidade F#sub[1] operam sincronicamente e simultaneamente, não alternadamente em ciclo.]),
   ("E", [No modelo do binding change, os três sítios catalíticos β alternam ciclicamente entre as conformações Open (libera ATP), Loose (captura ADP+Pi) e Tight (sintetiza espontaneamente ATP); a energia da PMF é usada principalmente para abrir o sítio Tight e liberar o ATP recém-formado, que sem energia ficaria preso pela altíssima afinidade do sítio pelo produto.])))

#questao-mc("19", badge-integracao,
  [Sobre o saldo total de ATP por molécula de glicose oxidada completamente até CO₂ e H₂O em condições aeróbicas, considerando os valores modernos de P/O, é correto afirmar:],
  (("A", [O saldo é sempre 38 ATP por glicose, independente do tecido considerado, pois esse é o valor estequiométrico fixo da via aeróbica completa em mamíferos.]),
   ("B", [O saldo é 36 ATP em todos os tecidos, calculado considerando 3 ATP por NADH e 2 ATP por FADH₂ e descontando 2 ATP gastos no transporte ativo para a matriz mitocondrial dos intermediários da glicólise.]),
   ("C", [O saldo varia entre 30 e 32 ATP por glicose dependendo da lançadeira usada pelo tecido (32 com malato-aspartato no fígado/rim/coração; 30 com glicerol-3-fosfato no músculo esquelético/cérebro), considerando P/O = 2,5 para NADH e P/O = 1,5 para FADH₂.]),
   ("D", [O saldo é 24 ATP por glicose porque os valores modernos de P/O são 1,5 para NADH e 1,0 para FADH₂, em razão dos custos elevados de transporte e da baixa eficiência do rotor F#sub[0] em humanos.]),
   ("E", [O saldo é exatamente 30 ATP em todos os tecidos humanos, porque a única lançadeira fisiologicamente relevante é a glicerol-3-P, e os tecidos que usam malato-aspartato têm rendimento idêntico devido a perdas adicionais de transporte.])))

#questao-mc("20", badge-integracao,
  [Sobre o ciclo Q no Complexo III e por que ele é necessário para o funcionamento eficiente da cadeia, é correto afirmar:],
  (("A", [O ciclo Q resolve a incompatibilidade estequiométrica entre a CoQ (que carrega 2 elétrons) e o citocromo c (que aceita apenas 1 elétron por vez) usando dois sítios distintos no Complexo III (Q#sub[o] e Q#sub[i]) em duas etapas, e como consequência da bifurcação dos elétrons o bombeamento de prótons dobra, totalizando 4 H⁺ por par de elétrons.]),
   ("B", [O ciclo Q é um mecanismo bioquímico de armazenamento temporário de elétrons reduzidos no Complexo III que ocorre fisiologicamente quando a célula está em jejum prolongado de carboidratos disponíveis, permitindo que a cadeia respiratória continue funcionando mesmo na ausência de NADH circulante imediatamente disponível para o Complexo I terminal.]),
   ("C", [O ciclo Q transfere elétrons reversivelmente da CoQ móvel para o citocromo b da membrana e novamente de volta para a CoQ inicial, sem participação alguma do citocromo c periférico, e por isso essencialmente dispensa o Complexo III na cadeia respiratória de tecidos altamente glicolíticos como hemácia anucleada madura e medula renal hipóxica.]),
   ("D", [O ciclo Q é um processo bioquímico restrito ao Complexo IV terminal, no qual a CoQ lipossolúvel entrega seus elétrons diretamente ao centro binuclear heme a#sub[3]–CuB do Complexo IV sem passar pelo citocromo c, e existe fisiologicamente principalmente para acelerar a redução do O₂ molecular no consumo basal.]),
   ("E", [O ciclo Q ocorre apenas em condições experimentais de bloqueio agudo do Complexo I por exposição tóxica à rotenona, funcionando como mecanismo compensatório de bypass dos elétrons do NADH diretamente para o Complexo III, sem passar pela CoQ móvel da bicamada lipídica nem pelo Complexo II adjacente.])))

#questao-ce("21", badge-integracao,
  [Sobre a succinato desidrogenase como ponto de integração entre o ciclo de Krebs e a cadeia respiratória, julgue os itens:],
  ((
    ("I", [A succinato desidrogenase catalisa a oxidação do succinato a fumarato no ciclo de Krebs e é a mesma enzima que constitui o Complexo II da cadeia respiratória.]),
    ("II", [É a única enzima do ciclo de Krebs cravada na membrana mitocondrial interna, justamente porque também participa diretamente da cadeia respiratória entregando elétrons à CoQ.]),
    ("III", [Os elétrons do succinato são transferidos primeiro ao FAD covalentemente ligado, depois descem por centros Fe-S internos do Complexo II e chegam à CoQ, sem bombeamento de prótons.]),
    ("IV", [Mutações nas subunidades SDHB e SDHD da succinato desidrogenase causam glicogenoses hepáticas hereditárias por bloqueio da síntese de glicogênio, sem qualquer relação com tumores da cadeia simpática.])
  )))

#questao-mc("22", badge-integracao,
  [Sobre o controle respiratório e a regulação da velocidade da cadeia respiratória pelo estado energético da célula, é correto afirmar:],
  (("A", [A cadeia respiratória é regulada principalmente por inibição alostérica em cada complexo individualmente, com ATP atuando como inibidor alostérico clássico nos quatro complexos I, II, III e IV simultaneamente, em um mecanismo regulador molecularmente similar ao da fosfofrutoquinase-1 na glicólise citosólica e ao da hexoquinase II em tecidos periféricos altamente metabólicos.]),
   ("B", [A velocidade global da cadeia respiratória é controlada principalmente pelo cálcio mitocondrial matricial, que ativa diretamente todos os complexos da cadeia quando a concentração intracelular livre de Ca²⁺ aumenta significativamente durante a contração muscular esquelética prolongada ou despolarização neuronal sustentada por estímulo periférico.]),
   ("C", [A regulação da cadeia respiratória é puramente hormonal e exclusiva da fase de jejum: glucagon ativa diretamente a cadeia no jejum prolongado e insulina inibe agudamente em alimentação, em uma resposta hormonal análoga à regulação clássica da glicogênese hepática e da gliconeogênese renal compensatória nas primeiras horas pós-prandiais.]),
   ("D", [A regulação é simples e direta pelo ADP disponível: quando há ADP livre, a ATP sintase usa-o, os prótons voltam à matriz, o gradiente diminui ligeiramente e a cadeia bombeia para repor; sem ADP, a sintase trava, o gradiente cresce e a cadeia para por retroinibição termodinâmica — auto-regulação direta pelo estado energético.]),
   ("E", [A cadeia respiratória funciona em velocidade constante e máxima durante toda a vida útil da célula em todos os tecidos sem variação observável, e o controle dinâmico do gasto energético basal de ATP é feito exclusivamente pela quantidade total de mitocôndrias presentes na célula (biogênese mitocondrial regulada por PGC-1α) sem qualquer regulação dinâmica da atividade enzimática individual.])))

#questao-ce("23", badge-integracao,
  [Sobre a integração funcional entre ciclo de Krebs e cadeia respiratória, julgue os itens:],
  ((
    ("I", [Os NADH e FADH₂ gerados pelo ciclo de Krebs são os principais combustíveis redutores da cadeia respiratória, que os reoxida a NAD⁺ e FAD para que o ciclo possa continuar.]),
    ("II", [Em condições de bloqueio da cadeia respiratória (por exemplo, hipóxia severa), o ciclo de Krebs continua funcionando normalmente, pois suas enzimas independem do estado redox de NAD⁺/NADH.]),
    ("III", [Por uma volta do ciclo de Krebs (1 acetil-CoA), são gerados 3 NADH + 1 FADH₂ + 1 GTP, que pela cadeia rendem aproximadamente 9 ATP adicionais (3 × 2,5 + 1 × 1,5 = 9 ATP), totalizando 10 ATP por acetil-CoA.]),
    ("IV", [A inibição da cadeia respiratória por cianeto causa acúmulo imediato de NADH na matriz, que inibe alostericamente a piruvato desidrogenase e a isocitrato desidrogenase, em prazo similar à parada da cadeia.])
  )))

#questao-mc("24", badge-integracao,
  [Sobre o papel duplo do citocromo c — transportador de elétrons na cadeia respiratória e sinalizador da apoptose intrínseca — é correto afirmar:],
  (("A", [O citocromo c funciona como transportador eletrônico ativo quando está oxidado em Fe³⁺ e como sinalizador apoptótico citosólico quando está completamente reduzido em Fe²⁺ após acúmulo redox prolongado na membrana; a transição molecular entre os dois papéis biológicos depende criticamente da concentração de O₂ disponível localmente na mitocôndria afetada.]),
   ("B", [Durante a apoptose intrínseca, proteínas da família Bcl-2 (BAX/BAK) permeabilizam a membrana mitocondrial externa; o citocromo c, normalmente preso à face externa da membrana interna, vaza para o citosol, liga-se ao Apaf-1 e ativa o apoptossomo, que cliva a procaspase-9 iniciando a cascata de caspases.]),
   ("C", [O citocromo c periférico só vaza para o citosol em condições específicas de necrose celular passiva por lesão membranar mecânica externa ou térmica direta, e nunca durante apoptose programada fisiológica ou patológica; sua presença citosólica não tem qualquer função sinalizadora bioquímica específica reconhecida em humanos adultos saudáveis.]),
   ("D", [Drogas-alvo seletivas como venetoclax (inibidor específico de Bcl-2 anti-apoptótica) impedem a permeabilização da membrana mitocondrial externa por BAX/BAK e por isso são fortemente pró-apoptóticas em células tumorais, ativando indiretamente o vazamento de citocromo c via mecanismo molecular paradoxal de inibição da inibição apoptótica clássica.]),
   ("E", [O citocromo c humano é codificado exclusivamente pelo DNA mitocondrial (mtDNA) e por isso herdado matrilinear da mãe pela transmissão citoplasmática do óvulo, padrão genético que explica fenomenologicamente a herança materna observada de algumas miopatias hereditárias por deficiência apoptótica mitocondrial sistêmica progressiva.])))

#questao-mc("25", badge-integracao,
  [Sobre a escolha tecidual de lançadeira e suas implicações funcionais, é correto afirmar:],
  (("A", [Todos os tecidos humanos saudáveis usam exclusivamente a lançadeira malato-aspartato em todas as condições metabólicas observadas, e a lançadeira glicerol-3-P é apenas um vestígio evolutivo arcaico presente residualmente apenas em peixes ectotérmicos e anfíbios primitivos sem qualquer relevância clínica em mamíferos placentários adultos contemporâneos.]),
   ("B", [O fígado humano usa preferencialmente a lançadeira glicerol-3-P em jejum e alimentação porque a malato-aspartato exige enzimas específicas que só funcionam no sistema nervoso central, em razão da alta dependência metabólica do cérebro humano pela transaminase mitocondrial isoforma 2 específica de neurônios glutamatérgicos corticais.]),
   ("C", [O músculo esquelético usa preferencialmente a lançadeira malato-aspartato durante o exercício extenuante prolongado porque ela é cineticamente mais rápida que a glicerol-3-P em condições anaeróbicas relativas, embora gere menos ATP por glicose oxidada; em repouso basal o tecido alterna para a glicerol-3-P por economia energética sistêmica.]),
   ("D", [Coração e rim alternam fisiologicamente entre as duas lançadeiras de forma estocástica completamente sem padrão preferencial observável reprodutível, em uma adaptação metabólica que explica diretamente a alta variabilidade interindividual e até intra-individual no consumo basal sistêmico de O₂ desses dois órgãos altamente metabólicos.]),
   ("E", [Músculo esquelético e cérebro usam a glicerol-3-P (rápida, irreversível, eficiente para turnover alto, mas rende menos ATP); fígado, rim e coração usam a malato-aspartato (mais regulada, eficiente em produção de ATP, preserva o estado redox); a escolha reflete o trade-off entre velocidade e rendimento energético no tecido.])))

// =================================================================
// APLICAÇÃO (Q26–Q30) — vinhetas clínicas + raciocínio integrado
// =================================================================

#questao-mc("26", badge-aplicacao,
  [Um homem de 42 anos é trazido ao pronto-socorro após tentativa de suicídio com ingestão de sal de cianeto disponível em laboratório de joalheria onde trabalha. Está agitado, com taquipneia (FR 32), taquicardia (FC 130) e hipotensão. Saturação de O₂ por oxímetro de pulso = 99% em ar ambiente; sangue venoso colhido para gasometria retorna *vermelho-cereja* aos olhos da equipe. Lactato arterial 12 mmol/L. Sobre o mecanismo responsável pelos achados clínicos, é correto afirmar:],
  (("A", [O cianeto bloqueia a hemoglobina por ligação ao Fe²⁺ do heme das hemácias com afinidade ~250 vezes superior à do O₂, impedindo o transporte de O₂ do pulmão para os tecidos periféricos; o sangue venoso vermelho-cereja reflete metemoglobinemia secundária com oxidação do Fe²⁺ a Fe³⁺ e perda de cooperatividade hemoglobínica. O tratamento consiste em metileno azul intravenoso, que age como aceptor artificial de elétrons reduzindo o Fe³⁺ de volta a Fe²⁺ e restaurando a saturação periférica em poucos minutos.]),
   ("B", [O cianeto desacopla a cadeia respiratória ao criar canais lipofílicos para retorno de prótons à matriz sem passar pela ATP sintase F#sub[0]F#sub[1]; o consumo de O₂ aumenta acentuadamente (sangue venoso saturado pelo hipermetabolismo periférico), o ATP citoplasmático cai e o paciente entra em hipertermia maligna por dissipação do gradiente como calor descontrolado — quadro fisiopatologicamente análogo ao da intoxicação clássica por dinitrofenol histórico em fisiculturismo ilegal.]),
   ("C", [O cianeto liga-se ao Fe³⁺ do heme a#sub[3] do Complexo IV da cadeia respiratória com altíssima afinidade, paralisando a transferência terminal de elétrons para o O₂ e causando hipóxia histotóxica — o O₂ chega ao tecido mas não pode ser usado, o sangue venoso retorna vermelho-cereja (saturado, não consumido), e a célula aciona glicólise anaeróbica gerando acidose lática severa.]),
   ("D", [O cianeto inibe alostericamente a piruvato desidrogenase e a isocitrato desidrogenase no ciclo de Krebs em razão da semelhança estrutural com o NAD⁺, paralisando a geração de NADH a montante da cadeia respiratória; os complexos I-IV continuam funcionais mas sem combustível redutor, o que explica a hiperlactatemia compensatória por desvio glicolítico anaeróbico e a coloração venosa cereja por consumo tecidual reduzido de O₂ nos capilares periféricos.]),
   ("E", [O cianeto bloqueia o Complexo I da cadeia respiratória ao ligar-se ao FMN da NADH desidrogenase, mecanismo molecular idêntico ao da rotenona usada em inseticidas naturais; o quadro de hipóxia histotóxica decorre da paralisação da entrada do NADH no início da cadeia, com sangue venoso vermelho-cereja por compensação periférica reflexa via quimiorreceptores carotídeos e bypass parcial pelo FADH₂ entrando no Complexo II.])))

#questao-mc("27", badge-aplicacao,
  [Vítima de incêndio em apartamento é resgatada inconsciente, com vestígios de fuligem nas narinas. SatO₂ por oxímetro de pulso convencional = 98% em ar ambiente (medida considerada não confiável pela equipe); cooximetria revela carboxihemoglobina (HbCO) = 38%. Paciente apresenta cefaleia, confusão mental, taquicardia e acidose lática. Sobre o mecanismo bioquímico responsável pelo quadro e a justificativa do tratamento com oxigênio hiperbárico, é correto afirmar:],
  (("A", [A intoxicação por CO é exclusivamente respiratória e o CO desloca o O₂ da hemoglobina formando carboxihemoglobina estável, bloqueando o transporte de O₂ aos tecidos periféricos sem qualquer envolvimento direto da cadeia respiratória mitocondrial; a hiperóxia atmosférica em pressão ambiente já é capaz de restaurar essa ligação por deslocamento competitivo do CO sem necessidade de pressão elevada, e o oxigênio hiperbárico é apenas uma alternativa logística institucional quando a normobárica não é viável por contraindicação clínica.]),
   ("B", [O CO age exclusivamente como desacoplador lipofílico da cadeia respiratória ao criar canais transmembranares para retorno de prótons à matriz sem passar pela ATP sintase, dissipando todo o gradiente como calor e gerando hipertermia maligna progressiva refratária ao resfriamento ativo; o oxigênio hiperbárico é usado puramente para resfriar o paciente por convulsão térmica reversa do gás molecular dissolvido aplicado em câmara pressurizada, sem efeito direto sobre o CO ligado.]),
   ("C", [O CO é um desacoplador parcial que se acopla seletivamente à UCP1 do tecido adiposo marrom em adultos por homologia estrutural com ácidos graxos endógenos, desencadeando termogênese descontrolada e sistêmica análoga à intoxicação histórica por dinitrofenol em fisiculturismo; o tratamento hiperbárico aproveita a hipóxia local induzida para desativar o desacoplamento via inibição reversível da UCP1 e restaurar o gradiente mitocondrial em poucas horas.]),
   ("D", [O CO age em dois locais: liga-se à hemoglobina (formando HbCO, com afinidade ~250× maior que a do O₂, deslocando a curva de dissociação para a esquerda) E liga-se ao Fe²⁺ do heme a#sub[3] do Complexo IV (mecanismo similar ao do cianeto), gerando duplo prejuízo — transporte e utilização de O₂. O oxigênio hiperbárico fornece O₂ dissolvido no plasma em quantidade suficiente para suprir tecidos mesmo com hemoglobina sequestrada, e acelera a dissociação de HbCO e do CO ligado ao Complexo IV pela lei de ação das massas.]),
   ("E", [O CO inibe seletivamente o Complexo II da cadeia respiratória (succinato desidrogenase) por bloqueio do sítio de transferência ao FAD covalente, impedindo a entrada do FADH₂ na cadeia mas preservando totalmente o caminho do NADH via Complexo I — o que justifica a relativa preservação do consumo basal de O₂ observada na cooximetria seriada; o oxigênio hiperbárico ativa enzimas antioxidantes redox-dependentes (superóxido dismutase, catalase) para limpar os radicais residuais formados pelo bypass parcial.])))

#questao-mc("28", badge-aplicacao,
  [Um fisiculturista de 24 anos é trazido ao pronto-socorro pela namorada com hipertermia (T axilar 41,5 °C), sudorese profusa, taquicardia (FC 150), taquipneia (FR 40) e rebaixamento de consciência progressivo. Ela relata que o paciente comprou comprimidos amarelos de "queima-gordura potente" em site obscuro de fisiculturismo e tomou dose dobrada esperando resultado mais rápido. Lactato arterial 8 mmol/L. Suspeita-se de intoxicação por 2,4-dinitrofenol (DNP). Sobre o mecanismo bioquímico do quadro, é correto afirmar:],
  (("A", [O DNP inibe a ATP sintase ao ligar-se à subunidade F#sub[0] do rotor membranar, travando a passagem de prótons de forma molecularmente análoga ao mecanismo da oligomicina; o gradiente eletroquímico cresce até o máximo termodinâmico, retroinibe os Complexos I-IV da cadeia respiratória, o consumo de O₂ cai bruscamente e o paciente entra em hipóxia histotóxica progressiva com cianose central — a hipertermia observada decorre exclusivamente do esforço respiratório compensatório acentuado mantido por muitas horas e do trabalho muscular reflexo associado ao desconforto.]),
   ("B", [O DNP é um desacoplador lipofílico: atravessa a membrana mitocondrial interna carregando prótons do espaço intermembranas para a matriz sem passar pela ATP sintase, colapsando o gradiente. A cadeia respiratória continua funcionando (e acelera, porque o gradiente não a freia mais), o O₂ é consumido em alta velocidade, mas toda a energia que deveria virar ATP vira CALOR — daí a hipertermia maligna. O paciente queima estoques de combustível em ritmo descontrolado, e mortes por DNP são frequentes mesmo com tratamento de suporte.]),
   ("C", [O DNP atua como inibidor competitivo direto da NADH desidrogenase do Complexo I por similaridade estrutural com o anel nicotinamida, mecanismo molecularmente idêntico ao da rotenona em inseticidas naturais derivados de raízes tropicais; a hipertermia observada no paciente é efeito tóxico colateral de neurotoxicidade central direta por acúmulo de NADH no citosol e desbalanço redox cerebral, sem relação fisiopatológica direta com a cadeia respiratória mitocondrial ou com o gradiente eletroquímico.]),
   ("D", [O DNP ativa farmacologicamente a UCP1 do tecido adiposo marrom em adultos por ligação direta ao receptor β#sub[3]-adrenérgico em pré-adipócitos cervicais e supraclaviculares humanos, mecanismo descoberto recentemente em estudos PET-CT do gasto basal; a termogênese descontrolada decorrente é restrita ao tecido adiposo e não afeta outros órgãos com mitocôndria, sendo a hipertermia sistêmica explicada por aumento isolado da gordura marrom periférica radialmente expansiva.]),
   ("E", [O DNP bloqueia o Complexo IV ao ligar-se ao centro binuclear heme a#sub[3]–CuB de forma análoga ao cianeto e ao monóxido de carbono, mas com afinidade químico-estrutural reduzida que permitiria uso clínico em doses microgramas; o quadro fisiopatológico do paciente seria hipóxia histotóxica clássica com sangue venoso vermelho-cereja, sendo a hipertermia observada explicada por convulsões musculares involuntárias secundárias à acidose lática severa.])))

#questao-mc("29", badge-aplicacao,
  [Recém-nascido de termo, parto extra-hospitalar em ambiente frio, é levado ao serviço de emergência neonatal duas horas após o nascimento. Apresenta temperatura axilar de 35,2 °C e leve cianose acral, mas exame cardiopulmonar normal. A equipe coloca o bebê em ambiente aquecido e contato pele-a-pele com a mãe; em 30 minutos a temperatura retorna a 36,8 °C sem necessidade de intervenções adicionais. Sobre o mecanismo bioquímico que permitiu ao recém-nascido restaurar a temperatura sem tremor muscular significativo, é correto afirmar:],
  (("A", [O recém-nascido restaura a temperatura corporal exclusivamente pela vasoconstrição periférica reflexa mediada por receptores α#sub[1]-adrenérgicos cutâneos e pelo isolamento térmico passivo proporcionado pelo contato pele-a-pele em ambiente aquecido, mecanismo central já maduro no neonato a termo desde a primeira hora; nenhum processo metabólico mitocondrial específico está envolvido no aquecimento neonatal nos primeiros dias de vida extrauterina, e a contribuição do tecido adiposo é apenas isolante térmica passiva sem geração ativa de calor.]),
   ("B", [O aquecimento decorre da ativação da glicogenólise hepática estimulada por glucagon e norepinefrina sistêmica, que libera grandes quantidades de glicose para o sangue circulante a partir dos depósitos hepáticos do neonato; o calor é gerado pela própria reação enzimática da glicose-6-fosfatase no retículo endoplasmático dos hepatócitos, em uma reação exergônica termogênica que libera energia sem participação direta de mitocôndria, cadeia respiratória ou tecido adiposo marrom periférico especializado.]),
   ("C", [O aquecimento depende quase exclusivamente de tremores musculares involuntários (shivering) intensos mas pouco visíveis externamente no recém-nascido pelo tamanho da musculatura esquelética, gerados por ciclos rápidos de contração-relaxamento muscular com gasto elevado de ATP e produção de calor por hidrólise das ligações fosfoanidrídicas terminais, exatamente como ocorre na resposta termorreguladora do adulto; o tecido adiposo marrom não tem papel fisiologicamente relevante no neonato humano contemporâneo.]),
   ("D", [O calor é gerado pela hidrólise direta de ácidos graxos do tecido adiposo branco subcutâneo pela lipase hormônio-sensível ativada por epinefrina suprarrenal, em uma reação exergônica que libera energia diretamente como calor químico sem necessidade de oxidação mitocondrial pela cadeia respiratória ou pelo ciclo de Krebs, sendo essa hidrólise lipídica enzimática a principal fonte de termogênese neonatal nas primeiras horas de vida extrauterina.]),
   ("E", [O frio ativa a liberação de norepinefrina por terminais simpáticos sobre o tecido adiposo MARROM (abundante no neonato em pescoço, escápulas e adjacente à coluna), ligando-se a receptores β#sub[3]-adrenérgicos. Isso desencadeia lipólise local com geração de ácidos graxos livres que ATIVAM A UCP1 (termogenina) da membrana mitocondrial interna; UCP1 abre um canal regulado para retorno de prótons sem passar pela ATP sintase, dissipando o gradiente como calor — termogênese sem tremor, vital para o recém-nascido que não tem coordenação muscular adequada para shivering.])))

#questao-mc("30", badge-aplicacao,
  [Uma mulher de 28 anos procura neurologista por queixa de fraqueza muscular progressiva nos últimos 4 anos, com intolerância marcada ao exercício (taquicardia desproporcional, fadiga após mínimos esforços), ptose palpebral bilateral e episódios recorrentes de cefaleia com sintomas neurológicos focais transitórios (afasia, parestesia em hemicorpo). A mãe relata antecedente similar em parente materno. Exames mostram lactato sérico cronicamente elevado (4,5 mmol/L em repouso, 12 mmol/L após exercício leve). Biópsia muscular evidencia *ragged-red fibers* à coloração de Gomori. Sobre a fisiopatologia da provável síndrome (MELAS), é correto afirmar:],
  (("A", [Mutações em DNA mitocondrial (mtDNA) — herdadas exclusivamente da mãe pela transmissão citoplasmática do óvulo — comprometem subunidades da cadeia respiratória (frequentemente do Complexo I, mas também IV e V); músculo esquelético e neurônio, tecidos altamente dependentes de ATP oxidativo, são os mais afetados clinicamente; o déficit de ATP mitocondrial é parcialmente compensado por hiperatividade glicolítica anaeróbica, gerando acidose lática crônica de jejum e exercício; o acúmulo de mitocôndrias defeituosas em arranjos subsarcolemais corados em vermelho pelo tricrômico de Gomori produz a aparência clássica de "ragged-red fibers" característica de MELAS, MERRF e Leber.]),
   ("B", [A doença é causada por mutações em genes nucleares que codificam enzimas-chave da glicólise citosólica (predominantemente hexoquinase II e fosfofrutoquinase-1), comprometendo a oxidação anaeróbica da glicose em condições basais e de esforço; a acidose lática persistente reflete a glicólise descontrolada com acúmulo de piruvato derivado para lactato pela LDH, e a biópsia muscular mostra ragged-red fibers pela degeneração reativa secundária do citoesqueleto sarcolemal exposto à hiperatividade glicolítica crônica e hipóxia tecidual relativa.]),
   ("C", [A síndrome resulta de auto-anticorpos circulantes específicos contra a ATP sintase mitocondrial humana, com bloqueio funcional progressivo da F#sub[0]F#sub[1] em múltiplos tecidos altamente metabólicos como músculo e neurônio; a herança materna aparente decorre da transferência passiva de auto-anticorpos pelo leite materno durante a lactação prolongada, e os ragged-red fibers à biópsia muscular refletem infiltrado inflamatório linfocítico crônico circundando as fibras musculares afetadas em arranjo subsarcolemal típico.]),
   ("D", [A doença é uma forma de glicogenose hepática tipo I (von Gierke) com manifestação muscular tardia por deficiência hereditária da glicose-6-fosfatase do retículo endoplasmático hepático, prejudicando a glicogenólise terminal; a acidose lática reflete a impossibilidade de hidrolisar glicose-6-P a glicose livre no fígado em jejum prolongado, e os ragged-red fibers indicam depósito intramuscular massivo de glicogênio estruturalmente anormal corado pelo tricrômico clássico de Gomori-Engel modificado.]),
   ("E", [A fisiopatologia depende exclusivamente de toxicidade ambiental por exposição crônica a desacopladores domésticos (resíduos de inseticidas com rotenona em alimentação ou poeira agrícola) que mimetizam de forma persistente um fenótipo bioquímico de miopatia mitocondrial sem real envolvimento genético mitocondrial; a herança materna aparente é coincidência epidemiológica familiar por compartilhamento crônico do mesmo ambiente doméstico contaminado entre múltiplas gerações de mulheres na mesma casa.])))
