RUN_ID = 'uc03-imuno37-20260930-codex'

SHORT = 'imuno37'

LESSON = '2026-uc03-imunologia-37-inflamacao-inicio-resolucao'

DECK = 'NEBLI::UC03::P2::Imunologia::Inflamação: início e resolução'

CRITERIOS = 'MEMORY + FEEDBACKS até F-20260930-CLAUDE-15; continuação Codex 30/09. Só decks.'

AUTHOR = 'uc03'

MEDIA = {}

CARDS = [{'key': 'ak-1487640028986',
  'kind': 'text',
  'src': 1487640028986,
  'flags': {1: 4, 2: 3, 3: 4},
  'bloco': 'A-reconhecimento',
  'alvo': 'CD{{c1::14}} is a co-receptor for TLR4 found on {{c3::macrophages}} that recognizes '
          '{{c2::lipopolysaccharide (LPS)}} on gram-negative bacteria ',
  'evid': 'Slides definição, funções, PRR, TLR, sensores citosólicos e ácido úrico',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640050564',
  'kind': 'text',
  'src': 1487640050564,
  'flags': {1: 3},
  'bloco': 'A-reconhecimento',
  'alvo': 'Toll-like receptor (TLR) activation results in upregulation of {{c1::NF-κB}}, a nuclear transcription '
          'factor that activates immune response genes',
  'evid': 'Slides definição, funções, PRR, TLR, sensores citosólicos e ácido úrico',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1500572039288',
  'kind': 'text',
  'src': 1500572039288,
  'flags': {3: 3},
  'bloco': 'A-reconhecimento',
  'alvo': 'Gram negative bacteria activate macrophages when lipopolysaccharide (endotoxin) binds to {{c2::CD14}} and '
          '{{c3::TLR4}}',
  'evid': 'Slides definição, funções, PRR, TLR, sensores citosólicos e ácido úrico',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1520715624658',
  'kind': 'text',
  'src': 1520715624658,
  'flags': {1: 3},
  'bloco': 'A-reconhecimento',
  'alvo': 'The {{c1::inflammasome}} is a cytoplasmic protein complex that recognizes products of dead cells, microbial '
          'products, and crystals',
  'evid': 'Slides definição, funções, PRR, TLR, sensores citosólicos e ácido úrico',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1520715849479',
  'kind': 'text',
  'src': 1520715849479,
  'flags': {1: 3},
  'bloco': 'A-reconhecimento',
  'alvo': 'Activation of the inflammasome leads to increased production of {{c1::IL-1β}} and IL-18',
  'evid': 'Slides definição, funções, PRR, TLR, sensores citosólicos e ácido úrico',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'extra': 'Inflammasome assembly activates caspase-1, which cleaves pro-IL-1β and pro-IL-18 into active cytokines. '
           'This processing step differs from the transcriptional induction of their precursors.'},
 {'key': 'ak-1487640248028',
  'kind': 'text',
  'src': 1487640248028,
  'flags': {1: 4},
  'bloco': 'B-celulas-vasos',
  'alvo': 'One cardinal sign of inflammation is redness, or {{c1::rubor}}',
  'evid': 'Slides acúmulo celular, eventos iniciais e sinais cardinais',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640253946',
  'kind': 'text',
  'src': 1487640253946,
  'flags': {1: 4},
  'bloco': 'B-celulas-vasos',
  'alvo': 'One cardinal sign of inflammation is warmth, or {{c1::calor}}',
  'evid': 'Slides acúmulo celular, eventos iniciais e sinais cardinais',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640263698',
  'kind': 'text',
  'src': 1487640263698,
  'flags': {1: 4},
  'bloco': 'B-celulas-vasos',
  'alvo': 'One cardinal sign of inflammation is swelling, or {{c1::tumor}}',
  'evid': 'Slides acúmulo celular, eventos iniciais e sinais cardinais',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640274492',
  'kind': 'text',
  'src': 1487640274492,
  'flags': {1: 4},
  'bloco': 'B-celulas-vasos',
  'alvo': 'One cardinal sign of inflammation is pain, or {{c1::dolor}}',
  'evid': 'Slides acúmulo celular, eventos iniciais e sinais cardinais',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1520443529180',
  'kind': 'text',
  'src': 1520443529180,
  'flags': {1: 4},
  'bloco': 'B-celulas-vasos',
  'alvo': 'One cardinal sign of inflammation is loss of function, or {{c1::functio laesa}}',
  'evid': 'Slides acúmulo celular, eventos iniciais e sinais cardinais',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640261037',
  'kind': 'text',
  'src': 1487640261037,
  'flags': {1: 3, 2: 3, 3: 3},
  'bloco': 'B-celulas-vasos',
  'alvo': 'The key mediators of redness and warmth in inflammation are {{c1::histamine}}, {{c2::prostaglandins}}, '
          '{{c3::bradykinin}}, and NO',
  'evid': 'Slides acúmulo celular, eventos iniciais e sinais cardinais',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640269487',
  'kind': 'text',
  'src': 1487640269487,
  'flags': {1: 3, 2: 3, 3: 3},
  'bloco': 'B-celulas-vasos',
  'alvo': 'Swelling in inflammation is mediated by endothelial cell disruption (due to tissue damage) and endothelial '
          'cell contraction (caused by {{c1::leukotrienes}}, {{c2::histamine}}, and {{c3::serotonin}})',
  'evid': 'Slides acúmulo celular, eventos iniciais e sinais cardinais',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1479267395454',
  'kind': 'text',
  'src': 1479267395454,
  'flags': {1: 3},
  'bloco': 'B-celulas-vasos',
  'alvo': 'Macrophages {{c1::phagocytose}} bacteria, cellular debris, and RBCs',
  'evid': 'Slides acúmulo celular, eventos iniciais e sinais cardinais',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487207084334',
  'kind': 'text',
  'src': 1487207084334,
  'flags': {1: 3, 2: 4},
  'bloco': 'B-celulas-vasos',
  'alvo': 'The immediate response of mast cell and basophil activation is release of preformed {{c1::histamine}} '
          'granules and {{c2::tryptase::marker of activation}}',
  'evid': 'Slides acúmulo celular, eventos iniciais e sinais cardinais',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487207091819',
  'kind': 'text',
  'src': 1487207091819,
  'flags': {2: 4},
  'bloco': 'B-celulas-vasos',
  'alvo': 'The delayed response of mast cell and basophil activation involves production of {{c2::chemokines}} (e.g., '
          'to attract eosinophils) and other proinflammatory mediators from mast cells',
  'evid': 'Slides acúmulo celular, eventos iniciais e sinais cardinais',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640132837',
  'kind': 'text',
  'src': 1487640132837,
  'flags': {1: 4},
  'bloco': 'B-celulas-vasos',
  'alvo': 'Mast cells may be activated by tissue {{c1::trauma}}',
  'evid': 'Slides acúmulo celular, eventos iniciais e sinais cardinais',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640136892',
  'kind': 'text',
  'src': 1487640136892,
  'flags': {1: 4},
  'bloco': 'B-celulas-vasos',
  'alvo': 'Mast cells may be activated by cross-linking of cell-surface {{c1::IgE}} by antigen',
  'evid': 'Slides acúmulo celular, eventos iniciais e sinais cardinais',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487642579270',
  'kind': 'text',
  'src': 1487642579270,
  'flags': {1: 4, 2: 4},
  'bloco': 'C-migracao',
  'alvo': '{{c2::P}}-selectin is released from {{c1::Weibel-Palade bodies}}',
  'evid': 'Slides migração leucocitária, selectinas, integrinas, ICAM, PECAM, quimioatraentes',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487642582069',
  'kind': 'text',
  'src': 1487642582069,
  'flags': {1: 4},
  'bloco': 'C-migracao',
  'alvo': 'Release of P-selectin from Weibel-Palade bodies is mediated by {{c1::histamine}}',
  'evid': 'Slides migração leucocitária, selectinas, integrinas, ICAM, PECAM, quimioatraentes',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487642620769',
  'kind': 'text',
  'src': 1487642620769,
  'flags': {1: 3, 2: 3},
  'bloco': 'C-migracao',
  'alvo': 'Integrin expression is upregulated on leukocytes by {{c1::C5a}} and {{c2::LTB4}}',
  'evid': 'Slides migração leucocitária, selectinas, integrinas, ICAM, PECAM, quimioatraentes',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487642625895',
  'kind': 'text',
  'src': 1487642625895,
  'flags': {1: 3, 2: 3},
  'bloco': 'C-migracao',
  'alvo': '{{c2::Leukocyte adhesion deficiency (type 1)::Specific type}} is due to a defect in {{c1::LFA-1 integrin '
          '(CD18 subunit)::specific}} protein on phagocytes',
  'evid': 'Slides migração leucocitária, selectinas, integrinas, ICAM, PECAM, quimioatraentes',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487642632527',
  'kind': 'text',
  'src': 1487642632527,
  'flags': {1: 3},
  'bloco': 'C-migracao',
  'alvo': 'Leukocyte adhesion deficiency is characterized by {{c1::increased}} circulating neutrophils ',
  'evid': 'Slides migração leucocitária, selectinas, integrinas, ICAM, PECAM, quimioatraentes',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487642637710',
  'kind': 'text',
  'src': 1487642637710,
  'flags': {1: 3},
  'bloco': 'C-migracao',
  'alvo': 'Leukocyte adhesion deficiency is characterized by {{c1::absent}} neutrophils at infection sites',
  'evid': 'Slides migração leucocitária, selectinas, integrinas, ICAM, PECAM, quimioatraentes',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1475890914685',
  'kind': 'text',
  'src': 1475890914685,
  'flags': {1: 4},
  'bloco': 'D-efetores',
  'alvo': 'In {{c1::neutrophils}}, the HMP shunt provides a source of NADPH for NADPH oxidase activity, which is used '
          'for respiratory burst ',
  'evid': 'Slides fagocitose, burst oxidativo, degranulação e NETs',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'extra': 'The pentose phosphate pathway supplies NADPH; NADPH oxidase transfers electrons to oxygen to generate '
           'superoxide. Downstream oxidants help kill ingested microbes.'},
 {'key': 'ak-1487642733736',
  'kind': 'text',
  'src': 1487642733736,
  'flags': {1: 3, 2: 3},
  'bloco': 'D-efetores',
  'alvo': '{{c2::Chronic granulomatous disease (CGD)}} is due to a defect in {{c1::NADPH oxidase}}',
  'evid': 'Slides fagocitose, burst oxidativo, degranulação e NETs',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'extra': 'NADPH oxidase generates superoxide during the respiratory burst. Its deficiency impairs oxidant-dependent '
           'intracellular killing despite preserved ingestion. This clinical example tests the killing mechanism, not '
           'a separate catalogue of infections.'},
 {'key': 'ak-1487640225601',
  'kind': 'text',
  'src': 1487640225601,
  'flags': {1: 4},
  'bloco': 'E-mediadores',
  'alvo': 'Which coagulation factor is a mediator of acute inflammation?{{c1::Factor XII (Hageman factor)}}',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'extra': 'Activated factor XII connects contact activation to kallikrein/kinin formation and links inflammatory, '
           'coagulation and fibrinolytic pathways. Kallikrein releases bradykinin from high-molecular-weight '
           'kininogen.'},
 {'key': 'ak-1487640230861',
  'kind': 'text',
  'src': 1487640230861,
  'flags': {1: 4, 2: 3},
  'bloco': 'E-mediadores',
  'alvo': '{{c1::Kallikrein}} cleaves high-molecular-weight kininogen (HMWK) to {{c2::bradykinin}}',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640059152',
  'kind': 'text',
  'src': 1487640059152,
  'flags': {1: 3, 2: 3},
  'bloco': 'E-mediadores',
  'alvo': '{{c1::Arachidonic acid}} is released from the phospholipid cell membrane by the enzyme {{c2::phospholipase '
          'A2}}',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640061733',
  'kind': 'text',
  'src': 1487640061733,
  'flags': {1: 3},
  'bloco': 'E-mediadores',
  'alvo': 'Arachidonic acids are converted to prostaglandins via the enzyme {{c1::cyclooxygenase (COX)}}',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640068745',
  'kind': 'text',
  'src': 1487640068745,
  'flags': {1: 3},
  'bloco': 'E-mediadores',
  'alvo': 'Which prostaglandins mediate vasodilation and increased vascular permeability? {{c1::PGD2, PGI2 '
          '(prostacyclin), and PGE2}}',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'text': 'Which prostaglandins promote vasodilation during inflammation? {{c1::PGD2, PGI2 (prostacyclin), and PGE2}}',
  'extra': 'Increased blood flow produces redness and warmth. These prostaglandins can enhance edema through '
           'vasodilation and cooperation with permeability mediators; do not equate vasodilation with direct '
           'endothelial contraction.'},
 {'key': 'ak-1487640078840',
  'kind': 'text',
  'src': 1487640078840,
  'flags': {1: 3},
  'bloco': 'E-mediadores',
  'alvo': 'Which prostaglandin mediates pain and fever? {{c1::PGE2}} ',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640089158',
  'kind': 'text',
  'src': 1487640089158,
  'flags': {1: 4, 2: 4},
  'bloco': 'E-mediadores',
  'alvo': 'Prostaglandin {{c1::I2 (prostacyclin)}} causes {{c2::decreased}} platelet aggregation',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640101055',
  'kind': 'text',
  'src': 1487640101055,
  'flags': {1: 3},
  'bloco': 'E-mediadores',
  'alvo': 'Arachidonic acids are converted to leukotrienes via the enzyme {{c1::5-lipoxygenase}} ',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640108934',
  'kind': 'text',
  'src': 1487640108934,
  'flags': {1: 4},
  'bloco': 'E-mediadores',
  'alvo': 'Which leukotrienes mediate vasoconstriction, bronchospasm, and increased vascular permeability? '
          '{{c1::Leukotrienes C4, D4, and E4}}',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'extra': 'The cysteinyl leukotrienes LTC4, LTD4 and LTE4 cause bronchial smooth-muscle contraction and increase '
           'microvascular permeability. LTB4 mainly recruits and activates leukocytes.'},
 {'key': 'ak-1488847671701',
  'kind': 'text',
  'src': 1488847671701,
  'flags': {1: 3, 2: 3},
  'bloco': 'E-mediadores',
  'alvo': 'Cyclooxygenase-2 expression is {{c2::induced}} by {{c1::inflammation}}',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1488847679422',
  'kind': 'text',
  'src': 1488847679422,
  'flags': {1: 3},
  'bloco': 'E-mediadores',
  'alvo': 'Thromboxane A2 (TXA2) causes vaso{{c1::constriction}}',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1488854922125',
  'kind': 'text',
  'src': 1488854922125,
  'flags': {1: 4},
  'bloco': 'E-mediadores',
  'alvo': 'COX-{{c1::1}} is constitutively expressed',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1488854930174',
  'kind': 'text',
  'src': 1488854930174,
  'flags': {1: 4},
  'bloco': 'E-mediadores',
  'alvo': 'COX-{{c1::1}} synthesizes gastric cytoprotective prostaglandins',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1488847688890',
  'kind': 'text',
  'src': 1488847688890,
  'flags': {1: 3},
  'bloco': 'E-mediadores',
  'alvo': 'Aspirin is a(n) {{c1::irreversible::reversible/irreversible}} inhibitor of COX-1 and COX-2',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'extra': 'Aspirin covalently acetylates COX. Platelets cannot synthesize new enzyme, so their antiaggregant effect '
           'lasts for the affected platelet’s lifespan. Nucleated cells can replace COX; anti-inflammatory effects do '
           'not all last a platelet lifetime.'},
 {'key': 'ak-1488847696894',
  'kind': 'text',
  'src': 1488847696894,
  'flags': {1: 4},
  'bloco': 'E-mediadores',
  'alvo': 'Aspirin inhibits cyclooxygenase via irreversible covalent {{c1::acetylation}} ',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1473986398130',
  'kind': 'text',
  'src': 1473986398130,
  'flags': {2: 3, 3: 3},
  'bloco': 'E-mediadores',
  'alvo': 'Aspirin irreversibly inactivates the enzyme {{c1::cyclooxygenase}}, thus decreasing synthesis of '
          '{{c2::thromboxane A2 (TXA2)}}, leading to impaired platelet {{c3::aggregation}}',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1463883753623',
  'kind': 'text',
  'src': 1463883753623,
  'flags': {1: 3},
  'bloco': 'E-mediadores',
  'alvo': 'Glucocorticoids prevent production of {{c1::arachidonic acid}} by inhibiting phospholipase A2',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1462061188088',
  'kind': 'text',
  'src': 1462061188088,
  'flags': {1: 4, 2: 4},
  'bloco': 'E-mediadores',
  'alvo': 'Glucocorticoids may have anti-inflammatory effects by inducing the synthesis of {{c1::lipocortin-1}}, an '
          'inhibitor of {{c2::phospholipase A2}} ',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1474580819655',
  'kind': 'text',
  'src': 1474580819655,
  'flags': {1: 4},
  'bloco': 'E-mediadores',
  'alvo': 'What is the mechanism of action of zileuton (asthma treatment)?{{c1::5-lipoxygenase inhibitor}}',
  'evid': 'Slides cininas, sistemas plasmáticos, mediadores lipídicos e intervenção terapêutica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487640278577',
  'kind': 'text',
  'src': 1487640278577,
  'flags': {1: 3, 2: 3},
  'bloco': 'F-sistemico',
  'alvo': 'Fever in inflammation is mediated by release of {{c1::IL-1}}, {{c1::IL-6}}, and {{c1::TNF}} by '
          '{{c2::macrophages}} in response to pyrogens (e.g., LPS from bacteria)',
  'evid': 'Slides IL-1/IL-6/TNF, fase aguda, febre, resposta sistêmica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1489969950421',
  'kind': 'text',
  'src': 1489969950421,
  'flags': {1: 3},
  'bloco': 'F-sistemico',
  'alvo': 'Which interleukin is primarily responsible for fever and acute inflammation?{{c1::IL-1}}',
  'evid': 'Slides IL-1/IL-6/TNF, fase aguda, febre, resposta sistêmica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1489970026548',
  'kind': 'text',
  'src': 1489970026548,
  'flags': {1: 3},
  'bloco': 'F-sistemico',
  'alvo': 'Which interleukin is primarily responsible for acute phase reactant production?{{c1::IL-6}}',
  'evid': 'Slides IL-1/IL-6/TNF, fase aguda, febre, resposta sistêmica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1489970181312',
  'kind': 'text',
  'src': 1489970181312,
  'flags': {1: 3},
  'bloco': 'F-sistemico',
  'alvo': 'TNF-α is a cytokine released from {{c1::macrophages}} that mediates cachexia and shock',
  'evid': 'Slides IL-1/IL-6/TNF, fase aguda, febre, resposta sistêmica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'text': 'Systemic release of TNF-α from activated {{c1::macrophages}} can cause widespread endothelial activation '
          'and shock.',
  'extra': 'A local TNF response helps recruit leukocytes. Excessive systemic TNF promotes vascular leakage, '
           'vasodilation and coagulation activation, which can impair tissue perfusion.'},
 {'key': 'ak-1487642795725',
  'kind': 'text',
  'src': 1487642795725,
  'flags': {1: 3},
  'bloco': 'F-sistemico',
  'alvo': 'Which cytokine is produced by macrophages to recruit neutrophils for persistent acute '
          'inflammation?{{c1::IL-8}}',
  'evid': 'Slides IL-1/IL-6/TNF, fase aguda, febre, resposta sistêmica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1520444046369',
  'kind': 'text',
  'src': 1520444046369,
  'flags': {1: 3, 2: 4},
  'bloco': 'F-sistemico',
  'alvo': '{{c1::Acute phase reactants}} are factors produced by the {{c2::liver::organ}}, whose serum concentrations '
          'change significantly in response to inflammation',
  'evid': 'Slides IL-1/IL-6/TNF, fase aguda, febre, resposta sistêmica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1520445108362',
  'kind': 'text',
  'src': 1520445108362,
  'flags': {1: 3},
  'bloco': 'F-sistemico',
  'alvo': 'What acute phase reactant is upregulated during inflammation to opsonize targets, fix complement, and '
          'facilitate phagocytosis?{{c1::C-reactive protein (CRP)}}',
  'evid': 'Slides IL-1/IL-6/TNF, fase aguda, febre, resposta sistêmica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1520445157941',
  'kind': 'text',
  'src': 1520445157941,
  'flags': {1: 4},
  'bloco': 'F-sistemico',
  'alvo': 'What acute phase reactant can be measured clinically as a nonspecific sign of ongoing '
          'inflammation?{{c1::C-reactive protein (CRP)}}',
  'evid': 'Slides IL-1/IL-6/TNF, fase aguda, febre, resposta sistêmica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1520444298927',
  'kind': 'text',
  'src': 1520444298927,
  'flags': {1: 4},
  'bloco': 'F-sistemico',
  'alvo': 'What acute phase reactant that correlates with ESR is upregulated during inflammation?{{c1::Fibrinogen}}',
  'evid': 'Slides IL-1/IL-6/TNF, fase aguda, febre, resposta sistêmica',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1487642784485',
  'kind': 'text',
  'src': 1487642784485,
  'flags': {1: 3},
  'bloco': 'G-resolucao',
  'alvo': 'By which process do neutrophil levels decrease following acute inflammation?{{c1::Apoptosis}}',
  'evid': 'Slides resolução IL-10/TGF-beta, reparo e ligação à imunidade adaptativa; prova P2 2019 1.8',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1520715124462',
  'kind': 'text',
  'src': 1520715124462,
  'flags': {1: 3, 2: 3},
  'bloco': 'G-resolucao',
  'alvo': 'Acute inflammation typically results in resolution and healing, which is mediated by {{c1::IL-10}} and '
          '{{c2::TGF-β}}',
  'evid': 'Slides resolução IL-10/TGF-beta, reparo e ligação à imunidade adaptativa; prova P2 2019 1.8',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.'},
 {'key': 'ak-1520716108281',
  'kind': 'text',
  'src': 1520716108281,
  'flags': {1: 3, 2: 4},
  'bloco': 'G-resolucao',
  'alvo': 'In the setting of chronic inflammation, macrophages can be activated to M1 macrophages by stimulation from '
          '{{c2::Th1}} cells, resulting in a(n) {{c1::proinflammatory}} phenotype',
  'evid': 'Slides resolução IL-10/TGF-beta, reparo e ligação à imunidade adaptativa; prova P2 2019 1.8',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'extra': 'IFN-γ (from NK or Th1 cells) and microbial signals promote classical activation: ROS/NO production and '
           'inflammatory cytokines. M1/M2 is a useful teaching contrast; real macrophage states form a spectrum.'},
 {'key': 'ak-1520717070355',
  'kind': 'text',
  'src': 1520717070355,
  'flags': {1: 3, 2: 4},
  'bloco': 'G-resolucao',
  'alvo': 'In the setting of chronic inflammation, macrophages can be activated to M2 macrophages by stimulation from '
          '{{c2::Th2}} cells, resulting in a(n) {{c1::anti-inflammatory}} phenotype',
  'evid': 'Slides resolução IL-10/TGF-beta, reparo e ligação à imunidade adaptativa; prova P2 2019 1.8',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'extra': 'IL-4/IL-13 promote alternative activation: tissue repair, fibrosis and dampening of inflammation. '
           'Resolution also requires removal of the stimulus and dead cells; it is not merely absence of cytokine '
           'production.'},
 {'key': 'ak-1479267468509',
  'kind': 'text',
  'src': 1479267468509,
  'flags': {1: 3},
  'bloco': 'G-resolucao',
  'alvo': '{{c1::Dendritic}} cells function as a link between the innate and adaptive immune systems ',
  'evid': 'Slides células da inflamação e ativação adaptativa',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'extra': 'Dendritic cells sense microbial/damage signals, acquire antigen and migrate to draining lymph nodes. They '
           'present antigen and co-stimulatory signals to naive T cells, linking local innate recognition to a '
           'specific adaptive response.'},
 {'key': 'ak-1487116849895',
  'kind': 'text',
  'src': 1487116849895,
  'flags': {1: 3},
  'bloco': 'G-resolucao',
  'alvo': 'The second signal for T-cell activation is a costimulatory signal via interaction between {{c1::B7 '
          '(CD80/86)}} (APC) and {{c1::CD28}} (T cell)',
  'evid': 'Slide ativação e modulação da resposta adaptativa',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'extra': 'Innate recognition induces B7 and cytokines on dendritic cells. Antigen recognition and co-stimulation '
           'together activate naive T cells; the response then feeds back on phagocytes through cytokines.'},
 {'key': 'ak-1487117308213',
  'kind': 'text',
  'src': 1487117308213,
  'flags': {1: 3},
  'bloco': 'B-celulas-vasos',
  'alvo': 'Natural killer cells may induce apoptosis of virally infected cells and tumor cells via release of '
          '{{c1::perforins}} and {{c1::granzymes}}',
  'evid': 'Slide células da inflamação: células NK e lise de infectadas',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'extra': 'Perforin facilitates delivery of granzymes, which activate apoptotic pathways in the target cell. NK cells '
           'also produce IFN-γ that activates macrophages; this differs from phagocytosis by neutrophils.'},
 {'key': 'ak-1497451553581',
  'kind': 'text',
  'src': 1497451553581,
  'flags': {2: 3},
  'bloco': 'D-efetores',
  'alvo': 'IFN-γ upregulates production of inducible {{c2::nitric oxide synthase (iNOS)}} which is involved in the '
          'generation of ONOO- (a powerful free radical)',
  'evid': 'Slides espécies reativas e células da inflamação',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'extra': 'iNOS converts arginine into nitric oxide. NO can react with superoxide to form peroxynitrite, supporting '
           'microbial killing. Microbial PRR signals and IFN-γ enhance this effector program; extracellular oxidants '
           'can also injure host tissue.'},
 {'key': 'ak-1554063916591',
  'kind': 'text',
  'src': 1554063916591,
  'flags': {1: 4},
  'bloco': 'F-sistemico',
  'alvo': '{{c1::Autocrine signaling}} is when the cell secretes a hormone or chemical messenger that {{c2::binds to a '
          'receptor on itself}}.',
  'evid': 'Slide citocinas: ação autócrina',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'origin': 'AnKing-MCAT'},
 {'key': 'ak-1554064102112',
  'kind': 'text',
  'src': 1554064102112,
  'flags': {1: 4},
  'bloco': 'F-sistemico',
  'alvo': '{{c1::Paracrine}} signaling is when a cell produces a signal to {{c2::induce changes in nearby cells}}.',
  'evid': 'Slide citocinas: ação parácrina',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'origin': 'AnKing-MCAT'},
 {'key': 'ak-1554064278093',
  'kind': 'text',
  'src': 1554064278093,
  'flags': {1: 4},
  'bloco': 'F-sistemico',
  'alvo': '{{c1::Endocrine}} signaling&nbsp;releases signals into the {{c2::bloodstream}}, which carries them to '
          '{{c2::target cells in distant parts of the body}}.',
  'evid': 'Slide citocinas: ação endócrina',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'origin': 'AnKing-MCAT'},
 {'key': 'tlr-endossomais',
  'kind': 'autoral',
  'flags': {1: 3, 2: 4},
  'bloco': 'A-reconhecimento',
  'text': 'TLRs that detect microbial nucleic acids (TLR3/7/8/9) are mainly {{c1::endosomal}}, whereas surface TLR5 '
          'recognizes bacterial {{c2::flagellin}}.',
  'extra': 'Endosomal TLR3 senses dsRNA, TLR7/8 ssRNA, and TLR9 CpG-rich DNA. Surface TLR4 senses LPS; TLR2 '
           'heterodimers recognize microbial lipoproteins. Compartmentalization helps detect where microbial material '
           'is encountered.',
  'alvo': 'TLRs that detect microbial nucleic acids (TLR3/7/8/9) are mainly {{c1::endosomal}}, whereas surface TLR5 '
          'recognizes bacterial {{c2::flagellin}}.',
  'evid': 'Slides família TLR; Abbas cap. 4',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'nod-rig',
  'kind': 'autoral',
  'flags': {1: 4, 2: 4},
  'bloco': 'A-reconhecimento',
  'text': 'Cytosolic {{c1::NOD1/NOD2}} detect bacterial peptidoglycan fragments; {{c2::RIG-I-like receptors}} detect '
          'viral RNA.',
  'extra': 'PRRs occur in distinct compartments: soluble (CRP, MBL), membrane/endosomal (TLRs), and cytosolic (NLRs '
           'and RLRs). NOD signaling promotes inflammatory gene expression; RLR signaling promotes antiviral '
           'interferons.',
  'alvo': 'Cytosolic {{c1::NOD1/NOD2}} detect bacterial peptidoglycan fragments; {{c2::RIG-I-like receptors}} detect '
          'viral RNA.',
  'evid': 'Slides tipos de receptores; Abbas cap. 4',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'dectina',
  'kind': 'autoral',
  'flags': {1: 4},
  'bloco': 'A-reconhecimento',
  'text': 'Fungal cell-wall β-glucans are recognized by {{c1::Dectin-1}}, a C-type lectin receptor on phagocytes.',
  'extra': 'Recognition promotes phagocytosis and inflammatory signaling. Fungal sensing also involves other '
           'receptors; Dectin-1 is not a TLR.',
  'alvo': 'Fungal cell-wall β-glucans are recognized by {{c1::Dectin-1}}, a C-type lectin receptor on phagocytes.',
  'evid': 'Slides Dectina-1; provas P2 2017 2.8 / 2018 1.5; Abbas cap. 4',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'damps',
  'kind': 'autoral',
  'flags': {1: 3},
  'bloco': 'A-reconhecimento',
  'text': 'Necrotic tissue can trigger inflammation without infection by releasing {{c1::damage-associated molecular '
          'patterns (DAMPs)}}.',
  'extra': 'ATP, nuclear proteins and other misplaced cellular contents alert resident phagocytes through innate '
           'sensors. After infarction, this response removes debris but activated neutrophils can also injure '
           'neighboring viable tissue.',
  'alvo': 'Necrotic tissue can trigger inflammation without infection by releasing {{c1::damage-associated molecular '
          'patterns (DAMPs)}}.',
  'evid': 'Slides agressão não infecciosa; prova P1 2017 2.5; Abbas cap. 4',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'urato-nlrp3',
  'kind': 'autoral',
  'flags': {1: 3},
  'bloco': 'A-reconhecimento',
  'text': 'Monosodium urate crystals can activate the {{c1::NLRP3 inflammasome}}, leading to caspase-1-dependent IL-1β '
          'release.',
  'extra': 'Crystal-induced cell stress promotes inflammasome assembly; NLRP3 is not simply a surface receptor binding '
           'dissolved uric acid. IL-1 recruits and activates inflammatory cells, explaining sterile inflammation in '
           'gout.',
  'alvo': 'Monosodium urate crystals can activate the {{c1::NLRP3 inflammasome}}, leading to caspase-1-dependent IL-1β '
          'release.',
  'evid': 'Slide ácido úrico; prova P1 2017 1.6; Abbas cap. 4; Martinon 2006',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'gota-il1',
  'kind': 'autoral',
  'flags': {1: 4},
  'bloco': 'A-reconhecimento',
  'text': 'Blocking {{c1::IL-1}} can suppress crystal-driven inflammation in gout downstream of NLRP3 activation.',
  'extra': 'This targets the inflammatory signal rather than removing urate crystals. IL-1 blockade is a '
           'mechanism-based option in selected refractory cases, not the routine first treatment for every gout flare.',
  'alvo': 'Blocking {{c1::IL-1}} can suppress crystal-driven inflammation in gout downstream of NLRP3 activation.',
  'evid': 'Prova P1 2017 1.6; slide ácido úrico e Abbas cap. 4',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'sequencia-vascular',
  'kind': 'autoral',
  'flags': {1: 4, 2: 3},
  'bloco': 'B-celulas-vasos',
  'text': 'A brief initial vasoconstriction may be followed by arteriolar {{c1::vasodilation}} and increased '
          '{{c2::postcapillary venular permeability}} during acute inflammation.',
  'extra': 'Dilation increases blood flow (redness/warmth); vascular leakage creates protein-rich exudate and edema. '
           'Plasma loss increases blood viscosity and promotes stasis and leukocyte margination.',
  'alvo': 'A brief initial vasoconstriction may be followed by arteriolar {{c1::vasodilation}} and increased '
          '{{c2::postcapillary venular permeability}} during acute inflammation.',
  'evid': 'Slides sequência de eventos e sinais cardinais',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'cinetica-celular',
  'kind': 'autoral',
  'flags': {1: 4},
  'bloco': 'B-celulas-vasos',
  'text': 'After the initial neutrophil wave, recruited {{c1::monocytes/macrophages}} become more prominent over '
          'roughly the next 1–2 days of acute inflammation.',
  'extra': 'The lecture gives macrophage recruitment at 12–48 h and later lymphocytes; eosinophils may increase after '
           '72 h in allergic inflammation. These are teaching timelines, not fixed cutoffs: the stimulus and tissue '
           'change the pattern. Resident macrophages are already present at the start.',
  'alvo': 'After the initial neutrophil wave, recruited {{c1::monocytes/macrophages}} become more prominent over '
          'roughly the next 1–2 days of acute inflammation.',
  'evid': 'Slide acúmulo celular; prova P2 2025 2.4',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'eotaxina',
  'kind': 'autoral',
  'flags': {1: 4},
  'bloco': 'C-migracao',
  'text': '{{c1::Eotaxin}} preferentially recruits eosinophils, whereas IL-8 and LTB4 are major neutrophil '
          'chemoattractants.',
  'extra': 'PAF can also activate/recruit eosinophils but has broader effects and is not an eosinophil-specific '
           'chemokine. Chemotaxis follows a chemical gradient into the affected tissue.',
  'alvo': '{{c1::Eotaxin}} preferentially recruits eosinophils, whereas IL-8 and LTB4 are major neutrophil '
          'chemoattractants.',
  'evid': 'Slide migração por quimioatraentes',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'nets',
  'kind': 'autoral',
  'flags': {1: 4},
  'bloco': 'D-efetores',
  'text': 'Neutrophil extracellular traps (NETs) are webs of {{c1::chromatin coated with antimicrobial proteins}} that '
          'trap microbes outside the cell.',
  'extra': 'NETs concentrate granule proteins around microbes. They complement phagocytosis but extracellular '
           'histones/proteases can also damage host tissue; trapping a microbe is not the same as internalizing it '
           'into a phagosome.',
  'alvo': 'Neutrophil extracellular traps (NETs) are webs of {{c1::chromatin coated with antimicrobial proteins}} that '
          'trap microbes outside the cell.',
  'evid': 'Slide ativação completa do neutrófilo; Rigby/DeLeo 2011 citado na aula',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'neuropeptideos',
  'kind': 'autoral',
  'flags': {1: 4, 2: 4},
  'bloco': 'E-mediadores',
  'text': 'In neurogenic inflammation, sensory nerves release {{c1::substance P}}, which promotes vascular leakage, '
          'and {{c2::CGRP}}, a potent vasodilator.',
  'extra': 'Local sensory nerve activity can amplify edema and blood flow and interact with mast cells. This is a '
           'local inflammatory mechanism as well as pain signaling.',
  'alvo': 'In neurogenic inflammation, sensory nerves release {{c1::substance P}}, which promotes vascular leakage, '
          'and {{c2::CGRP}}, a potent vasodilator.',
  'evid': 'Slide inflamação neurogênica',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'cinetica-mediadores',
  'kind': 'autoral',
  'flags': {1: 3, 2: 4},
  'bloco': 'E-mediadores',
  'text': 'Mast-cell {{c1::histamine}} acts rapidly because it is stored in granules; prostaglandins and leukotrienes '
          'must be {{c2::synthesized after activation}}.',
  'extra': 'Histamine/bradykinin dominate early vascular events; lipid mediators and cytokines sustain the response, '
           'while pro-resolving mediators help terminate it. These waves overlap rather than following strict '
           'exclusive time windows.',
  'alvo': 'Mast-cell {{c1::histamine}} acts rapidly because it is stored in granules; prostaglandins and leukotrienes '
          'must be {{c2::synthesized after activation}}.',
  'evid': 'Slides pré-formados/neoformados; prova P2 2025 2.4',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'lipoxinas-resolvinas',
  'kind': 'autoral',
  'flags': {1: 3, 2: 4},
  'bloco': 'G-resolucao',
  'text': 'Lipoxins and resolvins promote resolution by limiting further {{c1::neutrophil recruitment}} and enhancing '
          'macrophage clearance of {{c2::apoptotic cells}}.',
  'extra': 'Resolution is an active program. Lipoxins derive from arachidonic acid and resolvins from omega-3 fatty '
           'acids; both help end inflammation without simply preventing all immune defense.',
  'alvo': 'Lipoxins and resolvins promote resolution by limiting further {{c1::neutrophil recruitment}} and enhancing '
          'macrophage clearance of {{c2::apoptotic cells}}.',
  'evid': 'Slide resolução; prova P2 2025 2.4; Schwab et al., Nature 2007',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'eferocitose',
  'kind': 'autoral',
  'flags': {1: 3},
  'bloco': 'G-resolucao',
  'text': 'During resolution, macrophages remove apoptotic neutrophils by {{c1::efferocytosis}}, limiting release of '
          'their damaging contents.',
  'extra': 'Clearance of dying cells, withdrawal of the stimulus, and IL-10/TGF-β help switch the tissue toward '
           'repair. Failure to clear debris can perpetuate inflammation.',
  'alvo': 'During resolution, macrophages remove apoptotic neutrophils by {{c1::efferocytosis}}, limiting release of '
          'their damaging contents.',
  'evid': 'Slides resolução; Abbas cap. 4',
  'uso': 'Relacionar o fundamento da aula ao mecanismo e à interpretação das provas UC03.',
  'motivo': 'Verde para relação central; azul para nomenclatura/localização ou aprofundamento do mesmo mecanismo.',
  'busca': 'Duas rotas: seções First Aid e conteúdo/sinônimos. Consulta também aos externos (MCAT e demais modelos); '
           'candidatos em busca/alternativos*.json. Nenhum candidato recupera este alvo no recorte.'},
 {'key': 'ak-1475966862515',
  'kind': 'text',
  'src': 1475966862515,
  'flags': {1: 4},
  'bloco': 'A-reconhecimento',
  'alvo': 'Oxidized LDL is consumed by macrophages via {{c1::scavenger receptor-A::receptor}}',
  'evid': 'Slide tipos de receptores: scavengers e oxLDL',
  'uso': 'Reconstruir a resposta inflamatória e relacionar seu mecanismo aos sinais e aos defeitos de defesa.',
  'motivo': 'Verde: mecanismo reutilizado na interpretação de inflamação; azul: detalhe válido de menor manutenção.',
  'extra': 'Scavenger receptors recognize modified host molecules as well as some microbial ligands. Here oxidized LDL '
           'illustrates this receptor class; the wider pathogenesis of atherosclerosis belongs to another lesson.'}]

COMPARTILHADOS = {1790253141778: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253141870: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253142054: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253142154: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253142275: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253142376: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253142462: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253142565: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253142652: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253142739: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253142965: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253143094: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253143184: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253143273: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253143364: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253143504: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253143586: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253143686: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253143782: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253143896: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253144086: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253144184: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253144681: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253536796: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790261585472: 'Associação prévia da aula: mecanismo inflamatório pertinente, conferido no snapshot.',
 1790253141963: 'Mecanismo pré-existente pertinente: PRR, marginação, ROS, estase, PAF ou permeabilidade.',
 1790253142871: 'Mecanismo pré-existente pertinente: PRR, marginação, ROS, estase, PAF ou permeabilidade.',
 1790253144373: 'Mecanismo pré-existente pertinente: PRR, marginação, ROS, estase, PAF ou permeabilidade.',
 1790253144533: 'Mecanismo pré-existente pertinente: PRR, marginação, ROS, estase, PAF ou permeabilidade.',
 1790253537100: 'Mecanismo pré-existente pertinente: PRR, marginação, ROS, estase, PAF ou permeabilidade.',
 1790253537574: 'Mecanismo pré-existente pertinente: PRR, marginação, ROS, estase, PAF ou permeabilidade.',
 1790253537195: 'Mecanismo pré-existente pertinente: PRR, marginação, ROS, estase, PAF ou permeabilidade.'}

EXCLUIDOS = [(1479267358567,
  'Mesmo alvo de neutrófilos já testado no compartilhado 1790253141778; figura pode apoiar outros cards.'),
 (1520299451730, 'PRR/PAMP já recuperados no compartilhado 1790253141963.'),
 (1520299562982, 'IκB quinase detalha sinalização além da recuperação necessária no slide; NF-kB preservado.'),
 (1471541327679,
  'Vasodilatação/permeabilidade já testadas; contração venosa genérica não acrescenta ao mecanismo central.'),
 (1471541598687, 'Mesmo motivo: manter bradicinina/vasodilatação/permeabilidade nos compartilhados.'),
 (1487640120758,
  'Absoluto sobre permeabilidade por prostaglandinas é impreciso; apoio corrigido no alvo de vasodilatação.'),
 (1487640124653, 'Cisteinil-leucotrienos já recuperados; LTB4 não deve ser generalizado como vasoconstritor.'),
 (1488854891621, 'Precursor ácido araquidônico já recuperado na liberação por PLA2.'),
 (1499356681150, 'COX e seus produtos já recuperados, sem ganho na inversa.'),
 (1488854963588, 'COX-2, PGE2 e dor já recuperados.'),
 (1488854967929, 'COX-2, PGE2 e febre já recuperados.'),
 (1489970022577, 'Macrófagos como fonte de citocinas já recuperados no card de febre.'),
 (1489970054827, 'Fonte de IL-6 já recuperada no card de febre.'),
 (1489970091921, 'IL-8 de macrófagos já recuperada no card de recrutamento.'),
 (1489970615786, 'IL-10 já recuperada no card de resolução.'),
 (1520445172196,
  'Albumina negativa ausente no texto atual; não necessária para recuperar os efeitos sistêmicos centrais.'),
 (1487642801171,
  'Abscesso morfológico pertence à Patologia; rascunho trazia também absoluto incorreto sobre S. aureus.'),
 (1480563969014, 'Desvio à esquerda acrescentaria hematologia fora do mecanismo desta aula.')]

FORA_DO_RECORTE = ['Subtipos de hipersensibilidade, granulomas e diferenciação adaptativa completa são aulas próprias.',
 'Mastocitose, Chédiak-Higashi, critérios SIRS, tratamentos de sepse e catálogo clínico de imunodeficiências não são '
 'importados.',
 'LAD e CGD entram apenas como consequência compreensível da falha de adesão/killing; os demais irmãos clínicos ficam '
 'fora.',
 'Transcrição de fatos das provas não revoga a precisão científica nem amplia automaticamente o recorte.']
