#import "../typst-template/nebli_v2_apostila.typ": *

#pre-aula-page[
  Se você vai assistir a esta aula sem ter lido nada antes, comece por uma imagem só. Pense no sangue circulando dentro de um tubo de parede porosa — o *capilar*, o vaso mais fino do corpo, tão estreito que as hemácias passam quase em fila. Toda a aula acontece nessa parede. De um lado dela está o sangue; do outro está o *interstício*, que é o espaço entre as células. Interstício não é um vazio: é um gel que envolve as células e onde elas vivem. Tudo o que o professor vai chamar de inchaço é líquido sobrando *nesse* espaço, e não dentro das células.

  O nome técnico do inchaço é *edema*, e vale fixar a definição inteira já: acúmulo anormal de líquido no interstício ou dentro de uma cavidade do corpo. Note o "ou": quando o líquido se junta numa cavidade, ele ganha nome próprio conforme o lugar. Na barriga chamamos *ascite* — é o abdome volumoso e tenso do paciente com problema no fígado. Em volta do pulmão, *hidrotórax*. No saco que envolve o coração, *hidropericárdio*. E quando o inchaço é grave e toma o corpo inteiro, e não uma perna só, o nome é *anasarca*. São nomes de endereço, não de mecanismo — todos descrevem *onde* o líquido está, e nenhum diz por que ele chegou lá.

  O porquê é o coração da aula, e ele cabe numa disputa entre duas forças que agem na parede do capilar. A primeira é a *pressão hidrostática*: o sangue empurrando de dentro para fora, espremendo líquido para o tecido. A segunda é a *pressão oncótica*, e ela precisa de um passo a mais para ser entendida. O sangue tem uma parte líquida, o plasma, e dentro dele circulam proteínas — a mais abundante é a *albumina*. Essas proteínas são grandes demais para atravessar a parede do capilar, então ficam presas dentro do vaso, e por osmose puxam água de volta para junto de si. É esse puxão que a pressão oncótica descreve. Empurrar contra puxar, o dia inteiro, em cada capilar do corpo: é o que o professor vai chamar de *forças de Starling*.

  Falta uma terceira peça, e é a que o aluno costuma esquecer. Esse cabo de guerra não termina empatado: sobra sempre um pouco de líquido no tecido, alguns litros por dia somando o corpo todo. Quem recolhe essa sobra é o *sistema linfático*, uma segunda rede de vasos que corre em paralelo à do sangue, junta o excedente e o devolve à circulação. É o ralo do sistema. Guarde essa figura de três peças — *empurra, puxa, e o ralo* —, porque as causas de edema que virão a seguir são, todas, uma dessas três falhando.

  Com isso montado, a aula vai desfiar as causas, e cada uma mexe numa peça. Se a *pressão hidrostática* sobe, é porque o sangue não está escoando bem pelo lado venoso — o caso mais comum é a *insuficiência cardíaca*, em que o coração perde força, bombeia menos do que o corpo precisa e o sangue represa atrás dele. Aqui entra um detalhe que parece contraintuitivo e é central: percebendo que chega pouco sangue, o rim reage segurando sal e água para aumentar o volume circulante. Essa resposta tem nome, *sistema renina-angiotensina-aldosterona*, e ela é perfeitamente correta quando a pessoa perdeu sangue de verdade. Num coração que já falha, porém, ela só acrescenta volume a um sistema que não dá conta — e o inchaço piora.

  Se o que cai é a *pressão oncótica*, o problema é falta de proteína no sangue. Pode ser perda pela urina, quando o filtro do rim adoece e deixa escapar albumina — é a *síndrome nefrótica*; pode ser fabricação insuficiente, porque quem produz albumina é o fígado; pode ser desnutrição. O desfecho é o mesmo e vale entender por que ele é tão difícil de tratar: com pouca albumina, a água não fica retida no vaso, escapa para o tecido, o volume que circula de fato diminui, o rim lê isso como falta de sangue e retém ainda mais sal e água — que também escapam. O ciclo se realimenta.

  Se o *ralo entope*, temos o inchaço por obstrução linfática, e ele tem cara própria: instala-se devagar, atinge um membro só e, com o tempo, endurece. E há ainda a situação em que a própria parede do capilar passa a vazar — o que acontece na inflamação. Aqui o professor vai introduzir uma distinção que atravessa toda a patologia: quando a parede está íntegra e o problema é só de forças, o líquido que sai é ralo e pobre em proteína, e se chama *transudato*; quando a parede foi comprometida e deixa passar proteína e células, o líquido é espesso e se chama *exsudato*. *A composição do líquido denuncia o mecanismo* — e é por isso que, na prática, punciona-se e analisa-se o líquido acumulado.

  A segunda metade do título da aula é *congestão*, e ela é o problema visto do outro lado da parede. Não é líquido que saiu do vaso: é sangue que ficou preso dentro dele, porque não consegue escoar pelas veias. Ela costuma vir emparelhada com um fenômeno vizinho, a *hiperemia*, e a diferença entre os dois é de sentido, não de intensidade. Na hiperemia, as pequenas artérias se abrem e chega *mais* sangue, oxigenado: o local fica vermelho-vivo e quente, como ao redor de um machucado inflamado. Na congestão, o sangue não *sai*, e o sangue parado já entregou seu oxigênio: o local fica azulado — é a *cianose*. Uma é entrada aumentada, a outra é saída bloqueada.

  Isso importa porque sangue parado é sangue que não traz oxigênio novo. Quando a congestão dura meses ou anos, o tecido servido por aqueles vasos vive sufocado, células morrem, pequenos sangramentos deixam pigmento, e o órgão acaba endurecendo por fibrose. Você vai ver isso em dois órgãos, e por um motivo anatômico simples: o *fígado* fica logo atrás do lado direito do coração e o *pulmão*, logo atrás do lado esquerdo. Do fígado cronicamente congesto sai um aspecto manchado, com áreas escuras e claras alternadas, que ganhou o apelido de *fígado em noz-moscada*.

  Duas palavras finais para você não travar quando elas aparecerem. *Cirrose* é o fígado que, agredido por anos, endureceu e se encheu de nódulos; como o sangue passa a ter dificuldade para atravessá-lo, a pressão sobe na veia que traz sangue do intestino até ele — a *hipertensão portal* —, e é daí que nasce a ascite. E *edema pulmonar* é líquido dentro dos alvéolos, as bolsinhas microscópicas onde o ar encontra o sangue no fim do pulmão; um alvéolo cheio de líquido não troca gás mesmo estando inteiro, e a pessoa fica sem ar. *É a única situação desta aula que mata em minutos* — e por isso ela vai receber atenção desproporcional ao seu tamanho no assunto.
]
