#import "../typst-template/nebli_v2_apostila.typ": *

#discursiva("Q1",
  [O tônus muscular desaparece tanto no sono profundo (ou sob anestesia geral) quanto após a lesão do nervo motor. Explique o que essas duas situações, juntas, revelam sobre a natureza do tônus.],
  [O tônus é uma leve contração mantida no músculo em repouso — não produz movimento nem resistência ativa, mas confere firmeza e sustenta a postura. As duas situações revelam que ele é um estado *ativo*, dependente de comando nervoso contínuo, e não uma rigidez passiva do tecido. Na anestesia e no sono profundo, a perda de consciência interrompe a geração central do comando; na lesão do nervo (paralisia), o comando existe mas não chega ao músculo. Em ambos os casos retira-se o estímulo nervoso e o tônus cessa — prova de que ele precisa de inervação para existir.])

#discursiva("Q2",
  [Dois músculos de mesmo volume podem diferir muito em força e em amplitude de movimento conforme o arranjo de seus fascículos. Explique a base geométrica desse compromisso e por que não se pode maximizar as duas propriedades ao mesmo tempo.],
  [A força depende da área transversal do ventre — quantas fibras estão lado a lado puxando em paralelo —, enquanto a amplitude depende do comprimento das fibras, pois fibras mais longas encurtam mais. Num volume fixo, as duas competem: fibras longas e paralelas maximizam a amplitude, mas deixam poucas fibras na seção transversal (pouca força); fibras curtas e oblíquas, como no peniforme, empacotam muitas fibras na seção (muita força), mas encurtam pouco (pouca amplitude). Como o volume é finito, ganhar numa propriedade custa perder na outra — o arranjo fascicular é o ajuste que cada músculo adota conforme sua função.])

#discursiva("Q3",
  [O tendão é inextensível e tem suprimento vascular escasso. Explique a consequência funcional de cada uma dessas propriedades.],
  [A inextensibilidade garante transmissão fiel da força: como o tendão não estica, todo o encurtamento do ventre é repassado ao osso, produzindo movimento imediato. Se o tendão fosse elástico, parte do encurtamento se perderia esticando-o, e a força chegaria atenuada e atrasada. O suprimento vascular escasso dá ao tendão sua cor branca e explica uma consequência clínica: lesões de tendão cicatrizam devagar, porque pouco sangue significa pouca entrega de células e material para o reparo. Assim, a mesma composição de colágeno denso que torna o tendão eficiente na transmissão de força o torna lento para se regenerar.])

#discursiva("Q4",
  [Após um trauma na perna, um paciente desenvolve síndrome compartimental. Explique a fisiopatologia do quadro a partir de uma propriedade da fáscia muscular e indique a conduta que a resolve.],
  [A fáscia muscular é um tecido conjuntivo denso, resistente e pouco distensível, que delimita compartimentos contendo grupos musculares. Após o trauma, o inchaço aumenta o volume *dentro* do compartimento, mas a fáscia rígida não se expande para acomodá-lo. A pressão sobe nesse espaço fechado e comprime os vasos e nervos que ali passam, reduzindo a perfusão e ameaçando a viabilidade do tecido — daí a dor desproporcional. A conduta que resolve é a fasciotomia: abrir cirurgicamente a fáscia para aliviar a pressão. A mesma rigidez que torna a fáscia útil para conter e dirigir a força é o que a torna perigosa quando o volume interno aumenta.])

#discursiva("Q5",
  [A alavanca de 3ª classe é a mais comum no corpo humano, embora opere em desvantagem mecânica. Explique o que significa essa desvantagem, use o bíceps flexionando o cotovelo como exemplo e justifique por que o corpo "aceita" esse arranjo aparentemente ineficiente.],
  [Numa alavanca de 3ª classe a força é aplicada entre o eixo e a carga. No bíceps, o eixo é o cotovelo, a força entra pelo tendão *perto* da articulação e a carga (peso do antebraço e da mão) fica na extremidade distante. Operar em desvantagem mecânica significa que o músculo precisa gerar muita força para mover uma carga relativamente pequena, já que seu braço de força é curto. O corpo aceita esse "mau negócio" porque ganha outra coisa em troca: velocidade e amplitude. Um pequeno encurtamento do bíceps perto do cotovelo faz a mão percorrer uma grande distância rapidamente. Essa troca de força por velocidade e alcance é o que nos torna ágeis e capazes de movimentos amplos e rápidos, em vez de apenas fortes — vantagem decisiva para a maioria dos gestos cotidianos.])
