#import "../typst-template/nebli_v2_apostila.typ": *

#discursiva("Q1",
  [Uma paciente diabética apresenta, ao mesmo tempo, úlcera que não cicatriza, vasculopatia periférica e hemoglobina glicada elevada. Explique o principal mecanismo fisiopatológico capaz de dar conta de todas essas alterações simultaneamente.],
  [A glicação não-enzimática. A glicose, açúcar redutor, reage espontaneamente com grupos amino de proteínas: forma base de Schiff em horas, produto de Amadori em dias e ligação cruzada irreversível em meses. Na hemoglobina o produto de Amadori é a própria hemoglobina glicada, e por isso ela mede exposição acumulada. No colágeno, a reticulação torna a matriz resistente à digestão proteolítica e trava o remodelamento do reparo. Na LDL, a glicação favorece oxidação e captação por receptores scavenger de macrófago, que não têm freio por colesterol intracelular — e a célula espumosa funda a placa. Um mecanismo, três alvos.])

#discursiva("Q2",
  [Aponte as semelhanças e as diferenças, do ponto de vista de mecanismos, entre a descompensação aguda característica do diabetes tipo 1 e a do diabetes tipo 2.],
  [Semelhança: as duas partem de hiperglicemia que ultrapassa o limiar de reabsorção tubular, gerando diurese osmótica, perda de água e eletrólitos e hiperosmolaridade plasmática. A diferença está na insulina residual. No tipo 1 ela é praticamente nula, a lipase hormônio-sensível fica livre, o fígado é inundado por ácido graxo, a acetil-CoA excede o ciclo de Krebs e o excedente vira cetoácido: instala-se acidose metabólica. No tipo 2 a insulina residual não normaliza a glicemia mas basta para conter a lipólise; sem cetose, a descompensação é puramente osmótica, com glicemias mais altas e desidratação profunda.])

#discursiva("Q3",
  [Considerando seus conhecimentos de bioquímica e de patologia, explique por que a hiperglicemia crônica lesa preferencialmente retina, glomérulo, nervo periférico e cristalino, poupando relativamente o músculo esquelético.],
  [Porque o dano depende de glicose intracelular alta, e não da glicemia em si. Músculo e tecido adiposo captam glicose por GLUT-4 dependente de insulina e reduzem o transportador de superfície quando o sinal cai, limitando a própria carga. Pericito da retina, célula mesangial, endotélio, neurônio e cristalino usam transportadores independentes de insulina e não conseguem fechar essa porta: a concentração intracelular acompanha a plasmática. Dentro dessas células as quatro rotas operam — polióis com consumo de NADPH, hexosamina, proteína quinase C e glicação avançada — todas convergindo em estresse oxidativo.])

#discursiva("Q4",
  [Descreva os achados ultrassonográficos esperados no rim do paciente diabético na fase inicial e na fase final da nefropatia, e correlacione cada um com o seu substrato patológico.],
  [Na fase inicial, rins de dimensões aumentadas. O substrato é funcional e estrutural precoce: a arteríola aferente dilata mais que a eferente, a pressão no capilar glomerular sobe e a hiperfiltração se acompanha de hipertrofia glomerular. Na fase final, rins reduzidos, com córtex afilado e ecogenicidade aumentada. O substrato é a substituição do parênquima funcionante por glomeruloesclerose, hialinização arteriolar e fibrose intersticial; o tecido fibroso oferece mais interfaces acústicas e devolve mais som, o que explica a hiperecogenicidade. A albuminúria precede a elevação da creatinina porque a hiperfiltração dos néfrons remanescentes mascara a perda.])

#discursiva("Q5",
  [No pé de um paciente diabético com destruição óssea, aponte as semelhanças e as diferenças de mecanismo entre a artropatia de Charcot e a osteomielite, e justifique a escolha do método de imagem em cada situação.],
  [Semelhanças: ambas ocorrem em pé com neuropatia estabelecida, produzem destruição óssea e podem coexistir no mesmo paciente. Diferenças de mecanismo: a artropatia de Charcot é destruição mecânica — a articulação sem dor nem propriocepção sofre microtraumas repetidos sem correção postural, e a arquitetura do médio-pé se desmonta com erosão, fragmentação e colapso do arco, sem infecção. A osteomielite é infecção da medular óssea, em geral por contiguidade a partir de úlcera profunda. Quanto à imagem: a radiografia mostra bem o desalinhamento e a fragmentação de Charcot, mas só revela osteomielite após perda óssea significativa, com uma a duas semanas de atraso. A ressonância magnética detecta antes o edema da medular — baixo sinal em T1, alto sinal em T2 com saturação de gordura e realce após contraste.])
